Repository eclipse-sirius/sirius-web, pull requests merged in 2018-05, with the labels that each got.

#41 Improve card components' layout
  src/components/blank/BlankCard.css
  src/components/blank/BlankCard.js
  src/components/blank/__tests__/__snapshots__/BlankCard.test.js.snap
  src/components/cards/Card.css
  src/components/cards/Card.js
  src/components/cards/README.adoc
  src/components/cards/__tests__/Card.test.js
  src/components/cards/__tests__/__snapshots__/Card.test.js.snap
  src/components/dashboard/DashboardView.css
  src/components/dashboard/DashboardView.js
  src/components/dashboard/__tests__/__snapshots__/DashboardView.test.js.snap
  src/components/error/ErrorCard.css
  src/components/error/ErrorCard.js
  src/components/error/__tests__/__snapshots__/ErrorCard.test.js.snap
  src/components/form/Form.css
  src/components/form/Form.js
  src/components/info/InfoCard.css
  src/components/info/InfoCard.js
  src/components/info/__tests__/__snapshots__/InfoCard.test.js.snap
  src/components/projects/NewProjectCard.js
  src/components/projects/ProjectHeaderCard.js
  src/components/projects/ProjectRepresentationsListCard.js
  src/components/projects/ProjectSemanticResourcesListCard.js
  src/components/projects/ProjectSummaryCard.css
  src/components/projects/ProjectSummaryCard.js
  src/components/projects/ProjectsListCard.js
  src/components/projects/listprojects/__tests__/__snapshots__/ListProjectsView.test.js.snap
  src/components/projects/newproject/__tests__/__snapshots__/NewProjectView.test.js.snap
  src/components/projects/project/__tests__/__snapshots__/ProjectView.test.js.snap
  src/components/workflow/WorkflowCard.css
  src/components/workflow/WorkflowCard.js
  src/components/workflow/__tests__/__snapshots__/WorkflowCard.test.js.snap
Labels: difficulty: starter 👧, type: enhancement ✨

#42 Improve support for empty states
  src/components/cards/Card.css
  src/components/projects/ProjectRepresentationsListCard.js
  src/components/projects/ProjectSemanticResourcesListCard.js
  src/components/projects/project/__tests__/ProjectView.test.js
  src/components/projects/project/__tests__/__snapshots__/ProjectView.test.js.snap
  src/components/workflow/WorkflowCard.js
  src/containers/projects/__tests__/ProjectViewStateContainer.test.js
Labels: difficulty: starter 👧, type: enhancement ✨

#45 Prevent transitions to undefined states
  src/common/dispatcherCreator.js
  src/components/projects/listprojects/ListProjectsViewFiniteStateMachine.js
Labels: difficulty: starter 👧, type: bug 💥

#48 Update settings.json to remove organize imports
  .vscode/settings.json
Labels: difficulty: starter 👧, type: bug 💥

#49 Issue on using prettier cli on windows
  package.json
Labels: difficulty: starter 👧, type: enhancement ✨

#56 All project cards should have the same height
  src/components/dashboard/DashboardView.css
Labels: difficulty: starter 👧, type: enhancement ✨

#57 Add support for project description
  src/components/cards/Card.css
  src/components/dashboard/__tests__/__snapshots__/DashboardView.test.js.snap
  src/components/main/Main.js
  src/components/projects/ProjectHeaderCard.css
  src/components/projects/ProjectHeaderCard.js
  src/components/projects/ProjectSummaryCard.js
  src/components/projects/ProjectsListCard.js
  src/components/projects/listprojects/ListProjectsViewDispatcher.js
  src/components/projects/listprojects/__tests__/__snapshots__/ListProjectsView.test.js.snap
  src/components/projects/project/ProjectView.js
  src/components/projects/project/ProjectViewDispatcher.js
  src/components/projects/project/ProjectViewFiniteStateMachine.js
  src/components/projects/project/__tests__/__snapshots__/ProjectView.test.js.snap
  src/containers/projects/ProjectViewStateContainer.js
  src/containers/projects/__tests__/ListProjectsViewStateContainer.test.js
  src/containers/projects/__tests__/ProjectViewStateContainer.test.js
Labels: difficulty: medium 👩‍💻, type: feature request 🤔

#58 Add the ability to hide the sidebar
  src/components/app/App.css
  src/components/app/App.js
  src/components/aside/Aside.css
  src/components/main/Main.css
Labels: difficulty: starter 👧, type: feature request 🤔

#65 Switch to default props in EditDescription
  src/components/projects/ProjectHeaderCard.js
Labels: difficulty: starter 👧, type: enhancement ✨

#69 Use a component-based approach for spacing
  src/components/app/App.css
  src/components/app/App.js
  src/components/blank/BlankCard.css
  src/components/blank/BlankCard.js
  src/components/blank/__tests__/__snapshots__/BlankCard.test.js.snap
  src/components/buttons/Button.css
  src/components/buttons/Button.js
  src/components/buttons/__tests__/__snapshots__/Button.test.js.snap
  src/components/cards/Card.css
  src/components/cards/Card.js
  src/components/cards/__tests__/__snapshots__/Card.test.js.snap
  src/components/dashboard/__tests__/__snapshots__/DashboardView.test.js.snap
  src/components/error/ErrorCard.css
  src/components/error/ErrorCard.js
  src/components/error/__tests__/__snapshots__/ErrorCard.test.js.snap
  src/components/form/Form.css
  src/components/form/Form.js
  src/components/info/InfoCard.css
  src/components/info/InfoCard.js
  src/components/info/__tests__/__snapshots__/InfoCard.test.js.snap
  src/components/list/List.css
  src/components/list/List.js
  src/components/list/ListConstants.js
  src/components/main/Main.js
  src/components/navbar/Navbar.css
  src/components/navbar/Navbar.js
  src/components/navbar/__tests__/__snapshots__/Navbar.test.js.snap
  src/components/projects/ProjectHeaderCard.css
  src/components/projects/ProjectHeaderCard.js
  src/components/projects/ProjectRepresentationsListCard.js
  src/components/projects/ProjectSemanticResourcesListCard.js
  src/components/projects/ProjectSummaryCard.js
  src/components/projects/ProjectsListCard.js
  src/components/projects/listprojects/__tests__/__snapshots__/ListProjectsView.test.js.snap
  src/components/projects/newproject/__tests__/__snapshots__/NewProjectView.test.js.snap
  src/components/projects/project/__tests__/__snapshots__/ProjectView.test.js.snap
  src/components/spacing/Spacing.js
  src/components/spacing/SpacingConstants.js
  src/components/workflow/WorkflowCard.css
  src/components/workflow/WorkflowCard.js
  src/components/workflow/__tests__/__snapshots__/WorkflowCard.test.js.snap
Labels: difficulty: medium 👩‍💻, type: enhancement ✨

#73 Extract the button constants from the button component
  src/components/buttons/Button.js
  src/components/buttons/ButtonConstants.js
  src/components/buttons/__tests__/Button.test.js
  src/components/projects/NewProjectCard.js
Labels: difficulty: starter 👧, type: enhancement ✨

#77 Fix an issue with long labels in the tab bar
  src/components/projects/project/__tests__/__snapshots__/ProjectView.test.js.snap
  src/components/tabbar/TabBar.js
  src/components/tabbar/__tests__/__snapshots__/TabBar.test.js.snap
  src/components/workflow/__tests__/__snapshots__/WorkflowCard.test.js.snap
Labels: difficulty: starter 👧, type: bug 💥

#79 Remove the prettier formatting on paste
  .vscode/settings.json
Labels: area: project ⚙️, difficulty: starter 👧, type: enhancement ✨

#80 Improve support for loading
  src/components/dashboard/__tests__/__snapshots__/DashboardView.test.js.snap
  src/components/loading/Loading.css
  src/components/loading/Loading.js
  src/components/projects/listprojects/__tests__/__snapshots__/ListProjectsView.test.js.snap
  src/components/projects/project/__tests__/__snapshots__/ProjectView.test.js.snap
  src/components/text/Text.css
  src/components/text/Text.js
Labels: difficulty: starter 👧, type: enhancement ✨
