Repository eclipse-sirius/sirius-web, pull requests merged in 2021-05, with the labels that each got.

#470 [449] Move navigation bar to Material-UI
  frontend/src/common/BrandingContext.tsx
  frontend/src/icons/Help.tsx
  frontend/src/icons/SiriusIcon.tsx
  frontend/src/icons/index.ts
  frontend/src/index.ts
  frontend/src/navbar/LoggedInNavbar.module.css
  frontend/src/navbar/LoggedInNavbar.tsx
  frontend/src/navbar/Navbar.tsx
  frontend/src/navbar/NavigationBar.tsx
  frontend/src/navbar/UserStatusContextMenu.tsx
  frontend/src/stories/navbar/NavbarStory.tsx
Labels: pr: to be review soon, priority: high

#476 [perf] Remove duplicate call to layoutService.layout() on diagram creation
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/DiagramCreationService.java
Labels: pr: to be review soon, priority: high

#479 [59] Fix visited link color
  frontend/src/common/BrandingContext.tsx
  frontend/src/navbar/NavigationBar.tsx
Labels: pr: to be review soon, priority: high

#478 [58] Remove the hardcoded background color from avatars
  frontend/src/diagram/Toolbar.tsx
  frontend/src/index.ts
  frontend/src/properties/Properties.tsx
  frontend/src/properties/propertysections/PropertySectionLabel.tsx
Labels: pr: to be review soon, priority: high

#483 [fix] Only return well-formed EPackages
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/domain/DomainConverter.java
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/services/EditingContextEPackageService.java
Labels: pr: to be review soon, priority: high

#484 [cleanup] Make the editing context dispose delay configurable
  backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/projects/EditingContextEventProcessorRegistry.java
Labels: pr: to be review soon, priority: high

#517 [cleanup] Remove the JPAConfiguration from the persistence tests
  backend/sirius-web-persistence/src/test/java/org/eclipse/sirius/web/persistence/repositories/JPAConfiguration.java
  backend/sirius-web-persistence/src/test/java/org/eclipse/sirius/web/persistence/repositories/RepresentationRepositoryIntegrationTestCases.java
Labels: pr: to be review soon, priority: low

#509 🐛 [fix] Fix potential duplicate id on edges
  backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/components/EdgeComponent.java
  backend/sirius-web-diagrams/src/test/java/org/eclipse/sirius/web/diagrams/renderer/DiagramRendererEdgeTestCases.java
Labels: pr: to be review soon, priority: high, type: bug 💥

#507 🐛 [480] Fix inheritance support in DomainConverter
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/domain/DomainConverter.java
Labels: pr: to be review soon, priority: high, type: bug 💥

#506 🧹 [cleanup] Remove unused dependencies in the frontend
  frontend/.storybook/main.js
  frontend/.storybook/preview.js
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to review later, priority: low, type: enhancement ✨

#513 ✨ Improve the domain modeler ergonomics
  backend/sirius-web-domain-design/pom.xml
  backend/sirius-web-domain-design/src/main/java/org/eclipse/sirius/web/domain/design/services/DomainServices.java
  backend/sirius-web-domain-design/src/main/java/org/eclipse/sirius/web/domain/design/services/Services.java
  backend/sirius-web-domain-design/src/main/resources/description/domain.odesign
Labels: pr: to be review soon, priority: high, type: enhancement ✨

#508 🧹 [cleanup] Remove VariableManager.children
  backend/sirius-web-representations/src/main/java/org/eclipse/sirius/web/representations/VariableManager.java
Labels: pr: to review later, type: bug 💥

#516 ✨ [510] Add support for rounded corners
  backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/AbstractNodeMappingStyleProvider.java
  backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/ListNodeStyle.java
  backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/RectangularNodeStyle.java
  frontend/src/diagram/operations.ts
  frontend/src/diagram/sprotty/views/ListView.tsx
  frontend/src/diagram/sprotty/views/RectangleView.tsx
Labels: pr: to review later, priority: low, type: enhancement ✨
