Repository eclipse-sirius/sirius-web, pull requests merged in 2021-08, with the labels that each got.

#661 Update README.adoc
  README.adoc
Labels: pr: to review soon, priority: high

#191 [190] Add support for inverse references navigation
  backend/sirius-web-interpreter/src/main/java/org/eclipse/sirius/web/interpreter/AQLInterpreter.java
  backend/sirius-web-interpreter/src/main/java/org/eclipse/sirius/web/interpreter/SimpleCrossReferenceProvider.java
  backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/documents/EditingDomainFactory.java
  backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/editingcontext/EditingContextSearchService.java
  backend/sirius-web-services/src/test/java/org/eclipse/sirius/web/services/editingcontext/EditingContextSearchServiceTests.java
Labels: pr: to review later, priority: low

#678 [677] Add new representation default name
  frontend/src/modals/new-representation/NewRepresentationModal.tsx
  frontend/src/modals/new-representation/NewRepresentationModalMachine.ts
Labels: pr: to review soon, priority: high

#679 [enh] Add a validation rule on domain name
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/domain/DomainValidator.java
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/services/EMFValidationService.java
Labels: pr: to review soon, priority: high

#649 [fix] Fix default edge decorator on View definitions
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/ConditionalEdgeStyleImpl.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/EdgeStyleImpl.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/ViewPackageImpl.java
  backend/sirius-web-view/src/main/resources/model/view.ecore
Labels: pr: to review soon, priority: high

#650 [646] Fix default color for new edges in the View DSL
  backend/sirius-web-view-edit/src/main/java/org/eclipse/sirius/web/view/provider/EdgeDescriptionItemProvider.java
Labels: pr: to review soon, priority: high

#656 [654] Set Feature#optional feature default value to `true`
  backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/impl/DomainFactoryImpl.java
  backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/impl/DomainPackageImpl.java
  backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/impl/FeatureImpl.java
  backend/sirius-web-domain/src/main/resources/model/domain.ecore
Labels: pr: to review soon, priority: high

#664 [559] Add data attributes in SelectionDialogWebSocketContainer
  frontend/src/selection/SelectionDialogWebSocketContainer.tsx
  frontend/src/workbench/RepresentationNavigation.tsx
Labels: pr: to review soon, priority: high

#648 [588] Add support for multiple inheritance for domains
  backend/sirius-web-domain-design/src/main/resources/description/domain.odesign
  backend/sirius-web-domain-edit/src/main/java/org/eclipse/sirius/web/domain/provider/EntityItemProvider.java
  backend/sirius-web-domain-edit/src/main/resources/plugin.properties
  backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/DomainPackage.java
  backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/Entity.java
  backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/impl/DomainPackageImpl.java
  backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/impl/EntityImpl.java
  backend/sirius-web-domain/src/main/resources/model/domain.ecore
  backend/sirius-web-domain/src/main/resources/model/domain.genmodel
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/domain/DomainConverter.java
Labels: pr: to review soon, priority: high

#681 [doc] Add various ADRs to the 0.5.0 release of Sirius Components
  doc/adrs/024_add_support_for_view_deletion_requests.adoc
  doc/adrs/025_switch_to_a_schema_first_approach_for_our_graphql_schema.adoc
  doc/adrs/026_improve_the_performance_of_unsynchronized_nodes.adoc
  doc/adrs/027_make_the_explorer_independent_from_modeling_concepts.adoc
  doc/adrs/028_move_representations_out_of_the_explorer.adoc
  doc/adrs/029_introduce_some_object_services.adoc
Labels: pr: to review soon, priority: high

#644 Improve View meta-model with features that are already supported in our diagrams
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/StylesFactory.java
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/ViewPropertiesConfigurer.java
  backend/sirius-web-view-edit/src/main/java/org/eclipse/sirius/web/view/provider/ConditionalEdgeStyleItemProvider.java
  backend/sirius-web-view-edit/src/main/java/org/eclipse/sirius/web/view/provider/ConditionalNodeStyleItemProvider.java
  backend/sirius-web-view-edit/src/main/java/org/eclipse/sirius/web/view/provider/EdgeStyleItemProvider.java
  backend/sirius-web-view-edit/src/main/java/org/eclipse/sirius/web/view/provider/NodeStyleItemProvider.java
  backend/sirius-web-view-edit/src/main/resources/plugin.properties
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/EdgeStyle.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/NodeStyle.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/ViewPackage.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/ConditionalEdgeStyleImpl.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/ConditionalNodeStyleImpl.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/EdgeStyleImpl.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/NodeStyleImpl.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/ViewPackageImpl.java
  backend/sirius-web-view/src/main/resources/model/view.ecore
  backend/sirius-web-view/src/main/resources/model/view.genmodel
Labels: pr: to review soon, priority: high

#634 Improve support for custom images
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/CustomImage.java
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/ICustomImageSearchService.java
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/StylesFactory.java
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/ViewConverter.java
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/ViewPropertiesConfigurer.java
  backend/sirius-web-persistence/src/main/java/org/eclipse/sirius/web/persistence/entities/CustomImageEntity.java
  backend/sirius-web-persistence/src/main/java/org/eclipse/sirius/web/persistence/repositories/ICustomImageRepository.java
  backend/sirius-web-persistence/src/main/resources/db/changelog/sirius-web-schema.sql
  backend/sirius-web-services-api/src/main/java/org/eclipse/sirius/web/services/api/images/ICustomImageContentService.java
  backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/images/CustomImageContentService.java
  backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/images/CustomImageSearchService.java
  backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/representations/DynamicRepresentationDescriptionService.java
  backend/sirius-web-spring/src/main/java/org/eclipse/sirius/web/spring/controllers/ImagesController.java
  backend/sirius-web-spring/src/test/java/org/eclipse/sirius/web/spring/controllers/ImagesControllerTests.java
Labels: pr: to review later, priority: low

#682 [doc] Add an ADR on the link representation
  doc/adrs/030_add_a_link_representation.adoc
Labels: pr: to review soon, priority: high

#631 Disable move/resize of nodes on auto-layout diagrams
  backend/sirius-web-graphql-schema/src/main/java/org/eclipse/sirius/web/graphql/schema/DiagramTypesProvider.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/diagram/DiagramAutoLayoutDataFetcher.java
  frontend/src/diagram/DiagramWebSocketContainer.tsx
  frontend/src/diagram/Toolbar.tsx
  frontend/src/diagram/Toolbar.types.ts
  frontend/src/diagram/operations.ts
  frontend/src/diagram/sprotty/__tests__/convertDiagram.test.ts
  frontend/src/diagram/sprotty/convertDiagram.tsx
Labels: pr: to review soon, priority: high

#685 [fix] Fix the create document dialog
  frontend/src/modals/new-document/NewDocumentModal.tsx
  frontend/src/modals/new-document/NewDocumentModal.types.ts
  frontend/src/modals/new-document/NewDocumentModalMachine.ts
Labels: pr: to review soon, priority: high

#702 [doc] Fix a few typos in the recent ADRs
  doc/adrs/024_add_support_for_view_deletion_requests.adoc
  doc/adrs/026_improve_the_performance_of_unsynchronized_nodes.adoc
  doc/adrs/027_make_the_explorer_independent_from_modeling_concepts.adoc
  doc/adrs/029_introduce_some_object_services.adoc
  doc/adrs/030_add_a_link_representation.adoc
Labels: pr: to review soon, priority: high

#705 [fix] Avoid publishing rename event if there are no subscribers
  backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/projects/EditingContextEventProcessor.java
Labels: pr: to review later, priority: low

#707 [fix] Removes flow from where it is not needed
  backend/sirius-web-domain-design/pom.xml
  backend/sirius-web-domain-edit/pom.xml
  backend/sirius-web-domain/pom.xml
  backend/sirius-web-emf/pom.xml
  backend/sirius-web-tests/src/test/java/org/eclipse/sirius/web/tests/GeneralPurposeTests.java
  backend/sirius-web-view-edit/pom.xml
  backend/sirius-web-view/pom.xml
Labels: pr: to review soon, priority: low

#703 [doc] Contribute additional ADRs on metadata and identifiers
  doc/adrs/031_separate_metadata_from_representations.adoc
  doc/adrs/032_relax_our_constraints_on_some_of_our_identifiers.adoc
Labels: area: documentation 📋, pr: to review soon, priority: high

#708 [test] Add additional data-testid
  frontend/src/modals/new-representation/NewRepresentationModal.tsx
Labels: pr: to review soon, priority: high

#711 [690] Add selectedNode variable to execute tools
  backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/Node.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/DeleteFromDiagramEventHandler.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/InvokeNodeToolOnDiagramEventHandler.java
  doc/adrs/033_add_support_for_ unsynchronized_tools.adoc
Labels: pr: to review soon, priority: high

#712 [671] Add the GraphQL schemas of Sirius Components
  backend/sirius-web-spring-collaborative-diagrams/src/main/resources/schema/diagram.graphqls
  backend/sirius-web-spring-collaborative-forms/src/main/resources/schema/form.graphqls
  backend/sirius-web-spring-collaborative-selection/src/main/resources/.gitkeep
  backend/sirius-web-spring-collaborative-selection/src/main/resources/schema/selection.graphqls
  backend/sirius-web-spring-collaborative-trees/src/main/resources/.gitkeep
  backend/sirius-web-spring-collaborative-trees/src/main/resources/schema/tree.graphqls
  backend/sirius-web-spring-collaborative-validation/src/main/resources/.gitkeep
  backend/sirius-web-spring-collaborative-validation/src/main/resources/schema/validation.graphqls
  backend/sirius-web-spring-collaborative/src/main/resources/schema/core.graphqls
Labels: pr: to review soon, priority: high

#714 [fix] Fix erroneous error status when unsetting a mono-valued reference
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/compatibility/properties/MonoValuedNonContainmentReferenceIfDescriptionProvider.java
Labels: pr: to review soon, priority: high

#713 [releng] Trigger a pull request build only for remote PRs
  .github/workflows/build.yml
Labels: pr: to review soon, priority: high

#717 [releng] Bump version to v0.4.6
  backend/pom.xml
  backend/sirius-web-annotations-spring/pom.xml
  backend/sirius-web-annotations/pom.xml
  backend/sirius-web-api/pom.xml
  backend/sirius-web-compatibility/pom.xml
  backend/sirius-web-components/pom.xml
  backend/sirius-web-core-api/pom.xml
  backend/sirius-web-diagrams-layout-api/pom.xml
  backend/sirius-web-diagrams-layout/pom.xml
  backend/sirius-web-diagrams-tests/pom.xml
  backend/sirius-web-diagrams/pom.xml
  backend/sirius-web-domain-design/pom.xml
  backend/sirius-web-domain-edit/pom.xml
  backend/sirius-web-domain/pom.xml
  backend/sirius-web-emf/pom.xml
  backend/sirius-web-forms-tests/pom.xml
  backend/sirius-web-forms/pom.xml
  backend/sirius-web-graphiql/pom.xml
  backend/sirius-web-graphql-utils/pom.xml
  backend/sirius-web-graphql-voyager/pom.xml
  backend/sirius-web-interpreter/pom.xml
  backend/sirius-web-representations/pom.xml
  backend/sirius-web-selection/pom.xml
  backend/sirius-web-spring-collaborative-diagrams/pom.xml
  backend/sirius-web-spring-collaborative-forms/pom.xml
  backend/sirius-web-spring-collaborative-selection/pom.xml
  backend/sirius-web-spring-collaborative-trees/pom.xml
  backend/sirius-web-spring-collaborative-validation/pom.xml
  backend/sirius-web-spring-collaborative/pom.xml
  backend/sirius-web-spring-graphql-api/pom.xml
  backend/sirius-web-spring-graphql/pom.xml
  backend/sirius-web-spring-starter/pom.xml
  backend/sirius-web-spring-tests/pom.xml
  backend/sirius-web-tests/pom.xml
  backend/sirius-web-trees/pom.xml
  backend/sirius-web-validation/pom.xml
  backend/sirius-web-view-edit/pom.xml
  backend/sirius-web-view/pom.xml
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to review soon, priority: high
