Repository eclipse-sirius/sirius-web, pull requests merged in 2021-12, with the labels that each got.

#143 [releng] Switch to Sirius Components 0.5.6
  backend/sirius-web-frontend/pom.xml
  backend/sirius-web-graphql-schema/pom.xml
  backend/sirius-web-graphql/pom.xml
  backend/sirius-web-persistence/pom.xml
  backend/sirius-web-sample-application/pom.xml
  backend/sirius-web-services-api/pom.xml
  backend/sirius-web-services/pom.xml
  backend/sirius-web-spring/pom.xml
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to review soon, priority: high

#146 [releng] Bump version to 2021.12.0
  backend/pom.xml
  backend/sirius-web-frontend/pom.xml
  backend/sirius-web-graphql-schema/pom.xml
  backend/sirius-web-graphql/pom.xml
  backend/sirius-web-persistence/pom.xml
  backend/sirius-web-sample-application/pom.xml
  backend/sirius-web-services-api/pom.xml
  backend/sirius-web-services/pom.xml
  backend/sirius-web-spring/pom.xml
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to review soon, priority: high

#145 [releng] Upgrade to Spring Boot 2.6.1
  backend/sirius-web-frontend/pom.xml
  backend/sirius-web-graphql-schema/pom.xml
  backend/sirius-web-graphql/pom.xml
  backend/sirius-web-persistence/pom.xml
  backend/sirius-web-sample-application/pom.xml
  backend/sirius-web-sample-application/src/main/resources/application-dev.properties
  backend/sirius-web-sample-application/src/main/resources/application.properties
  backend/sirius-web-services-api/pom.xml
  backend/sirius-web-services/pom.xml
  backend/sirius-web-spring/pom.xml
Labels: pr: to review soon, priority: high

#147 [releng] Switch to Sirius Components 2021.12.3
  backend/sirius-web-frontend/pom.xml
  backend/sirius-web-graphql-schema/pom.xml
  backend/sirius-web-graphql/pom.xml
  backend/sirius-web-persistence/pom.xml
  backend/sirius-web-sample-application/pom.xml
  backend/sirius-web-services-api/pom.xml
  backend/sirius-web-services/pom.xml
  backend/sirius-web-spring/pom.xml
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to review soon, priority: high

#135 Fix coding rules test errors
  backend/sirius-web-services-api/src/main/java/org/eclipse/sirius/web/services/api/projects/UnzippedProject.java
  backend/sirius-web-services-api/src/main/java/org/eclipse/sirius/web/services/api/representations/RepresentationDescriptor.java
  backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/projects/ProjectImportService.java
Labels: pr: to review later, priority: low

#148 [releng] Update our frontend dependencies
  backend/sirius-web-frontend/pom.xml
  backend/sirius-web-graphql-schema/pom.xml
  backend/sirius-web-graphql/pom.xml
  backend/sirius-web-persistence/pom.xml
  backend/sirius-web-sample-application/pom.xml
  backend/sirius-web-services-api/pom.xml
  backend/sirius-web-services/pom.xml
  backend/sirius-web-spring/pom.xml
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to review soon, priority: high, waiting for sirius components

#150 [releng] Switch to Sirius Components 2021.12.5
  backend/sirius-web-frontend/pom.xml
  backend/sirius-web-graphql-schema/pom.xml
  backend/sirius-web-graphql/pom.xml
  backend/sirius-web-persistence/pom.xml
  backend/sirius-web-sample-application/pom.xml
  backend/sirius-web-services-api/pom.xml
  backend/sirius-web-services/pom.xml
  backend/sirius-web-spring/pom.xml
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to review soon, priority: high

#149 [144] Add some Cypress-based integration tests
  frontend/src/views/edit-project/EditProjectNavbar/EditProjectNavbar.tsx
  frontend/src/views/new-project/NewProjectView.tsx
  frontend/src/views/projects/ProjectsView.tsx
  integration-tests/.prettierrc
  integration-tests/.vscode/settings.json
  integration-tests/cypress-dev.json
  integration-tests/cypress.json
  integration-tests/cypress/fixtures/Robot.xmi
  integration-tests/cypress/integration/project/edit/diagram-context-menu_spec.js
  integration-tests/cypress/integration/project/edit/diagram-edit-robot_spec.js
  integration-tests/cypress/integration/project/edit/diagram-selection-dialog_spec.js
  integration-tests/cypress/integration/project/edit/diagram_spec.js
  integration-tests/cypress/integration/project/edit/document-context-menu_spec.js
  integration-tests/cypress/integration/project/edit/explorer_spec.js
  integration-tests/cypress/integration/project/edit/object-context-menu_spec.js
  integration-tests/cypress/integration/project/edit/onboarding_spec.js
  integration-tests/cypress/integration/project/edit/project-context-menu_spec.js
  integration-tests/cypress/integration/project/edit/properties_spec.js
  integration-tests/cypress/integration/project/edit/representation-context-menu_spec.js
  integration-tests/cypress/integration/project/edit/representations_spec.js
  integration-tests/cypress/integration/project/edit/validation_specs.js
  integration-tests/cypress/integration/project/new-project_spec.js
  integration-tests/cypress/integration/project/projects-spec.js
  integration-tests/cypress/integration/project/upload-project_spec.js
  integration-tests/cypress/plugins/index.js
  integration-tests/cypress/support/index.js
  integration-tests/cypress/support/serverCommands.js
  integration-tests/cypress/support/testIdCommands.js
  integration-tests/package-lock.json
  integration-tests/package.json
Labels: pr: to review soon, priority: high

#151 [132] Add support for drag and drop from the explorer to a diagram
  backend/sirius-web-frontend/pom.xml
  backend/sirius-web-graphql-schema/pom.xml
  backend/sirius-web-graphql/pom.xml
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationDropOnDiagramDataFetcher.java
  backend/sirius-web-persistence/pom.xml
  backend/sirius-web-sample-application/pom.xml
  backend/sirius-web-services-api/pom.xml
  backend/sirius-web-services/pom.xml
  backend/sirius-web-spring/pom.xml
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to review soon, priority: high

#152 [releng] Switch to Sirius Components 2021.12.7
  backend/sirius-web-frontend/pom.xml
  backend/sirius-web-graphql-schema/pom.xml
  backend/sirius-web-graphql/pom.xml
  backend/sirius-web-persistence/pom.xml
  backend/sirius-web-sample-application/pom.xml
  backend/sirius-web-services-api/pom.xml
  backend/sirius-web-services/pom.xml
  backend/sirius-web-spring/pom.xml
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to review soon, priority: high, waiting for sirius components
