Repository eclipse-sirius/sirius-web, pull requests merged in 2021-07, with the labels that each got.

#605 [604] Use the ClickAwayListener to close the ContextMenu
  frontend/src/core/contextmenu/ContextMenu.tsx
Labels: pr: to be review soon, priority: high

#606 [test] Update the default vaue of the TestDiagramBuilder
  backend/sirius-web-diagrams-tests/src/main/java/org/eclipse/sirius/web/diagrams/tests/TestDiagramBuilder.java
Labels: pr: to review later, priority: low

#608 [607] Format the TypeScript code with Prettier
  frontend/package.json
  frontend/src/index.ts
  frontend/src/onboarding/NewDocumentArea.types.ts
  frontend/src/onboarding/NewRepresentationArea.types.ts
  frontend/src/onboarding/RepresentationsArea.types.ts
Labels: pr: to be review soon, priority: high

#609 [cleanup] Simplify studio definition feature flag implementation
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/domain/DomainConverter.java
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/ViewConverter.java
  backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/editingcontext/EditingContextEPackageService.java
  backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/representations/DynamicRepresentationDescriptionService.java
Labels: pr: to be review soon, priority: high

#618 [test] Make all tests run
  backend/sirius-web-api/pom.xml
  backend/sirius-web-collaborative-api/pom.xml
  backend/sirius-web-collaborative-diagrams-api/pom.xml
  backend/sirius-web-collaborative-forms-api/pom.xml
  backend/sirius-web-collaborative-trees-api/pom.xml
  backend/sirius-web-compatibility/pom.xml
  backend/sirius-web-components/pom.xml
  backend/sirius-web-core-api/pom.xml
  backend/sirius-web-diagrams-layout/pom.xml
  backend/sirius-web-diagrams/pom.xml
  backend/sirius-web-emf/pom.xml
  backend/sirius-web-forms/pom.xml
  backend/sirius-web-graphql-schema/pom.xml
  backend/sirius-web-graphql-utils/pom.xml
  backend/sirius-web-graphql/pom.xml
  backend/sirius-web-interpreter/pom.xml
  backend/sirius-web-persistence/pom.xml
  backend/sirius-web-services-api/pom.xml
  backend/sirius-web-services/pom.xml
  backend/sirius-web-spring-collaborative-diagrams/pom.xml
  backend/sirius-web-spring-collaborative-forms/pom.xml
  backend/sirius-web-spring-collaborative-trees/pom.xml
  backend/sirius-web-spring-collaborative/pom.xml
  backend/sirius-web-spring-graphql/pom.xml
  backend/sirius-web-spring-tests/pom.xml
  backend/sirius-web-spring/pom.xml
  backend/sirius-web-tests/pom.xml
  backend/sirius-web-trees/pom.xml
Labels: pr: to be review soon, priority: high

#624 Avoid resetting edge's routing in some cases when it is not needed
  backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/incremental/updater/ContainmentUpdater.java
Labels: area: backend, pr: to be review soon, priority: high

#630 [629] Improve validation messages
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/services/EMFValidationService.java
Labels: pr: to be review soon, priority: high

#627 [602] Improve the properties and validation view
  frontend/src/properties/PropertiesWebSocketContainer.tsx
  frontend/src/validation/ValidationWebSocketContainer.tsx
Labels: pr: to be review soon, priority: high

#636 [610] Revert the previous commit to remove the global CSS rule
  frontend/src/core/contextmenu/ContextMenu.module.css
Labels: pr: to be review soon, priority: high

#643 [releng] Bump version to v0.3.6
  backend/pom.xml
  backend/sirius-web-annotations-spring/pom.xml
  backend/sirius-web-annotations/pom.xml
  backend/sirius-web-api/pom.xml
  backend/sirius-web-collaborative-api/pom.xml
  backend/sirius-web-collaborative-diagrams-api/pom.xml
  backend/sirius-web-collaborative-forms-api/pom.xml
  backend/sirius-web-collaborative-trees-api/pom.xml
  backend/sirius-web-collaborative-validation-api/pom.xml
  backend/sirius-web-compatibility/pom.xml
  backend/sirius-web-components/pom.xml
  backend/sirius-web-core-api/pom.xml
  backend/sirius-web-diagrams-layout-api/pom.xml
  backend/sirius-web-diagrams-layout/pom.xml
  backend/sirius-web-diagrams-tests/pom.xml
  backend/sirius-web-diagrams/pom.xml
  backend/sirius-web-domain-design/pom.xml
  backend/sirius-web-domain-edit/pom.xml
  backend/sirius-web-domain/pom.xml
  backend/sirius-web-emf/pom.xml
  backend/sirius-web-forms-tests/pom.xml
  backend/sirius-web-forms/pom.xml
  backend/sirius-web-graphiql/pom.xml
  backend/sirius-web-graphql-schema/pom.xml
  backend/sirius-web-graphql-utils/pom.xml
  backend/sirius-web-graphql-voyager/pom.xml
  backend/sirius-web-graphql/pom.xml
  backend/sirius-web-interpreter/pom.xml
  backend/sirius-web-persistence/pom.xml
  backend/sirius-web-representations/pom.xml
  backend/sirius-web-services-api/pom.xml
  backend/sirius-web-services/pom.xml
  backend/sirius-web-spring-collaborative-diagrams/pom.xml
  backend/sirius-web-spring-collaborative-forms/pom.xml
  backend/sirius-web-spring-collaborative-trees/pom.xml
  backend/sirius-web-spring-collaborative-validation/pom.xml
  backend/sirius-web-spring-collaborative/pom.xml
  backend/sirius-web-spring-graphql-api/pom.xml
  backend/sirius-web-spring-graphql/pom.xml
  backend/sirius-web-spring-starter/pom.xml
  backend/sirius-web-spring-tests/pom.xml
  backend/sirius-web-spring/pom.xml
  backend/sirius-web-tests/pom.xml
  backend/sirius-web-trees/pom.xml
  backend/sirius-web-validation/pom.xml
  backend/sirius-web-view-edit/pom.xml
  backend/sirius-web-view/pom.xml
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to review soon, priority: high

#641 [640] Use accordions for the layout of the left and right sites
  frontend/src/explorer/Explorer.module.css
  frontend/src/properties/Properties.tsx
  frontend/src/workbench/LeftSite.tsx
  frontend/src/workbench/RightSite.tsx
  frontend/src/workbench/RightSite.types.ts
Labels: pr: to review soon, priority: high

#660 [releng] Switch to EMFJson 2.3.1-SNAPSHOT
  backend/sirius-web-emf/pom.xml
Labels: pr: to review soon, priority: high

#647 [fix] Enable support for configuring multiple origins for WS
  backend/sirius-web-spring-graphql/src/main/java/org/eclipse/sirius/web/spring/graphql/configuration/WebSocketConfiguration.java
Labels: pr: to review soon, priority: high

#652 [559] Fix SelectionDialog collaborative edition & lifecycle issues
  backend/sirius-web-collaborative-selection-api/src/main/java/org/eclipse/sirius/web/collaborative/selection/api/SelectionConfiguration.java
  backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/SelectModelElementVariableConverter.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/subscriptions/SubscriptionSelectionEventDataFetcher.java
  backend/sirius-web-selection/src/main/java/org/eclipse/sirius/web/selection/Selection.java
  backend/sirius-web-selection/src/main/java/org/eclipse/sirius/web/selection/description/SelectionDescription.java
  backend/sirius-web-selection/src/main/java/org/eclipse/sirius/web/selection/renderer/SelectionRenderer.java
  backend/sirius-web-spring-collaborative-selection/src/main/java/org/eclipse/sirius/web/spring/collaborative/selection/SelectionEventProcessor.java
  backend/sirius-web-spring-collaborative-selection/src/main/java/org/eclipse/sirius/web/spring/collaborative/selection/SelectionEventProcessorFactory.java
  frontend/src/diagram/DiagramWebSocketContainerMachine.ts
  frontend/src/selection/SelectionDialogWebSocketContainer.tsx
  frontend/src/selection/SelectionDialogWebSocketContainerMachine.ts
Labels: pr: to review soon, priority: high

#670 [releng] Bump to v0.4.0
  backend/pom.xml
  backend/sirius-web-annotations-spring/pom.xml
  backend/sirius-web-annotations/pom.xml
  backend/sirius-web-api/pom.xml
  backend/sirius-web-collaborative-api/pom.xml
  backend/sirius-web-collaborative-diagrams-api/pom.xml
  backend/sirius-web-collaborative-forms-api/pom.xml
  backend/sirius-web-collaborative-selection-api/pom.xml
  backend/sirius-web-collaborative-trees-api/pom.xml
  backend/sirius-web-collaborative-validation-api/pom.xml
  backend/sirius-web-compatibility/pom.xml
  backend/sirius-web-components/pom.xml
  backend/sirius-web-core-api/pom.xml
  backend/sirius-web-diagrams-layout-api/pom.xml
  backend/sirius-web-diagrams-layout/pom.xml
  backend/sirius-web-diagrams-tests/pom.xml
  backend/sirius-web-diagrams/pom.xml
  backend/sirius-web-domain-design/pom.xml
  backend/sirius-web-domain-edit/pom.xml
  backend/sirius-web-domain/pom.xml
  backend/sirius-web-emf/pom.xml
  backend/sirius-web-forms-tests/pom.xml
  backend/sirius-web-forms/pom.xml
  backend/sirius-web-graphiql/pom.xml
  backend/sirius-web-graphql-schema/pom.xml
  backend/sirius-web-graphql-utils/pom.xml
  backend/sirius-web-graphql-voyager/pom.xml
  backend/sirius-web-graphql/pom.xml
  backend/sirius-web-interpreter/pom.xml
  backend/sirius-web-persistence/pom.xml
  backend/sirius-web-representations/pom.xml
  backend/sirius-web-selection/pom.xml
  backend/sirius-web-services-api/pom.xml
  backend/sirius-web-services/pom.xml
  backend/sirius-web-spring-collaborative-diagrams/pom.xml
  backend/sirius-web-spring-collaborative-forms/pom.xml
  backend/sirius-web-spring-collaborative-selection/pom.xml
  backend/sirius-web-spring-collaborative-trees/pom.xml
  backend/sirius-web-spring-collaborative-validation/pom.xml
  backend/sirius-web-spring-collaborative/pom.xml
  backend/sirius-web-spring-graphql-api/pom.xml
  backend/sirius-web-spring-graphql/pom.xml
  backend/sirius-web-spring-starter/pom.xml
  backend/sirius-web-spring-tests/pom.xml
  backend/sirius-web-spring/pom.xml
  backend/sirius-web-tests/pom.xml
  backend/sirius-web-trees/pom.xml
  backend/sirius-web-validation/pom.xml
  backend/sirius-web-view-edit/pom.xml
  backend/sirius-web-view/pom.xml
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to review soon, priority: high
