Repository eclipse-sirius/sirius-web, pull requests merged in 2021-04, with the labels that each got.

#409 [407] Add support for edges' sizeComputationExpression
  backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/ColorDescriptionConverter.java
  backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/ContainerMappingStyleProvider.java
  backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/EdgeMappingStyleProvider.java
  backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/LabelStyleDescriptionConverter.java
  backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/NodeMappingStyleProvider.java
  backend/sirius-web-compatibility/src/test/java/org/eclipse/sirius/web/compat/diagrams/ColorDescriptionConverterTestCases.java
Labels: pr: to review later, priority: low

#410 [408] Add missing 'element' variable for delete tool
  backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/ToolConverter.java
Labels: pr: to review later, priority: low

#415 [fix] Fix NPE in forms on missing Group label expression
  backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/forms/GroupDescriptionConverter.java
Labels: pr: to review later, priority: low, type: bug 💥

#421 [420] Fix direct edit on diagrams
  backend/sirius-web-diagrams-services-api/src/main/java/org/eclipse/sirius/web/diagrams/services/api/IDiagramService.java
  backend/sirius-web-diagrams-services/src/main/java/org/eclipse/sirius/web/diagrams/services/DiagramService.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/EditLabelEventHandler.java
Labels: pr: to be review soon, priority: high

#434 [test] Fix path used to ignore generated files for windows users
  backend/sirius-web-tests/src/test/java/org/eclipse/sirius/web/tests/GeneralPurposeTestCases.java
Labels: pr: to be review soon, priority: low

#427 [426] Hide the contextual palette when zooming or scrolling/panning
  frontend/src/diagram/sprotty/DependencyInjection.ts
  frontend/src/diagram/sprotty/WebSocketDiagramServer.tsx
Labels: pr: to review later, priority: low

#438 [437] Expose "self" variable to VSM-based edge creation tools
  backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/services/diagrams/ToolProvider.java
Labels: pr: to be review soon, priority: high

#440 [439] Fix relation creation tool in VSM-based domain modeler
  backend/sirius-web-domain-design/src/main/resources/description/domain.odesign
Labels: pr: to be review soon, priority: high

#414 [397] Be more specific when looking for potential domain or view documents
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/services/EditingContextEPackageService.java
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/DynamicRepresentationDescriptionService.java
  backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/services/NoOpDocumentRepository.java
  backend/sirius-web-persistence/src/main/java/org/eclipse/sirius/web/persistence/repositories/IDocumentRepository.java
  backend/sirius-web-persistence/src/main/resources/db/sirius-web-named-queries.properties
Labels: area: backend, pr: to be review soon, priority: high

#447 [fix] Add missing properties files
  backend/sirius-web-domain-design/.settings/org.eclipse.core.resources.prefs
  backend/sirius-web-domain-design/.settings/org.eclipse.core.runtime.prefs
  backend/sirius-web-domain-design/.settings/org.eclipse.jdt.apt.core.prefs
  backend/sirius-web-domain-design/.settings/org.eclipse.jdt.core.prefs
  backend/sirius-web-domain-design/.settings/org.eclipse.jdt.ui.prefs
  backend/sirius-web-domain-design/.settings/org.eclipse.m2e.core.prefs
  backend/sirius-web-domain-design/.settings/org.springframework.ide.eclipse.prefs
Labels: pr: to be review soon, priority: low

#444 [enh] Upgrade Batik to the latest version (1.14)
  backend/sirius-web-diagrams-layout/pom.xml
Labels: pr: to be review soon, priority: low

#445 [releng] Upgrade to Spring Boot 2.4.5
  backend/sirius-web-annotations-spring/pom.xml
  backend/sirius-web-annotations/pom.xml
  backend/sirius-web-api/pom.xml
  backend/sirius-web-collaborative-api/pom.xml
  backend/sirius-web-collaborative-diagrams-api/pom.xml
  backend/sirius-web-collaborative-forms-api/pom.xml
  backend/sirius-web-collaborative-trees-api/pom.xml
  backend/sirius-web-compatibility/pom.xml
  backend/sirius-web-components/pom.xml
  backend/sirius-web-core-api/pom.xml
  backend/sirius-web-diagrams-layout-api/pom.xml
  backend/sirius-web-diagrams-layout/pom.xml
  backend/sirius-web-diagrams-services-api/pom.xml
  backend/sirius-web-diagrams-services/pom.xml
  backend/sirius-web-diagrams-tests/pom.xml
  backend/sirius-web-diagrams/pom.xml
  backend/sirius-web-domain-design/pom.xml
  backend/sirius-web-domain-edit/pom.xml
  backend/sirius-web-domain/pom.xml
  backend/sirius-web-emf/pom.xml
  backend/sirius-web-forms-tests/pom.xml
  backend/sirius-web-forms/pom.xml
  backend/sirius-web-graphiql/pom.xml
  backend/sirius-web-graphql-schema/pom.xml
  backend/sirius-web-graphql-utils/pom.xml
  backend/sirius-web-graphql-voyager/pom.xml
  backend/sirius-web-graphql/pom.xml
  backend/sirius-web-interpreter/pom.xml
  backend/sirius-web-persistence/pom.xml
  backend/sirius-web-representations/pom.xml
  backend/sirius-web-services-api/pom.xml
  backend/sirius-web-services/pom.xml
  backend/sirius-web-spring-collaborative-diagrams/pom.xml
  backend/sirius-web-spring-collaborative-forms/pom.xml
  backend/sirius-web-spring-collaborative-trees/pom.xml
  backend/sirius-web-spring-collaborative/pom.xml
  backend/sirius-web-spring-graphql-api/pom.xml
  backend/sirius-web-spring-graphql/pom.xml
  backend/sirius-web-spring-starter/pom.xml
  backend/sirius-web-spring-tests/pom.xml
  backend/sirius-web-spring/pom.xml
  backend/sirius-web-test-diagrams-only-application/pom.xml
  backend/sirius-web-test-sample-application/pom.xml
  backend/sirius-web-tests/pom.xml
  backend/sirius-web-trees/pom.xml
  backend/sirius-web-view-edit/pom.xml
  backend/sirius-web-view/pom.xml
Labels: pr: to be review soon, priority: low

#436 [446] Print in the console the elk graph in json
  backend/sirius-web-diagrams-layout/pom.xml
  backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/LayoutService.java
Labels: pr: to review later, priority: low

#448 [releng] Switch to 0.2.19
  backend/pom.xml
  backend/sirius-web-annotations-spring/pom.xml
  backend/sirius-web-annotations/pom.xml
  backend/sirius-web-api/pom.xml
  backend/sirius-web-collaborative-api/pom.xml
  backend/sirius-web-collaborative-diagrams-api/pom.xml
  backend/sirius-web-collaborative-forms-api/pom.xml
  backend/sirius-web-collaborative-trees-api/pom.xml
  backend/sirius-web-compatibility/pom.xml
  backend/sirius-web-components/pom.xml
  backend/sirius-web-core-api/pom.xml
  backend/sirius-web-diagrams-layout-api/pom.xml
  backend/sirius-web-diagrams-layout/pom.xml
  backend/sirius-web-diagrams-services-api/pom.xml
  backend/sirius-web-diagrams-services/pom.xml
  backend/sirius-web-diagrams-tests/pom.xml
  backend/sirius-web-diagrams/pom.xml
  backend/sirius-web-domain-design/pom.xml
  backend/sirius-web-domain-edit/pom.xml
  backend/sirius-web-domain/pom.xml
  backend/sirius-web-emf/pom.xml
  backend/sirius-web-forms-tests/pom.xml
  backend/sirius-web-forms/pom.xml
  backend/sirius-web-graphiql/pom.xml
  backend/sirius-web-graphql-schema/pom.xml
  backend/sirius-web-graphql-utils/pom.xml
  backend/sirius-web-graphql-voyager/pom.xml
  backend/sirius-web-graphql/pom.xml
  backend/sirius-web-interpreter/pom.xml
  backend/sirius-web-persistence/pom.xml
  backend/sirius-web-representations/pom.xml
  backend/sirius-web-services-api/pom.xml
  backend/sirius-web-services/pom.xml
  backend/sirius-web-spring-collaborative-diagrams/pom.xml
  backend/sirius-web-spring-collaborative-forms/pom.xml
  backend/sirius-web-spring-collaborative-trees/pom.xml
  backend/sirius-web-spring-collaborative/pom.xml
  backend/sirius-web-spring-graphql-api/pom.xml
  backend/sirius-web-spring-graphql/pom.xml
  backend/sirius-web-spring-starter/pom.xml
  backend/sirius-web-spring-tests/pom.xml
  backend/sirius-web-spring/pom.xml
  backend/sirius-web-test-diagrams-only-application/pom.xml
  backend/sirius-web-test-sample-application/pom.xml
  backend/sirius-web-tests/pom.xml
  backend/sirius-web-trees/pom.xml
  backend/sirius-web-view-edit/pom.xml
  backend/sirius-web-view/pom.xml
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to be review soon, priority: high

#245 [doc] Complete ADR-007
  doc/adrs/007_adopt_stable_identifiers_for_diagrams.adoc
Labels: pr: to review later, priority: low

#223 Add ADR describing the domain DSL (simplified Ecore)
  doc/adrs/018_adopt_a_subset_of_ecore_to_define_data_schemas.adoc
Labels: pr: to review later, priority: low

#246 [243] Add ADR for simple diagram definitions
  doc/adrs/019_support_simple_diagram_definitions.adoc
Labels: pr: to review later, priority: low
