Repository eclipse-sirius/sirius-web, pull requests merged in 2021-03, with the labels that each got.

#363 [cleanup] Fix the number of some of the latest ADR
  doc/adrs/012_incremental_layout_move_and_create_element_location.adoc
  doc/adrs/013_refactor_incremental_layout.adoc
  doc/adrs/014_add_a_correlation_identifier_to_inputs_and_payloads.adoc
Labels: pr: to review later, priority: low

#364 [360] Restore the use of the auto layout on diagram creation
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/DiagramCreationService.java
Labels: pr: to be review soon, priority: high

#366 [351] Transform ChangeKind in ChangeDescription with the source of the change
  backend/sirius-web-collaborative-api/src/main/java/org/eclipse/sirius/web/collaborative/api/services/ChangeDescription.java
  backend/sirius-web-collaborative-api/src/main/java/org/eclipse/sirius/web/collaborative/api/services/EventHandlerResponse.java
  backend/sirius-web-collaborative-api/src/main/java/org/eclipse/sirius/web/collaborative/api/services/IRepresentationEventProcessor.java
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/services/CreateDocumentEventHandler.java
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/services/DeleteDocumentEventHandler.java
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/services/RenameDocumentEventHandler.java
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/services/UploadDocumentEventHandler.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/DiagramEventProcessor.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/CreateDiagramEventHandler.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/DeleteFromDiagramEventHandler.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/EditLabelEventHandler.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/InvokeEdgeToolOnDiagramEventHandler.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/InvokeNodeToolOnDiagramEventHandler.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/RenameDiagramEventHandler.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/UpdateNodePositionEventHandler.java
  backend/sirius-web-spring-collaborative-forms/src/main/java/org/eclipse/sirius/web/spring/collaborative/forms/FormEventProcessor.java
  backend/sirius-web-spring-collaborative-forms/src/main/java/org/eclipse/sirius/web/spring/collaborative/forms/PropertiesEventProcessor.java
  backend/sirius-web-spring-collaborative-forms/src/main/java/org/eclipse/sirius/web/spring/collaborative/forms/handlers/CreateFormEventHandler.java
  backend/sirius-web-spring-collaborative-forms/src/main/java/org/eclipse/sirius/web/spring/collaborative/forms/handlers/EditCheckboxEventHandler.java
  backend/sirius-web-spring-collaborative-forms/src/main/java/org/eclipse/sirius/web/spring/collaborative/forms/handlers/EditRadioEventHandler.java
  backend/sirius-web-spring-collaborative-forms/src/main/java/org/eclipse/sirius/web/spring/collaborative/forms/handlers/EditSelectEventHandler.java
  backend/sirius-web-spring-collaborative-forms/src/main/java/org/eclipse/sirius/web/spring/collaborative/forms/handlers/EditTextfieldEventHandler.java
  backend/sirius-web-spring-collaborative-trees/src/main/java/org/eclipse/sirius/web/spring/collaborative/trees/TreeEventProcessor.java
  backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/handlers/CreateChildEventHandler.java
  backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/handlers/CreateRootObjectEventHandler.java
  backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/handlers/DeleteObjectEventHandler.java
  backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/handlers/DeleteRepresentationEventHandler.java
  backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/handlers/RenameObjectEventHandler.java
  backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/projects/EditingContextEventProcessor.java
  backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/projects/RenameProjectEventHandler.java
  backend/sirius-web-spring-collaborative/src/test/java/org/eclipse/sirius/web/spring/collaborative/handlers/CreateChildEventHandlerTestCases.java
  backend/sirius-web-spring-collaborative/src/test/java/org/eclipse/sirius/web/spring/collaborative/handlers/CreateRootObjectEventHandlerTestCases.java
  backend/sirius-web-spring-collaborative/src/test/java/org/eclipse/sirius/web/spring/collaborative/handlers/DeleteObjectEventHandlerTestCases.java
  backend/sirius-web-spring-collaborative/src/test/java/org/eclipse/sirius/web/spring/collaborative/handlers/RenameObjectEventHandlerTestCases.java
  backend/sirius-web-spring-collaborative/src/test/java/org/eclipse/sirius/web/spring/collaborative/handlers/RenameProjectEventHandlerTestCases.java
Labels: pr: to be review soon, priority: high

#340 Add an ADR for the resizing support
  doc/adrs/015_add_resize_support_in_diagram.adoc
Labels: pr: to be review soon, priority: high

#350 Add new builders for position and size
  backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/LayoutedDiagramProvider.java
  backend/sirius-web-diagrams-layout/src/test/java/org/eclipse/sirius/web/diagrams/layout/services/DiagramConverterTestCases.java
  backend/sirius-web-diagrams-layout/src/test/java/org/eclipse/sirius/web/diagrams/layout/services/ImageNodeStyleSizeProviderTestCases.java
  backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/ImageNodeStyleSizeProvider.java
  backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/ImageSizeProvider.java
  backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/Position.java
  backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/Size.java
  backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/TextBoundsProvider.java
  backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/components/DiagramComponent.java
  backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/components/EdgeLabelPositionProvider.java
  backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/components/EdgeRoutingPointsProvider.java
  backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/components/NodeComponent.java
  backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/components/NodeLabelPositionProvider.java
  backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/components/NodePositionProvider.java
  backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/components/NodeSizeProvider.java
  backend/sirius-web-diagrams/src/test/java/org/eclipse/sirius/web/diagrams/components/EdgeLabelPositionProviderTestCases.java
  backend/sirius-web-diagrams/src/test/java/org/eclipse/sirius/web/diagrams/components/EdgeRoutingPointsProviderTestCases.java
  backend/sirius-web-diagrams/src/test/java/org/eclipse/sirius/web/diagrams/components/NodeLabelPositionProviderTestCases.java
  backend/sirius-web-diagrams/src/test/java/org/eclipse/sirius/web/diagrams/components/NodePositionProviderTestCases.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/InvokeNodeToolOnDiagramEventHandler.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/UpdateNodePositionEventHandler.java
  backend/sirius-web-spring-collaborative-diagrams/src/test/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/RenameDiagramEventHandlerTestCases.java
Labels: pr: to be review soon, priority: high

#354 [346] Fix handling of Unset VSM operation
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/compatibility/modeloperations/UnsetOperationHandler.java
  backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/compatibility/operations/UnsetOperationHandlerTestCases.java
Labels: pr: to be review soon, priority: high

#400 [cleanup] Remove dead code
  backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/services/diagrams/tools/CanCreateMappingTester.java
  backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/services/diagrams/tools/ToolDescriptionQuery.java
Labels: pr: to review later, priority: low

#401 [269] Upgrade to Spring Boot 2.4.4
  backend/sirius-web-annotations-spring/pom.xml
  backend/sirius-web-annotations/pom.xml
  backend/sirius-web-api/pom.xml
  backend/sirius-web-collaborative-api/pom.xml
  backend/sirius-web-collaborative-diagrams-api/pom.xml
  backend/sirius-web-collaborative-forms-api/pom.xml
  backend/sirius-web-collaborative-trees-api/pom.xml
  backend/sirius-web-compatibility/pom.xml
  backend/sirius-web-components/pom.xml
  backend/sirius-web-core-api/pom.xml
  backend/sirius-web-diagrams-layout-api/pom.xml
  backend/sirius-web-diagrams-layout/pom.xml
  backend/sirius-web-diagrams-services-api/pom.xml
  backend/sirius-web-diagrams-services/pom.xml
  backend/sirius-web-diagrams-tests/pom.xml
  backend/sirius-web-diagrams/pom.xml
  backend/sirius-web-domain-design/pom.xml
  backend/sirius-web-domain-edit/pom.xml
  backend/sirius-web-domain/pom.xml
  backend/sirius-web-emf/pom.xml
  backend/sirius-web-forms-tests/pom.xml
  backend/sirius-web-forms/pom.xml
  backend/sirius-web-graphiql/pom.xml
  backend/sirius-web-graphql-schema/pom.xml
  backend/sirius-web-graphql-utils/pom.xml
  backend/sirius-web-graphql-voyager/pom.xml
  backend/sirius-web-graphql/pom.xml
  backend/sirius-web-interpreter/pom.xml
  backend/sirius-web-persistence/pom.xml
  backend/sirius-web-representations/pom.xml
  backend/sirius-web-services-api/pom.xml
  backend/sirius-web-services/pom.xml
  backend/sirius-web-spring-collaborative-diagrams/pom.xml
  backend/sirius-web-spring-collaborative-forms/pom.xml
  backend/sirius-web-spring-collaborative-trees/pom.xml
  backend/sirius-web-spring-collaborative/pom.xml
  backend/sirius-web-spring-graphql-api/pom.xml
  backend/sirius-web-spring-graphql/pom.xml
  backend/sirius-web-spring-starter/pom.xml
  backend/sirius-web-spring-tests/pom.xml
  backend/sirius-web-spring/pom.xml
  backend/sirius-web-test-diagrams-only-application/pom.xml
  backend/sirius-web-test-sample-application/pom.xml
  backend/sirius-web-tests/pom.xml
  backend/sirius-web-trees/pom.xml
  backend/sirius-web-view-edit/pom.xml
  backend/sirius-web-view/pom.xml
Labels: area: backend, pr: to review later, priority: low

#404 [releng] Switch to 0.2.18
  backend/pom.xml
  backend/sirius-web-annotations-spring/pom.xml
  backend/sirius-web-annotations/pom.xml
  backend/sirius-web-api/pom.xml
  backend/sirius-web-collaborative-api/pom.xml
  backend/sirius-web-collaborative-diagrams-api/pom.xml
  backend/sirius-web-collaborative-forms-api/pom.xml
  backend/sirius-web-collaborative-trees-api/pom.xml
  backend/sirius-web-compatibility/pom.xml
  backend/sirius-web-components/pom.xml
  backend/sirius-web-core-api/pom.xml
  backend/sirius-web-diagrams-layout-api/pom.xml
  backend/sirius-web-diagrams-layout/pom.xml
  backend/sirius-web-diagrams-services-api/pom.xml
  backend/sirius-web-diagrams-services/pom.xml
  backend/sirius-web-diagrams-tests/pom.xml
  backend/sirius-web-diagrams/pom.xml
  backend/sirius-web-domain-design/pom.xml
  backend/sirius-web-domain-edit/pom.xml
  backend/sirius-web-domain/pom.xml
  backend/sirius-web-emf/pom.xml
  backend/sirius-web-forms-tests/pom.xml
  backend/sirius-web-forms/pom.xml
  backend/sirius-web-graphiql/pom.xml
  backend/sirius-web-graphql-schema/pom.xml
  backend/sirius-web-graphql-utils/pom.xml
  backend/sirius-web-graphql-voyager/pom.xml
  backend/sirius-web-graphql/pom.xml
  backend/sirius-web-interpreter/pom.xml
  backend/sirius-web-persistence/pom.xml
  backend/sirius-web-representations/pom.xml
  backend/sirius-web-services-api/pom.xml
  backend/sirius-web-services/pom.xml
  backend/sirius-web-spring-collaborative-diagrams/pom.xml
  backend/sirius-web-spring-collaborative-forms/pom.xml
  backend/sirius-web-spring-collaborative-trees/pom.xml
  backend/sirius-web-spring-collaborative/pom.xml
  backend/sirius-web-spring-graphql-api/pom.xml
  backend/sirius-web-spring-graphql/pom.xml
  backend/sirius-web-spring-starter/pom.xml
  backend/sirius-web-spring-tests/pom.xml
  backend/sirius-web-spring/pom.xml
  backend/sirius-web-test-diagrams-only-application/pom.xml
  backend/sirius-web-test-sample-application/pom.xml
  backend/sirius-web-tests/pom.xml
  backend/sirius-web-trees/pom.xml
  backend/sirius-web-view-edit/pom.xml
  backend/sirius-web-view/pom.xml
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to be review soon, priority: high
