Repository eclipse-sirius/sirius-web, pull requests merged in 2021-04, with the labels that each got.

#52 [releng] Upgrade to Spring Boot 2.4.5
  backend/sirius-web-frontend/pom.xml
  backend/sirius-web-sample-application/pom.xml
Labels: pr: to be review soon, priority: low

#54 [releng] Upgrade to Sirius Components 0.2.19
  backend/sirius-web-frontend/pom.xml
  backend/sirius-web-sample-application/pom.xml
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to be review soon, priority: high

#55 [402] Move the views in Sirius Web
  backend/sirius-web-frontend/pom.xml
  backend/sirius-web-sample-application/pom.xml
  backend/sirius-web-sample-application/src/main/resources/application-dev.properties
  frontend/package-lock.json
  frontend/package.json
  frontend/src/main/Main.tsx
  frontend/src/views/edit-project/EditProjectNavbar/EditProjectNavbar.module.css
  frontend/src/views/edit-project/EditProjectNavbar/EditProjectNavbar.tsx
  frontend/src/views/edit-project/EditProjectNavbar/EditProjectNavbar.types.ts
  frontend/src/views/edit-project/EditProjectNavbar/EditProjectNavbarContextMenu.tsx
  frontend/src/views/edit-project/EditProjectNavbar/EditProjectNavbarContextMenu.types.ts
  frontend/src/views/edit-project/EditProjectNavbar/machine.ts
  frontend/src/views/edit-project/EditProjectNavbar/reducer.ts
  frontend/src/views/edit-project/EditProjectView.tsx
  frontend/src/views/edit-project/EditProjectView.types.ts
  frontend/src/views/edit-project/EditProjectViewMachine.ts
  frontend/src/views/new-project/NewProjectView.tsx
  frontend/src/views/new-project/NewProjectView.types.ts
  frontend/src/views/new-project/NewProjectViewMachine.ts
  frontend/src/views/projects/ProjectsView.tsx
  frontend/src/views/projects/ProjectsView.types.ts
  frontend/src/views/projects/ProjectsViewMachine.ts
  frontend/src/views/upload-project/UploadProjectView.tsx
  frontend/src/views/upload-project/UploadProjectViewMachine.tsx
  frontend/tsconfig.json
Labels: area: frontend, pr: to be review soon, priority: low
