Repository eclipse-sirius/sirius-web, pull requests merged in 2021-11, with the labels that each got.

#806 [804] List and update the various configuration properties
  CHANGELOG.adoc
  backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/projects/EditingContextEventProcessorRegistry.java
  backend/sirius-web-spring-graphql/src/main/java/org/eclipse/sirius/web/spring/graphql/configuration/WebSocketConfiguration.java
  backend/sirius-web-spring-starter/pom.xml
  backend/sirius-web-spring-starter/src/main/java/org/eclipse/sirius/web/starter/configurationproperties/CorsConfigurationProperty.java
  backend/sirius-web-spring-starter/src/main/java/org/eclipse/sirius/web/starter/configurationproperties/EditingContextConfigurationProperty.java
  backend/sirius-web-spring-starter/src/main/java/org/eclipse/sirius/web/starter/configurationproperties/SiriusComponentsConfigurationProperties.java
  doc/configuration.adoc
Labels: pr: to review soon, priority: high

#800 [799] Add tooltips to the diagram toolbar's icons
  CHANGELOG.adoc
  frontend/src/diagram/Toolbar.tsx
Labels: type: enhancement ✨, pr: to review later, priority: low

#809 [releng] Bump version to v0.5.1
  backend/pom.xml
  backend/sirius-web-annotations-spring/pom.xml
  backend/sirius-web-annotations/pom.xml
  backend/sirius-web-api/pom.xml
  backend/sirius-web-compatibility/pom.xml
  backend/sirius-web-components/pom.xml
  backend/sirius-web-core-api/pom.xml
  backend/sirius-web-diagrams-layout-api/pom.xml
  backend/sirius-web-diagrams-layout/pom.xml
  backend/sirius-web-diagrams-tests/pom.xml
  backend/sirius-web-diagrams/pom.xml
  backend/sirius-web-domain-design/pom.xml
  backend/sirius-web-domain-edit/pom.xml
  backend/sirius-web-domain/pom.xml
  backend/sirius-web-emf/pom.xml
  backend/sirius-web-forms-tests/pom.xml
  backend/sirius-web-forms/pom.xml
  backend/sirius-web-graphiql/pom.xml
  backend/sirius-web-graphql-utils/pom.xml
  backend/sirius-web-graphql-voyager/pom.xml
  backend/sirius-web-interpreter/pom.xml
  backend/sirius-web-representations/pom.xml
  backend/sirius-web-selection/pom.xml
  backend/sirius-web-spring-collaborative-diagrams/pom.xml
  backend/sirius-web-spring-collaborative-forms/pom.xml
  backend/sirius-web-spring-collaborative-selection/pom.xml
  backend/sirius-web-spring-collaborative-trees/pom.xml
  backend/sirius-web-spring-collaborative-validation/pom.xml
  backend/sirius-web-spring-collaborative/pom.xml
  backend/sirius-web-spring-graphql-api/pom.xml
  backend/sirius-web-spring-graphql/pom.xml
  backend/sirius-web-spring-starter/pom.xml
  backend/sirius-web-spring-tests/pom.xml
  backend/sirius-web-tests/pom.xml
  backend/sirius-web-trees/pom.xml
  backend/sirius-web-validation/pom.xml
  backend/sirius-web-view-edit/pom.xml
  backend/sirius-web-view/pom.xml
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to review soon, priority: high

#819 [818] Contribute the ADR about a more structured selection
  CHANGELOG.adoc
  doc/adrs/036_adopt_a_more_structured_selection.adoc
Labels: pr: to review soon, priority: high

#824 [cleanup] Add a task to display typescript errors in vscode problems
  CHANGELOG.adoc
  frontend/.vscode/tasks.json
  frontend/tsconfig-noEmit.json
Labels: pr: to review soon, priority: low

#612 Add support for external java actions
  .gitignore
  CHANGELOG.adoc
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/compatibility/api/IExternalJavaActionProvider.java
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/compatibility/modeloperations/ChildModelOperationHandler.java
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/compatibility/modeloperations/ExternalJavaActionOperationHandler.java
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/compatibility/modeloperations/ModelOperationHandlerSwitch.java
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/configuration/CompatibilityConfiguration.java
  backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/compatibility/diagrams/EdgeMappingConverterTests.java
  backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/compatibility/operations/ChangeContextOperationHandlerTests.java
  backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/compatibility/operations/CreateInstanceOperationHandlerTests.java
  backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/compatibility/operations/CreateViewOperationHandlerTests.java
  backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/compatibility/operations/DeleteViewOperationHandlerTests.java
  backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/compatibility/operations/ForOperationHandlerTests.java
  backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/compatibility/operations/IfOperationHandlerTests.java
  backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/compatibility/operations/LetOperationHandlerTests.java
  backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/compatibility/operations/MoveElementOperationHandlerTests.java
  backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/compatibility/operations/RemoveElementOperationHandlerTests.java
  backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/compatibility/operations/SetValueOperationHandlerTests.java
  backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/compatibility/operations/SwitchOperationHandlerTests.java
  backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/compatibility/operations/UnsetOperationHandlerTests.java
  backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/compatibility/properties/FormRendererTests.java
Labels: pr: to review soon, priority: low

#214 [154] Add edit edge label support
  CHANGELOG.adoc
  backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/EdgeMappingConverter.java
  backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/description/EdgeDescription.java
  backend/sirius-web-diagrams/src/test/java/org/eclipse/sirius/web/diagrams/renderer/DiagramRendererEdgeTests.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/DiagramQueryService.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/api/IDiagramQueryService.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/EditLabelEventHandler.java
  frontend/src/diagram/sprotty/WebSocketDiagramServer.tsx
  frontend/src/diagram/sprotty/__tests__/convertDiagram.test.ts
  frontend/src/diagram/sprotty/convertDiagram.tsx
Labels: pr: to review soon, priority: high

#827 Setup the Node.SELECTED_NODE and SELECTED OBJECT independently
  CHANGELOG.adoc
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/InvokeNodeToolOnDiagramEventHandler.java
Labels: pr: to review soon, priority: low

#829 [releng] Switch some projects from Spring Boot 2.5.1 to 2.5.6
  backend/sirius-web-selection/pom.xml
  backend/sirius-web-spring-collaborative-selection/pom.xml
  backend/sirius-web-spring-collaborative-validation/pom.xml
  backend/sirius-web-validation/pom.xml
Labels: pr: to review soon, priority: high

#842 [releng] Add script to check license compatibility
  scripts/check-licenses
Labels: area: build 🚧, type: enhancement ✨, pr: to review later, priority: low
