Repository eclipse-sirius/sirius-web, pull requests merged in 2021-06, with the labels that each got.

#526 [325] Move ViewExtensionDescriptionConverter to sirius-web-compatibility
  backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/forms/ViewExtensionDescriptionConverter.java
  backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/compatibility/properties/FormRendererTestCases.java
Labels: pr: to be review soon, priority: low

#522 ✨ [520] Add support for providing Java services to dynamic modelers
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/DynamicRepresentationDescriptionService.java
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/IJavaServiceProvider.java
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/ToolInterpreter.java
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/ViewConverter.java
  backend/sirius-web-representations/src/main/java/org/eclipse/sirius/web/representations/VariableManager.java
Labels: pr: to be review soon, priority: high, type: feature request 🤔

#531 [fix] Force the use of guava 30
  backend/sirius-web-diagrams-layout/pom.xml
Labels: pr: to be review soon, priority: high

#527 [500] Add initial support for conditional styles
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/StylesFactory.java
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/ViewConverter.java
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/ViewPropertiesConfigurer.java
  backend/sirius-web-view-edit/src/main/java/org/eclipse/sirius/web/view/provider/ConditionalEdgeStyleItemProvider.java
  backend/sirius-web-view-edit/src/main/java/org/eclipse/sirius/web/view/provider/ConditionalItemProvider.java
  backend/sirius-web-view-edit/src/main/java/org/eclipse/sirius/web/view/provider/ConditionalNodeStyleItemProvider.java
  backend/sirius-web-view-edit/src/main/java/org/eclipse/sirius/web/view/provider/EdgeDescriptionItemProvider.java
  backend/sirius-web-view-edit/src/main/java/org/eclipse/sirius/web/view/provider/NodeDescriptionItemProvider.java
  backend/sirius-web-view-edit/src/main/java/org/eclipse/sirius/web/view/provider/ViewItemProviderAdapterFactory.java
  backend/sirius-web-view-edit/src/main/resources/icons/full/obj16/Conditional.gif
  backend/sirius-web-view-edit/src/main/resources/icons/full/obj16/ConditionalEdgeStyle.gif
  backend/sirius-web-view-edit/src/main/resources/icons/full/obj16/ConditionalNodeStyle.gif
  backend/sirius-web-view-edit/src/main/resources/plugin.properties
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/Conditional.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/ConditionalEdgeStyle.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/ConditionalNodeStyle.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/EdgeDescription.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/NodeDescription.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/ViewFactory.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/ViewPackage.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/ConditionalEdgeStyleImpl.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/ConditionalImpl.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/ConditionalNodeStyleImpl.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/EdgeDescriptionImpl.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/NodeDescriptionImpl.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/ViewFactoryImpl.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/ViewPackageImpl.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/util/ViewAdapterFactory.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/util/ViewSwitch.java
  backend/sirius-web-view/src/main/resources/model/view.ecore
  backend/sirius-web-view/src/main/resources/model/view.genmodel
Labels: pr: to be review soon, priority: high

#525 ✨ [512] View DSL: Add support for layout mode configuration
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/ViewConverter.java
  backend/sirius-web-view-edit/src/main/java/org/eclipse/sirius/web/view/provider/DiagramDescriptionItemProvider.java
  backend/sirius-web-view-edit/src/main/resources/plugin.properties
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/DiagramDescription.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/ViewPackage.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/DiagramDescriptionImpl.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/ViewPackageImpl.java
  backend/sirius-web-view/src/main/resources/model/view.ecore
  backend/sirius-web-view/src/main/resources/model/view.genmodel
Labels: area: backend, pr: to be review soon, priority: high

#528 [431] Fix project and document upload/download that contain instance of a dynamically-defined domain
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/services/DocumentService.java
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/services/ProjectExportService.java
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/services/UploadDocumentEventHandler.java
Labels: pr: to be review soon, priority: high

#533 [532] Improve explorer child creation
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/services/EditService.java
  frontend/src/modals/new-object/NewObjectModal.tsx
Labels: pr: to be review soon, priority: high

#538 [537] Layout configurator override issue
  backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/SiriusWebLayoutConfigurator.java
Labels: pr: to be review soon, priority: low

#536 [enh] Add the initial support of contributed representations
  frontend/src/onboarding/NewRepresentationArea.tsx
  frontend/src/properties/PropertiesWebSocketContainer.tsx
  frontend/src/properties/PropertiesWebSocketContainerMachine.ts
  frontend/src/tree/TreeItem.tsx
  frontend/src/workbench/RepresentationContext.ts
  frontend/src/workbench/RepresentationContext.types.ts
  frontend/src/workbench/Workbench.tsx
  frontend/src/workbench/WorkbenchMachine.ts
Labels: pr: to be review soon, priority: high

#543 [fix] Force the use of guava 30
  backend/sirius-web-diagrams-layout/pom.xml
Labels: pr: to be review soon, priority: high

#542 [fix] Fix open existing representation from onboarding area
  frontend/src/onboarding/RepresentationsArea.tsx
  frontend/src/workbench/OnboardArea.tsx
Labels: pr: to be review soon, priority: high

#544 [enh] Only enable Domain and View conversion if the proper feature flag is set
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/domain/DomainConverter.java
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/services/EditingContextEPackageService.java
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/DynamicRepresentationDescriptionService.java
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/ViewConverter.java
Labels: pr: to be review soon, priority: high

#553 [515] Build artifact's sources
  backend/sirius-web-annotations-spring/pom.xml
  backend/sirius-web-annotations/pom.xml
  backend/sirius-web-api/pom.xml
  backend/sirius-web-collaborative-api/pom.xml
  backend/sirius-web-collaborative-diagrams-api/pom.xml
  backend/sirius-web-collaborative-forms-api/pom.xml
  backend/sirius-web-collaborative-trees-api/pom.xml
  backend/sirius-web-compatibility/pom.xml
  backend/sirius-web-components/pom.xml
  backend/sirius-web-core-api/pom.xml
  backend/sirius-web-diagrams-layout-api/pom.xml
  backend/sirius-web-diagrams-layout/pom.xml
  backend/sirius-web-diagrams-services-api/pom.xml
  backend/sirius-web-diagrams-services/pom.xml
  backend/sirius-web-diagrams-tests/pom.xml
  backend/sirius-web-diagrams/pom.xml
  backend/sirius-web-domain-design/pom.xml
  backend/sirius-web-domain-edit/pom.xml
  backend/sirius-web-domain/pom.xml
  backend/sirius-web-emf/pom.xml
  backend/sirius-web-forms-tests/pom.xml
  backend/sirius-web-forms/pom.xml
  backend/sirius-web-graphql-schema/pom.xml
  backend/sirius-web-graphql-utils/pom.xml
  backend/sirius-web-graphql/pom.xml
  backend/sirius-web-interpreter/pom.xml
  backend/sirius-web-persistence/pom.xml
  backend/sirius-web-representations/pom.xml
  backend/sirius-web-services-api/pom.xml
  backend/sirius-web-services/pom.xml
  backend/sirius-web-spring-collaborative-diagrams/pom.xml
  backend/sirius-web-spring-collaborative-forms/pom.xml
  backend/sirius-web-spring-collaborative-trees/pom.xml
  backend/sirius-web-spring-collaborative/pom.xml
  backend/sirius-web-spring-graphql-api/pom.xml
  backend/sirius-web-spring-graphql/pom.xml
  backend/sirius-web-spring-starter/pom.xml
  backend/sirius-web-spring-tests/pom.xml
  backend/sirius-web-spring/pom.xml
  backend/sirius-web-test-diagrams-only-application/pom.xml
  backend/sirius-web-test-sample-application/pom.xml
  backend/sirius-web-tests/pom.xml
  backend/sirius-web-trees/pom.xml
  backend/sirius-web-view-edit/pom.xml
  backend/sirius-web-view/pom.xml
Labels: pr: to be review soon, priority: high

#575 [doc] Add the first version of the ADR on the validation
  doc/adrs/020_add_support_for_validation_in_the_workbench.adoc
  doc/adrs/021_add_validation_support_to_forms.adoc
Labels: pr: to be review soon, priority: high

#576 [doc] Contribute the ADR for the support of the selection dialog
  doc/adrs/022_add_support_for_selection_dialog.adoc
Labels: pr: to be review soon, priority: high

#577 [doc] Contribute the ADR for the move of our business code to Sirius Web
  doc/adrs/023_move_business_code_from_sirius_components_to_sirius_web.adoc
Labels: pr: to be review soon, priority: high

#573 [572] Move the object type name in a tooltip for tree items
  frontend/src/tree/TreeItem.tsx
Labels: pr: to be review soon, priority: low

#581 [releng] Bump version to v0.3.2
  backend/pom.xml
  backend/sirius-web-annotations-spring/pom.xml
  backend/sirius-web-annotations/pom.xml
  backend/sirius-web-api/pom.xml
  backend/sirius-web-collaborative-api/pom.xml
  backend/sirius-web-collaborative-diagrams-api/pom.xml
  backend/sirius-web-collaborative-forms-api/pom.xml
  backend/sirius-web-collaborative-trees-api/pom.xml
  backend/sirius-web-compatibility/pom.xml
  backend/sirius-web-components/pom.xml
  backend/sirius-web-core-api/pom.xml
  backend/sirius-web-diagrams-layout-api/pom.xml
  backend/sirius-web-diagrams-layout/pom.xml
  backend/sirius-web-diagrams-tests/pom.xml
  backend/sirius-web-diagrams/pom.xml
  backend/sirius-web-domain-design/pom.xml
  backend/sirius-web-domain-edit/pom.xml
  backend/sirius-web-domain/pom.xml
  backend/sirius-web-emf/pom.xml
  backend/sirius-web-forms-tests/pom.xml
  backend/sirius-web-forms/pom.xml
  backend/sirius-web-graphiql/pom.xml
  backend/sirius-web-graphql-schema/pom.xml
  backend/sirius-web-graphql-utils/pom.xml
  backend/sirius-web-graphql-voyager/pom.xml
  backend/sirius-web-graphql/pom.xml
  backend/sirius-web-interpreter/pom.xml
  backend/sirius-web-persistence/pom.xml
  backend/sirius-web-representations/pom.xml
  backend/sirius-web-services-api/pom.xml
  backend/sirius-web-services/pom.xml
  backend/sirius-web-spring-collaborative-diagrams/pom.xml
  backend/sirius-web-spring-collaborative-forms/pom.xml
  backend/sirius-web-spring-collaborative-trees/pom.xml
  backend/sirius-web-spring-collaborative/pom.xml
  backend/sirius-web-spring-graphql-api/pom.xml
  backend/sirius-web-spring-graphql/pom.xml
  backend/sirius-web-spring-starter/pom.xml
  backend/sirius-web-spring-tests/pom.xml
  backend/sirius-web-spring/pom.xml
  backend/sirius-web-test-diagrams-only-application/pom.xml
  backend/sirius-web-test-sample-application/pom.xml
  backend/sirius-web-tests/pom.xml
  backend/sirius-web-trees/pom.xml
  backend/sirius-web-view-edit/pom.xml
  backend/sirius-web-view/pom.xml
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to be review soon, priority: high

#582 [releng] Update the dependabot configuration
  .dependabot/config.yml
Labels: pr: to be review soon, priority: low
