Repository eclipse-sirius/sirius-web, pull requests merged in 2021-12, with the labels that each got.

#849 [fix] Add support for property groups defined in a different category
  backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/forms/ViewExtensionDescriptionConverter.java
Labels: pr: to review soon, priority: low

#848 Fix the diagram selection that should be updated while the workbench selection is changed.
  frontend/src/diagram/sprotty/DiagramServer.tsx
Labels: pr: to review soon, priority: high

#853 [852] Fix regression on label ids
  backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/components/LabelComponent.java
  backend/sirius-web-diagrams/src/test/java/org/eclipse/sirius/web/diagrams/renderer/DiagramRendererNodeTests.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/DiagramQueryService.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/api/IDiagramQueryService.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/EditLabelEventHandler.java
Labels: pr: to review soon, priority: high

#855 [releng] Bump version to v0.5.6
  backend/pom.xml
  backend/sirius-web-annotations-spring/pom.xml
  backend/sirius-web-annotations/pom.xml
  backend/sirius-web-api/pom.xml
  backend/sirius-web-compatibility/pom.xml
  backend/sirius-web-components/pom.xml
  backend/sirius-web-core-api/pom.xml
  backend/sirius-web-diagrams-layout-api/pom.xml
  backend/sirius-web-diagrams-layout/pom.xml
  backend/sirius-web-diagrams-tests/pom.xml
  backend/sirius-web-diagrams/pom.xml
  backend/sirius-web-domain-design/pom.xml
  backend/sirius-web-domain-edit/pom.xml
  backend/sirius-web-domain/pom.xml
  backend/sirius-web-emf/pom.xml
  backend/sirius-web-forms-tests/pom.xml
  backend/sirius-web-forms/pom.xml
  backend/sirius-web-graphiql/pom.xml
  backend/sirius-web-graphql-utils/pom.xml
  backend/sirius-web-graphql-voyager/pom.xml
  backend/sirius-web-interpreter/pom.xml
  backend/sirius-web-representations/pom.xml
  backend/sirius-web-selection/pom.xml
  backend/sirius-web-spring-collaborative-diagrams/pom.xml
  backend/sirius-web-spring-collaborative-forms/pom.xml
  backend/sirius-web-spring-collaborative-selection/pom.xml
  backend/sirius-web-spring-collaborative-trees/pom.xml
  backend/sirius-web-spring-collaborative-validation/pom.xml
  backend/sirius-web-spring-collaborative/pom.xml
  backend/sirius-web-spring-graphql-api/pom.xml
  backend/sirius-web-spring-graphql/pom.xml
  backend/sirius-web-spring-starter/pom.xml
  backend/sirius-web-spring-tests/pom.xml
  backend/sirius-web-tests/pom.xml
  backend/sirius-web-trees/pom.xml
  backend/sirius-web-validation/pom.xml
  backend/sirius-web-view-edit/pom.xml
  backend/sirius-web-view/pom.xml
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to review soon, priority: high

#859 [doc] Update the CHANGELOG for the upcoming release
  CHANGELOG.adoc
Labels: pr: to review soon, priority: high

#874 [releng] Bump version to 2021.12.0
  backend/pom.xml
  backend/sirius-web-annotations-spring/pom.xml
  backend/sirius-web-annotations/pom.xml
  backend/sirius-web-api/pom.xml
  backend/sirius-web-compatibility/pom.xml
  backend/sirius-web-components/pom.xml
  backend/sirius-web-core-api/pom.xml
  backend/sirius-web-diagrams-layout-api/pom.xml
  backend/sirius-web-diagrams-layout/pom.xml
  backend/sirius-web-diagrams-tests/pom.xml
  backend/sirius-web-diagrams/pom.xml
  backend/sirius-web-domain-design/pom.xml
  backend/sirius-web-domain-edit/pom.xml
  backend/sirius-web-domain/pom.xml
  backend/sirius-web-emf/pom.xml
  backend/sirius-web-forms-tests/pom.xml
  backend/sirius-web-forms/pom.xml
  backend/sirius-web-graphiql/pom.xml
  backend/sirius-web-graphql-utils/pom.xml
  backend/sirius-web-graphql-voyager/pom.xml
  backend/sirius-web-interpreter/pom.xml
  backend/sirius-web-representations/pom.xml
  backend/sirius-web-selection/pom.xml
  backend/sirius-web-spring-collaborative-diagrams/pom.xml
  backend/sirius-web-spring-collaborative-forms/pom.xml
  backend/sirius-web-spring-collaborative-selection/pom.xml
  backend/sirius-web-spring-collaborative-trees/pom.xml
  backend/sirius-web-spring-collaborative-validation/pom.xml
  backend/sirius-web-spring-collaborative/pom.xml
  backend/sirius-web-spring-graphql-api/pom.xml
  backend/sirius-web-spring-graphql/pom.xml
  backend/sirius-web-spring-starter/pom.xml
  backend/sirius-web-spring-tests/pom.xml
  backend/sirius-web-tests/pom.xml
  backend/sirius-web-trees/pom.xml
  backend/sirius-web-validation/pom.xml
  backend/sirius-web-view-edit/pom.xml
  backend/sirius-web-view/pom.xml
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to review soon, priority: high

#861 [fix] Fix potential NPE in logging code
  CHANGELOG.adoc
  backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/forms/WidgetDescriptionConverter.java
Labels: type: bug 💥, area: backend, pr: to review later, priority: low

#875 [releng] Bump version to 2021.12.3
  backend/pom.xml
  backend/sirius-web-annotations-spring/pom.xml
  backend/sirius-web-annotations/pom.xml
  backend/sirius-web-api/pom.xml
  backend/sirius-web-compatibility/pom.xml
  backend/sirius-web-components/pom.xml
  backend/sirius-web-core-api/pom.xml
  backend/sirius-web-diagrams-layout-api/pom.xml
  backend/sirius-web-diagrams-layout/pom.xml
  backend/sirius-web-diagrams-tests/pom.xml
  backend/sirius-web-diagrams/pom.xml
  backend/sirius-web-domain-design/pom.xml
  backend/sirius-web-domain-edit/pom.xml
  backend/sirius-web-domain/pom.xml
  backend/sirius-web-emf/pom.xml
  backend/sirius-web-forms-tests/pom.xml
  backend/sirius-web-forms/pom.xml
  backend/sirius-web-graphiql/pom.xml
  backend/sirius-web-graphql-utils/pom.xml
  backend/sirius-web-graphql-voyager/pom.xml
  backend/sirius-web-interpreter/pom.xml
  backend/sirius-web-representations/pom.xml
  backend/sirius-web-selection/pom.xml
  backend/sirius-web-spring-collaborative-diagrams/pom.xml
  backend/sirius-web-spring-collaborative-forms/pom.xml
  backend/sirius-web-spring-collaborative-selection/pom.xml
  backend/sirius-web-spring-collaborative-trees/pom.xml
  backend/sirius-web-spring-collaborative-validation/pom.xml
  backend/sirius-web-spring-collaborative/pom.xml
  backend/sirius-web-spring-graphql-api/pom.xml
  backend/sirius-web-spring-graphql/pom.xml
  backend/sirius-web-spring-starter/pom.xml
  backend/sirius-web-spring-tests/pom.xml
  backend/sirius-web-tests/pom.xml
  backend/sirius-web-trees/pom.xml
  backend/sirius-web-validation/pom.xml
  backend/sirius-web-view-edit/pom.xml
  backend/sirius-web-view/pom.xml
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to review soon, priority: high

#877 [134] Switch to a multi-selection API in the workbench
  CHANGELOG.adoc
  doc/adrs/036_adopt_a_more_structured_selection.adoc
  frontend/src/diagram/DiagramWebSocketContainer.tsx
  frontend/src/diagram/DiagramWebSocketContainerMachine.ts
  frontend/src/diagram/sprotty/DiagramServer.tsx
  frontend/src/explorer/Explorer.types.ts
  frontend/src/explorer/ExplorerWebSocketContainer.types.ts
  frontend/src/modals/new-object/NewObjectModal.tsx
  frontend/src/modals/new-object/NewObjectModalMachine.ts
  frontend/src/modals/new-representation/NewRepresentationModal.tsx
  frontend/src/modals/new-root-object/NewRootObjectModal.tsx
  frontend/src/modals/new-root-object/NewRootObjectModalMachine.ts
  frontend/src/onboarding/NewRepresentationArea.tsx
  frontend/src/onboarding/NewRepresentationArea.types.ts
  frontend/src/onboarding/OnboardArea.tsx
  frontend/src/onboarding/OnboardArea.types.ts
  frontend/src/onboarding/RepresentationsArea.tsx
  frontend/src/properties/PropertiesWebSocketContainer.tsx
  frontend/src/properties/PropertiesWebSocketContainerMachine.ts
  frontend/src/properties/propertysections/ListPropertySection.tsx
  frontend/src/representations/RepresentationsWebSocketContainer.tsx
  frontend/src/representations/RepresentationsWebSocketContainerMachine.ts
  frontend/src/tree/Tree.types.ts
  frontend/src/tree/TreeItem.tsx
  frontend/src/tree/TreeItem.types.ts
  frontend/src/workbench/LeftSite.types.ts
  frontend/src/workbench/RepresentationNavigation.tsx
  frontend/src/workbench/Workbench.tsx
  frontend/src/workbench/Workbench.types.ts
  frontend/src/workbench/WorkbenchMachine.ts
Labels: pr: to review soon, priority: high

#880 [fix] Fix the canonical domain-based edge creation tool
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/CanonicalBehaviors.java
Labels: area: view

#882 [enh] Add a tooltip to always make the full label available
  frontend/src/properties/Properties.tsx
Labels: pr: to review soon, priority: low

#881 [845] Switch to Sirius Desktop 6.6.0
  CHANGELOG.adoc
  backend/sirius-web-compatibility/pom.xml
Labels: pr: to review later, priority: low

#850 Do not use the index of the diagram root as it does not exist
  frontend/src/diagram/sprotty/DiagramServer.tsx
Labels: pr: to review later, priority: low

#857 View DSL: add support for computed size for nodes
  CHANGELOG.adoc
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/ViewConverter.java
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/ViewPropertiesConfigurer.java
  backend/sirius-web-view-edit/src/main/java/org/eclipse/sirius/web/view/provider/ConditionalNodeStyleItemProvider.java
  backend/sirius-web-view-edit/src/main/java/org/eclipse/sirius/web/view/provider/NodeStyleItemProvider.java
  backend/sirius-web-view-edit/src/main/resources/plugin.properties
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/NodeStyle.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/ViewPackage.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/ConditionalNodeStyleImpl.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/NodeStyleImpl.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/ViewPackageImpl.java
  backend/sirius-web-view/src/main/resources/model/view.ecore
  backend/sirius-web-view/src/main/resources/model/view.genmodel
Labels: pr: to review soon, priority: high

#883 View DSL: Add support for defining border nodes
  CHANGELOG.adoc
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/ViewConverter.java
  backend/sirius-web-view-edit/src/main/java/org/eclipse/sirius/web/view/provider/NodeDescriptionItemProvider.java
  backend/sirius-web-view-edit/src/main/resources/plugin.properties
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/NodeDescription.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/ViewPackage.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/NodeDescriptionImpl.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/ViewPackageImpl.java
  backend/sirius-web-view/src/main/resources/model/view.ecore
  backend/sirius-web-view/src/main/resources/model/view.genmodel
Labels: pr: to review soon, priority: high

#890 [enh] Improve object mapper configuration
  CHANGELOG.adoc
  backend/sirius-web-spring-starter/pom.xml
  backend/sirius-web-spring-starter/src/main/java/org/eclipse/sirius/web/starter/configuration/ObjectMapperConfiguration.java
Labels: pr: to review soon, priority: high

#889 [fix] Fix border node size computation
  backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/ELKDiagramConverter.java
Labels: pr: to review soon, priority: high

#891 [377] Restore rename representation feedback
  CHANGELOG.adoc
  backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/projects/EditingContextEventProcessor.java
  frontend/src/workbench/Workbench.tsx
  frontend/src/workbench/Workbench.types.ts
  frontend/src/workbench/WorkbenchMachine.ts
Labels: pr: to review soon, priority: high

#894 [893] Export tree/TreeItemContextMenu
  frontend/src/index.ts
Labels: pr: to review soon, priority: high

#895 [868] Compute the position of an edge label when it does not have any
  CHANGELOG.adoc
  backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/incremental/IncrementalLayoutEngine.java
Labels: pr: to review soon, priority: high

#901 [865] Fix workspace image path customization
  backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/WorkspaceImageDescriptionConverter.java
Labels: type: bug 💥, area: backend

#902 [746] Fix SubscriptionManager.isEmpty()
  backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/representations/SubscriptionManager.java
Labels: pr: to review soon, priority: high

#273 [132] Add a drop tool
  CHANGELOG.adoc
  backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/ToolConverter.java
  backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/services/diagrams/DiagramDescriptionNodeAndEdgeDescriptionsPopulator.java
  backend/sirius-web-diagrams-tests/src/main/java/org/eclipse/sirius/web/diagrams/tests/TestDiagramDescriptionBuilder.java
  backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/description/DiagramDescription.java
  backend/sirius-web-diagrams/src/test/java/org/eclipse/sirius/web/diagrams/renderer/DiagramRendererEdgeTests.java
  backend/sirius-web-diagrams/src/test/java/org/eclipse/sirius/web/diagrams/renderer/DiagramRendererNodeTests.java
  backend/sirius-web-diagrams/src/test/java/org/eclipse/sirius/web/diagrams/renderer/UnsynchronizedDiagramTests.java
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/ViewConverter.java
  backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/compatibility/operations/CreateViewOperationHandlerTests.java
  backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/compatibility/operations/DeleteViewOperationHandlerTests.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/dto/DropOnDiagramInput.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/dto/DropOnDiagramSuccessPayload.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/DropOnDiagramEventHandler.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/messages/CollaborativeDiagramMessageService.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/messages/ICollaborativeDiagramMessageService.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/messages/MessageConstants.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/resources/messages/sirius-web-spring-collaborative-diagrams.properties
  backend/sirius-web-spring-collaborative-diagrams/src/main/resources/schema/diagram.graphqls
  backend/sirius-web-spring-collaborative-diagrams/src/test/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/CreateDiagramEventHandlerTests.java
  backend/sirius-web-spring-collaborative-diagrams/src/test/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/NoOpCollaborativeDiagramMessageService.java
  doc/adrs/034_add_support_for_drag_and_drop.adoc
  frontend/src/common/dataTransferTypes.ts
  frontend/src/diagram/DiagramWebSocketContainer.tsx
  frontend/src/diagram/DropArea.module.css
  frontend/src/diagram/DropArea.tsx
  frontend/src/diagram/DropArea.types.ts
  frontend/src/diagram/DropAreaMachine.ts
  frontend/src/index.ts
  frontend/src/tree/TreeItem.tsx
Labels: pr: to review soon, priority: high

#898 [896] Allow to make specific changes before and after the layout
  CHANGELOG.adoc
  backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/ISiriusWebLayoutConfigurator.java
  backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/LayoutConfiguratorRegistry.java
  backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/LayoutService.java
  backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/SiriusWebLayoutConfigurator.java
Labels: pr: to review soon, priority: low

#905 [419] Restore the set default tool action
  frontend/src/diagram/DiagramWebSocketContainerMachine.ts
Labels: pr: to review soon, priority: high

#904 [enh] Add treeId to the context menu props
  frontend/src/tree/TreeItem.tsx
  frontend/src/tree/TreeItemContextMenu.tsx
  frontend/src/tree/TreeItemContextMenu.types.ts
  frontend/src/tree/TreeItemContextMenuContribution.types.ts
Labels: pr: to review soon, priority: high

#832 [359] Fix border node's size computation
  backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/incremental/IncrementalLayoutDiagramConverter.java
  backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/incremental/data/NodeLayoutData.java
  backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/incremental/provider/NodeSizeProvider.java
Labels: pr: to review soon, priority: low

#906 [releng] Bump version to 2021.12.7
  backend/pom.xml
  backend/sirius-web-annotations-spring/pom.xml
  backend/sirius-web-annotations/pom.xml
  backend/sirius-web-api/pom.xml
  backend/sirius-web-compatibility/pom.xml
  backend/sirius-web-components/pom.xml
  backend/sirius-web-core-api/pom.xml
  backend/sirius-web-diagrams-layout-api/pom.xml
  backend/sirius-web-diagrams-layout/pom.xml
  backend/sirius-web-diagrams-tests/pom.xml
  backend/sirius-web-diagrams/pom.xml
  backend/sirius-web-domain-design/pom.xml
  backend/sirius-web-domain-edit/pom.xml
  backend/sirius-web-domain/pom.xml
  backend/sirius-web-emf/pom.xml
  backend/sirius-web-forms-tests/pom.xml
  backend/sirius-web-forms/pom.xml
  backend/sirius-web-graphiql/pom.xml
  backend/sirius-web-graphql-utils/pom.xml
  backend/sirius-web-graphql-voyager/pom.xml
  backend/sirius-web-interpreter/pom.xml
  backend/sirius-web-representations/pom.xml
  backend/sirius-web-selection/pom.xml
  backend/sirius-web-spring-collaborative-diagrams/pom.xml
  backend/sirius-web-spring-collaborative-forms/pom.xml
  backend/sirius-web-spring-collaborative-selection/pom.xml
  backend/sirius-web-spring-collaborative-trees/pom.xml
  backend/sirius-web-spring-collaborative-validation/pom.xml
  backend/sirius-web-spring-collaborative/pom.xml
  backend/sirius-web-spring-graphql-api/pom.xml
  backend/sirius-web-spring-graphql/pom.xml
  backend/sirius-web-spring-starter/pom.xml
  backend/sirius-web-spring-tests/pom.xml
  backend/sirius-web-tests/pom.xml
  backend/sirius-web-trees/pom.xml
  backend/sirius-web-validation/pom.xml
  backend/sirius-web-view-edit/pom.xml
  backend/sirius-web-view/pom.xml
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to review soon, priority: high
