Repository eclipse-sirius/sirius-web, pull requests merged in 2021-02, with the labels that each got.

#284 Re-enable missing test suites, and fix the few ones that were broken
  backend/sirius-web-emf/pom.xml
  backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/services/EditingContextPersistenceServiceTestCases.java
  backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/services/ObjectServiceTestCases.java
  backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/services/RenameDocumentEventHandlerTestCases.java
  backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/services/UploadDocumentEventHandlerTestCases.java
  backend/sirius-web-emf/src/test/resources/test_import/document.xmi
  backend/sirius-web-persistence/pom.xml
  backend/sirius-web-persistence/src/main/java/org/eclipse/sirius/web/persistence/repositories/IModelerRepository.java
  backend/sirius-web-spring-graphql/pom.xml
  backend/sirius-web-spring-tests/src/main/java/org/eclipse/sirius/web/spring/tests/architecture/AbstractServicesTestCases.java
  backend/sirius-web-spring/pom.xml
  backend/sirius-web-test-diagrams-only-application/pom.xml
  backend/sirius-web-test-sample-application/pom.xml
Labels: pr: ready to be reviewed, priority: high

#266 [261] Avoid unneeded work in DocumentService.getBytes()
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/services/DocumentService.java
Labels: pr: ready to be reviewed, priority: low

#304 [303] Remove the link to modelers from the project context menu
  frontend/src/views/edit-project/EditProjectNavbar/EditProjectNavbarContextMenu.tsx
Labels: pr: to be review soon, priority: high

#280 [cleanup] Remove useless code in the NewProjectView
  frontend/src/views/new-project/NewProjectView.tsx
Labels: pr: to be review soon, priority: low

#305 [300] Fix size computation
  backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/components/NodeComponent.java
  backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/components/NodeSizeProvider.java
Labels: pr: to be review soon, priority: high

#160 [152] Update some of our dependencies
  frontend/package-lock.json
  frontend/package.json
  frontend/src/core/contextmenu/ContextMenu.tsx
Labels: pr: to review later, priority: low

#324 [fix] Make sure ObjectService returns a non-null id form EMF proxies
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/services/ObjectService.java
  backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/services/ObjectServiceTestCases.java
Labels: pr: to review later, priority: low

#319 [fix] Fix NPE on missing NodeMapping.getStyle()
  backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/NodeMappingConverter.java
Labels: pr: to review later, priority: low

#316 [314] Handle iconPath property
  backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/LabelStyleDescriptionConverter.java
  backend/sirius-web-compatibility/src/test/java/org/eclipse/sirius/web/compat/AllSiriusWebCompatibilityTests.java
  backend/sirius-web-compatibility/src/test/java/org/eclipse/sirius/web/compat/diagrams/LabelStyleDescriptionConverterTestCases.java
Labels: pr: to review later, priority: low

#317 Fix conditional style handling for containers and nodes
  backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/ContainerMappingConverter.java
  backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/ContainerMappingStyleProvider.java
  backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/ContainerStyleDescriptionProvider.java
  backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/EdgeMappingConverter.java
  backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/EdgeMappingStyleProvider.java
  backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/EdgeStyleDescriptionProvider.java
  backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/LabelStyleDescriptionConverter.java
  backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/NodeMappingConverter.java
  backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/NodeMappingStyleProvider.java
  backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/diagrams/NodeStyleDescriptionProvider.java
  backend/sirius-web-compatibility/src/test/java/org/eclipse/sirius/web/compat/AllSiriusWebCompatibilityTests.java
  backend/sirius-web-compatibility/src/test/java/org/eclipse/sirius/web/compat/diagrams/BasicLabelStyleDescriptionPopulator.java
  backend/sirius-web-compatibility/src/test/java/org/eclipse/sirius/web/compat/diagrams/MappingConverterTestCases.java
  backend/sirius-web-diagrams-tests/src/main/java/org/eclipse/sirius/web/diagrams/tests/TestDiagramDescriptionBuilder.java
  backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/components/LabelComponent.java
  backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/description/LabelDescription.java
  backend/sirius-web-diagrams/src/test/java/org/eclipse/sirius/web/diagrams/renderer/DiagramRendererEdgeTestCases.java
  backend/sirius-web-diagrams/src/test/java/org/eclipse/sirius/web/diagrams/renderer/DiagramRendererNodeTestCases.java
  backend/sirius-web-diagrams/src/test/java/org/eclipse/sirius/web/diagrams/renderer/UnsynchronizedDiagramTestCases.java
  backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/compatibility/diagrams/EdgeMappingConverterTestCases.java
Labels: pr: to review later, priority: low

#336 [cleanup] Remove usage of the deprecated DirectProcessor
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/DiagramEventFlux.java
  backend/sirius-web-spring-collaborative-forms/src/main/java/org/eclipse/sirius/web/spring/collaborative/forms/FormEventProcessor.java
  backend/sirius-web-spring-collaborative-forms/src/main/java/org/eclipse/sirius/web/spring/collaborative/forms/PropertiesEventProcessor.java
  backend/sirius-web-spring-collaborative-forms/src/main/java/org/eclipse/sirius/web/spring/collaborative/forms/WidgetSubscriptionManager.java
  backend/sirius-web-spring-collaborative-trees/src/main/java/org/eclipse/sirius/web/spring/collaborative/trees/TreeEventProcessor.java
  backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/projects/EditingContextEventProcessor.java
  backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/representations/SubscriptionManager.java
Labels: pr: to be review soon, priority: high

#299 Refactor the layout algorithm
  doc/adrs/012_refactor_incremental_layout.adoc
Labels: area: layout, pr: to be review soon, priority: high
