Repository eclipse-sirius/sirius-web, pull requests merged in 2021-09, with the labels that each got.

#720 [719] Add support for the 'container' and 'element' compatibility variables
  backend/sirius-web-compatibility/src/main/java/org/eclipse/sirius/web/compat/services/diagrams/ToolProvider.java
Labels: pr: to review later, priority: low

#728 [729] Improve ResourceSet creation to be a IEditingDomainProvider
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/services/EditService.java
  backend/sirius-web-emf/src/test/java/org/eclipse/sirius/web/emf/services/EditingDomainFactory.java
Labels: pr: to review soon, priority: low

#718 Improve warnings for Java extension loading errors
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/compatibility/AQLInterpreterFactory.java
Labels: pr: to review soon, priority: low

#748 [747] Fix bounding box computation for images with wide labels
  backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/LayoutConfiguratorRegistry.java
Labels: pr: to review soon, priority: high

#733 Add support for a ViewDeletionRequest
  backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/ViewDeletionRequest.java
  backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/components/DiagramComponent.java
  backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/components/DiagramComponentProps.java
  backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/components/NodeComponent.java
  backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/components/NodeComponentProps.java
  backend/sirius-web-diagrams/src/test/java/org/eclipse/sirius/web/diagrams/renderer/DiagramRendererEdgeTests.java
  backend/sirius-web-diagrams/src/test/java/org/eclipse/sirius/web/diagrams/renderer/DiagramRendererNodeTests.java
  backend/sirius-web-diagrams/src/test/java/org/eclipse/sirius/web/diagrams/renderer/UnsynchronizedDiagramTests.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/DiagramContext.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/DiagramCreationService.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/api/IDiagramContext.java
  backend/sirius-web-spring-collaborative-diagrams/src/test/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/NoOpDiagramContext.java
  backend/sirius-web-spring-collaborative-diagrams/src/test/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/RenameDiagramEventHandlerTests.java
Labels: pr: to review soon, priority: high

#745 Use Reactor to communicate event handler results
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/DiagramEventProcessor.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/api/IDiagramEventHandler.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/ArrangeAllEventHandler.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/CreateDiagramEventHandler.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/DeleteFromDiagramEventHandler.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/EditLabelEventHandler.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/InvokeEdgeToolOnDiagramEventHandler.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/InvokeNodeToolOnDiagramEventHandler.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/RenameDiagramEventHandler.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/UpdateNodeBoundsEventHandler.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/UpdateNodePositionEventHandler.java
  backend/sirius-web-spring-collaborative-diagrams/src/test/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/CreateDiagramEventHandlerTests.java
  backend/sirius-web-spring-collaborative-diagrams/src/test/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/NoOpCollaborativeDiagramMessageService.java
  backend/sirius-web-spring-collaborative-diagrams/src/test/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/RenameDiagramEventHandlerTests.java
  backend/sirius-web-spring-collaborative-forms/src/main/java/org/eclipse/sirius/web/spring/collaborative/forms/FormEventProcessor.java
  backend/sirius-web-spring-collaborative-forms/src/main/java/org/eclipse/sirius/web/spring/collaborative/forms/api/IFormEventHandler.java
  backend/sirius-web-spring-collaborative-forms/src/main/java/org/eclipse/sirius/web/spring/collaborative/forms/handlers/CreateFormEventHandler.java
  backend/sirius-web-spring-collaborative-forms/src/main/java/org/eclipse/sirius/web/spring/collaborative/forms/handlers/EditCheckboxEventHandler.java
  backend/sirius-web-spring-collaborative-forms/src/main/java/org/eclipse/sirius/web/spring/collaborative/forms/handlers/EditMultiSelectEventHandler.java
  backend/sirius-web-spring-collaborative-forms/src/main/java/org/eclipse/sirius/web/spring/collaborative/forms/handlers/EditRadioEventHandler.java
  backend/sirius-web-spring-collaborative-forms/src/main/java/org/eclipse/sirius/web/spring/collaborative/forms/handlers/EditSelectEventHandler.java
  backend/sirius-web-spring-collaborative-forms/src/main/java/org/eclipse/sirius/web/spring/collaborative/forms/handlers/EditTextfieldEventHandler.java
  backend/sirius-web-spring-collaborative-forms/src/test/java/org/eclipse/sirius/web/spring/collaborative/forms/handlers/EditCheckboxEventHandlerTests.java
  backend/sirius-web-spring-collaborative-forms/src/test/java/org/eclipse/sirius/web/spring/collaborative/forms/handlers/EditRadioEventHandlerTests.java
  backend/sirius-web-spring-collaborative-forms/src/test/java/org/eclipse/sirius/web/spring/collaborative/forms/handlers/EditTextfieldEventHandlerTests.java
  backend/sirius-web-spring-collaborative-selection/src/main/java/org/eclipse/sirius/web/spring/collaborative/selection/SelectionEventProcessor.java
  backend/sirius-web-spring-collaborative-trees/src/main/java/org/eclipse/sirius/web/spring/collaborative/trees/TreeEventProcessor.java
  backend/sirius-web-spring-collaborative-trees/src/main/java/org/eclipse/sirius/web/spring/collaborative/trees/api/ITreeEventHandler.java
  backend/sirius-web-spring-collaborative-validation/src/main/java/org/eclipse/sirius/web/spring/collaborative/validation/ValidationEventProcessor.java
  backend/sirius-web-spring-collaborative-validation/src/main/java/org/eclipse/sirius/web/spring/collaborative/validation/api/IValidationEventHandler.java
  backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/api/ChangeDescription.java
  backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/api/EventHandlerResponse.java
  backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/api/IEditingContextEventHandler.java
  backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/api/IEditingContextEventProcessor.java
  backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/api/IEditingContextEventProcessorRegistry.java
  backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/api/IRepresentationEventProcessor.java
  backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/handlers/CreateChildEventHandler.java
  backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/handlers/CreateRootObjectEventHandler.java
  backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/handlers/DeleteObjectEventHandler.java
  backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/handlers/QueryBasedBooleanEventHandler.java
  backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/handlers/QueryBasedIntEventHandler.java
  backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/handlers/QueryBasedObjectEventHandler.java
  backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/handlers/QueryBasedObjectsEventHandler.java
  backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/handlers/QueryBasedStringEventHandler.java
  backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/handlers/RenameObjectEventHandler.java
  backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/projects/EditingContextEventProcessor.java
  backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/projects/EditingContextEventProcessorRegistry.java
  backend/sirius-web-spring-collaborative/src/test/java/org/eclipse/sirius/web/spring/collaborative/handlers/CreateChildEventHandlerTests.java
  backend/sirius-web-spring-collaborative/src/test/java/org/eclipse/sirius/web/spring/collaborative/handlers/CreateRootObjectEventHandlerTests.java
  backend/sirius-web-spring-collaborative/src/test/java/org/eclipse/sirius/web/spring/collaborative/handlers/DeleteObjectEventHandlerTests.java
  backend/sirius-web-spring-collaborative/src/test/java/org/eclipse/sirius/web/spring/collaborative/handlers/QueryBasedBooleanEventHandlerTests.java
  backend/sirius-web-spring-collaborative/src/test/java/org/eclipse/sirius/web/spring/collaborative/handlers/QueryBasedIntEventHandlerTests.java
  backend/sirius-web-spring-collaborative/src/test/java/org/eclipse/sirius/web/spring/collaborative/handlers/QueryBasedObjectEventHandlerTests.java
  backend/sirius-web-spring-collaborative/src/test/java/org/eclipse/sirius/web/spring/collaborative/handlers/QueryBasedObjectsEventHandlerTests.java
  backend/sirius-web-spring-collaborative/src/test/java/org/eclipse/sirius/web/spring/collaborative/handlers/QueryBasedStringEventHandlerTests.java
  backend/sirius-web-spring-collaborative/src/test/java/org/eclipse/sirius/web/spring/collaborative/handlers/RenameObjectEventHandlerTests.java
Labels: pr: to review soon, priority: high

#752 [releng] Bump version to v0.4.7
  backend/pom.xml
  backend/sirius-web-annotations-spring/pom.xml
  backend/sirius-web-annotations/pom.xml
  backend/sirius-web-api/pom.xml
  backend/sirius-web-compatibility/pom.xml
  backend/sirius-web-components/pom.xml
  backend/sirius-web-core-api/pom.xml
  backend/sirius-web-diagrams-layout-api/pom.xml
  backend/sirius-web-diagrams-layout/pom.xml
  backend/sirius-web-diagrams-tests/pom.xml
  backend/sirius-web-diagrams/pom.xml
  backend/sirius-web-domain-design/pom.xml
  backend/sirius-web-domain-edit/pom.xml
  backend/sirius-web-domain/pom.xml
  backend/sirius-web-emf/pom.xml
  backend/sirius-web-forms-tests/pom.xml
  backend/sirius-web-forms/pom.xml
  backend/sirius-web-graphiql/pom.xml
  backend/sirius-web-graphql-utils/pom.xml
  backend/sirius-web-graphql-voyager/pom.xml
  backend/sirius-web-interpreter/pom.xml
  backend/sirius-web-representations/pom.xml
  backend/sirius-web-selection/pom.xml
  backend/sirius-web-spring-collaborative-diagrams/pom.xml
  backend/sirius-web-spring-collaborative-forms/pom.xml
  backend/sirius-web-spring-collaborative-selection/pom.xml
  backend/sirius-web-spring-collaborative-trees/pom.xml
  backend/sirius-web-spring-collaborative-validation/pom.xml
  backend/sirius-web-spring-collaborative/pom.xml
  backend/sirius-web-spring-graphql-api/pom.xml
  backend/sirius-web-spring-graphql/pom.xml
  backend/sirius-web-spring-starter/pom.xml
  backend/sirius-web-spring-tests/pom.xml
  backend/sirius-web-tests/pom.xml
  backend/sirius-web-trees/pom.xml
  backend/sirius-web-validation/pom.xml
  backend/sirius-web-view-edit/pom.xml
  backend/sirius-web-view/pom.xml
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to review soon, priority: high

#754 [739] Add a name to node and edge descriptions
  backend/sirius-web-view-edit/src/main/java/org/eclipse/sirius/web/view/provider/DiagramDescriptionItemProvider.java
  backend/sirius-web-view-edit/src/main/java/org/eclipse/sirius/web/view/provider/DiagramElementDescriptionItemProvider.java
  backend/sirius-web-view-edit/src/main/java/org/eclipse/sirius/web/view/provider/EdgeDescriptionItemProvider.java
  backend/sirius-web-view-edit/src/main/java/org/eclipse/sirius/web/view/provider/NodeDescriptionItemProvider.java
  backend/sirius-web-view-edit/src/main/resources/plugin.properties
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/DiagramElementDescription.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/ViewPackage.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/DiagramElementDescriptionImpl.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/ViewPackageImpl.java
  backend/sirius-web-view/src/main/resources/model/view.ecore
  backend/sirius-web-view/src/main/resources/model/view.genmodel
Labels: pr: to review soon, priority: high

#757 [releng] Bump version to v0.4.8
  backend/pom.xml
  backend/sirius-web-annotations-spring/pom.xml
  backend/sirius-web-annotations/pom.xml
  backend/sirius-web-api/pom.xml
  backend/sirius-web-compatibility/pom.xml
  backend/sirius-web-components/pom.xml
  backend/sirius-web-core-api/pom.xml
  backend/sirius-web-diagrams-layout-api/pom.xml
  backend/sirius-web-diagrams-layout/pom.xml
  backend/sirius-web-diagrams-tests/pom.xml
  backend/sirius-web-diagrams/pom.xml
  backend/sirius-web-domain-design/pom.xml
  backend/sirius-web-domain-edit/pom.xml
  backend/sirius-web-domain/pom.xml
  backend/sirius-web-emf/pom.xml
  backend/sirius-web-forms-tests/pom.xml
  backend/sirius-web-forms/pom.xml
  backend/sirius-web-graphiql/pom.xml
  backend/sirius-web-graphql-utils/pom.xml
  backend/sirius-web-graphql-voyager/pom.xml
  backend/sirius-web-interpreter/pom.xml
  backend/sirius-web-representations/pom.xml
  backend/sirius-web-selection/pom.xml
  backend/sirius-web-spring-collaborative-diagrams/pom.xml
  backend/sirius-web-spring-collaborative-forms/pom.xml
  backend/sirius-web-spring-collaborative-selection/pom.xml
  backend/sirius-web-spring-collaborative-trees/pom.xml
  backend/sirius-web-spring-collaborative-validation/pom.xml
  backend/sirius-web-spring-collaborative/pom.xml
  backend/sirius-web-spring-graphql-api/pom.xml
  backend/sirius-web-spring-graphql/pom.xml
  backend/sirius-web-spring-starter/pom.xml
  backend/sirius-web-spring-tests/pom.xml
  backend/sirius-web-tests/pom.xml
  backend/sirius-web-trees/pom.xml
  backend/sirius-web-validation/pom.xml
  backend/sirius-web-view-edit/pom.xml
  backend/sirius-web-view/pom.xml
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to review soon, priority: high
