Repository eclipse-sirius/sirius-web, pull requests merged in 2021-07, with the labels that each got.

#83 [releng] Add a direct dependency to sirius-web-services and sirius-web-spring
  backend/sirius-web-sample-application/pom.xml
Labels: pr: to be review soon, priority: high, waiting for sirius components

#84 [releng] Switch to Sirius Components 0.3.4
  backend/sirius-web-frontend/pom.xml
  backend/sirius-web-sample-application/pom.xml
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to be review soon, priority: high, waiting for sirius components

#85 [607] Format the TypeScript code with Prettier
  .github/workflows/build-sample-app.yml
  frontend/package.json
  frontend/src/ApolloGraphQLClient.tsx
  frontend/src/footer/Footer.tsx
  frontend/src/index.tsx
  frontend/src/navigationBar/Help.tsx
  frontend/src/navigationBar/NavigationBar.tsx
  frontend/src/views/edit-project/EditProjectNavbar/EditProjectNavbar.tsx
  frontend/src/views/edit-project/EditProjectNavbar/EditProjectNavbarContextMenu.tsx
  frontend/src/views/edit-project/EditProjectNavbar/reducer.ts
  frontend/src/views/edit-project/EditProjectView.tsx
  frontend/src/views/edit-project/EditProjectViewMachine.ts
  frontend/src/views/new-project/NewProjectView.tsx
  frontend/src/views/projects/ProjectsView.tsx
  frontend/src/views/upload-project/UploadProjectView.tsx
  frontend/src/views/upload-project/UploadProjectViewMachine.tsx
Labels: area: frontend, difficulty: medium 👩‍💻, type: enhancement ✨

#87 [releng] Switch to Sirius Components 0.3.5
  backend/sirius-web-frontend/pom.xml
  backend/sirius-web-sample-application/pom.xml
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to be review soon, priority: high

#89 [fix] Prevent exception on startup if optional property is not set
  backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/configuration/CustomImagesLoader.java
Labels: pr: to be review soon, priority: high

#90 [557] Improve the default View definition
  backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/configuration/StudioConfiguration.java
Labels: pr: to be review soon, priority: high

#93 [releng] Switch to Sirius Components 0.3.6
  backend/sirius-web-frontend/pom.xml
  backend/sirius-web-sample-application/pom.xml
  backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/configuration/StereotypeBuilder.java
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to review soon, priority: high

#92 [releng] Switch to Sirius Components 0.3.7
  backend/sirius-web-frontend/pom.xml
  backend/sirius-web-sample-application/pom.xml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/views/edit-project/EditProjectView.tsx
Labels: pr: to review soon, priority: high

#95 [94] Fix Typo on parameter name in EditProjectNavbar#onProjectDeleted
  frontend/src/views/edit-project/EditProjectNavbar/EditProjectNavbar.tsx
Labels: pr: to review soon, priority: high

#96 [releng] Switch to Sirius Components 0.3.9
  backend/sirius-web-frontend/pom.xml
  backend/sirius-web-sample-application/pom.xml
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to review soon, priority: high

#97 [releng] Bump to Sirius Web 0.4.0
  backend/pom.xml
  backend/sirius-web-frontend/pom.xml
  backend/sirius-web-sample-application/pom.xml
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to review soon, priority: high
