Repository eclipse-sirius/sirius-web, pull requests merged in 2022-02, with the labels that each got.

#177 [cleanup] Adapt the ViewConverter API change
  backend/sirius-web-frontend/pom.xml
  backend/sirius-web-graphql-schema/pom.xml
  backend/sirius-web-graphql/pom.xml
  backend/sirius-web-persistence/pom.xml
  backend/sirius-web-sample-application/pom.xml
  backend/sirius-web-services-api/pom.xml
  backend/sirius-web-services/pom.xml
  backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/representations/DynamicRepresentationDescriptionService.java
  backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/representations/RepresentationService.java
  backend/sirius-web-spring/pom.xml
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to review soon, priority: high

#165 [937] Integrate diagram SVG export to the frontend
  backend/sirius-web-frontend/pom.xml
  backend/sirius-web-graphql-schema/pom.xml
  backend/sirius-web-graphql/pom.xml
  backend/sirius-web-persistence/pom.xml
  backend/sirius-web-sample-application/pom.xml
  backend/sirius-web-services-api/pom.xml
  backend/sirius-web-services/pom.xml
  backend/sirius-web-spring/pom.xml
  backend/sirius-web-spring/src/main/java/org/eclipse/sirius/web/spring/controllers/RepresentationController.java
  backend/sirius-web-spring/src/main/java/org/eclipse/sirius/web/spring/controllers/URLConstants.java
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to review soon, priority: high

#178 [releng] Ignore .factorypath files generated by m2e
  .gitignore
Labels: pr: to review later, priority: low

#171 [fix] Fix document context menu items' enablement
  frontend/src/views/edit-project/DocumentTreeItemContextMenuContribution.tsx
Labels: pr: to review later, priority: low

#180 [699] Improve support of representation metadata
  backend/sirius-web-frontend/pom.xml
  backend/sirius-web-graphql-schema/pom.xml
  backend/sirius-web-graphql/pom.xml
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/editingcontext/EditingContextRepresentationDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/editingcontext/EditingContextRepresentationsDataFetcher.java
  backend/sirius-web-persistence/pom.xml
  backend/sirius-web-sample-application/pom.xml
  backend/sirius-web-services-api/pom.xml
  backend/sirius-web-services/pom.xml
  backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/explorer/ExplorerDescriptionProvider.java
  backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/representations/RepresentationService.java
  backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/representations/RepresentationsDescriptionProvider.java
  backend/sirius-web-spring/pom.xml
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to review soon, priority: high

#170 [fix] Protect domain & view search from malformed documents
  backend/sirius-web-persistence/src/main/resources/db/sirius-web-named-queries.properties
Labels: pr: to review later, priority: low

#185 [1045] Use List<?> instead of List<Object>
  backend/sirius-web-frontend/pom.xml
  backend/sirius-web-graphql-schema/pom.xml
  backend/sirius-web-graphql/pom.xml
  backend/sirius-web-persistence/pom.xml
  backend/sirius-web-sample-application/pom.xml
  backend/sirius-web-services-api/pom.xml
  backend/sirius-web-services/pom.xml
  backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/representations/RepresentationsDescriptionProvider.java
  backend/sirius-web-spring/pom.xml
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to review soon, priority: high

#187 [1068] Add support for displaying details on arbitrary element kinds
  backend/sirius-web-frontend/pom.xml
  backend/sirius-web-graphql-schema/pom.xml
  backend/sirius-web-graphql/pom.xml
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/subscriptions/SubscriptionPropertiesEventDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/subscriptions/SubscriptionRepresentationsEventDataFetcher.java
  backend/sirius-web-persistence/pom.xml
  backend/sirius-web-sample-application/pom.xml
  backend/sirius-web-services-api/pom.xml
  backend/sirius-web-services/pom.xml
  backend/sirius-web-spring/pom.xml
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to review soon, priority: high, waiting for sirius components

#190 [1068] Fix a regression in the representations view
  backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/representations/RepresentationsDescriptionProvider.java
Labels: pr: to review soon, priority: high
