Repository eclipse-sirius/sirius-web, pull requests merged in 2022-10, with the labels that each got.

#1383 [cleanup] Remove duplicate dependencies in some POMs
  packages/diagrams/backend/sirius-components-diagrams-graphql/pom.xml
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors-graphql/pom.xml
  packages/forms/backend/sirius-components-forms-graphql/pom.xml
  packages/selection/backend/sirius-components-selection-graphql/pom.xml
  packages/trees/backend/sirius-components-trees-graphql/pom.xml
  packages/validation/backend/sirius-components-validation-graphql/pom.xml
Labels: pr: to review soon, priority: low

#1382 [cleanup] Make ArchUnit more quiet on sirius-components-charts
  packages/charts/backend/sirius-components-charts/.classpath
  packages/charts/backend/sirius-components-charts/src/test/resources/logback-test.xml
Labels: pr: to review soon, priority: low

#1080 Add support for edge routing points edition
  CHANGELOG.adoc
  doc/adrs/072_add_support_for_edition_of_routing_points.adoc
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/dto/UpdateEdgeRoutingPointsInput.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/dto/UpdateEdgeRoutingPointsSuccessPayload.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/UpdateEdgeRoutingPointsEventHandler.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/resources/schema/diagram.graphqls
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/test/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/UpdateEdgeRoutingPointsEventHandlerTests.java
  packages/diagrams/backend/sirius-components-diagrams-graphql/src/main/java/org/eclipse/sirius/components/diagrams/graphql/datafetchers/mutation/MutationUpdateEdgeRoutingPointsDataFetcher.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/LayoutService.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/IncrementalLayoutEngine.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/provider/EdgeLabelPositionProvider.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/provider/EdgeRoutingPointsProvider.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/updater/OverlapsUpdater.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/incremental/BorderNodePositionTests.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/incremental/EdgeRoutingPointsProviderTests.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/incremental/NodeMoveTests.java
  packages/diagrams/backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/EdgeAssert.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/events/UpdateEdgeRoutingPointsEvent.java
  packages/diagrams/frontend/sirius-components-diagrams/src/representation/DiagramRepresentation.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/representation/DiagramRepresentation.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/representation/DiagramRepresentationMachine.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/representation/operations.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/sprotty/DependencyInjection.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/sprotty/DiagramServer.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/sprotty/__tests__/borderNodes.test.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/sprotty/__tests__/convertDiagram.test.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/sprotty/common/CursorMouseListener.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/sprotty/common/isSiriusModelElementRequest.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/sprotty/common/siriusCommonModule.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/sprotty/convertDiagram.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/sprotty/dragAndDrop/__tests__/siriusMove.test.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/sprotty/dragAndDrop/model.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/sprotty/dragAndDrop/siriusDragAndDropModule.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/sprotty/dragAndDrop/siriusDragAndDropMouseListener.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/sprotty/dragAndDrop/siriusMove.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/sprotty/dragAndDrop/siriusResize.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/sprotty/edgeEdition/siriusEdgeEditModule.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/sprotty/edgeEdition/siriusSwitchEditModeCommand.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/sprotty/routing/siriusPolylineEdgeRouter.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/sprotty/siriusMove.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/sprotty/views/RoutingHandleView.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/sprotty/views/ViewUtils.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/sprotty/views/VolatileRoutingHandleView.tsx
Labels: pr: to review soon, priority: high

#1372 [1368] Do not render rectangle view children twice
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/sprotty/views/RectangleView.tsx
Labels: pr: to review soon, priority: high

#1391 [releng] Add support for CODEOWNERS
  .github/CODEOWNERS
Labels: pr: to review soon, priority: high

#1388 [1387] Migrate Sirius Web VSCode Extension to Sirius Components
  .github/CODEOWNERS
  .github/workflows/build.yml
  CHANGELOG.adoc
  vscode-extension/.gitignore
  vscode-extension/.npmrc
  vscode-extension/.prettierrc
  vscode-extension/.vscode/extensions.json
  vscode-extension/.vscode/launch.json
  vscode-extension/.vscode/settings.json
  vscode-extension/.vscode/tasks.json
  vscode-extension/.vscodeignore
  vscode-extension/LICENSE
  vscode-extension/README.md
  vscode-extension/images/icon.png
  vscode-extension/images/icon_32.png
  vscode-extension/images/siriusweb-visuel1.gif
  vscode-extension/package-lock.json
  vscode-extension/package.json
  vscode-extension/src/data/ModelData.ts
  vscode-extension/src/data/ProjectData.ts
  vscode-extension/src/data/RepresentationData.ts
  vscode-extension/src/data/ServerData.ts
  vscode-extension/src/data/getTreeEventSubscription.ts
  vscode-extension/src/extension.ts
  vscode-extension/src/view/WebViewLoader.ts
  vscode-extension/src/view/app/App.tsx
  vscode-extension/src/view/app/Sprotty.css
  vscode-extension/src/view/app/index.css
  vscode-extension/src/view/app/index.tsx
  vscode-extension/src/view/app/reset.css
  vscode-extension/src/view/app/tsconfig.json
  vscode-extension/src/view/app/variables.css
  vscode-extension/src/viewsContainer/views/explorerView.ts
  vscode-extension/src/viewsContainer/views/projectsView.ts
  vscode-extension/src/viewsContainer/views/representationsView.ts
  vscode-extension/src/viewsContainer/views/serversView.ts
  vscode-extension/tsconfig.json
  vscode-extension/tslint.json
  vscode-extension/webpack.config.js
Labels: pr: to review soon, priority: low

#1399 [fix] Fix regression in EditService.createRootObject()
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/services/EditService.java
Labels: pr: to review soon, priority: high

#1416 [cleanup] Remove the unused OptionDescription
  packages/forms/backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/description/OptionDescription.java
Labels: pr: to review later, priority: low

#1415 [cleanup] Remove the unused EditProjectNavbarContextMenu component
  packages/sirius-web/frontend/sirius-web/src/views/edit-project/EditProjectNavbar/EditProjectNavbarContextMenu.tsx
  packages/sirius-web/frontend/sirius-web/src/views/edit-project/EditProjectNavbar/EditProjectNavbarContextMenu.types.ts
Labels: pr: to review later, priority: low

#1419 [perf] Log SQL queries slower than 20ms in dev mode
  packages/sirius-web/backend/sirius-web-sample-application/src/main/resources/application-dev.properties
Labels: pr: to review later, priority: low

#1424 [1423] Disable spell-checking on text fields
  CHANGELOG.adoc
  packages/forms/frontend/sirius-components-forms/src/propertysections/TextfieldPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/TextfieldPropertySection.test.tsx.snap
Labels: pr: to review later, priority: low
