Repository eclipse-sirius/sirius-web, pull requests merged in 2022-01, with the labels that each got.

#913 [908] Fix potential FAIL_ZERO_SUBSCRIBER errors
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/DiagramEventFlux.java
  backend/sirius-web-spring-collaborative-forms/src/main/java/org/eclipse/sirius/web/spring/collaborative/forms/FormEventProcessor.java
  backend/sirius-web-spring-collaborative-selection/src/main/java/org/eclipse/sirius/web/spring/collaborative/selection/SelectionEventProcessor.java
  backend/sirius-web-spring-collaborative-trees/src/main/java/org/eclipse/sirius/web/spring/collaborative/trees/TreeEventProcessor.java
  backend/sirius-web-spring-collaborative-validation/src/main/java/org/eclipse/sirius/web/spring/collaborative/validation/ValidationEventProcessor.java
  backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/projects/EditingContextEventProcessor.java
Labels: pr: to review soon, priority: high

#910 [896] Add default implementation of the new methods to the interface
  backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/ISiriusWebLayoutConfigurator.java
  backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/SiriusWebLayoutConfigurator.java
Labels: pr: to review later, priority: low

#916 [596] Fix a regresion which prevented the manual creation of node styles
  backend/sirius-web-view-edit/src/main/java/org/eclipse/sirius/web/view/provider/NodeDescriptionItemProvider.java
Labels: pr: to review soon, priority: high, area: view

#917 [915] Use failure messages to create error payload messages
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/DeleteFromDiagramEventHandler.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/DropOnDiagramEventHandler.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/InvokeDeleteToolOnDiagramEventHandler.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/InvokeEdgeToolOnDiagramEventHandler.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/InvokeNodeToolOnDiagramEventHandler.java
  backend/sirius-web-spring-collaborative-forms/src/main/java/org/eclipse/sirius/web/spring/collaborative/forms/handlers/DeleteListItemEventHandler.java
  backend/sirius-web-spring-collaborative-forms/src/main/java/org/eclipse/sirius/web/spring/collaborative/forms/handlers/EditCheckboxEventHandler.java
  backend/sirius-web-spring-collaborative-forms/src/main/java/org/eclipse/sirius/web/spring/collaborative/forms/handlers/EditMultiSelectEventHandler.java
  backend/sirius-web-spring-collaborative-forms/src/main/java/org/eclipse/sirius/web/spring/collaborative/forms/handlers/EditRadioEventHandler.java
  backend/sirius-web-spring-collaborative-forms/src/main/java/org/eclipse/sirius/web/spring/collaborative/forms/handlers/EditSelectEventHandler.java
  backend/sirius-web-spring-collaborative-forms/src/main/java/org/eclipse/sirius/web/spring/collaborative/forms/handlers/EditTextfieldEventHandler.java
  backend/sirius-web-spring-collaborative-trees/src/main/java/org/eclipse/sirius/web/spring/collaborative/trees/handlers/DeleteTreeItemEventHandler.java
  backend/sirius-web-spring-collaborative-trees/src/main/java/org/eclipse/sirius/web/spring/collaborative/trees/handlers/RenameTreeItemEventHandler.java
Labels: pr: to review soon, priority: high

#921 [enh] Update the Checkstyle configuration to prevent package modifiers
  backend/sirius-web-forms/src/main/java/org/eclipse/sirius/web/forms/components/WidgetIdCounter.java
  backend/sirius-web-resources/checkstyle/CheckstyleConfiguration.xml
Labels: pr: to review soon, priority: high

#922 [fix] Fix bug in edge tools conversion
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/ViewConverter.java
Labels: pr: to review soon, priority: high

#920 [888] Fix the initial expression in default edge create tools
  backend/sirius-web-view-edit/src/main/java/org/eclipse/sirius/web/view/provider/EdgeDescriptionItemProvider.java
Labels: pr: to review soon, priority: high

#911 [565] Improve the layout of multiple edges between the same nodes
  CHANGELOG.adoc
  backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/incremental/IncrementalLayoutDiagramConverter.java
  backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/incremental/IncrementalLayoutEngine.java
  backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/incremental/IncrementalLayoutedDiagramProvider.java
  backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/incremental/data/EdgeLayoutData.java
  backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/incremental/provider/EdgeRoutingPointsProvider.java
  backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/incremental/provider/NodePositionProvider.java
  backend/sirius-web-diagrams-layout/src/test/java/org/eclipse/sirius/web/diagrams/layout/incremental/NodePositionProviderTests.java
  backend/sirius-web-diagrams-tests/src/main/java/org/eclipse/sirius/web/diagrams/tests/TestDiagramBuilder.java
  backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/Edge.java
  backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/Ratio.java
  backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/components/EdgeComponent.java
  backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/elements/EdgeElementProps.java
  backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/events/EdgeCreationEvent.java
  backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/events/NodeCreationEvent.java
  backend/sirius-web-diagrams/src/main/java/org/eclipse/sirius/web/diagrams/renderer/DiagramElementFactory.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/dto/InvokeEdgeToolOnDiagramInput.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/DropOnDiagramEventHandler.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/InvokeEdgeToolOnDiagramEventHandler.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/java/org/eclipse/sirius/web/spring/collaborative/diagrams/handlers/InvokeNodeToolOnDiagramEventHandler.java
  backend/sirius-web-spring-collaborative-diagrams/src/main/resources/schema/diagram.graphqls
  doc/adrs/038_improve_the_layout_of_multiple_edges_between_the_same_nodes.adoc
  doc/adrs/images/038/038_anchors.png
  doc/adrs/images/038/038_initial_layout.png
  doc/adrs/images/038/038_move.png
  doc/adrs/images/038/038_relative_positions.png
  doc/adrs/images/038/038_routing_points.png
  frontend/src/diagram/DiagramWebSocketContainer.tsx
  frontend/src/diagram/DiagramWebSocketContainer.types.ts
  frontend/src/diagram/DiagramWebSocketContainerMachine.ts
  frontend/src/diagram/sprotty/DependencyInjection.ts
  frontend/src/diagram/sprotty/DiagramServer.tsx
  frontend/src/diagram/sprotty/DiagramServer.types.ts
Labels: pr: to review soon, priority: high

#935 [132] Fix a regression with the drop tool
  frontend/src/diagram/DropArea.tsx
  frontend/src/tree/TreeItem.tsx
Labels: pr: to review soon, priority: high

#918 [914] Add the graphical selection for nodes and edges
  CHANGELOG.adoc
  frontend/src/diagram/DiagramWebSocketContainer.tsx
  frontend/src/diagram/DiagramWebSocketContainerMachine.ts
  frontend/src/diagram/sprotty/DependencyInjection.ts
  frontend/src/diagram/sprotty/Diagram.types.ts
  frontend/src/diagram/sprotty/DiagramServer.tsx
  frontend/src/diagram/sprotty/DiagramServer.types.ts
  frontend/src/diagram/sprotty/__tests__/convertDiagram.test.ts
  frontend/src/diagram/sprotty/convertDiagram.tsx
Labels: pr: to review soon, priority: high

#926 [925] Perform a fit to screen after the first render of a diagram
  CHANGELOG.adoc
  frontend/src/diagram/sprotty/DiagramServer.tsx
Labels: pr: to review soon, priority: high

#941 [914] Consider that GQLNode#borderNodes and GQLNode#childNodes can be undefined
  frontend/src/diagram/DiagramWebSocketContainer.types.ts
  frontend/src/diagram/sprotty/convertDiagram.tsx
Labels: pr: to review soon, priority: high

#923 [884] Add support for defining unsynchronized diagram elements
  CHANGELOG.adoc
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/CanonicalBehaviors.java
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/ToolInterpreter.java
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/ViewConverter.java
  backend/sirius-web-view-edit/src/main/java/org/eclipse/sirius/web/view/provider/CreateViewItemProvider.java
  backend/sirius-web-view-edit/src/main/java/org/eclipse/sirius/web/view/provider/DeleteViewItemProvider.java
  backend/sirius-web-view-edit/src/main/java/org/eclipse/sirius/web/view/provider/DiagramDescriptionItemProvider.java
  backend/sirius-web-view-edit/src/main/java/org/eclipse/sirius/web/view/provider/DiagramElementDescriptionItemProvider.java
  backend/sirius-web-view-edit/src/main/java/org/eclipse/sirius/web/view/provider/DropToolItemProvider.java
  backend/sirius-web-view-edit/src/main/java/org/eclipse/sirius/web/view/provider/OperationItemProvider.java
  backend/sirius-web-view-edit/src/main/java/org/eclipse/sirius/web/view/provider/ToolItemProvider.java
  backend/sirius-web-view-edit/src/main/java/org/eclipse/sirius/web/view/provider/ViewItemProviderAdapterFactory.java
  backend/sirius-web-view-edit/src/main/resources/icons/full/obj16/CreateView.svg
  backend/sirius-web-view-edit/src/main/resources/icons/full/obj16/DeleteView.svg
  backend/sirius-web-view-edit/src/main/resources/icons/full/obj16/DropTool.svg
  backend/sirius-web-view-edit/src/main/resources/plugin.properties
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/CreateView.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/DeleteView.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/DiagramDescription.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/DiagramElementDescription.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/DropTool.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/SynchronizationPolicy.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/ViewFactory.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/ViewPackage.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/CreateViewImpl.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/DeleteViewImpl.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/DiagramDescriptionImpl.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/DiagramElementDescriptionImpl.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/DropToolImpl.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/ViewFactoryImpl.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/ViewPackageImpl.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/util/ViewAdapterFactory.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/util/ViewSwitch.java
  backend/sirius-web-view/src/main/resources/model/view.ecore
  backend/sirius-web-view/src/main/resources/model/view.genmodel
Labels: pr: to review soon, priority: high

#947 [936] Add support for preconditionExpression in dynamic representations
  CHANGELOG.adoc
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/ViewConverter.java
  backend/sirius-web-view-edit/src/main/java/org/eclipse/sirius/web/view/provider/RepresentationDescriptionItemProvider.java
  backend/sirius-web-view-edit/src/main/resources/plugin.properties
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/RepresentationDescription.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/ViewPackage.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/RepresentationDescriptionImpl.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/ViewPackageImpl.java
  backend/sirius-web-view/src/main/resources/model/view.ecore
  backend/sirius-web-view/src/main/resources/model/view.genmodel
Labels: pr: to review soon, priority: high

#950 [949] Fix the position of the begin/end labels on edges
  CHANGELOG.adoc
  backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/ELKDiagramConverter.java
Labels: pr: to review soon, priority: high

#953 [878] Fix tooltips for tree items
  CHANGELOG.adoc
  frontend/src/tree/TreeItem.tsx
Labels: pr: to review later, priority: low

#963 [doc] Mention external contributors to v2022.01.0 in the CHANGELOG
  CHANGELOG.adoc
Labels: pr: to review later, priority: low

#955 [enh] Use simple type names for the canonical creation tools
  CHANGELOG.adoc
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/ViewConverter.java
Labels: pr: to review later, priority: low

#961 [957] Fix the fit to screen triggered by initialize canvas bounds
  frontend/src/diagram/sprotty/DiagramServer.tsx
Labels: pr: to review later, priority: high

#951 [943] Add support for begin/end labels on edges
  CHANGELOG.adoc
  backend/sirius-web-emf/src/main/java/org/eclipse/sirius/web/emf/view/ViewConverter.java
  backend/sirius-web-view-edit/src/main/java/org/eclipse/sirius/web/view/provider/EdgeDescriptionItemProvider.java
  backend/sirius-web-view-edit/src/main/resources/plugin.properties
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/EdgeDescription.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/ViewPackage.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/EdgeDescriptionImpl.java
  backend/sirius-web-view/src/main/java/org/eclipse/sirius/web/view/impl/ViewPackageImpl.java
  backend/sirius-web-view/src/main/resources/model/view.ecore
  backend/sirius-web-view/src/main/resources/model/view.genmodel
Labels: pr: to review soon, priority: high

#968 [822] Fix a crash while clicking on an edge
  frontend/src/diagram/DiagramWebSocketContainer.types.ts
  frontend/src/diagram/palette/ContextualPalette.tsx
Labels: pr: to review soon, priority: high

#973 [972] Prevent the changeDescriptionSink from crashing because of the refresh
  backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/editingcontext/EditingContextEventProcessor.java
  backend/sirius-web-tests/src/test/java/org/eclipse/sirius/web/tests/GeneralPurposeTests.java
Labels: pr: to review soon, priority: high

#971 [948] Fix edge label positioning
  backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/incremental/provider/EdgeLabelPositionProvider.java
  backend/sirius-web-diagrams-layout/src/main/java/org/eclipse/sirius/web/diagrams/layout/incremental/provider/EdgeRoutingPointsProvider.java
Labels: pr: to review soon, priority: high

#1011 [releng] Bump version to 2022.01.0
  CHANGELOG.adoc
  backend/pom.xml
  backend/sirius-web-annotations-spring/pom.xml
  backend/sirius-web-annotations/pom.xml
  backend/sirius-web-api/pom.xml
  backend/sirius-web-compatibility/pom.xml
  backend/sirius-web-components/pom.xml
  backend/sirius-web-core-api/pom.xml
  backend/sirius-web-diagrams-layout-api/pom.xml
  backend/sirius-web-diagrams-layout/pom.xml
  backend/sirius-web-diagrams-tests/pom.xml
  backend/sirius-web-diagrams/pom.xml
  backend/sirius-web-domain-design/pom.xml
  backend/sirius-web-domain-edit/pom.xml
  backend/sirius-web-domain/pom.xml
  backend/sirius-web-emf/pom.xml
  backend/sirius-web-forms-tests/pom.xml
  backend/sirius-web-forms/pom.xml
  backend/sirius-web-graphiql/pom.xml
  backend/sirius-web-graphql-utils/pom.xml
  backend/sirius-web-graphql-voyager/pom.xml
  backend/sirius-web-interpreter/pom.xml
  backend/sirius-web-representations/pom.xml
  backend/sirius-web-selection/pom.xml
  backend/sirius-web-spring-collaborative-diagrams/pom.xml
  backend/sirius-web-spring-collaborative-forms/pom.xml
  backend/sirius-web-spring-collaborative-selection/pom.xml
  backend/sirius-web-spring-collaborative-trees/pom.xml
  backend/sirius-web-spring-collaborative-validation/pom.xml
  backend/sirius-web-spring-collaborative/pom.xml
  backend/sirius-web-spring-graphql-api/pom.xml
  backend/sirius-web-spring-graphql/pom.xml
  backend/sirius-web-spring-starter/pom.xml
  backend/sirius-web-spring-tests/pom.xml
  backend/sirius-web-tests/pom.xml
  backend/sirius-web-trees/pom.xml
  backend/sirius-web-validation/pom.xml
  backend/sirius-web-view-edit/pom.xml
  backend/sirius-web-view/pom.xml
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to review soon, priority: high

#1016 [releng] Fix package name in the sirius-components-starter
  backend/sirius-components-starter/src/main/java/org/eclipse/sirius/components/starter/SiriusWebStarterConfiguration.java
Labels: pr: to review soon, priority: high

#965 [test] Add code coverage aggregation
  .github/workflows/build.yml
  backend/pom.xml
  backend/sirius-components-test-coverage/.project
  backend/sirius-components-test-coverage/pom.xml
Labels: pr: to review later, priority: low

#981 [releng] Remove the unused dependency to EEF
  backend/sirius-components-compatibility/pom.xml
Labels: pr: to review later, priority: low

#993 [992] Accept static domain types
  CHANGELOG.adoc
  backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/view/ViewValidator.java
Labels: pr: to review later, priority: low

#1024 [releng] Make the test coverage project work with the bump-version script
  backend/pom.xml
  backend/sirius-components-annotations-spring/pom.xml
  backend/sirius-components-annotations/pom.xml
  backend/sirius-components-collaborative-diagrams/pom.xml
  backend/sirius-components-collaborative-forms/pom.xml
  backend/sirius-components-collaborative-selection/pom.xml
  backend/sirius-components-collaborative-trees/pom.xml
  backend/sirius-components-collaborative-validation/pom.xml
  backend/sirius-components-collaborative/pom.xml
  backend/sirius-components-compatibility/pom.xml
  backend/sirius-components-core/pom.xml
  backend/sirius-components-diagrams-layout-api/pom.xml
  backend/sirius-components-diagrams-layout/pom.xml
  backend/sirius-components-diagrams-tests/pom.xml
  backend/sirius-components-diagrams/pom.xml
  backend/sirius-components-domain-design/pom.xml
  backend/sirius-components-domain-edit/pom.xml
  backend/sirius-components-domain/pom.xml
  backend/sirius-components-emf/pom.xml
  backend/sirius-components-forms-tests/pom.xml
  backend/sirius-components-forms/pom.xml
  backend/sirius-components-graphiql/pom.xml
  backend/sirius-components-graphql-api/pom.xml
  backend/sirius-components-graphql-utils/pom.xml
  backend/sirius-components-graphql-voyager/pom.xml
  backend/sirius-components-graphql/pom.xml
  backend/sirius-components-interpreter/pom.xml
  backend/sirius-components-representations/pom.xml
  backend/sirius-components-selection/pom.xml
  backend/sirius-components-spring-tests/pom.xml
  backend/sirius-components-starter/pom.xml
  backend/sirius-components-test-coverage/pom.xml
  backend/sirius-components-tests/pom.xml
  backend/sirius-components-trees/pom.xml
  backend/sirius-components-validation/pom.xml
  backend/sirius-components-view-edit/pom.xml
  backend/sirius-components-view/pom.xml
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to review soon, priority: high
