Repository eclipse-sirius/sirius-web, pull requests merged in 2022-01, with the labels that each got.

#154 [enh] Update the snippet for EPL 2.0 block
  frontend/.vscode/snippets.code-snippets
Labels: pr: to review soon, priority: high

#153 [878] Switch to a URL based kind for the selection
  backend/sirius-web-frontend/pom.xml
  backend/sirius-web-graphql-schema/pom.xml
  backend/sirius-web-graphql-schema/src/main/java/org/eclipse/sirius/web/graphql/schema/EditingContextTypeProvider.java
  backend/sirius-web-graphql/pom.xml
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/editingcontext/EditingContextChildCreationDescriptionsDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/editingcontext/EditingContextRepresentationDescriptionsDataFetcher.java
  backend/sirius-web-persistence/pom.xml
  backend/sirius-web-sample-application/pom.xml
  backend/sirius-web-services-api/pom.xml
  backend/sirius-web-services/pom.xml
  backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/explorer/DeleteObjectTreeItemEventHandler.java
  backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/explorer/DeleteRepresentationTreeItemEventHandler.java
  backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/explorer/ExplorerDescriptionProvider.java
  backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/explorer/RenameObjectTreeItemEventHandler.java
  backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/explorer/RenameRepresentationTreeItemHandler.java
  backend/sirius-web-spring/pom.xml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/views/edit-project/EditProjectView.tsx
Labels: pr: to review soon, priority: high

#159 [932] Add support for the RepresentationMetadata
  backend/sirius-web-frontend/pom.xml
  backend/sirius-web-graphql-schema/pom.xml
  backend/sirius-web-graphql/pom.xml
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/diagram/DiagramToolsDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/editingcontext/EditingContextRepresentationDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/editingcontext/EditingContextRepresentationsDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/representation/RepresentationMetadataDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/representation/RepresentationMetadataDescriptionDataFetcher.java
  backend/sirius-web-persistence/pom.xml
  backend/sirius-web-sample-application/pom.xml
  backend/sirius-web-services-api/pom.xml
  backend/sirius-web-services/pom.xml
  backend/sirius-web-spring/pom.xml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/views/edit-project/EditProjectView.types.ts
Labels: pr: to review soon, priority: high

#163 [releng] Switch to Sirius Components 2021.12.12
  backend/sirius-web-frontend/pom.xml
  backend/sirius-web-graphql-schema/pom.xml
  backend/sirius-web-graphql/pom.xml
  backend/sirius-web-persistence/pom.xml
  backend/sirius-web-sample-application/pom.xml
  backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/configuration/GraphQLWebSocketConfiguration.java
  backend/sirius-web-services-api/pom.xml
  backend/sirius-web-services/pom.xml
  backend/sirius-web-spring/pom.xml
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to review soon, priority: high

#157 [878] Adjust Cypress tests to URL-based kinds
  backend/sirius-web-frontend/pom.xml
  backend/sirius-web-graphql-schema/pom.xml
  backend/sirius-web-graphql/pom.xml
  backend/sirius-web-persistence/pom.xml
  backend/sirius-web-sample-application/pom.xml
  backend/sirius-web-services-api/pom.xml
  backend/sirius-web-services/pom.xml
  backend/sirius-web-spring/pom.xml
  frontend/package-lock.json
  frontend/package.json
  integration-tests/cypress/integration/project/edit/diagram-edit-robot_spec.js
  integration-tests/cypress/support/serverCommands.js
Labels: pr: to review soon, priority: high

#166 [releng] Switch to Sirius Components 2021.12.15
  backend/sirius-web-frontend/pom.xml
  backend/sirius-web-graphql-schema/pom.xml
  backend/sirius-web-graphql/pom.xml
  backend/sirius-web-persistence/pom.xml
  backend/sirius-web-sample-application/pom.xml
  backend/sirius-web-services-api/pom.xml
  backend/sirius-web-services/pom.xml
  backend/sirius-web-spring/pom.xml
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to review soon, priority: high

#167 [releng] Switch to Sirius Components 2021.12.16
  backend/sirius-web-frontend/pom.xml
  backend/sirius-web-graphql-schema/pom.xml
  backend/sirius-web-graphql/pom.xml
  backend/sirius-web-persistence/pom.xml
  backend/sirius-web-sample-application/pom.xml
  backend/sirius-web-services-api/pom.xml
  backend/sirius-web-services/pom.xml
  backend/sirius-web-spring/pom.xml
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to review soon, priority: high

#168 [cleanup] Fix invalid copyright and license
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationDeleteListItemDataFetcher.java
  backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/services/EditingDomainServicesProvider.java
Labels: pr: to review later, priority: low

#174 [releng] Bump version to 2022.01.0
  backend/pom.xml
  backend/sirius-web-frontend/pom.xml
  backend/sirius-web-graphql-schema/pom.xml
  backend/sirius-web-graphql/pom.xml
  backend/sirius-web-persistence/pom.xml
  backend/sirius-web-sample-application/pom.xml
  backend/sirius-web-services-api/pom.xml
  backend/sirius-web-services/pom.xml
  backend/sirius-web-spring/pom.xml
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to review soon, priority: high

#175 [releng] Switch to Sirius Components 2022.01.1
  backend/sirius-web-frontend/pom.xml
  backend/sirius-web-graphql-schema/pom.xml
  backend/sirius-web-graphql/pom.xml
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/editingcontext/EditingContextStereotypeDescriptionsDataFetcher.java
  backend/sirius-web-persistence/pom.xml
  backend/sirius-web-sample-application/pom.xml
  backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/configuration/StereotypeDescriptionRegistryConfigurer.java
  backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/services/ImagePathService.java
  backend/sirius-web-services-api/pom.xml
  backend/sirius-web-services-api/src/main/java/org/eclipse/sirius/web/services/api/stereotypes/IStereotypeDescriptionService.java
  backend/sirius-web-services/pom.xml
  backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/configuration/RepresentationDescriptionConfiguration.java
  backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/configuration/StereotypeDescriptionConfiguration.java
  backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/documents/CreateDocumentEventHandler.java
  backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/representations/RepresentationDescriptionRegistry.java
  backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/stereotypes/StereotypeDescriptionRegistry.java
  backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/stereotypes/StereotypeDescriptionService.java
  backend/sirius-web-services/src/test/java/org/eclipse/sirius/web/services/documents/CreateDocumentEventHandlerTests.java
  backend/sirius-web-spring/pom.xml
  backend/sirius-web-spring/src/main/java/org/eclipse/sirius/web/spring/controllers/ImagesController.java
  backend/sirius-web-spring/src/test/java/org/eclipse/sirius/web/spring/controllers/ImagesControllerTests.java
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to review soon, priority: high, waiting for sirius components

#169 [998] Remove the GraphQL annotations
  backend/sirius-web-graphql-schema/src/main/java/org/eclipse/sirius/web/graphql/schema/MutationTypeProvider.java
  backend/sirius-web-graphql-schema/src/main/java/org/eclipse/sirius/web/graphql/schema/SubscriptionTypeProvider.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationArrangeAllDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationCreateChildDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationCreateDocumentDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationCreateProjectDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationCreateRepresentationDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationCreateRootObjectDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationDeleteDocumentDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationDeleteFromDiagramDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationDeleteListItemDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationDeleteObjectDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationDeleteProjectDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationDeleteRepresentationDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationDeleteTreeItemDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationEditCheckboxDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationEditLabelDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationEditMultiSelectDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationEditRadioDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationEditSelectDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationEditTextfieldDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationInvokeEdgeToolOnDiagramDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationInvokeNodeToolOnDiagramDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationRenameDocumentDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationRenameObjectDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationRenameProjectDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationRenameRepresentationDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationRenameTreeItemDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationUpdateNodeBoundsDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationUpdateNodePositionDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationUpdateWidgetFocusDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationUploadDocumentDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationUploadProjectDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/subscriptions/SubscriptionDiagramEventDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/subscriptions/SubscriptionEditingContextEventDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/subscriptions/SubscriptionFormEventDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/subscriptions/SubscriptionPropertiesEventDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/subscriptions/SubscriptionRepresentationsEventDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/subscriptions/SubscriptionSelectionEventDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/subscriptions/SubscriptionTreeEventDataFetcher.java
  backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/subscriptions/SubscriptionValidationEventDataFetcher.java
  backend/sirius-web-services-api/src/main/java/org/eclipse/sirius/web/services/api/accounts/Profile.java
  backend/sirius-web-services-api/src/main/java/org/eclipse/sirius/web/services/api/document/UploadDocumentInput.java
  backend/sirius-web-services-api/src/main/java/org/eclipse/sirius/web/services/api/document/UploadDocumentSuccessPayload.java
  backend/sirius-web-services-api/src/main/java/org/eclipse/sirius/web/services/api/projects/AccessLevel.java
  backend/sirius-web-services-api/src/main/java/org/eclipse/sirius/web/services/api/projects/CreateProjectInput.java
  backend/sirius-web-services-api/src/main/java/org/eclipse/sirius/web/services/api/projects/CreateProjectSuccessPayload.java
  backend/sirius-web-services-api/src/main/java/org/eclipse/sirius/web/services/api/projects/DeleteProjectInput.java
  backend/sirius-web-services-api/src/main/java/org/eclipse/sirius/web/services/api/projects/DeleteProjectSuccessPayload.java
  backend/sirius-web-services-api/src/main/java/org/eclipse/sirius/web/services/api/projects/RenameProjectInput.java
  backend/sirius-web-services-api/src/main/java/org/eclipse/sirius/web/services/api/projects/RenameProjectSuccessPayload.java
  backend/sirius-web-services-api/src/main/java/org/eclipse/sirius/web/services/api/projects/UploadProjectInput.java
  backend/sirius-web-services-api/src/main/java/org/eclipse/sirius/web/services/api/projects/UploadProjectSuccessPayload.java
  backend/sirius-web-services-api/src/main/java/org/eclipse/sirius/web/services/api/projects/Visibility.java
  backend/sirius-web-services-api/src/main/java/org/eclipse/sirius/web/services/api/viewer/IViewer.java
  backend/sirius-web-services-api/src/test/java/org/eclipse/sirius/web/services/api/architecture/CodingRulesTests.java
Labels: pr: to review later, priority: low

#164 [975] Add some Sirius Web GraphQL fields removed from Sirius Components
  backend/sirius-web-frontend/pom.xml
  backend/sirius-web-graphql-schema/pom.xml
  backend/sirius-web-graphql-schema/src/main/java/org/eclipse/sirius/web/graphql/schema/ChildCreationDescriptionTypeProvider.java
  backend/sirius-web-graphql-schema/src/main/java/org/eclipse/sirius/web/graphql/schema/DiagramTypesProvider.java
  backend/sirius-web-graphql-schema/src/main/java/org/eclipse/sirius/web/graphql/schema/DocumentTypesProvider.java
  backend/sirius-web-graphql-schema/src/main/java/org/eclipse/sirius/web/graphql/schema/DomainTypeProvider.java
  backend/sirius-web-graphql-schema/src/main/java/org/eclipse/sirius/web/graphql/schema/EditingContextTypeProvider.java
  backend/sirius-web-graphql-schema/src/main/java/org/eclipse/sirius/web/graphql/schema/FormTypesProvider.java
  backend/sirius-web-graphql-schema/src/main/java/org/eclipse/sirius/web/graphql/schema/MutationTypeProvider.java
  backend/sirius-web-graphql-schema/src/main/java/org/eclipse/sirius/web/graphql/schema/ObjectTypeProvider.java
  backend/sirius-web-graphql-schema/src/main/java/org/eclipse/sirius/web/graphql/schema/PageInfoTypeProvider.java
  backend/sirius-web-graphql-schema/src/main/java/org/eclipse/sirius/web/graphql/schema/ProfileTypeProvider.java
  backend/sirius-web-graphql-schema/src/main/java/org/eclipse/sirius/web/graphql/schema/ProjectTypeProvider.java
  backend/sirius-web-graphql-schema/src/main/java/org/eclipse/sirius/web/graphql/schema/QueryTypeProvider.java
  backend/sirius-web-graphql-schema/src/main/java/org/eclipse/sirius/web/graphql/schema/RepresentationDescriptionTypeProvider.java
  backend/sirius-web-graphql-schema/src/main/java/org/eclipse/sirius/web/graphql/schema/RepresentationTypeProvider.java
  backend/sirius-web-graphql-schema/src/main/java/org/eclipse/sirius/web/graphql/schema/SelectionTypesProvider.java
  backend/sirius-web-graphql-schema/src/main/java/org/eclipse/sirius/web/graphql/schema/StereotypeDescriptionTypeProvider.java
  backend/sirius-web-graphql-schema/src/main/java/org/eclipse/sirius/web/graphql/schema/SubscriptionTypeProvider.java
  backend/sirius-web-graphql-schema/src/main/java/org/eclipse/sirius/web/graphql/schema/ToolTypeProvider.java
  backend/sirius-web-graphql-schema/src/main/java/org/eclipse/sirius/web/graphql/schema/TreeTypeProvider.java
  backend/sirius-web-graphql-schema/src/main/java/org/eclipse/sirius/web/graphql/schema/ValidationTypesProvider.java
  backend/sirius-web-graphql-schema/src/main/java/org/eclipse/sirius/web/graphql/schema/ViewerTypeProvider.java
  backend/sirius-web-graphql/pom.xml
  backend/sirius-web-graphql/src/main/resources/schema/siriusweb.graphqls
  backend/sirius-web-persistence/pom.xml
  backend/sirius-web-sample-application/pom.xml
  backend/sirius-web-services-api/pom.xml
  backend/sirius-web-services/pom.xml
  backend/sirius-web-spring/pom.xml
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to review later, priority: low, waiting for sirius components
