Repository eclipse-sirius/sirius-web, pull requests merged in 2022-04, with the labels that each got.

#1137 [cleanup] Fix CheckStyle error
  backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/view/diagram/NodeStylePropertiesConfigurer.java
Labels: pr: to review soon, priority: low

#1143 [cleanup] Improve the typing of PropertiesWebSocketContainer
  frontend/src/form/FormEventFragments.types.ts
  frontend/src/properties/PropertiesWebSocketContainer.tsx
Labels: pr: to review soon, priority: low

#1166 [1165] Improve the pull request template
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.adoc
Labels: pr: to review soon, priority: high

#1167 [releng] Bump version to 2022.3.5
  backend/pom.xml
  backend/sirius-components-annotations-spring/pom.xml
  backend/sirius-components-annotations/pom.xml
  backend/sirius-components-collaborative-diagrams/pom.xml
  backend/sirius-components-collaborative-forms/pom.xml
  backend/sirius-components-collaborative-selection/pom.xml
  backend/sirius-components-collaborative-trees/pom.xml
  backend/sirius-components-collaborative-validation/pom.xml
  backend/sirius-components-collaborative/pom.xml
  backend/sirius-components-compatibility/pom.xml
  backend/sirius-components-core/pom.xml
  backend/sirius-components-diagrams-layout-api/pom.xml
  backend/sirius-components-diagrams-layout/pom.xml
  backend/sirius-components-diagrams-tests/pom.xml
  backend/sirius-components-diagrams/pom.xml
  backend/sirius-components-domain-design/pom.xml
  backend/sirius-components-domain-edit/pom.xml
  backend/sirius-components-domain/pom.xml
  backend/sirius-components-emf/pom.xml
  backend/sirius-components-forms-tests/pom.xml
  backend/sirius-components-forms/pom.xml
  backend/sirius-components-graphiql/pom.xml
  backend/sirius-components-graphql-api/pom.xml
  backend/sirius-components-graphql-utils/pom.xml
  backend/sirius-components-graphql-voyager/pom.xml
  backend/sirius-components-graphql/pom.xml
  backend/sirius-components-interpreter/pom.xml
  backend/sirius-components-representations/pom.xml
  backend/sirius-components-selection/pom.xml
  backend/sirius-components-spring-tests/pom.xml
  backend/sirius-components-starter/pom.xml
  backend/sirius-components-test-coverage/pom.xml
  backend/sirius-components-tests/pom.xml
  backend/sirius-components-trees/pom.xml
  backend/sirius-components-validation/pom.xml
  backend/sirius-components-view-edit/pom.xml
  backend/sirius-components-view/pom.xml
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to review soon, priority: high

#1153 [test] Fix the edge rendering in tests
  backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/incremental/DiagramLayoutTests.java
  backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/services/DefaultTestDiagramDescriptionProvider.java
  backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/services/DiagramELKLayoutTest.java
  backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/builder/TestLayoutDiagramBuilder.java
Labels: pr: to review soon, priority: high

#1156 [1154] Display the palette where the click has been made
  CHANGELOG.adoc
  frontend/src/diagram/sprotty/DiagramServer.tsx
  frontend/src/diagram/sprotty/DiagramServer.types.ts
Labels: pr: to review soon, priority: high

#1111 [cleanup] Express TreeItem css with material ui
  frontend/src/tree/TreeItem.module.css
  frontend/src/tree/TreeItem.tsx
Labels: pr: to review soon, priority: high

#1162 [doc] Add ADR for form descriptions in the view converter support
  CHANGELOG.adoc
  doc/adrs/053_add_support_for_form_descriptions_in_the_view_converter.adoc
Labels: pr: to review soon, priority: high

#1190 [releng] Exclude removed files from the list to check copyrights
  scripts/check-copyright.js
Labels: pr: to review soon, priority: high

#1189 [1179] Make WorkbenchSelection and WorkbenchSelectionEntry serializable
  backend/sirius-components-representations/src/main/java/org/eclipse/sirius/components/representations/WorkbenchSelection.java
  backend/sirius-components-representations/src/main/java/org/eclipse/sirius/components/representations/WorkbenchSelectionEntry.java
Labels: pr: to review soon, priority: high

#1188 [1176] Fix Exception in ViewDiagramDescriptionConverter
  CHANGELOG.adoc
  backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/BorderNodesOnSide.java
  backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/view/diagram/ViewDiagramDescriptionConverter.java
  backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/view/diagram/ViewDiagramDescriptionConverterContext.java
  backend/sirius-components-tests/src/main/java/org/eclipse/sirius/components/tests/architecture/AbstractCodingRulesTests.java
Labels: type: bug 💥, pr: to review soon, priority: high

#1172 [doc] Update ADR to support textfield editing
  doc/adrs/053_add_support_for_form_descriptions_in_the_view_converter.adoc
Labels: pr: to review soon, priority: high
