Repository eclipse-sirius/sirius-web, pull requests merged in 2022-11, with the labels that each got.

#1455 [1454] Misprint in VSCode Extension README
  CHANGELOG.adoc
  vscode-extension/README.md
Labels: pr: to review soon, priority: low

#1459 [releng] Setup the continuous deployment
  .github/workflows/build.yml
  Dockerrun.aws.json.template
  packages/sirius-web/backend/sirius-web-sample-application/Dockerfile
  packages/sirius-web/backend/sirius-web-sample-application/docker-compose.yml
Labels: pr: to review soon, priority: high

#1445 [releng] Upgrade to Batik 1.16
  CHANGELOG.adoc
  packages/diagrams/backend/sirius-components-diagrams-layout/pom.xml
Labels: pr: to review soon, priority: low

#1371 [releng] Swith to Spring Boot 2.7.5
  CHANGELOG.adoc
  packages/charts/backend/sirius-components-charts/pom.xml
  packages/charts/backend/sirius-components-collaborative-charts/pom.xml
  packages/compatibility/backend/sirius-components-compatibility-emf/pom.xml
  packages/compatibility/backend/sirius-components-compatibility/pom.xml
  packages/core/backend/sirius-components-annotations-spring/pom.xml
  packages/core/backend/sirius-components-annotations/pom.xml
  packages/core/backend/sirius-components-collaborative/pom.xml
  packages/core/backend/sirius-components-core/pom.xml
  packages/core/backend/sirius-components-graphql-api/pom.xml
  packages/core/backend/sirius-components-representations/pom.xml
  packages/diagrams/backend/sirius-components-collaborative-diagrams/pom.xml
  packages/diagrams/backend/sirius-components-diagrams-graphql/pom.xml
  packages/diagrams/backend/sirius-components-diagrams-layout-api/pom.xml
  packages/diagrams/backend/sirius-components-diagrams-layout/pom.xml
  packages/diagrams/backend/sirius-components-diagrams-tests/pom.xml
  packages/diagrams/backend/sirius-components-diagrams/pom.xml
  packages/domain/backend/sirius-components-domain-design/pom.xml
  packages/domain/backend/sirius-components-domain-edit/pom.xml
  packages/domain/backend/sirius-components-domain-emf/pom.xml
  packages/domain/backend/sirius-components-domain/pom.xml
  packages/emf/backend/sirius-components-emf/pom.xml
  packages/emf/backend/sirius-components-interpreter/pom.xml
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/pom.xml
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors-graphql/pom.xml
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors/pom.xml
  packages/forms/backend/sirius-components-collaborative-forms/pom.xml
  packages/forms/backend/sirius-components-forms-graphql/pom.xml
  packages/forms/backend/sirius-components-forms-tests/pom.xml
  packages/forms/backend/sirius-components-forms/pom.xml
  packages/releng/backend/sirius-components-test-coverage/pom.xml
  packages/selection/backend/sirius-components-collaborative-selection/pom.xml
  packages/selection/backend/sirius-components-selection-graphql/pom.xml
  packages/selection/backend/sirius-components-selection/pom.xml
  packages/sirius-web/backend/sirius-web-frontend/pom.xml
  packages/sirius-web/backend/sirius-web-graphql-schema/pom.xml
  packages/sirius-web/backend/sirius-web-graphql/pom.xml
  packages/sirius-web/backend/sirius-web-persistence/pom.xml
  packages/sirius-web/backend/sirius-web-sample-application/pom.xml
  packages/sirius-web/backend/sirius-web-services-api/pom.xml
  packages/sirius-web/backend/sirius-web-services/pom.xml
  packages/sirius-web/backend/sirius-web-spring/pom.xml
  packages/starters/backend/sirius-components-starter/pom.xml
  packages/tests/backend/sirius-components-spring-tests/pom.xml
  packages/tests/backend/sirius-components-tests/pom.xml
  packages/tools/backend/sirius-components-graphiql/pom.xml
  packages/tools/backend/sirius-components-graphql-voyager/pom.xml
  packages/trees/backend/sirius-components-collaborative-trees/pom.xml
  packages/trees/backend/sirius-components-trees-graphql/pom.xml
  packages/trees/backend/sirius-components-trees/pom.xml
  packages/validation/backend/sirius-components-collaborative-validation/pom.xml
  packages/validation/backend/sirius-components-validation-graphql/pom.xml
  packages/validation/backend/sirius-components-validation/pom.xml
  packages/view/backend/sirius-components-view-edit/pom.xml
  packages/view/backend/sirius-components-view-emf/pom.xml
  packages/view/backend/sirius-components-view/pom.xml
  packages/web/backend/sirius-components-graphql/pom.xml
  packages/web/backend/sirius-components-web/pom.xml
Labels: pr: to review later, priority: low

#1432 [1431] Prevent using default String widget for multivaluated attributes
  CHANGELOG.adoc
  packages/compatibility/backend/sirius-components-compatibility-emf/src/main/java/org/eclipse/sirius/components/compatibility/emf/properties/EStringIfDescriptionProvider.java
Labels: pr: to review soon, priority: low

#1465 [1453] Add new arrow styles Circle, FillCircle and CrossedCircle
  CHANGELOG.adoc
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/resources/schema/diagram.graphqls
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/ArrowStyle.java
  packages/diagrams/frontend/sirius-components-diagrams/src/representation/DiagramRepresentation.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/sprotty/Diagram.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/sprotty/views/EdgeView.tsx
  packages/view/backend/sirius-components-view-edit/src/main/resources/plugin.properties
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/ArrowStyle.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/impl/ViewPackageImpl.java
  packages/view/backend/sirius-components-view/src/main/resources/model/view.ecore
  packages/view/backend/sirius-components-view/src/main/resources/model/view.genmodel
Labels: pr: to review soon, priority: high

#1449 [1448] Make AddWidgetEventHandler less dependent on naming conventions
  CHANGELOG.adoc
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/AddWidgetEventHandler.java
Labels: pr: to review soon, priority: high

#1466 [releng] Package the VSCode extension during the build
  .github/workflows/build.yml
  vscode-extension/package-lock.json
  vscode-extension/package.json
Labels: pr: to review soon, priority: high

#1436 [doc] Add ADR about improving the support for direct edit
  CHANGELOG.adoc
  doc/adrs/077_improve_support_for_direct_edit.adoc
Labels: pr: to review soon, priority: high

#1472 [1364] Refactor DynamicFormsTests to please Checkstyle
  packages/view/backend/sirius-components-view-emf/src/test/java/org/eclipse/sirius/components/view/emf/view/DynamicFormsTests.java
Labels: pr: to review soon, priority: high

#1476 [fix] Fix potential NPEs in upload data fetchers
  packages/sirius-web/backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationUploadDocumentDataFetcher.java
  packages/sirius-web/backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationUploadProjectDataFetcher.java
Labels: pr: to review soon, priority: low

#1471 [releng] Run checkstyle on test folders during the build
  packages/charts/backend/sirius-components-charts/pom.xml
  packages/charts/backend/sirius-components-collaborative-charts/pom.xml
  packages/compatibility/backend/sirius-components-compatibility-emf/pom.xml
  packages/compatibility/backend/sirius-components-compatibility/pom.xml
  packages/core/backend/sirius-components-annotations-spring/pom.xml
  packages/core/backend/sirius-components-annotations/pom.xml
  packages/core/backend/sirius-components-collaborative/pom.xml
  packages/core/backend/sirius-components-core/pom.xml
  packages/core/backend/sirius-components-graphql-api/pom.xml
  packages/core/backend/sirius-components-representations/pom.xml
  packages/diagrams/backend/sirius-components-collaborative-diagrams/pom.xml
  packages/diagrams/backend/sirius-components-diagrams-graphql/pom.xml
  packages/diagrams/backend/sirius-components-diagrams-layout-api/pom.xml
  packages/diagrams/backend/sirius-components-diagrams-layout/pom.xml
  packages/diagrams/backend/sirius-components-diagrams-tests/pom.xml
  packages/diagrams/backend/sirius-components-diagrams/pom.xml
  packages/domain/backend/sirius-components-domain-emf/pom.xml
  packages/emf/backend/sirius-components-emf/pom.xml
  packages/emf/backend/sirius-components-interpreter/pom.xml
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/pom.xml
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors-graphql/pom.xml
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors/pom.xml
  packages/forms/backend/sirius-components-collaborative-forms/pom.xml
  packages/forms/backend/sirius-components-forms-graphql/pom.xml
  packages/forms/backend/sirius-components-forms-tests/pom.xml
  packages/forms/backend/sirius-components-forms/pom.xml
  packages/releng/backend/sirius-components-resources/checkstyle/CheckstyleConfiguration.xml
  packages/selection/backend/sirius-components-collaborative-selection/pom.xml
  packages/selection/backend/sirius-components-selection-graphql/pom.xml
  packages/selection/backend/sirius-components-selection/pom.xml
  packages/starters/backend/sirius-components-starter/pom.xml
  packages/tests/backend/sirius-components-spring-tests/pom.xml
  packages/tests/backend/sirius-components-tests/pom.xml
  packages/trees/backend/sirius-components-collaborative-trees/pom.xml
  packages/trees/backend/sirius-components-trees-graphql/pom.xml
  packages/trees/backend/sirius-components-trees/pom.xml
  packages/validation/backend/sirius-components-collaborative-validation/pom.xml
  packages/validation/backend/sirius-components-validation-graphql/pom.xml
  packages/validation/backend/sirius-components-validation/pom.xml
  packages/view/backend/sirius-components-view-emf/pom.xml
  packages/web/backend/sirius-components-graphql/pom.xml
  packages/web/backend/sirius-components-web/pom.xml
Labels: pr: to review soon, priority: high

#1475 [1397] Improve support for canonical tools of reused node descriptions
  CHANGELOG.adoc
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewDiagramDescriptionConverter.java
  packages/view/backend/sirius-components-view-emf/src/test/java/org/eclipse/sirius/components/view/emf/view/DynamicDiagramsTests.java
Labels: pr: to review soon, priority: high

#1478 [1439] Add frontend tests for ToolbarActions
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/ToolbarActionWidget.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/ToolbarActions.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/__tests__/ToolbarActions.test.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/__tests__/WidgetEntry.test.tsx
Labels: pr: to review soon, priority: high

#1480 [666] Make the contextual palette display the tools of the current selection
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/palette/ContextualPalette.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/palette/ContextualPaletteMachine.ts
Labels: pr: to review soon, priority: high

#1414 [1428] Add support for list compartment
  CHANGELOG.adoc
  doc/adrs/069_add_support_for_children_layout_strategy.adoc
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/ELKDiagramConverter.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/ILayoutEngineHandlerSwitchProvider.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/LayoutConfiguratorRegistry.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/LayoutOptionValues.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/configuration/LayoutConfiguration.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/BorderNodeLayoutEngine.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/ChildLayoutStrategyEngineHandler.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/ChildNodeIncrementalLayoutEngineHandler.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/IBorderNodeLayoutEngine.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/ILayoutStrategyEngine.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/INodeIncrementalLayoutEngine.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/IconLabelIncrementalLayoutEngine.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/IncrementalLayoutEngine.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/LayoutEngineHandlerSwitch.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/LayoutStrategyEngineHandlerSwitch.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/ListLayoutStrategyEngine.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/ParametricSVGIncrementalLayoutEngine.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/RectangleIncrementalLayoutEngine.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/incremental/BorderNodePositionTests.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/incremental/DiagramLayoutTests.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/incremental/EdgeLayoutTests.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/incremental/IncrementalLayoutTests.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/incremental/NodeCreationTests.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/incremental/NodeMoveTests.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/incremental/NodeResizeTests.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/incremental/ReconnectEdgeTests.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/services/DiagramELKLayoutTest.java
Labels: pr: to review later, priority: low

#1486 [1442] Ensure that selecting an edge does not make other disappear
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/sprotty/DependencyInjection.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/sprotty/zorder/siriusBringToFrontCommand.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/sprotty/zorder/siriusZOrderModule.ts
Labels: pr: to review soon, priority: high

#1487 [1462] Restore the missing hover / selected feedback on parametric SVG style
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/sprotty/views/ParametricSVGImageView.tsx
Labels: pr: to review soon, priority: high

#1488 [1437] Fix empty Image URL for FormDescriptionEditor styles preview
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/formdescriptioneditors/components/ViewFormDescriptionEditorConverterSwitch.java
Labels: pr: to review soon, priority: high

#1489 [fix] Get the creation node tools always in the same order
  CHANGELOG.adoc
  packages/compatibility/backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/services/diagrams/DiagramDescriptionNodeAndEdgeDescriptionsPopulator.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewDiagramDescriptionConverterContext.java
Labels: type: bug 💥, difficulty: starter 👧, area: backend, priority: low
