Repository eclipse-sirius/sirius-web, pull requests merged in 2022-02, with the labels that each got.

#1023 [959] Remove the concept of DeleteTool
  CHANGELOG.adoc
  backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/InvokeDeleteToolOnDiagramEventHandler.java
  backend/sirius-components-collaborative-diagrams/src/main/resources/schema/diagram.graphqls
  backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/services/diagrams/ToolProvider.java
  backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/tools/DeleteTool.java
  frontend/src/diagram/DiagramWebSocketContainer.tsx
  frontend/src/diagram/DiagramWebSocketContainer.types.ts
  frontend/src/diagram/operations.ts
  frontend/src/diagram/sprotty/DiagramServer.tsx
  frontend/src/diagram/toolServices.ts
Labels: pr: to review soon, priority: high

#994 [test] Add basic unit tests for domain converter
  backend/sirius-components-emf/src/test/java/org/eclipse/sirius/components/emf/domain/DomainConverterTests.java
Labels: pr: to review later, priority: low

#995 [test] Add basic dynamic diagram rendering test
  backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/api/IRepresentationPersistenceService.java
  backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/api/IEditingContextPersistenceService.java
  backend/sirius-components-emf/src/test/java/org/eclipse/sirius/components/emf/view/DynamicDiagramsTests.java
Labels: pr: to review later, priority: low

#1000 [985] Provide a variable to detect which environment is used
  CHANGELOG.adoc
  backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/DiagramCreationService.java
  backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/DeleteFromDiagramEventHandler.java
  backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/DropOnDiagramEventHandler.java
  backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/EditLabelEventHandler.java
  backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/InvokeEdgeToolOnDiagramEventHandler.java
  backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/InvokeNodeToolOnDiagramEventHandler.java
  backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/services/diagrams/DiagramDescriptionNodeAndEdgeDescriptionsPopulator.java
  backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/api/Environment.java
Labels: pr: to review later, priority: low

#1002 [releng] Add support for checking dependencies IP
  .github/workflows/ip-verify.yml
  DEPENDENCIES
  backend/pom.xml
Labels: area: build 🚧, pr: to review later, priority: low

#1012 [cleanup] Use the existing EditingDomainFactory in tests
  backend/sirius-components-emf/src/test/java/org/eclipse/sirius/components/emf/compatibility/operations/CreateInstanceOperationHandlerTests.java
  backend/sirius-components-emf/src/test/java/org/eclipse/sirius/components/emf/compatibility/operations/CreateViewOperationHandlerTests.java
  backend/sirius-components-emf/src/test/java/org/eclipse/sirius/components/emf/compatibility/operations/DeleteViewOperationHandlerTests.java
Labels: pr: to review later, priority: low

#1010 Define api to build diagram
  CHANGELOG.adoc
  backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/ELKDiagramConverter.java
  backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/IELKDiagramConverter.java
  backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/LayoutService.java
  backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/provider/ImageSizeProvider.java
  backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/incremental/DiagramLayoutTest.java
  backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/services/DefaultTestDiagramDescriptionProvider.java
  backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/services/TestDiagramCreationService.java
  backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/services/TestLayoutObjectService.java
  backend/sirius-components-diagrams-layout/src/test/resources/editing-contexts/testSimpleDiagramLayout
  backend/sirius-components-diagrams-tests/pom.xml
  backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/builder/Element.java
  backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/builder/JsonBasedEditingContext.java
  backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/builder/TestLayoutDiagramBuilder.java
  backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/builder/edge/EdgeBuilder.java
  backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/builder/edge/EdgeEnd.java
  backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/builder/label/LabelBuilder.java
  backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/builder/node/ImageNodeBuilder.java
  backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/builder/node/NodeBuilder.java
  backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/builder/node/NodesBuilder.java
  backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/builder/node/RectangleNodeBuilder.java
Labels: pr: to review later, priority: low

#1020 [988] Add support for a post selection
  CHANGELOG.adoc
  backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/dto/InvokeEdgeToolOnDiagramSuccessPayload.java
  backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/dto/InvokeNodeToolOnDiagramSuccessPayload.java
  backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/InvokeEdgeToolOnDiagramEventHandler.java
  backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/InvokeNodeToolOnDiagramEventHandler.java
  backend/sirius-components-collaborative-diagrams/src/main/resources/schema/diagram.graphqls
  backend/sirius-components-collaborative/src/main/resources/schema/core.graphqls
  backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/api/IIdentifierProvider.java
  backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/services/diagrams/ToolProvider.java
  backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/api/WorkbenchSelection.java
  backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/api/WorkbenchSelectionEntry.java
  backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/compatibility/modeloperations/ChildModelOperationHandler.java
  backend/sirius-components-representations/src/main/java/org/eclipse/sirius/components/representations/Success.java
  frontend/src/diagram/DiagramWebSocketContainer.tsx
  frontend/src/diagram/DiagramWebSocketContainer.types.ts
  frontend/src/diagram/operations.ts
Labels: pr: to review later, priority: low

#1037 [988] Make the newSelection field optional
  backend/sirius-components-collaborative-diagrams/src/main/resources/schema/diagram.graphqls
Labels: pr: to review soon, priority: high

#1032 [991] Fix edge creation tools feedback
  CHANGELOG.adoc
  frontend/src/diagram/DiagramWebSocketContainer.tsx
  frontend/src/diagram/DiagramWebSocketContainer.types.ts
  frontend/src/diagram/sprotty/DiagramServer.tsx
  frontend/src/diagram/toolServices.ts
Labels: pr: to review later, priority: low

#1055 [1054] Add missing variables to compute the label of an edge
  CHANGELOG.adoc
  backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/EdgeComponent.java
Labels: pr: to review soon, priority: high

#1057 [1056] Fix an issue with invalid forwardRef usage
  CHANGELOG.adoc
  frontend/src/tree/DiagramTreeItemContextMenuContribution.tsx
Labels: pr: to review soon, priority: high

#1053 [1052] Add an ADR for the contribution of additional services in the EMFQueryService
  CHANGELOG.adoc
  doc/adrs/041_add_the_ability_to_contribute_additional_services_to_the_EMFQueryService.adoc
Labels: pr: to review soon, priority: high

#1058 [1052] Add the ability to contribute additional services in the EMFQueryService
  backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/query/EMFQueryService.java
  backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/query/api/IQueryJavaServiceProvider.java
  backend/sirius-components-emf/src/test/java/org/eclipse/sirius/components/emf/query/EMFQueryServiceTests.java
Labels: pr: to review soon, priority: high

#1061 [releng] Bump version to 2022.01.12
  backend/pom.xml
  backend/sirius-components-annotations-spring/pom.xml
  backend/sirius-components-annotations/pom.xml
  backend/sirius-components-collaborative-diagrams/pom.xml
  backend/sirius-components-collaborative-forms/pom.xml
  backend/sirius-components-collaborative-selection/pom.xml
  backend/sirius-components-collaborative-trees/pom.xml
  backend/sirius-components-collaborative-validation/pom.xml
  backend/sirius-components-collaborative/pom.xml
  backend/sirius-components-compatibility/pom.xml
  backend/sirius-components-core/pom.xml
  backend/sirius-components-diagrams-layout-api/pom.xml
  backend/sirius-components-diagrams-layout/pom.xml
  backend/sirius-components-diagrams-tests/pom.xml
  backend/sirius-components-diagrams/pom.xml
  backend/sirius-components-domain-design/pom.xml
  backend/sirius-components-domain-edit/pom.xml
  backend/sirius-components-domain/pom.xml
  backend/sirius-components-emf/pom.xml
  backend/sirius-components-forms-tests/pom.xml
  backend/sirius-components-forms/pom.xml
  backend/sirius-components-graphiql/pom.xml
  backend/sirius-components-graphql-api/pom.xml
  backend/sirius-components-graphql-utils/pom.xml
  backend/sirius-components-graphql-voyager/pom.xml
  backend/sirius-components-graphql/pom.xml
  backend/sirius-components-interpreter/pom.xml
  backend/sirius-components-representations/pom.xml
  backend/sirius-components-selection/pom.xml
  backend/sirius-components-spring-tests/pom.xml
  backend/sirius-components-starter/pom.xml
  backend/sirius-components-test-coverage/pom.xml
  backend/sirius-components-tests/pom.xml
  backend/sirius-components-trees/pom.xml
  backend/sirius-components-validation/pom.xml
  backend/sirius-components-view-edit/pom.xml
  backend/sirius-components-view/pom.xml
  frontend/package-lock.json
  frontend/package.json
Labels: pr: to review soon, priority: high

#1063 [1062] Allow expand/collapse of tree items without selecting them
  CHANGELOG.adoc
  frontend/src/tree/TreeItem.tsx
Labels: pr: to review soon, priority: high

#1072 [1063] Fix layout regression on tree items without children
  frontend/src/tree/TreeItem.tsx
Labels: pr: to review soon, priority: high

#1074 [1073] Add missing error callback on the canBeDisposed subscriber
  CHANGELOG.adoc
  backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/EditingContextEventProcessor.java
Labels: pr: to review soon, priority: high

#1077 [test] Ensure that a minimal global code coverage is respected
  .github/workflows/build.yml
  scripts/check-coverage.jsh
Labels: pr: to review later, priority: low
