Repository eclipse-sirius/sirius-web, pull requests merged in 2022-12, with the labels that each got.

#1498 [releng] Ensure that pull requests have the proper labels and a milestone
  .github/workflows/pull-request.yml
  scripts/check-labels.js
  scripts/check-milestone.js
Labels: pr: to review soon, priority: high

#1497 [1485] Select the relevant edge reconnection tools
  CHANGELOG.adoc
  packages/compatibility/backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/services/diagrams/CompatibilityReconnectionToolsExecutor.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/api/IReconnectionToolsExecutor.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/api/ReconnectionToolInterpreterData.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/ReconnectEdgeEventHandler.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/test/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/ReconnectEdgeEventHandlerTests.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewReconnectionToolsExecutor.java
Labels: pr: to review soon, priority: high

#1495 [1494] Add width and height attributes to BarChart
  CHANGELOG.adoc
  packages/charts/backend/sirius-components-charts/src/main/java/org/eclipse/sirius/components/charts/barchart/BarChart.java
  packages/charts/backend/sirius-components-charts/src/main/java/org/eclipse/sirius/components/charts/barchart/components/BarChartComponent.java
  packages/charts/backend/sirius-components-charts/src/main/java/org/eclipse/sirius/components/charts/barchart/descriptions/BarChartDescription.java
  packages/charts/backend/sirius-components-charts/src/main/java/org/eclipse/sirius/components/charts/barchart/elements/BarChartElementProps.java
  packages/charts/backend/sirius-components-collaborative-charts/src/main/resources/schema/charts.graphqls
  packages/charts/frontend/sirius-components-charts/src/bar/BarChart.tsx
  packages/charts/frontend/sirius-components-charts/src/bar/BarChart.types.ts
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/formdescriptioneditors/components/ViewFormDescriptionEditorConverterSwitch.java
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/BarChartWidget.tsx
  packages/forms/backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/renderer/FormElementFactory.java
  packages/forms/frontend/sirius-components-forms/src/form/FormEventFragments.ts
  packages/forms/frontend/sirius-components-forms/src/form/FormEventFragments.types.ts
  packages/forms/frontend/sirius-components-forms/src/propertysections/ChartWidgetPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/ChartWidgetPropertySection.test.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/ChartWidgetPropertySection.test.tsx.snap
  packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/BarChartDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-edit/src/main/resources/plugin.properties
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/form/ViewFormDescriptionConverterSwitch.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/BarChartDescription.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/ViewPackage.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/impl/BarChartDescriptionImpl.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/impl/CheckboxDescriptionImpl.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/impl/MultiSelectDescriptionImpl.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/impl/PieChartDescriptionImpl.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/impl/TextAreaDescriptionImpl.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/impl/TextfieldDescriptionImpl.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/impl/ViewPackageImpl.java
  packages/view/backend/sirius-components-view/src/main/resources/model/view.ecore
  packages/view/backend/sirius-components-view/src/main/resources/model/view.genmodel
Labels: pr: to review soon, priority: high

#1506 [fix] Add UTF-8 encoding pref to /src/test/resources folders
  .gitignore
  packages/charts/backend/sirius-components-charts/.settings/org.eclipse.core.resources.prefs
  packages/compatibility/backend/sirius-components-compatibility/.settings/org.eclipse.core.resources.prefs
  packages/core/backend/sirius-components-collaborative/.settings/org.eclipse.core.resources.prefs
  packages/core/backend/sirius-components-core/.settings/org.eclipse.core.resources.prefs
  packages/diagrams/backend/sirius-components-collaborative-diagrams/.settings/org.eclipse.core.resources.prefs
  packages/diagrams/backend/sirius-components-diagrams-graphql/.settings/org.eclipse.core.resources.prefs
  packages/diagrams/backend/sirius-components-diagrams-layout-api/.settings/org.eclipse.core.resources.prefs
  packages/diagrams/backend/sirius-components-diagrams/.settings/org.eclipse.core.resources.prefs
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors-graphql/.settings/org.eclipse.core.resources.prefs
  packages/forms/backend/sirius-components-collaborative-forms/.settings/org.eclipse.core.resources.prefs
  packages/forms/backend/sirius-components-forms-graphql/.settings/org.eclipse.core.resources.prefs
  packages/forms/backend/sirius-components-forms/.settings/org.eclipse.core.resources.prefs
  packages/selection/backend/sirius-components-collaborative-selection/.settings/org.eclipse.core.resources.prefs
  packages/selection/backend/sirius-components-selection-graphql/.settings/org.eclipse.core.resources.prefs
  packages/selection/backend/sirius-components-selection/.settings/org.eclipse.core.resources.prefs
  packages/sirius-web/backend/sirius-web-graphql-schema/.settings/org.eclipse.core.resources.prefs
  packages/sirius-web/backend/sirius-web-graphql/.settings/org.eclipse.core.resources.prefs
  packages/sirius-web/backend/sirius-web-persistence/.settings/org.eclipse.core.resources.prefs
  packages/sirius-web/backend/sirius-web-services-api/.settings/org.eclipse.core.resources.prefs
  packages/sirius-web/backend/sirius-web-services/.settings/org.eclipse.core.resources.prefs
  packages/sirius-web/backend/sirius-web-spring/.settings/org.eclipse.core.resources.prefs
  packages/tests/backend/sirius-components-spring-tests/.settings/org.eclipse.core.resources.prefs
  packages/tests/backend/sirius-components-tests/.settings/org.eclipse.core.resources.prefs
  packages/trees/backend/sirius-components-collaborative-trees/.settings/org.eclipse.core.resources.prefs
  packages/trees/backend/sirius-components-trees-graphql/.settings/org.eclipse.core.resources.prefs
  packages/trees/backend/sirius-components-trees/.settings/org.eclipse.core.resources.prefs
  packages/validation/backend/sirius-components-collaborative-validation/.settings/org.eclipse.core.resources.prefs
  packages/validation/backend/sirius-components-validation-graphql/.settings/org.eclipse.core.resources.prefs
  packages/validation/backend/sirius-components-validation/.settings/org.eclipse.core.resources.prefs
  packages/web/backend/sirius-components-graphql/.settings/org.eclipse.core.resources.prefs
  packages/web/backend/sirius-components-web/.settings/org.eclipse.core.resources.prefs
Labels: pr: to review soon, priority: low

#1520 [1346] Avoid unnecessary invocations of the editRichText mutation
  packages/forms/frontend/sirius-components-forms/src/propertysections/RichTextPropertySection.tsx
Labels: pr: to review soon, priority: high

#1370 [doc] Add an ADR about hidden elements
  CHANGELOG.adoc
  doc/adrs/083_add_the_possibility_to_hide_or_fade_a_diagram_element.adoc
Labels: pr: to review soon, priority: high

#1524 [cleanup] Remove leftover test data
  packages/forms/frontend/sirius-components-forms/src/propertysections/TextfieldPropertySection.types.ts
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/TextfieldPropertySection.test.tsx
Labels: pr: to review soon, priority: high

#1483 [1482] Allow CustomImageLoader to get images from the bundled projects
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/configuration/CustomImagesLoader.java
Labels: pr: to review later, priority: low

#1533 [releng] Add variables needed for docker tag
  .github/workflows/build.yml
Labels: pr: to review soon, priority: high

#1538 [doc] Add missing space in CHANGELOG
  CHANGELOG.adoc
Labels: pr: to review later, priority: low

#1544 [fix] Fix reveal operation
  packages/diagrams/frontend/sirius-components-diagrams/src/representation/DiagramRepresentation.tsx
Labels: pr: to review soon, priority: high
