Repository eclipse-sirius/sirius-web, pull requests merged in 2023-05, with the labels that each got.

#1740 [1621] Migrate the onboard area to Material UI
  CHANGELOG.adoc
  packages/core/frontend/sirius-components-core/src/index.ts
  packages/core/frontend/sirius-components/src/icons/NewDocument.tsx
  packages/core/frontend/sirius-components/src/icons/NewRepresentation.tsx
  packages/core/frontend/sirius-components/src/icons/index.ts
  packages/core/frontend/sirius-components/src/index.ts
  packages/core/frontend/sirius-components/src/onboarding/AreaContainer.module.css
  packages/core/frontend/sirius-components/src/onboarding/AreaContainer.tsx
  packages/core/frontend/sirius-components/src/onboarding/NewDocumentArea.tsx
  packages/core/frontend/sirius-components/src/onboarding/NewRepresentationArea.module.css
  packages/core/frontend/sirius-components/src/onboarding/NewRepresentationArea.tsx
  packages/core/frontend/sirius-components/src/onboarding/NewRepresentationArea.types.ts
  packages/core/frontend/sirius-components/src/onboarding/OnboardArea.module.css
  packages/core/frontend/sirius-components/src/onboarding/RepresentationsArea.module.css
  packages/core/frontend/sirius-components/src/onboarding/RepresentationsArea.tsx
  packages/sirius-web/frontend/sirius-web/src/onboarding/NewDocumentArea.tsx
  packages/sirius-web/frontend/sirius-web/src/onboarding/NewDocumentArea.types.ts
  packages/sirius-web/frontend/sirius-web/src/onboarding/NewRepresentationArea.tsx
  packages/sirius-web/frontend/sirius-web/src/onboarding/NewRepresentationArea.types.ts
  packages/sirius-web/frontend/sirius-web/src/onboarding/OnboardArea.tsx
  packages/sirius-web/frontend/sirius-web/src/onboarding/RepresentationsArea.tsx
  packages/sirius-web/frontend/sirius-web/src/onboarding/RepresentationsArea.types.ts
  packages/sirius-web/frontend/sirius-web/src/views/edit-project/EditProjectView.tsx
Labels: pr: to review later, priority: low

#1941 [1940] Remove duplicated dependency in sirius-web-sample-application
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-sample-application/pom.xml
Labels: pr: to review later, priority: low

#1937 [1936] Switch to Cypress 12.11.0
  .github/workflows/build.yml
  CHANGELOG.adoc
  integration-tests/cypress-dev.config.js
  integration-tests/cypress-dev.json
  integration-tests/cypress.config.js
  integration-tests/cypress.json
  integration-tests/cypress/e2e/project/edit/diagram-context-menu.cy.js
  integration-tests/cypress/e2e/project/edit/diagram-contextual-palette.cy.js
  integration-tests/cypress/e2e/project/edit/diagram-edit-robot.cy.js
  integration-tests/cypress/e2e/project/edit/diagram-selection-dialog.cy.js
  integration-tests/cypress/e2e/project/edit/diagram.cy.js
  integration-tests/cypress/e2e/project/edit/document-context-menu.cy.js
  integration-tests/cypress/e2e/project/edit/explorer-toolbar.cy.js
  integration-tests/cypress/e2e/project/edit/explorer.cy.js
  integration-tests/cypress/e2e/project/edit/formdescriptioneditor.cy.js
  integration-tests/cypress/e2e/project/edit/object-context-menu.cy.js
  integration-tests/cypress/e2e/project/edit/onboarding.cy.js
  integration-tests/cypress/e2e/project/edit/project-context-menu.cy.js
  integration-tests/cypress/e2e/project/edit/properties.cy.js
  integration-tests/cypress/e2e/project/edit/representation-context-menu.cy.js
  integration-tests/cypress/e2e/project/edit/representations.cy.js
  integration-tests/cypress/e2e/project/edit/studio.cy.js
  integration-tests/cypress/e2e/project/edit/validation_specs.cy.js
  integration-tests/cypress/e2e/project/new-project.cy.js
  integration-tests/cypress/e2e/project/projects.cy.js
  integration-tests/cypress/e2e/project/upload-project.cy.js
  integration-tests/cypress/support/e2e.js
  integration-tests/package-lock.json
  integration-tests/package.json
  packages/tests/backend/sirius-components-tests/src/test/java/org/eclipse/sirius/components/tests/GitCommitMessageTests.java
Labels: pr: to review soon, priority: low

#1931 [1918] Add shape about the filtering of tree based representations
  CHANGELOG.adoc
  doc/iterations/2023.6/shapes/filter_tree_based_representations.adoc
  doc/iterations/2023.6/shapes/images/filter_tree_based_representations_01.png
Labels: pr: to review soon, priority: low

#1944 [doc] Contribute a shape for the addition of pages to the view DSL
  CHANGELOG.adoc
  doc/iterations/2023.6/shapes/add_pages_to_form_in_the_view_dsl.adoc
  doc/iterations/2023.6/shapes/images/add_pages_to_form_in_the_view_dsl_01.png
  doc/iterations/2023.6/shapes/images/add_pages_to_form_in_the_view_dsl_02.png
  doc/iterations/2023.6/shapes/images/add_pages_to_form_in_the_view_dsl_03.png
  packages/tests/backend/sirius-components-tests/src/test/java/org/eclipse/sirius/components/tests/GitCommitMessageTests.java
Labels: pr: to review soon, priority: high

#1953 [1952] Fix regression on View-based Forms creation
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/PapayaViewProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/overviewform/OverviewFormProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/test/java/org/eclipse/sirius/web/sample/tests/integration/view/ViewFormIntegrationTests.java
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/representations/ViewRepresentationDescriptionSearchService.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/IRepresentationDescriptionIdProvider.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/IViewRepresentationDescriptionPredicate.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/ViewConverter.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/ViewRepresentationDescriptionPredicate.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/ViewRepresentationDescriptionsProvider.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ConnectorToolsProviderDiagram.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/DiagramIdProvider.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/IDiagramIdProvider.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewDiagramDescriptionConverter.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewReconnectionToolsExecutor.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewToolSectionsProvider.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/providers/ViewInitialDirectEditElementLabelProvider.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/form/FormIdProvider.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/form/IFormIdProvider.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/form/ViewFormDescriptionConverter.java
  packages/view/backend/sirius-components-view-emf/src/test/java/org/eclipse/sirius/components/view/emf/view/DynamicFormsTests.java
Labels: pr: to review soon, priority: high

#1951 [doc] Contribute the shapes of the view creation API
  CHANGELOG.adoc
  doc/iterations/2023.6/shapes/add_missing_features_in_the_view_support.adoc
  doc/iterations/2023.6/shapes/odesign_to_view_converter_api.adoc
  doc/iterations/2023.6/shapes/provide_a_view_based_version_of_flow.adoc
  doc/iterations/2023.6/shapes/simplify_the_programmatic_creation_of_view_models.adoc
Labels: pr: to review soon, priority: high

#1945 [1916] Add shape for View-based details example
  CHANGELOG.adoc
  doc/iterations/2023.6/shapes/view-based_details_view.adoc
Labels: pr: to review soon, priority: low

#1924 [1518] Disable the 'correct indentation' save action
  packages/charts/backend/sirius-components-charts/.settings/org.eclipse.jdt.ui.prefs
  packages/charts/backend/sirius-components-collaborative-charts/.settings/org.eclipse.jdt.ui.prefs
  packages/compatibility/backend/sirius-components-compatibility-emf/.settings/org.eclipse.jdt.ui.prefs
  packages/compatibility/backend/sirius-components-compatibility/.settings/org.eclipse.jdt.ui.prefs
  packages/core/backend/sirius-components-annotations-spring/.settings/org.eclipse.jdt.ui.prefs
  packages/core/backend/sirius-components-annotations/.settings/org.eclipse.jdt.ui.prefs
  packages/core/backend/sirius-components-collaborative/.settings/org.eclipse.jdt.ui.prefs
  packages/core/backend/sirius-components-core/.settings/org.eclipse.jdt.ui.prefs
  packages/core/backend/sirius-components-graphql-api/.settings/org.eclipse.jdt.ui.prefs
  packages/core/backend/sirius-components-representations/.settings/org.eclipse.jdt.ui.prefs
  packages/diagrams/backend/sirius-components-collaborative-diagrams/.settings/org.eclipse.jdt.ui.prefs
  packages/diagrams/backend/sirius-components-diagrams-graphql/.settings/org.eclipse.jdt.ui.prefs
  packages/diagrams/backend/sirius-components-diagrams-layout-api/.settings/org.eclipse.jdt.ui.prefs
  packages/diagrams/backend/sirius-components-diagrams-layout/.settings/org.eclipse.jdt.ui.prefs
  packages/diagrams/backend/sirius-components-diagrams-tests/.settings/org.eclipse.jdt.ui.prefs
  packages/diagrams/backend/sirius-components-diagrams/.settings/org.eclipse.jdt.ui.prefs
  packages/domain/backend/sirius-components-domain-design/.settings/org.eclipse.jdt.ui.prefs
  packages/domain/backend/sirius-components-domain-edit/.settings/org.eclipse.jdt.ui.prefs
  packages/domain/backend/sirius-components-domain-emf/.settings/org.eclipse.jdt.ui.prefs
  packages/domain/backend/sirius-components-domain/.settings/org.eclipse.jdt.ui.prefs
  packages/emf/backend/sirius-components-emf/.settings/org.eclipse.jdt.ui.prefs
  packages/emf/backend/sirius-components-interpreter/.settings/org.eclipse.jdt.ui.prefs
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/.settings/org.eclipse.jdt.ui.prefs
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors-graphql/.settings/org.eclipse.jdt.ui.prefs
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors/.settings/org.eclipse.jdt.ui.prefs
  packages/forms/backend/sirius-components-collaborative-forms/.settings/org.eclipse.jdt.ui.prefs
  packages/forms/backend/sirius-components-forms-graphql/.settings/org.eclipse.jdt.ui.prefs
  packages/forms/backend/sirius-components-forms-tests/.settings/org.eclipse.jdt.ui.prefs
  packages/forms/backend/sirius-components-forms/.settings/org.eclipse.jdt.ui.prefs
  packages/selection/backend/sirius-components-collaborative-selection/.settings/org.eclipse.jdt.ui.prefs
  packages/selection/backend/sirius-components-selection-graphql/.settings/org.eclipse.jdt.ui.prefs
  packages/selection/backend/sirius-components-selection/.settings/org.eclipse.jdt.ui.prefs
  packages/sirius-web/backend/sirius-web-frontend/.settings/org.eclipse.jdt.ui.prefs
  packages/sirius-web/backend/sirius-web-graphql/.settings/org.eclipse.jdt.ui.prefs
  packages/sirius-web/backend/sirius-web-persistence/.settings/org.eclipse.jdt.ui.prefs
  packages/sirius-web/backend/sirius-web-sample-application/.settings/org.eclipse.jdt.ui.prefs
  packages/sirius-web/backend/sirius-web-services-api/.settings/org.eclipse.jdt.ui.prefs
  packages/sirius-web/backend/sirius-web-services/.settings/org.eclipse.jdt.ui.prefs
  packages/sirius-web/backend/sirius-web-spring/.settings/org.eclipse.jdt.ui.prefs
  packages/starters/backend/sirius-components-starter/.settings/org.eclipse.jdt.ui.prefs
  packages/tests/backend/sirius-components-spring-tests/.settings/org.eclipse.jdt.ui.prefs
  packages/tests/backend/sirius-components-tests/.settings/org.eclipse.jdt.ui.prefs
  packages/tools/backend/sirius-components-graphiql/.settings/org.eclipse.jdt.ui.prefs
  packages/tools/backend/sirius-components-graphql-voyager/.settings/org.eclipse.jdt.ui.prefs
  packages/trees/backend/sirius-components-collaborative-trees/.settings/org.eclipse.jdt.ui.prefs
  packages/trees/backend/sirius-components-trees-graphql/.settings/org.eclipse.jdt.ui.prefs
  packages/trees/backend/sirius-components-trees/.settings/org.eclipse.jdt.ui.prefs
  packages/validation/backend/sirius-components-collaborative-validation/.settings/org.eclipse.jdt.ui.prefs
  packages/validation/backend/sirius-components-validation-graphql/.settings/org.eclipse.jdt.ui.prefs
  packages/validation/backend/sirius-components-validation/.settings/org.eclipse.jdt.ui.prefs
  packages/view/backend/sirius-components-view-edit/.settings/org.eclipse.jdt.ui.prefs
  packages/view/backend/sirius-components-view-emf/.settings/org.eclipse.jdt.ui.prefs
  packages/view/backend/sirius-components-view/.settings/org.eclipse.jdt.ui.prefs
  packages/web/backend/sirius-components-graphql/.settings/org.eclipse.jdt.ui.prefs
  packages/web/backend/sirius-components-web/.settings/org.eclipse.jdt.ui.prefs
Labels: pr: to review later, priority: low

#1959 [doc] Fix typo in CHANGELOG
  CHANGELOG.adoc
Labels: pr: to review later, priority: low

#1950 [doc] Add shape about layout improvements
  CHANGELOG.adoc
  doc/iterations/2023.6/shapes/improve_simple_nodes_layout.adoc
Labels: pr: to review soon, priority: low

#1964 [cleanup] Fix incorrect error message due to a bad copy/paste
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/handlers/EditingContextRepresentationDescriptionsEventHandler.java
Labels: pr: to review later, priority: low

#1957 [1946] Enable child extenders in the View DSL implementation
  CHANGELOG.adoc
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/configuration/ChildExtenderProvider.java
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/configuration/EMFConfiguration.java
  packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/ConditionalItemProvider.java
  packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/DiagramElementDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/DiagramPaletteItemProvider.java
  packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/EdgePaletteItemProvider.java
  packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/FreeFormLayoutStrategyDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/GroupDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/LabelStyleItemProvider.java
  packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/ListLayoutStrategyDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/NodePaletteItemProvider.java
  packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/OperationItemProvider.java
  packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/RepresentationDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/StyleItemProvider.java
  packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/ToolItemProvider.java
  packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/ViewItemProvider.java
  packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/ViewItemProviderAdapterFactory.java
  packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/WidgetDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/WidgetDescriptionStyleItemProvider.java
  packages/view/backend/sirius-components-view/src/main/resources/model/view.genmodel
Labels: pr: to review soon, priority: high

#1948 [1914] Add shape for custom widgets support
  CHANGELOG.adoc
  doc/iterations/2023.6/shapes/support_custom_widgets_in_form_representations.adoc
Labels: pr: to review soon, priority: high

#1969 [releng] fix sirius-web integration tests version
  integration-tests/package-lock.json
  integration-tests/package.json
  scripts/bump-version
Labels: pr: to review soon, priority: high

#1977 [1970] Simplify the lifecycle of the diagram layout engine
  CHANGELOG.adoc
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/DiagramCreationService.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/DiagramEventProcessor.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/DiagramEventProcessorFactory.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/DiagramEventProcessorParameters.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/test/java/org/eclipse/sirius/components/collaborative/diagrams/DiagramEventProcessorTests.java
  packages/diagrams/backend/sirius-components-diagrams-layout-api/src/main/java/org/eclipse/sirius/components/diagrams/layout/api/IDiagramLayoutEngine.java
  packages/diagrams/backend/sirius-components-diagrams-layout-api/src/main/java/org/eclipse/sirius/components/diagrams/layout/api/configuration/DiagramLayoutConfiguration.java
  packages/diagrams/backend/sirius-components-diagrams-layout-api/src/main/java/org/eclipse/sirius/components/diagrams/layout/api/configuration/EdgeLayoutConfiguration.java
  packages/diagrams/backend/sirius-components-diagrams-layout-api/src/main/java/org/eclipse/sirius/components/diagrams/layout/api/configuration/LabelLayoutConfiguration.java
  packages/diagrams/backend/sirius-components-diagrams-layout-api/src/main/java/org/eclipse/sirius/components/diagrams/layout/api/configuration/NodeLayoutConfiguration.java
  packages/diagrams/backend/sirius-components-diagrams-layout-api/src/main/java/org/eclipse/sirius/components/diagrams/layout/api/experimental/Anchor.java
  packages/diagrams/backend/sirius-components-diagrams-layout-api/src/main/java/org/eclipse/sirius/components/diagrams/layout/api/experimental/DiagramLayoutConfiguration.java
  packages/diagrams/backend/sirius-components-diagrams-layout-api/src/main/java/org/eclipse/sirius/components/diagrams/layout/api/experimental/EdgeLayoutConfiguration.java
  packages/diagrams/backend/sirius-components-diagrams-layout-api/src/main/java/org/eclipse/sirius/components/diagrams/layout/api/experimental/FontStyle.java
  packages/diagrams/backend/sirius-components-diagrams-layout-api/src/main/java/org/eclipse/sirius/components/diagrams/layout/api/experimental/IDiagramLayoutConfigurationProvider.java
  packages/diagrams/backend/sirius-components-diagrams-layout-api/src/main/java/org/eclipse/sirius/components/diagrams/layout/api/experimental/IDiagramLayoutEngine.java
  packages/diagrams/backend/sirius-components-diagrams-layout-api/src/main/java/org/eclipse/sirius/components/diagrams/layout/api/experimental/IParentLayoutConfiguration.java
  packages/diagrams/backend/sirius-components-diagrams-layout-api/src/main/java/org/eclipse/sirius/components/diagrams/layout/api/experimental/IconLayoutConfiguration.java
  packages/diagrams/backend/sirius-components-diagrams-layout-api/src/main/java/org/eclipse/sirius/components/diagrams/layout/api/experimental/LabelLayoutConfiguration.java
  packages/diagrams/backend/sirius-components-diagrams-layout-api/src/main/java/org/eclipse/sirius/components/diagrams/layout/api/experimental/NodeLayoutConfiguration.java
  packages/diagrams/backend/sirius-components-diagrams-layout-api/src/main/java/org/eclipse/sirius/components/diagrams/layout/api/experimental/NodeLayoutStrategy.java
  packages/diagrams/backend/sirius-components-diagrams-layout-api/src/main/java/org/eclipse/sirius/components/diagrams/layout/api/experimental/Offsets.java
  packages/diagrams/backend/sirius-components-diagrams-layout-api/src/main/java/org/eclipse/sirius/components/diagrams/layout/api/experimental/Rectangle.java
  packages/diagrams/backend/sirius-components-diagrams-layout-api/src/test/java/.gitkeep
  packages/diagrams/backend/sirius-components-diagrams-layout-api/src/test/java/org/eclipse/sirius/components/diagrams/layout/api/experimental/AnchorTests.java
  packages/diagrams/backend/sirius-components-diagrams-layout-api/src/test/java/org/eclipse/sirius/components/diagrams/layout/api/experimental/OffsetsTests.java
  packages/diagrams/backend/sirius-components-diagrams-layout-api/src/test/java/org/eclipse/sirius/components/diagrams/layout/api/experimental/RectangleTests.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/api/IDiagramLayoutConfigurationProvider.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/experimental/Canvas.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/experimental/CanvasLayoutEngine.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/experimental/DiagramLayoutConfigurationProvider.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/experimental/DiagramLayoutEngine.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/experimental/DiagramLayoutInput.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/experimental/OverlapHandler.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/experimental/OverlapHandlerTests.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/layoutdata/DiagramLayoutData.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/configuration/FlowProjectTemplatesInitializer.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/configuration/StudioProjectTemplatesInitializer.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/PapayaStudioTemplatesInitializer.java
  packages/tests/backend/sirius-components-tests/src/test/java/org/eclipse/sirius/components/tests/GeneralPurposeTests.java
  packages/view/backend/sirius-components-view-emf/src/test/java/org/eclipse/sirius/components/view/emf/view/DynamicDiagramsTests.java
Labels: pr: to review soon, priority: high

#1979 [1971] Add the first new layout engine integration test
  CHANGELOG.adoc
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/DiagramCreationService.java
  packages/diagrams/backend/sirius-components-diagrams-layout-api/src/main/java/org/eclipse/sirius/components/diagrams/layout/api/experimental/DiagramLayoutConfiguration.java
  packages/diagrams/backend/sirius-components-diagrams-layout-api/src/main/java/org/eclipse/sirius/components/diagrams/layout/api/experimental/IDiagramLayoutConfigurationProvider.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/experimental/DiagramLayoutConfigurationProvider.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/experimental/DiagramLayoutEngine.java
  packages/diagrams/backend/sirius-components-diagrams-tests/pom.xml
  packages/sirius-web/backend/sirius-web-sample-application/pom.xml
  packages/sirius-web/backend/sirius-web-sample-application/src/test/java/org/eclipse/sirius/web/sample/tests/integration/diagram/DiagramLayoutIntegrationTests.java
Labels: pr: to review soon, priority: high

#1981 [1831] Improve the internal data structure of the layout algorithm
  CHANGELOG.adoc
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/experimental/DiagramBoxModel.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/experimental/DiagramLayoutConfigurationProvider.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/experimental/DiagramLayoutEngine.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/experimental/NodeBoxModel.java
  packages/sirius-web/backend/sirius-web-sample-application/src/test/java/org/eclipse/sirius/web/sample/tests/integration/diagram/DiagramLayoutIntegrationTests.java
Labels: pr: to review soon, priority: high

#1973 [1968] Fixed colorProvider to search in all ColorPalettes
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/ColorProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/test/java/org/eclipse/sirius/web/sample/papaya/view/ColorProviderTests.java
Labels: pr: to review soon, priority: high

#1992 [1991] Fix widget ID from different groups
  CHANGELOG.adoc
  packages/compatibility/backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/forms/WidgetIdProvider.java
  packages/forms/backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/components/FormComponent.java
  packages/forms/backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/components/GroupComponent.java
Labels: pr: to review soon, priority: high

#2001 [1305] Fix update of the default tools of the palette's tool sections
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/edit/diagram-contextual-palette.cy.js
  packages/diagrams/frontend/sirius-components-diagrams/src/palette/ContextualPalette.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/palette/ContextualPalette.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/palette/tool-section/ToolSection.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/palette/tool-section/ToolSection.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/representation/DiagramRepresentation.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/representation/DiagramRepresentation.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/representation/DiagramRepresentationMachine.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/representation/toolServices.ts
Labels: pr: to review soon, priority: low

#2002 Fix reconnection tool for applications with a custom IViewRepresentationDescriptionSearchService
  CHANGELOG.adoc
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewReconnectionToolsExecutor.java
Labels: pr: to review soon, priority: high
