Repository eclipse-sirius/sirius-web, pull requests merged in 2023-12, with the labels that each got.

#2709 [2703] Remove the explorer menu used to export diagrams as SVG images
  CHANGELOG.adoc
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/DiagramTreeItemContextMenuContribution.tsx
Labels: pr: to review soon, priority: high

#2688 [2687] Change selector used by ConnectionHandles
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/handles/ConnectionHandles.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/handles/useHandleChange.tsx
Labels: pr: to review soon, priority: high

#2719 [2600] Add a small margin at the top of a page
  CHANGELOG.adoc
  packages/forms/frontend/sirius-components-forms/src/form/Form.tsx
  packages/forms/frontend/sirius-components-forms/src/pages/Page.tsx
  packages/forms/frontend/sirius-components-forms/src/representations/FormRepresentation.tsx
Labels: pr: to review soon, priority: low

#2711 [2698] Fix an issue that prevents _imageNode_ to be resizable
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/ImageNodeLayoutHandler.ts
Labels: pr: to review soon, priority: high

#2730 [2726] Filters the last tool used to match the ones from tool sections
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/tool-section/ToolSection.tsx
Labels: pr: to review soon, priority: high

#2729 [2728] Prevents unnecessary rerenders in DiagramPanel
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/panel/DiagramPanel.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/snap-to-grid/useSnapToGrid.tsx
Labels: pr: to review soon, priority: high

#2712 [2683] Hide diagram element palette when the element itself is moved
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramRenderer.tsx
Labels: pr: to review soon, priority: high

#2676 [2675] Improve IViewDiagramElementFinder
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/ViewDiagramElementFinder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/IViewDiagramElementFinder.java
Labels: pr: to review later, priority: low

#2724 [2720] Add a dev mode to the vite build
  CHANGELOG.adoc
  packages/charts/frontend/sirius-components-charts/package.json
  packages/core/frontend/sirius-components-core/package.json
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/package.json
  packages/diagrams/frontend/sirius-components-diagrams/package.json
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/package.json
  packages/forms/frontend/sirius-components-forms/package.json
  packages/forms/frontend/sirius-components-widget-reference/package.json
  packages/gantt/frontend/sirius-components-gantt/package.json
  packages/selection/frontend/sirius-components-selection/package.json
  packages/sirius-web/frontend/sirius-web-application/package.json
  packages/trees/frontend/sirius-components-trees/package.json
  packages/validation/frontend/sirius-components-validation/package.json
  turbo.json
Labels: pr: to review later, priority: low

#2782 [2780] Upgrade github/aws actions versions in github workflows
  .github/workflows/build.yml
  .github/workflows/ip-verify.yml
  .github/workflows/pull-request.yml
  CHANGELOG.adoc
Labels: pr: to review later, priority: low

#2645 [2644] Highlight nodes on hover
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/index.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/node/IconLabelNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/node/ImageNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/node/ListNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/node/RectangularNode.tsx
  packages/sirius-web/frontend/sirius-web-application/src/nodes/EllipseNode.tsx
Labels: pr: to review soon, priority: low

#2816 [releng] Switch to @ObeoNetwork/gantt-task-react v0.3.12
  CHANGELOG.adoc
  package-lock.json
  packages/gantt/frontend/sirius-components-gantt/package.json
  packages/sirius-web/frontend/sirius-web-application/package.json
  packages/sirius-web/frontend/sirius-web/package.json
Labels: pr: to review soon, priority: high

#2814 [fix] Add missing tooltips on diagram panel actions
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/panel/DiagramPanel.tsx
Labels: pr: to review soon, priority: low

#2773 [2772] Replace useLazyQuery with useQuery in palette
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/Palette.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/Palette.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/tool-section/ToolSection.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/tool-section/ToolSection.types.ts
Labels: pr: to review later, priority: low

#2677 [2580] Cancel direct edit on 'Escape'
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/diagrams/direct-edit-label.cy.ts
  integration-tests/cypress/workbench/Explorer.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/direct-edit/DiagramDirectEditInput.tsx
Labels: pr: to review soon, priority: low

#2690 [2679] Align the input element like the corresponding label
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/Label.tsx
Labels: pr: to review later, priority: low

#2405 [2403] Add support for If and Let constructs in the operations DSL
  CHANGELOG.adoc
  packages/view/backend/sirius-components-view-builder/pom.xml
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/IfBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/LetBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/ViewBuilders.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generator/BuilderGenerator.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/ToolItemProvider.java
  packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/IfItemProvider.java
  packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/LetItemProvider.java
  packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/OperationItemProvider.java
  packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/ViewItemProviderAdapterFactory.java
  packages/view/backend/sirius-components-view-edit/src/main/resources/icons/full/obj16/If.svg
  packages/view/backend/sirius-components-view-edit/src/main/resources/icons/full/obj16/Let.svg
  packages/view/backend/sirius-components-view-edit/src/main/resources/plugin.properties
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/OperationInterpreterViewSwitch.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/If.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/Let.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/ViewFactory.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/ViewPackage.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/impl/IfImpl.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/impl/LetImpl.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/impl/ViewFactoryImpl.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/impl/ViewPackageImpl.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/util/ViewAdapterFactory.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/util/ViewSwitch.java
  packages/view/backend/sirius-components-view/src/main/resources/model/view.ecore
  packages/view/backend/sirius-components-view/src/main/resources/model/view.genmodel
Labels: pr: to review later, priority: low

#2767 [2718] Replacing useNodes and useEdges by useReactFlow
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/delete/useDiagramDelete.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/direct-edit/useDiagramDirectEdit.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/Palette.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/selection/useDiagramSelection.tsx
Labels: pr: to review later, priority: low

#2820 [2784] Add more monitored functions
  CHANGELOG.adoc
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/api/Monitoring.java
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/EditingContextEventProcessor.java
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/EditingContextEventProcessorFactory.java
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/EditingContextEventProcessorFactoryParameters.java
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/EditingContextEventProcessorParameters.java
  packages/web/backend/sirius-components-web/pom.xml
  packages/web/backend/sirius-components-web/src/main/java/org/eclipse/sirius/components/web/configuration/TimedConfiguration.java
Labels: pr: to review soon, priority: low

#2834 [fix] Apply tsc during the sirius-web build phase
  packages/sirius-web/frontend/sirius-web/package.json
Labels: pr: to review soon, priority: high

#2768 [releng] Bump ReactFlow to 11.10.1
  package-lock.json
  packages/diagrams/backend/sirius-components-diagrams-layout-server/package-lock.json
  packages/diagrams/backend/sirius-components-diagrams-layout-server/package.json
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/package.json
  packages/sirius-web/frontend/sirius-web-application/package.json
  packages/sirius-web/frontend/sirius-web/package.json
  vscode-extension/package.json
Labels: pr: to review soon, priority: high

#2761 [2760] Reduce edge's label overlap
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/converter/convertDiagram.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/edge/MultiLabelEdge.tsx
Labels: pr: to review later, priority: low

#2840 [cleanup] Do not set the selected representation in useSelection hook
  packages/core/frontend/sirius-components-core/src/selection/SelectionContext.tsx
Labels: pr: to review soon, priority: high

#2691 Shapes for Gantt, Deck and Portal
  CHANGELOG.adoc
  doc/iterations/2024.1/shapes/add_support_for_deck_representation.adoc
  doc/iterations/2024.1/shapes/add_support_for_gantt_representation.adoc
  doc/iterations/2024.1/shapes/add_support_for_portal_representation.adoc
  doc/iterations/2024.1/shapes/images/deck/deck_Card_Lane.png
  doc/iterations/2024.1/shapes/images/deck/deck_lane_actions.png
  doc/iterations/2024.1/shapes/images/deck/deck_overview.png
  doc/iterations/2024.1/shapes/images/deck/deck_toolbar_actions.png
  doc/iterations/2024.1/shapes/images/deck/overview-deck.png
  doc/iterations/2024.1/shapes/images/deck/taskMMForDeck.png
  doc/iterations/2024.1/shapes/images/gantt/gantt_action_share.png
  doc/iterations/2024.1/shapes/images/gantt/gantt_columns.png
  doc/iterations/2024.1/shapes/images/gantt/gantt_displayColumns.png
  doc/iterations/2024.1/shapes/images/gantt/gantt_display_actions.png
  doc/iterations/2024.1/shapes/images/gantt/gantt_handles.png
  doc/iterations/2024.1/shapes/images/gantt/gantt_overview.png
  doc/iterations/2024.1/shapes/images/gantt/gantt_palette.png
  doc/iterations/2024.1/shapes/images/gantt/gantt_tasks.png
  doc/iterations/2024.1/shapes/images/gantt/taskMMForGantt.png
  doc/iterations/2024.1/shapes/images/portal/empty_main_view.png
  doc/iterations/2024.1/shapes/images/portal/portal_drop_area.png
  doc/iterations/2024.1/shapes/images/portal/portal_palette.png
  doc/iterations/2024.1/shapes/images/portal/portal_representation_creation.png
  doc/iterations/2024.1/shapes/images/portal/portal_representation_example.png
  doc/iterations/2024.1/shapes/images/portal/representation_gantt_with_header.png
  doc/iterations/2024.1/shapes/images/portal/representations_view.png
  doc/iterations/2024.1/shapes/images/portal/web_page_representation_example.png
Labels: pr: to review later

#2832 [2790] Increase node resizer size
  CHANGELOG.adoc
  doc/screenshots/biggerResizeHandles.png
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/node/ImageNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/node/ListNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/node/RectangularNode.tsx
  packages/sirius-web/frontend/sirius-web/src/nodes/EllipseNode.tsx
Labels: pr: to review soon, priority: low

#2847 [cleanup] Remove the obsolete EditProjectNavbar.module.css
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/EditProjectNavbar/EditProjectNavbar.module.css
Labels: pr: to review later, priority: low

#2850 [2849] Optimize handlers used to retrieve diagram description
  CHANGELOG.adoc
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/GetNodeDescriptionBorderNodeDescriptionsEventHandler.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/GetNodeDescriptionChildNodeDescriptionsEventHandler.java
Labels: pr: to review soon, priority: high

#2851 [fix] Put back default icons in ToolConverter
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ToolConverter.java
Labels: pr: to review soon, priority: high

#2856 [2736] Add a starter project for beans related to the task meta-model
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-sample-application/pom.xml
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/gantt/GanttEMFConfiguration.java
  packages/starters/backend/pom.xml
  packages/starters/backend/sirius-components-task-starter/.checkstyle
  packages/starters/backend/sirius-components-task-starter/.classpath
  packages/starters/backend/sirius-components-task-starter/.project
  packages/starters/backend/sirius-components-task-starter/.settings/org.eclipse.core.resources.prefs
  packages/starters/backend/sirius-components-task-starter/.settings/org.eclipse.core.runtime.prefs
  packages/starters/backend/sirius-components-task-starter/.settings/org.eclipse.jdt.apt.core.prefs
  packages/starters/backend/sirius-components-task-starter/.settings/org.eclipse.jdt.core.prefs
  packages/starters/backend/sirius-components-task-starter/.settings/org.eclipse.jdt.ui.prefs
  packages/starters/backend/sirius-components-task-starter/.settings/org.eclipse.m2e.core.prefs
  packages/starters/backend/sirius-components-task-starter/.settings/org.springframework.ide.eclipse.boot.prefs
  packages/starters/backend/sirius-components-task-starter/.settings/org.springframework.ide.eclipse.prefs
  packages/starters/backend/sirius-components-task-starter/README.adoc
  packages/starters/backend/sirius-components-task-starter/pom.xml
  packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/configuration/TaskEMFConfiguration.java
  packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/configuration/TaskProjectTemplatesProvider.java
  packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/configuration/TaskStereotypeDescriptionRegistryConfigurer.java
  packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/configuration/TaskStudioTemplatesInitializer.java
  packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/configuration/view/TaskJavaService.java
  packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/configuration/view/TaskJavaServiceProvider.java
  packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/configuration/view/ViewGanttDescriptionBuilder.java
  packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/configuration/view/ViewsStereotypeDescriptionRegistryConfigurer.java
  packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/helper/StereotypeBuilder.java
  packages/task/backend/sirius-components-task-edit/src/main/java/org/eclipse/sirius/components/task/configuration/TaskEditEMFConfiguration.java
  packages/task/backend/sirius-components-task/pom.xml
Labels: pr: to review soon, priority: high

#2863 [fix] Fix task template image name
  packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/configuration/TaskProjectTemplatesProvider.java
Labels: pr: to review soon, priority: low

#2862 [2819] Add missing start script
  packages/deck/frontend/sirius-components-deck/package.json
Labels: pr: to review soon, priority: high

#2762 [2609] Order handles on each side to reduce edges crossing
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/diagrams/diagram-contextual-palette.cy.js
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/converter/convertHandles.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/edge/EdgeLayout.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/handles/ConnectionHandles.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/handles/ConnectionHandles.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/handles/useHandleChange.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/handles/useRefreshConnectionHandles.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/layout.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/layoutHandles.ts
Labels: pr: to review later, priority: low

#2716 [2715] Stop refreshing the layout with a select change
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/diagrams/graphical-dnd.cy.ts
  integration-tests/cypress/workbench/Diagram.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramRenderer.tsx
Labels: pr: to review soon, priority: high
