Repository eclipse-sirius/sirius-web, pull requests merged in 2023-07, with the labels that each got.

#2139 [doc] Fix title of ADR 105
  doc/adrs/105_reference_widget.adoc
Labels: pr: to review later, priority: low

#2129 [2124] Rename DocumentMetadataAdapter and move it in sirius-components-emf
  CHANGELOG.adoc
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/ResourceMetadataAdapter.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/configuration/FlowProjectTemplatesInitializer.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/configuration/StudioProjectTemplatesInitializer.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/PapayaStudioTemplatesInitializer.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/services/EditingContextActionHandler.java
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/documents/CreateDocumentEventHandler.java
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/documents/RenameDocumentEventHandler.java
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/documents/UploadDocumentEventHandler.java
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/editingcontext/EditingContextPersistenceService.java
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/editingcontext/EditingContextSearchService.java
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/explorer/ExplorerDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/explorer/RenameDocumentTreeItemHandler.java
  packages/sirius-web/backend/sirius-web-services/src/test/java/org/eclipse/sirius/web/services/documents/CreateDocumentEventHandlerTests.java
  packages/sirius-web/backend/sirius-web-services/src/test/java/org/eclipse/sirius/web/services/documents/RenameDocumentEventHandlerTests.java
  packages/sirius-web/backend/sirius-web-services/src/test/java/org/eclipse/sirius/web/services/editingcontext/EditingContextPersistenceServiceTests.java
  packages/sirius-web/backend/sirius-web-services/src/test/java/org/eclipse/sirius/web/services/editingcontext/EditingContextSearchServiceTests.java
Labels: pr: to review soon, priority: high

#2136 [2135] Allow TreeItemContextMenuContributions to only apply to specific trees
  CHANGELOG.adoc
  packages/sirius-web/frontend/sirius-web/src/views/edit-project/EditProjectView.tsx
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItem.tsx
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItemContextMenuContribution.types.ts
Labels: pr: to review soon, priority: high

#2153 [2152] Some characters typed in the filter bar raise exception
  CHANGELOG.adoc
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItem.tsx
Labels: pr: to review soon, priority: high

#2156 [2155] Fix "Expand All" does not always reveal the last level
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/edit/document-context-menu.cy.js
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/explorer/ExplorerExpandAllTreePathProvider.java
Labels: pr: to review soon, priority: high

#2145 [2144] Fix default properties values for widgets with no style
  CHANGELOG.adoc
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/ButtonWidget.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/LabelWidget.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/LinkWidget.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/ListWidget.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/MultiSelectWidget.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/RadioWidget.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/SelectWidget.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/TextAreaWidget.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/TextfieldWidget.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/ToolbarActionWidget.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/ButtonPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/LabelWidgetPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/LinkPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/ListPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/MultiSelectPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/RadioPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/SelectPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/TextfieldPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/getTextDecorationLineValue.ts
  packages/forms/frontend/sirius-components-forms/src/toolbaraction/ToolbarAction.tsx
Labels: pr: to review soon, priority: low

#2143 [2142] Add support for Edge labels (begin, center, end)
  CHANGELOG.adoc
  packages/charts/frontend/sirius-components-charts/src/chartOperations.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/converter/convertDiagram.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramRenderer.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramRenderer.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/edge/CustomEdge.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/edge/CustomEdge.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/edge/EdgeLabeL.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/edge/EdgeLabel.tsx
Labels: pr: to review soon, priority: high

#2160 [fix] Fix direct-edit on list nodes
  integration-tests/cypress/e2e/project/edit/studio.cy.js
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/converter/convertDiagram.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/Label.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/ListNode.tsx
Labels: pr: to review soon, priority: high

#2151 [2125] Add the possibility to programmatically order and filter pages…
  CHANGELOG.adoc
  packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/FormEventProcessor.java
  packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/FormEventProcessorFactory.java
  packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/PropertiesEventProcessorFactory.java
  packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/RelatedElementsEventProcessorFactory.java
  packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/RepresentationsEventProcessorFactory.java
  packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/api/IFormPostProcessor.java
  packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/configuration/FormEventProcessorConfiguration.java
  packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/configuration/FormEventProcessorFactoryConfiguration.java
  packages/forms/backend/sirius-components-collaborative-forms/src/test/java/org/eclipse/sirius/components/collaborative/forms/FormEventProcessorTests.java
Labels: pr: to review later, priority: low

#2157 [2097] Add click handler support for the reference widget
  CHANGELOG.adoc
  packages/forms/backend/sirius-components-widget-reference-view-edit/src/main/java/org/eclipse/sirius/components/widgets/reference/provider/ReferenceWidgetDescriptionItemProvider.java
  packages/forms/backend/sirius-components-widget-reference-view-edit/src/main/resources/plugin.properties
  packages/forms/backend/sirius-components-widget-reference-view/src/main/java/org/eclipse/sirius/components/widgets/reference/ReferencePackage.java
  packages/forms/backend/sirius-components-widget-reference-view/src/main/java/org/eclipse/sirius/components/widgets/reference/ReferenceWidgetDescription.java
  packages/forms/backend/sirius-components-widget-reference-view/src/main/java/org/eclipse/sirius/components/widgets/reference/impl/ReferencePackageImpl.java
  packages/forms/backend/sirius-components-widget-reference-view/src/main/java/org/eclipse/sirius/components/widgets/reference/impl/ReferenceWidgetDescriptionImpl.java
  packages/forms/backend/sirius-components-widget-reference-view/src/main/resources/model/reference.ecore
  packages/forms/backend/sirius-components-widget-reference-view/src/main/resources/model/reference.genmodel
  packages/forms/backend/sirius-components-widget-reference/src/main/java/org/eclipse/sirius/components/widget/reference/ReferenceValue.java
  packages/forms/backend/sirius-components-widget-reference/src/main/java/org/eclipse/sirius/components/widget/reference/ReferenceWidget.java
  packages/forms/backend/sirius-components-widget-reference/src/main/java/org/eclipse/sirius/components/widget/reference/ReferenceWidgetComponent.java
  packages/forms/backend/sirius-components-widget-reference/src/main/java/org/eclipse/sirius/components/widget/reference/ReferenceWidgetDescription.java
  packages/forms/backend/sirius-components-widget-reference/src/main/java/org/eclipse/sirius/components/widget/reference/ReferenceWidgetDescriptionConverterProvider.java
  packages/forms/backend/sirius-components-widget-reference/src/main/java/org/eclipse/sirius/components/widget/reference/ReferenceWidgetDescriptionConverterSwitch.java
  packages/forms/backend/sirius-components-widget-reference/src/main/java/org/eclipse/sirius/components/widget/reference/ReferenceWidgetDescriptor.java
  packages/forms/backend/sirius-components-widget-reference/src/main/java/org/eclipse/sirius/components/widget/reference/ReferenceWidgetPreviewConverterProvider.java
  packages/forms/backend/sirius-components-widget-reference/src/main/java/org/eclipse/sirius/components/widget/reference/datafetchers/MutationClickReferenceValueDataFetcher.java
  packages/forms/backend/sirius-components-widget-reference/src/main/java/org/eclipse/sirius/components/widget/reference/datafetchers/ReferenceValueHasClickActionDataFetcher.java
  packages/forms/backend/sirius-components-widget-reference/src/main/java/org/eclipse/sirius/components/widget/reference/dto/ClickReferenceValueInput.java
  packages/forms/backend/sirius-components-widget-reference/src/main/java/org/eclipse/sirius/components/widget/reference/handlers/ClickReferenceValueEventHandler.java
  packages/forms/backend/sirius-components-widget-reference/src/main/resources/schema/reference.graphqls
  packages/forms/backend/sirius-components-widget-reference/src/test/java/org/eclipse/sirius/components/widget/reference/handlers/ClickReferenceValueEventHandlerTests.java
  packages/forms/frontend/sirius-components-forms/src/index.ts
  packages/forms/frontend/sirius-components-forms/src/propertysections/ListPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/useClickHandler.ts
  packages/forms/frontend/sirius-components-widget-reference/src/ReferencePropertySection.tsx
  packages/forms/frontend/sirius-components-widget-reference/src/ReferenceWidgetFragment.types.ts
  packages/sirius-web/frontend/sirius-web/src/index.tsx
Labels: pr: to review later, priority: low

#2176 [cleanup] Update the View elements builders
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/ButtonDescriptionBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/CheckboxDescriptionBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/CheckboxDescriptionStyleBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/ConditionalCheckboxDescriptionStyleBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/ConditionalContainerBorderStyleBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/ContainerBorderStyleBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/FlexboxContainerDescriptionBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/GroupDescriptionBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/ListDescriptionBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/MultiSelectDescriptionBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/RadioDescriptionBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/RichTextDescriptionBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/SelectDescriptionBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/TextAreaDescriptionBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/TextfieldDescriptionBuilder.java
Labels: pr: to review later, priority: low

#2164 [2140] Fix Drag'n'drop when a representation is selected
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/edit/diagram.cy.js
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItem.tsx
Labels: pr: to review later, priority: low

#2131 [2123] Add support for non-selectable tree items
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/explorer/ExplorerDescriptionProvider.java
  packages/trees/backend/sirius-components-collaborative-trees/src/main/resources/schema/tree.graphqls
  packages/trees/backend/sirius-components-trees/src/main/java/org/eclipse/sirius/components/trees/TreeItem.java
  packages/trees/backend/sirius-components-trees/src/main/java/org/eclipse/sirius/components/trees/description/TreeDescription.java
  packages/trees/backend/sirius-components-trees/src/main/java/org/eclipse/sirius/components/trees/renderer/TreeRenderer.java
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItem.tsx
  packages/trees/frontend/sirius-components-trees/src/views/ExplorerView.types.ts
  packages/trees/frontend/sirius-components-trees/src/views/__tests__/GraphqlTreeEventSubscription.test.ts
  packages/trees/frontend/sirius-components-trees/src/views/getTreeEventSubscription.ts
Labels: pr: to review later, priority: low

#2148 [2126] Add support for multiple TreeDescription
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/edit/diagram-context-menu.cy.js
  integration-tests/cypress/e2e/project/edit/document-context-menu.cy.js
  integration-tests/cypress/e2e/project/edit/explorer-toolbar.cy.js
  integration-tests/cypress/e2e/project/edit/explorer.cy.js
  integration-tests/cypress/e2e/project/edit/object-context-menu.cy.js
  integration-tests/cypress/e2e/project/edit/onboarding.cy.js
  integration-tests/cypress/e2e/project/edit/properties.cy.js
  integration-tests/cypress/e2e/project/edit/representation-context-menu.cy.js
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/explorer/ExplorerDescriptionProvider.java
  packages/trees/backend/sirius-components-collaborative-trees/src/main/java/org/eclipse/sirius/components/collaborative/trees/TreeEventProcessor.java
  packages/trees/backend/sirius-components-collaborative-trees/src/main/java/org/eclipse/sirius/components/collaborative/trees/TreeEventProcessorFactory.java
  packages/trees/backend/sirius-components-collaborative-trees/src/main/java/org/eclipse/sirius/components/collaborative/trees/api/IExplorerDescriptionProvider.java
  packages/trees/backend/sirius-components-collaborative-trees/src/main/java/org/eclipse/sirius/components/collaborative/trees/api/ITreeEventHandler.java
  packages/trees/backend/sirius-components-collaborative-trees/src/main/java/org/eclipse/sirius/components/collaborative/trees/api/TreeConfiguration.java
  packages/trees/backend/sirius-components-collaborative-trees/src/main/java/org/eclipse/sirius/components/collaborative/trees/handlers/DeleteTreeItemEventHandler.java
  packages/trees/backend/sirius-components-collaborative-trees/src/main/java/org/eclipse/sirius/components/collaborative/trees/handlers/ExpandAllTreePathEventHandler.java
  packages/trees/backend/sirius-components-collaborative-trees/src/main/java/org/eclipse/sirius/components/collaborative/trees/handlers/InitialDirectEditTreeItemLabelEventHandler.java
  packages/trees/backend/sirius-components-collaborative-trees/src/main/java/org/eclipse/sirius/components/collaborative/trees/handlers/RenameTreeItemEventHandler.java
  packages/trees/backend/sirius-components-collaborative-trees/src/main/java/org/eclipse/sirius/components/collaborative/trees/handlers/TreePathEventHandler.java
  packages/trees/backend/sirius-components-trees-graphql/src/main/java/org/eclipse/sirius/components/trees/graphql/datafetchers/subscription/SubscriptionTreeEventDataFetcher.java
  packages/trees/frontend/sirius-components-trees/src/index.ts
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItem.types.ts
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItemArrow.types.ts
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItemContextMenu.types.ts
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItemContextMenuContribution.types.ts
  packages/trees/frontend/sirius-components-trees/src/treeitems/filterTreeItem.ts
  packages/trees/frontend/sirius-components-trees/src/trees/Tree.types.ts
  packages/trees/frontend/sirius-components-trees/src/views/ExplorerView.tsx
  packages/trees/frontend/sirius-components-trees/src/views/TreeView.tsx
  packages/trees/frontend/sirius-components-trees/src/views/TreeView.types.ts
  packages/trees/frontend/sirius-components-trees/src/views/TreeViewMachine.ts
Labels: pr: to review soon, priority: high

#2141 [2096] Add style for the reference widget
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/edit/formdescriptioneditor.cy.js
  packages/forms/backend/sirius-components-widget-reference-view-edit/src/main/java/org/eclipse/sirius/components/widgets/reference/provider/ConditionalReferenceWidgetDescriptionStyleItemProvider.java
  packages/forms/backend/sirius-components-widget-reference-view-edit/src/main/java/org/eclipse/sirius/components/widgets/reference/provider/ReferenceItemProviderAdapterFactory.java
  packages/forms/backend/sirius-components-widget-reference-view-edit/src/main/java/org/eclipse/sirius/components/widgets/reference/provider/ReferenceWidgetDescriptionItemProvider.java
  packages/forms/backend/sirius-components-widget-reference-view-edit/src/main/java/org/eclipse/sirius/components/widgets/reference/provider/ReferenceWidgetDescriptionStyleItemProvider.java
  packages/forms/backend/sirius-components-widget-reference-view-edit/src/main/resources/plugin.properties
  packages/forms/backend/sirius-components-widget-reference-view/src/main/java/org/eclipse/sirius/components/widgets/reference/ConditionalReferenceWidgetDescriptionStyle.java
  packages/forms/backend/sirius-components-widget-reference-view/src/main/java/org/eclipse/sirius/components/widgets/reference/ReferenceFactory.java
  packages/forms/backend/sirius-components-widget-reference-view/src/main/java/org/eclipse/sirius/components/widgets/reference/ReferencePackage.java
  packages/forms/backend/sirius-components-widget-reference-view/src/main/java/org/eclipse/sirius/components/widgets/reference/ReferenceWidgetDescription.java
  packages/forms/backend/sirius-components-widget-reference-view/src/main/java/org/eclipse/sirius/components/widgets/reference/ReferenceWidgetDescriptionStyle.java
  packages/forms/backend/sirius-components-widget-reference-view/src/main/java/org/eclipse/sirius/components/widgets/reference/impl/ConditionalReferenceWidgetDescriptionStyleImpl.java
  packages/forms/backend/sirius-components-widget-reference-view/src/main/java/org/eclipse/sirius/components/widgets/reference/impl/ReferenceFactoryImpl.java
  packages/forms/backend/sirius-components-widget-reference-view/src/main/java/org/eclipse/sirius/components/widgets/reference/impl/ReferencePackageImpl.java
  packages/forms/backend/sirius-components-widget-reference-view/src/main/java/org/eclipse/sirius/components/widgets/reference/impl/ReferenceWidgetDescriptionImpl.java
  packages/forms/backend/sirius-components-widget-reference-view/src/main/java/org/eclipse/sirius/components/widgets/reference/impl/ReferenceWidgetDescriptionStyleImpl.java
  packages/forms/backend/sirius-components-widget-reference-view/src/main/java/org/eclipse/sirius/components/widgets/reference/util/ReferenceAdapterFactory.java
  packages/forms/backend/sirius-components-widget-reference-view/src/main/java/org/eclipse/sirius/components/widgets/reference/util/ReferenceSwitch.java
  packages/forms/backend/sirius-components-widget-reference-view/src/main/resources/model/reference.ecore
  packages/forms/backend/sirius-components-widget-reference-view/src/main/resources/model/reference.genmodel
  packages/forms/backend/sirius-components-widget-reference/src/main/java/org/eclipse/sirius/components/widget/reference/ReferenceElementProps.java
  packages/forms/backend/sirius-components-widget-reference/src/main/java/org/eclipse/sirius/components/widget/reference/ReferenceWidget.java
  packages/forms/backend/sirius-components-widget-reference/src/main/java/org/eclipse/sirius/components/widget/reference/ReferenceWidgetComponent.java
  packages/forms/backend/sirius-components-widget-reference/src/main/java/org/eclipse/sirius/components/widget/reference/ReferenceWidgetDescription.java
  packages/forms/backend/sirius-components-widget-reference/src/main/java/org/eclipse/sirius/components/widget/reference/ReferenceWidgetDescriptionConverterSwitch.java
  packages/forms/backend/sirius-components-widget-reference/src/main/java/org/eclipse/sirius/components/widget/reference/ReferenceWidgetDescriptor.java
  packages/forms/backend/sirius-components-widget-reference/src/main/java/org/eclipse/sirius/components/widget/reference/ReferenceWidgetPreviewConverterProvider.java
  packages/forms/backend/sirius-components-widget-reference/src/main/java/org/eclipse/sirius/components/widget/reference/ReferenceWidgetStyle.java
  packages/forms/backend/sirius-components-widget-reference/src/main/java/org/eclipse/sirius/components/widget/reference/ReferenceWidgetStyleProvider.java
  packages/forms/backend/sirius-components-widget-reference/src/main/resources/schema/reference.graphqls
  packages/forms/frontend/sirius-components-widget-reference/src/ReferencePreview.tsx
  packages/forms/frontend/sirius-components-widget-reference/src/ReferencePropertySection.tsx
  packages/forms/frontend/sirius-components-widget-reference/src/ReferenceWidgetFragment.types.ts
  packages/sirius-web/frontend/sirius-web/src/index.tsx
Labels: pr: to review later, priority: low

#2181 [2179] Fix whole word pattern is not detected by the filter bar
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/edit/explorer-filterbar.cy.js
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItem.tsx
  packages/trees/frontend/sirius-components-trees/src/treeitems/__tests__/filterTreeItem.test.ts
  packages/trees/frontend/sirius-components-trees/src/treeitems/filterTreeItem.ts
Labels: pr: to review soon, priority: high

#2180 [2178] Fix an error when opening an EdgeStyle
  CHANGELOG.adoc
  packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/DiagramDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/EdgeDescriptionItemProvider.java
Labels: pr: to review later, priority: low

#2177 [2019] Export & import project natures
  CHANGELOG.adoc
  integration-tests/cypress/support/serverCommands.js
  packages/sirius-web/backend/sirius-web-graphql/src/main/resources/schema/siriusweb.graphqls
  packages/sirius-web/backend/sirius-web-services-api/src/main/java/org/eclipse/sirius/web/services/api/projects/CreateProjectInput.java
  packages/sirius-web/backend/sirius-web-services-api/src/main/java/org/eclipse/sirius/web/services/api/projects/IProjectService.java
  packages/sirius-web/backend/sirius-web-services-api/src/main/java/org/eclipse/sirius/web/services/api/projects/ProjectManifest.java
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/projects/ProjectExportService.java
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/projects/ProjectImportService.java
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/projects/ProjectService.java
  packages/sirius-web/frontend/sirius-web/src/views/new-project/NewProjectView.tsx
Labels: pr: to review soon, priority: high

#2189 [2183] Add some data-testid to help cypress tests redaction
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/edit/explorer-toolbar.cy.js
  packages/forms/frontend/sirius-components-forms/src/form/Form.tsx
  packages/forms/frontend/sirius-components-forms/src/groups/Group.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/FlexboxContainerPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/ListPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/ListPropertySection.test.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/FlexboxContainerPropertySection.test.tsx.snap
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/ListPropertySection.test.tsx.snap
  packages/trees/frontend/sirius-components-trees/src/modals/upload-document/UploadDocumentModal.tsx
  packages/trees/frontend/sirius-components-trees/src/toolbar/TreeToolBar.tsx
Labels: pr: to review later, priority: low

#2193 [2083] Add support for edge markers
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/converter/convertDiagram.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/MarkerDefinitions.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/edge/CustomEdge.tsx
Labels: pr: to review soon, priority: high

#2159 [2103] Add support for edge reconnection
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramRenderer.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/reconnect-edge/useReconnectEdge.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/reconnect-edge/useReconnectEdge.types.ts
Labels: pr: to review later, priority: low

#2147 [2086] Add support for hide/fade nodes
  CHANGELOG.adoc
  doc/images/DiagramPanelUnhideUnfade.png
  doc/images/NodePaletteWithHideFade.png
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/converter/convertDiagram.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/graphql/subscription/nodeFragment.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramPanel.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramRenderer.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/ImageNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/Label.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/Label.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/ListNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/RectangularNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/fade/useFadeDiagramElements.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/fade/useFadeDiagramElements.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/hide/useHideDiagramElements.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/hide/useHideDiagramElements.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/DiagramPalette.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/NodePalette.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/Palette.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/Palette.types.ts
Labels: pr: to review later, priority: low

#2203 [2190] Fix Image Node creation size
  CHANGELOG.adoc
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/LayoutConfiguratorRegistry.java
Labels: pr: to review soon, priority: high

#2212 [2211] Fix edges labels icons are not displayed
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/edge/EdgeLabel.tsx
Labels: pr: to review later, priority: low

#2199 [2194] Fix the possibility to set None for color properties in View
  CHANGELOG.adoc
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/NodeStylePropertiesConfigurer.java
Labels: pr: to review soon, priority: high

#2150 [2095] Add support for the creation of new edges
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramRenderer.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/RectangularNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/connector/ConnectorContext.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/connector/ConnectorContext.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/connector/ConnectorContextualMenu.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/connector/ConnectorContextualMenu.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/connector/useConnector.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/connector/useConnector.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/representation/DiagramRepresentation.tsx
Labels: pr: to review soon, priority: high
