Repository eclipse-sirius/sirius-web, pull requests merged in 2023-08, with the labels that each got.

#2221 [2220] Fixes for vscode extenstion
  CHANGELOG.adoc
  vscode-extension/package-lock.json
  vscode-extension/package.json
  vscode-extension/src/data/ProjectData.ts
  vscode-extension/src/data/ProjectData.types.ts
  vscode-extension/src/view/app/App.tsx
  vscode-extension/src/view/app/index.tsx
Labels: pr: to review soon, priority: high

#2243 [doc] Prepare the CHANGELOG for 2023.10.0
  CHANGELOG.adoc
Labels: pr: to review soon, priority: high

#2237 [enh] Build packages using tsconfig.json
  packages/charts/frontend/sirius-components-charts/package.json
  packages/charts/frontend/sirius-components-charts/tsconfig.json
  packages/core/frontend/sirius-components-core/package.json
  packages/core/frontend/sirius-components-core/src/workbench/RepresentationContext.ts
  packages/core/frontend/sirius-components-core/tsconfig.json
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/package.json
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/tsconfig.json
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/package.json
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/ToolbarActionWidget.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/tsconfig.json
  packages/forms/frontend/sirius-components-forms/package.json
  packages/forms/frontend/sirius-components-forms/src/form/FormContext.ts
  packages/forms/frontend/sirius-components-forms/src/views/FormBasedViewMachine.ts
  packages/forms/frontend/sirius-components-forms/src/views/RepresentationsViewMachine.ts
  packages/forms/frontend/sirius-components-forms/tsconfig.json
  packages/forms/frontend/sirius-components-widget-reference/package.json
  packages/forms/frontend/sirius-components-widget-reference/tsconfig.json
  packages/selection/frontend/sirius-components-selection/package.json
  packages/selection/frontend/sirius-components-selection/src/SelectionDialog.tsx
  packages/selection/frontend/sirius-components-selection/tsconfig.json
  packages/trees/frontend/sirius-components-trees/package.json
  packages/trees/frontend/sirius-components-trees/tsconfig.json
  packages/validation/frontend/sirius-components-validation/package.json
  packages/validation/frontend/sirius-components-validation/tsconfig.json
Labels: pr: to review later, priority: low

#2207 [releng] Add some automatic checks to simplify reviews
  .github/workflows/pull-request.yml
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/palette/tool/Tool.tsx
  scripts/check-ts.js
Labels: pr: to review soon, priority: low

#2246 [fix] Check only added code
  scripts/check-ts.js
Labels: pr: to review soon, priority: high

#2248 [enh] Improve the usage of TypeScript in frontend packages
  packages/core/frontend/sirius-components-core/src/workbench/Workbench.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/ImageNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/connector/ConnectorContextualMenu.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/direct-edit/DiagramDirectEditInput.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/edge/EdgeLabel.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/palette/tool/Tool.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/ButtonWidget.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FlexboxContainerWidget.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FlexboxContainerWidget.types.ts
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FormDescriptionEditorRepresentation.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/Group.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/ImageWidget.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/ToolbarActionWidget.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/WidgetEntry.tsx
  packages/forms/frontend/sirius-components-forms/src/form/FormContext.ts
  packages/forms/frontend/sirius-components-forms/src/form/FormContext.types.ts
  packages/forms/frontend/sirius-components-forms/src/groups/Group.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/ButtonPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/ImagePropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/ListPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/MultiSelectPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/PropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/ProposalsList.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/ProposalsList.types.ts
  packages/forms/frontend/sirius-components-forms/src/propertysections/SelectPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/TextfieldPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/TextfieldPropertySection.types.ts
  packages/forms/frontend/sirius-components-forms/src/propertysections/TreePropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/representations/FormRepresentation.tsx
  packages/forms/frontend/sirius-components-forms/src/richtexteditor/RichTextEditor.tsx
  packages/forms/frontend/sirius-components-forms/src/richtexteditor/RichTextEditor.types.ts
  packages/forms/frontend/sirius-components-forms/src/toolbaraction/ToolbarAction.tsx
  packages/forms/frontend/sirius-components-forms/src/views/FormBasedView.tsx
  packages/forms/frontend/sirius-components-forms/src/views/RepresentationsView.tsx
  packages/forms/frontend/sirius-components-widget-reference/src/ReferencePreview.tsx
  packages/forms/frontend/sirius-components-widget-reference/src/ReferencePropertySection.tsx
  packages/selection/frontend/sirius-components-selection/src/SelectionDialog.tsx
  packages/sirius-web/frontend/sirius-web/src/index.tsx
  packages/sirius-web/frontend/sirius-web/src/modals/upload-image/UploadImageModal.tsx
  packages/sirius-web/frontend/sirius-web/src/views/edit-project/DiagramTreeItemContextMenuContribution.tsx
  packages/sirius-web/frontend/sirius-web/src/views/edit-project/DocumentTreeItemContextMenuContribution.tsx
  packages/sirius-web/frontend/sirius-web/src/views/edit-project/EditProjectNavbar/EditProjectNavbar.tsx
  packages/sirius-web/frontend/sirius-web/src/views/edit-project/EditProjectView.tsx
  packages/sirius-web/frontend/sirius-web/src/views/project-settings/ProjectImagesSettings.tsx
  packages/sirius-web/frontend/sirius-web/src/views/project-template-card/ProjectTemplateCard.tsx
  packages/sirius-web/frontend/sirius-web/src/views/projects/ProjectsView.tsx
  packages/sirius-web/frontend/sirius-web/src/views/upload-project/UploadProjectView.tsx
  packages/sirius-web/frontend/sirius-web/src/widgets/SliderPropertySection.tsx
  packages/trees/frontend/sirius-components-trees/src/modals/upload-document/UploadDocumentModal.tsx
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItem.tsx
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItemContextMenu.tsx
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItemContextMenu.types.ts
Labels: pr: to review soon, priority: high

#2278 [fix] Fix check-changelog script
  scripts/check-changelog.js
Labels: pr: to review soon, priority: high

#2271 [2270] Move modals from sirius-components to sirius-web
  CHANGELOG.adoc
  packages/core/frontend/sirius-components/src/index.ts
  packages/sirius-web/frontend/sirius-web/src/modals/delete-project/DeleteProjectModal.tsx
  packages/sirius-web/frontend/sirius-web/src/modals/delete-project/DeleteProjectModal.types.ts
  packages/sirius-web/frontend/sirius-web/src/modals/delete-project/DeleteProjectModalMachine.ts
  packages/sirius-web/frontend/sirius-web/src/modals/new-object/NewObjectModal.tsx
  packages/sirius-web/frontend/sirius-web/src/modals/new-object/NewObjectModal.types.ts
  packages/sirius-web/frontend/sirius-web/src/modals/new-object/NewObjectModalMachine.ts
  packages/sirius-web/frontend/sirius-web/src/modals/new-representation/NewRepresentationModal.tsx
  packages/sirius-web/frontend/sirius-web/src/modals/new-representation/NewRepresentationModal.types.ts
  packages/sirius-web/frontend/sirius-web/src/modals/new-representation/NewRepresentationModalMachine.ts
  packages/sirius-web/frontend/sirius-web/src/modals/new-root-object/NewRootObjectModal.tsx
  packages/sirius-web/frontend/sirius-web/src/modals/new-root-object/NewRootObjectModal.types.ts
  packages/sirius-web/frontend/sirius-web/src/modals/new-root-object/NewRootObjectModalMachine.ts
  packages/sirius-web/frontend/sirius-web/src/modals/rename-project/RenameProjectModal.tsx
  packages/sirius-web/frontend/sirius-web/src/modals/rename-project/RenameProjectModal.types.ts
  packages/sirius-web/frontend/sirius-web/src/modals/rename-project/RenameProjectModalMachine.ts
  packages/sirius-web/frontend/sirius-web/src/views/edit-project/DocumentTreeItemContextMenuContribution.tsx
  packages/sirius-web/frontend/sirius-web/src/views/edit-project/EditProjectNavbar/EditProjectNavbar.tsx
  packages/sirius-web/frontend/sirius-web/src/views/edit-project/ObjectTreeItemContextMenuContribution.tsx
  packages/sirius-web/frontend/sirius-web/src/views/projects/ProjectsView.tsx
Labels: pr: to review soon, priority: high

#2275 [2274] Remove uses of Form and FormContainer components
  CHANGELOG.adoc
  packages/core/frontend/sirius-components/src/core/form/Form.tsx
  packages/core/frontend/sirius-components/src/index.ts
  packages/core/frontend/sirius-components/src/views/FormContainer.tsx
  packages/sirius-web/frontend/sirius-web/src/modals/upload-image/UploadImageModal.tsx
  packages/sirius-web/frontend/sirius-web/src/views/new-project/NewProjectView.tsx
  packages/sirius-web/frontend/sirius-web/src/views/upload-project/UploadProjectView.tsx
Labels: pr: to review soon, priority: high

#2280 [2279] Remove the sirius-components package
  CHANGELOG.adoc
  packages/core/frontend/sirius-components/.eslintrc.json
  packages/core/frontend/sirius-components/.gitignore
  packages/core/frontend/sirius-components/.prettierrc
  packages/core/frontend/sirius-components/.vscode/settings.json
  packages/core/frontend/sirius-components/.vscode/snippets.code-snippets
  packages/core/frontend/sirius-components/.vscode/tasks.json
  packages/core/frontend/sirius-components/README.adoc
  packages/core/frontend/sirius-components/__mocks__/styleMock.js
  packages/core/frontend/sirius-components/cypress.json
  packages/core/frontend/sirius-components/jest.config.js
  packages/core/frontend/sirius-components/jsconfig.json
  packages/core/frontend/sirius-components/package-lock.json
  packages/core/frontend/sirius-components/package.json
  packages/core/frontend/sirius-components/rollup-dev.config.js
  packages/core/frontend/sirius-components/rollup.config.js
  packages/core/frontend/sirius-components/src/core/banner/Banner.module.css
  packages/core/frontend/sirius-components/src/core/banner/Banner.tsx
  packages/core/frontend/sirius-components/src/core/button/Button.module.css
  packages/core/frontend/sirius-components/src/core/button/Button.tsx
  packages/core/frontend/sirius-components/src/core/contextmenu/ContextMenu.module.css
  packages/core/frontend/sirius-components/src/core/contextmenu/ContextMenu.tsx
  packages/core/frontend/sirius-components/src/core/label/Label.module.css
  packages/core/frontend/sirius-components/src/core/label/Label.tsx
  packages/core/frontend/sirius-components/src/core/linkbutton/LinkButton.module.css
  packages/core/frontend/sirius-components/src/core/linkbutton/LinkButton.tsx
  packages/core/frontend/sirius-components/src/core/select/Select.module.css
  packages/core/frontend/sirius-components/src/core/select/Select.tsx
  packages/core/frontend/sirius-components/src/core/spacing/Spacing.adoc
  packages/core/frontend/sirius-components/src/core/spacing/Spacing.tsx
  packages/core/frontend/sirius-components/src/core/spacing/__tests__/Spacing.test.tsx
  packages/core/frontend/sirius-components/src/core/text/Text.module.css
  packages/core/frontend/sirius-components/src/core/text/Text.tsx
  packages/core/frontend/sirius-components/src/core/textfield/Textfield.module.css
  packages/core/frontend/sirius-components/src/core/textfield/Textfield.tsx
  packages/core/frontend/sirius-components/src/icons/Danger.tsx
  packages/core/frontend/sirius-components/src/icons/Delete.tsx
  packages/core/frontend/sirius-components/src/icons/Edit.tsx
  packages/core/frontend/sirius-components/src/icons/Exit.tsx
  packages/core/frontend/sirius-components/src/icons/GenericTool.tsx
  packages/core/frontend/sirius-components/src/icons/NoIcon.tsx
  packages/core/frontend/sirius-components/src/icons/Representation.tsx
  packages/core/frontend/sirius-components/src/icons/index.ts
  packages/core/frontend/sirius-components/src/index.ts
  packages/core/frontend/sirius-components/src/reset.css
  packages/core/frontend/sirius-components/src/typings.d.ts
  packages/core/frontend/sirius-components/src/variables.css
  packages/core/frontend/sirius-components/src/vite-env.d.ts
  packages/core/frontend/sirius-components/src/workbench/Workbench.types.ts
  packages/core/frontend/sirius-components/tsconfig-noEmit.json
  packages/core/frontend/sirius-components/tsconfig.json
Labels: pr: to review soon, priority: high

#2273 [test] Make cypress tests more robust.
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/edit/document-context-menu.cy.js
  integration-tests/cypress/e2e/project/edit/formdescriptioneditor.cy.js
  integration-tests/cypress/e2e/project/edit/object-context-menu.cy.js
  integration-tests/cypress/e2e/project/edit/studio.cy.js
Labels: pr: to review later, priority: low

#2223 [2222] Fix error during not editable tree item renaming
  CHANGELOG.adoc
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/services/ObjectService.java
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/explorer/RenameObjectTreeItemEventHandler.java
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItemDirectEditInput.tsx
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItemDirectEditInput.types.ts
Labels: pr: to review later, priority: low

#2050 [releng] Stop minifying the code for Sirius Components packages
  CHANGELOG.adoc
  packages/charts/frontend/sirius-components-charts/vite.config.js
  packages/core/frontend/sirius-components-core/vite.config.js
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/vite.config.js
  packages/diagrams/frontend/sirius-components-diagrams/vite.config.js
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/vite.config.js
  packages/forms/frontend/sirius-components-forms/vite.config.js
  packages/forms/frontend/sirius-components-widget-reference/vite.config.js
  packages/selection/frontend/sirius-components-selection/vite.config.js
  packages/sirius-web/frontend/sirius-web/vite.config.js
  packages/trees/frontend/sirius-components-trees/vite.config.js
  packages/validation/frontend/sirius-components-validation/vite.config.js
Labels: pr: to review later, priority: low

#2200 [2185] Add support for drop tool from the explorer
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/react-flow/drop-on-diagram.cy.js
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramRenderer.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/ImageNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/ListNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/RectangularNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/drop/useDrop.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/drop/useDrop.types.ts
Labels: pr: to review later, priority: low

#2219 [releng] Switch to Sirius Desktop 7.2.0
  CHANGELOG.adoc
  packages/compatibility/backend/sirius-components-compatibility/pom.xml
Labels: pr: to review later, priority: low

#2304 [2296] Create a dedicated hook for the export to image action
  CHANGELOG.adoc
  package-lock.json
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/package.json
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramRenderer.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/panel/DiagramPanel.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/panel/DiagramPanel.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/panel/useExportToImage.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/panel/useExportToImage.types.ts
  packages/sirius-web/frontend/sirius-web/package.json
Labels: pr: to review soon, priority: high

#2303 [releng] Fix possible compilation error caused by Batik dependencies
  packages/diagrams/backend/sirius-components-diagrams-layout/pom.xml
Labels: pr: to review later, priority: low

#2307 [2295] Support direct edit on edges labels on reactflow diagrams
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramRenderer.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/Label.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/Label.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/direct-edit/DiagramDirectEditInput.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/direct-edit/DiagramDirectEditInput.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/edge/EdgeLabeL.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/edge/EdgeLabel.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/edge/MultiLabelEdge.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/layout.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/node/ListNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/node/RectangularNode.tsx
Labels: pr: to review soon, priority: high

#2247 [2245] Fix an issue when triggering expandAll on models with multiple…
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-services-api/src/main/java/org/eclipse/sirius/web/services/api/representations/IRepresentationService.java
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/explorer/ExpandAllTreePathProvider.java
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/explorer/api/IExplorerNavigationService.java
  packages/sirius-web/backend/sirius-web-services/src/test/java/org/eclipse/sirius/web/services/explorer/ExpandAllTreePathProviderTests.java
Labels: pr: to review later, priority: low

#2286 [cleanup] Remove reference to Eclipse PDE in project classpath
  packages/forms/backend/sirius-components-widget-reference-view/.classpath
Labels: pr: to review later, priority: low

#2234 [2233] Move arrange all in the diagram panel
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramRenderer.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/panel/DiagramPanel.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/panel/DiagramPanel.types.ts
Labels: pr: to review later, priority: low

#2209 [2208] Add Cypress tests to ReactFlow
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/react-flow/diagram-contextual-palette.cy.js
  integration-tests/cypress/e2e/project/react-flow/diagram.reactflow.cy.js
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/Label.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/Tool.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/layout.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/panel/DiagramPanel.tsx
Labels: pr: to review later, priority: low

#2317 [perfs] Improve document type detection performance
  packages/sirius-web/backend/sirius-web-persistence/src/main/java/org/eclipse/sirius/web/persistence/repositories/IDocumentRepository.java
Labels: pr: to review later, priority: low
