Repository eclipse-sirius/sirius-web, pull requests merged in 2023-11, with the labels that each got.

#2518 [2460] Reference widget default handler/provider do not need to be @Service
  packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/ReferenceWidgetDefaultCreateElementHandler.java
  packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/browser/ModelBrowsersDescriptionProvider.java
  packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/browser/ReferenceWidgetDefaultCandidateSearchProvider.java
  packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/handlers/CreateElementEventHandler.java
  packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/handlers/ReferenceWidgetChildCreationDescriptionsEventHandler.java
  packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/handlers/ReferenceWidgetRootCreationDescriptionsEventHandler.java
  packages/forms/backend/sirius-components-collaborative-widget-reference/src/test/java/org/eclipse/sirius/components/collaborative/widget/reference/handlers/CreateElementEventHandlerTests.java
Labels: pr: to review later, priority: low

#2526 [fix] Add a small offset to create the node under the click position
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/layout.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/useLayout.ts
Labels: pr: to review soon, priority: high

#2533 [2532] Allows border to move on all parent node sizes
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramRenderer.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/border/useBorderChange.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/border/useBorderChange.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/layoutBorderNodes.ts
Labels: pr: to review soon, priority: high

#2545 [2543] Prevent list items being moved to inconsistent positions
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/dropNode/useDropNode.tsx
Labels: pr: to review soon, priority: low

#2527 [2500] Fix edge selection in React Flow
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramRenderer.tsx
Labels: pr: to review later, priority: low

#2536 [2516] Improve the diagram core API to hide the header separator
  CHANGELOG.adoc
  packages/compatibility/backend/sirius-components-compatibility-emf/src/test/java/org/eclipse/sirius/components/compatibility/emf/compatibility/diagrams/EdgeMappingConverterTests.java
  packages/compatibility/backend/sirius-components-compatibility-emf/src/test/java/org/eclipse/sirius/components/compatibility/emf/compatibility/operations/CreateViewOperationHandlerTests.java
  packages/compatibility/backend/sirius-components-compatibility-emf/src/test/java/org/eclipse/sirius/components/compatibility/emf/compatibility/operations/DeleteViewOperationHandlerTests.java
  packages/compatibility/backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/diagrams/AbstractNodeMappingConverter.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/resources/schema/diagram.graphqls
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/test/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/GetConnectorToolsEventHandlerTests.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/test/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/InvokeSingleClickOnDiagramElementToolEventHandlerTests.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/ELKLayoutedDiagramProvider.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/IncrementalLayoutedDiagramProvider.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/services/DefaultTestDiagramDescriptionProvider.java
  packages/diagrams/backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/TestDiagramBuilder.java
  packages/diagrams/backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/TestDiagramDescriptionBuilder.java
  packages/diagrams/backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/builder/label/LabelBuilder.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/InsideLabel.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/InsideLabelComponent.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/description/InsideLabelDescription.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/elements/InsideLabelElementProps.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/renderer/DiagramElementFactory.java
  packages/diagrams/backend/sirius-components-diagrams/src/test/java/org/eclipse/sirius/components/diagrams/renderer/DiagramElementChangeVisibilityTests.java
  packages/diagrams/backend/sirius-components-diagrams/src/test/java/org/eclipse/sirius/components/diagrams/renderer/DiagramRendererEdgeTests.java
  packages/diagrams/backend/sirius-components-diagrams/src/test/java/org/eclipse/sirius/components/diagrams/renderer/DiagramRendererNodeTests.java
  packages/diagrams/backend/sirius-components-diagrams/src/test/java/org/eclipse/sirius/components/diagrams/renderer/UnsynchronizedDiagramTests.java
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/converter/ListNodeConverterHandler.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/converter/RectangleNodeConverterHandler.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/graphql/subscription/labelFragment.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/graphql/subscription/labelFragment.types.ts
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/DiagramOperationInterpreterViewSwitch.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewDiagramDescriptionConverter.java
  packages/view/backend/sirius-components-view-emf/src/test/java/org/eclipse/sirius/components/view/emf/diagram/ViewPaletteProviderTests.java
Labels: pr: to review soon, priority: high

#2525 [2388] Consolidated icons overlay management into a single component
  CHANGELOG.adoc
  packages/compatibility/backend/sirius-components-compatibility-emf/src/main/java/org/eclipse/sirius/components/compatibility/emf/properties/NonContainmentReferenceIfDescriptionProvider.java
  packages/core/frontend/sirius-components-core/src/icon/IconOverlay.tsx
  packages/core/frontend/sirius-components-core/src/icon/IconOverlay.types.ts
  packages/core/frontend/sirius-components-core/src/index.ts
  packages/diagrams/backend/sirius-components-diagrams-graphql/src/main/java/org/eclipse/sirius/components/diagrams/graphql/datafetchers/diagram/DeleteToolIconURLDataFetcher.java
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/Label.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/Tool.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/connector/ConnectorContextualMenu.tsx
  packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/ReferenceWidgetDescriptionConverterSwitch.java
  packages/forms/backend/sirius-components-widget-reference/src/main/java/org/eclipse/sirius/components/widget/reference/ReferenceWidgetComponent.java
  packages/forms/backend/sirius-components-widget-reference/src/main/java/org/eclipse/sirius/components/widget/reference/ReferenceWidgetDescription.java
  packages/forms/backend/sirius-components-widget-reference/src/main/java/org/eclipse/sirius/components/widget/reference/ReferenceWidgetPreviewConverterProvider.java
  packages/forms/frontend/sirius-components-forms/src/groups/Group.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/ListPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/MultiSelectPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/SelectPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/ListPropertySection.test.tsx.snap
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/MultiSelectPropertySection.test.tsx.snap
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/SelectPropertySection.test.tsx.snap
  packages/forms/frontend/sirius-components-widget-reference/src/components/FilterableSortableList.tsx
  packages/forms/frontend/sirius-components-widget-reference/src/components/ValuedReferenceAutocomplete.tsx
  packages/forms/frontend/sirius-components-widget-reference/src/modals/CreateModal.tsx
  packages/selection/frontend/sirius-components-selection/src/SelectionDialog.tsx
  packages/sirius-web/frontend/sirius-web/src/modals/new-object/NewObjectModal.tsx
  packages/sirius-web/frontend/sirius-web/src/modals/new-root-object/NewRootObjectModal.tsx
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItem.tsx
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/compatibility/PropertiesWidgetCreationService.java
Labels: pr: to review later, priority: low

#2542 [2535] Make possible to hide the header separator in the view DSL
  CHANGELOG.adoc
  doc/screenshots/compartmentWithHeaderWithoutSeparator.png
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/converter/ListNodeConverterHandler.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/converter/RectangleNodeConverterHandler.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramRenderer.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/ListNodeLayoutHandler.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/RectangleNodeLayoutHandler.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/layoutNode.ts
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/classdiagram/CDClassNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/classdiagram/CDInterfaceNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/classdiagram/CDPackageNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/logicalarchitecture/ClassNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/logicalarchitecture/ComponentNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/logicalarchitecture/EnumNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/logicalarchitecture/InterfaceNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/logicalarchitecture/PackageNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/operationalanalysis/OperationalActorNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/operationalanalysis/OperationalEntityNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/operationalanalysis/OperationalPerimeterNodeDescriptionProvider.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/RectangularNodeStyleDescriptionBuilder.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/RectangularNodeStyleDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/resources/plugin.properties
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/DiagramPackage.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/RectangularNodeStyleDescription.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/DiagramPackageImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/RectangularNodeStyleDescriptionImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/resources/model/diagram.ecore
  packages/view/backend/sirius-components-view-diagram/src/main/resources/model/diagram.genmodel
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/NodeStylePropertiesConfigurer.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewDiagramDescriptionConverter.java
Labels: pr: to review soon, priority: high

#2553 [2547] Ensure edge labels can not be hidden by selected nodes
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/converter/convertDiagram.ts
Labels: pr: to review later, priority: low

#2452 [doc] Add architectural concerns to the review checklist
  doc/review-checklist.adoc
Labels: pr: to review soon, priority: high

#2558 [2555] Add distinct edge creation handles
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/index.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/connector/useConnector.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/connector/useConnector.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/handles/ConnectionCreationHandles.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/handles/ConnectionCreationHandles.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/handles/useConnectionCandidatesQuery.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/node/ImageNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/node/ListNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/node/RectangularNode.tsx
  packages/sirius-web/frontend/sirius-web/src/nodes/EllipseNode.tsx
Labels: pr: to review soon, priority: high

#2540 [2359] Ignore hidden nodes when computing DnD targets & overlaps
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/dropNode/useDropNode.tsx
Labels: pr: to review later, priority: low

#2551 [2550] Palette should be hidden on viewport or zoom change
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramRenderer.tsx
Labels: pr: to review soon, priority: low

#2447 [doc] Contribute a new shape to specify aspect ratio on node
  CHANGELOG.adoc
  doc/iterations/2023.12/shapes/images/keep_node_aspect_ratio_01.png
  doc/iterations/2023.12/shapes/images/keep_node_aspect_ratio_02.png
  doc/iterations/2023.12/shapes/images/keep_node_aspect_ratio_03.png
  doc/iterations/2023.12/shapes/images/keep_node_aspect_ratio_04.png
  doc/iterations/2023.12/shapes/keep_node_aspect_ratio.adoc
Labels: pr: to review later, priority: low

#2560 [288] Add some tests for drag and drop of nodes
  integration-tests/cypress/e2e/project/edit/widget-reference.cy.js
  integration-tests/cypress/e2e/project/react-flow/graphical-dnd.cy.js
  integration-tests/cypress/support/e2e.js
  integration-tests/cypress/support/reactFlowCommands.js
  integration-tests/cypress/support/studioCommands.js
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/test/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/DropNodeEventHandlerTests.java
Labels: pr: to review later, priority: low

#2544 [doc] Contribute a shape for rotatable border node
  CHANGELOG.adoc
  doc/iterations/2023.12.0/shapes/images/rotatable_border_node_01.gif
  doc/iterations/2023.12.0/shapes/images/rotatable_border_node_02.png
  doc/iterations/2023.12.0/shapes/images/rotatable_border_node_03.png
  doc/iterations/2023.12.0/shapes/rotatable_border_node.adoc
Labels: pr: to review later, priority: low

#2563 [2562] Prevent a created node to overlap the header
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/RectangleNodeLayoutHandler.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/layoutNode.ts
Labels: pr: to review soon, priority: high

#2546 [2522] Add support for rotatable border node
  CHANGELOG.adoc
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/resources/schema/diagram.graphqls
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/ImageNodeStyle.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/NodeComponent.java
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/converter/ImageNodeConverterHandler.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/graphql/subscription/nodeFragment.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/graphql/subscription/nodeFragment.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/border/useBorderChange.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/layoutBorderNodes.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/layoutNode.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/layoutParams.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/node/ImageNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/node/ImageNode.types.ts
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/logicalarchitecture/ProvidedServiceNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/logicalarchitecture/RequiredServiceNodeDescriptionProvider.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/ImageNodeStyleDescriptionBuilder.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/ImageNodeStyleDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/resources/plugin.properties
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/DiagramPackage.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/ImageNodeStyleDescription.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/DiagramPackageImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/ImageNodeStyleDescriptionImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/resources/model/diagram.ecore
  packages/view/backend/sirius-components-view-diagram/src/main/resources/model/diagram.genmodel
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ImageNodeStyleProvider.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/NodeStylePropertiesConfigurer.java
Labels: pr: to review soon, priority: low

#2422 [2235] Reduce the amount of code in DiagramRenderer
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramRenderer.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/selection/useDiagramSelection.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/selection/useDiagramSelection.types.ts
Labels: pr: to review soon, priority: low

#2578 [2571] Make sure edges are drawn up to the border of their target node
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/connector/useConnector.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/edge/EdgeLayout.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/handles/ConnectionCreationHandles.tsx
Labels: pr: to review later, priority: low

#2575 [test] Fix some flaky Cypress tests
  integration-tests/cypress/e2e/project/edit/diagram.cy.js
  integration-tests/cypress/e2e/project/edit/form.cy.js
  integration-tests/cypress/e2e/project/react-flow/diagram.reactflow.cy.js
  integration-tests/cypress/plugins/index.js
  integration-tests/cypress/support/explorerCommands.js
  integration-tests/package-lock.json
  integration-tests/package.json
  packages/sirius-web/frontend/sirius-web/src/modals/new-object/NewObjectModal.tsx
Labels: pr: to review later, priority: low

#2576 [2568] Allow explorer to change its content
  CHANGELOG.adoc
  doc/adrs/116_add_support_for_changing_the_content_of_the_explorer.adoc
  packages/forms/frontend/sirius-components-widget-reference/src/components/ModelBrowserTreeView.tsx
  packages/trees/frontend/sirius-components-trees/src/index.ts
  packages/trees/frontend/sirius-components-trees/src/views/ExplorerView.tsx
  packages/trees/frontend/sirius-components-trees/src/views/ExplorerViewConfiguration.tsx
  packages/trees/frontend/sirius-components-trees/src/views/ExplorerViewConfiguration.types.ts
  packages/trees/frontend/sirius-components-trees/src/views/ExplorerViewContext.tsx
  packages/trees/frontend/sirius-components-trees/src/views/ExplorerViewContext.types.ts
  packages/trees/frontend/sirius-components-trees/src/views/TreeConverter.types.ts
  packages/trees/frontend/sirius-components-trees/src/views/TreeView.tsx
  packages/trees/frontend/sirius-components-trees/src/views/TreeView.types.ts
Labels: pr: to review soon, priority: high

#2573 [2572] Use dynamic handles
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/converter/ConvertEngine.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/converter/IconLabelNodeConverterHandler.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/converter/ImageNodeConverterHandler.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/converter/ListNodeConverterHandler.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/converter/RectangleNodeConverterHandler.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/converter/convertDiagram.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/converter/convertHandles.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/index.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramRenderer.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramRenderer.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/edge/EdgeLayout.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/edge/EdgeLayout.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/edge/MultiLabelEdge.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/handles/ConnectionHandles.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/handles/ConnectionHandles.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/handles/useHandleChange.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/handles/useHandleChange.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/handles/useRefreshConnectionHandles.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/layout.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/layoutHandles.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/node/ImageNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/node/ListNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/node/RectangularNode.tsx
  packages/sirius-web/frontend/sirius-web-application/src/nodes/EllipseNode.tsx
  packages/sirius-web/frontend/sirius-web-application/src/nodes/EllipseNodeConverterHandler.ts
Labels: pr: to review soon, priority: high

#2561 [2549] Use our algorithm instead of elk.js to do the arrange-all
  CHANGELOG.adoc
  package-lock.json
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/package.json
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramRenderer.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/IconLabelNodeLayoutHandler.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/ImageNodeLayoutHandler.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/LayoutEngine.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/LayoutEngine.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/ListNodeLayoutHandler.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/RectangleNodeLayoutHandler.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/layout.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/layout.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/layoutHandles.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/layoutNode.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/useLayout.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/useLayout.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/panel/DiagramPanel.tsx
Labels: pr: to review soon, priority: high

#2585 [2584] Add feedback during edge creation
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramRenderer.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/connector/ConnectorContext.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/connector/useConnector.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/connector/useConnector.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/dropNode/useDropNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/handles/ConnectionHandles.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/node/ImageNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/node/ListNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/node/NodeContext.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/node/NodeContext.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/node/RectangularNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/representation/DiagramRepresentation.tsx
  packages/sirius-web/frontend/sirius-web-application/src/nodes/EllipseNode.tsx
Labels: pr: to review soon, priority: high

#2586 [enh] Ensure edges point exactly on the node's border
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/edge/MultiLabelEdge.tsx
Labels: pr: to review soon, priority: high

#2592 [2591] Give right node descriptions to node converter handlers
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/converter/ImageNodeConverterHandler.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/converter/ListNodeConverterHandler.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/converter/RectangleNodeConverterHandler.ts
  packages/sirius-web/frontend/sirius-web-application/src/nodes/EllipseNodeConverterHandler.ts
Labels: pr: to review soon, priority: high

#2602 [2601] Prevent the deletion of references to moved objects
  CHANGELOG.adoc
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/services/EditingContextCrossReferenceAdapter.java
Labels: pr: to review later, priority: high

#2583 [2582] Fix a delay while palette tools are displayed
  CHANGELOG.adoc
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/GetPaletteEventHandler.java
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/Palette.tsx
Labels: pr: to review soon, priority: high

#2607 [test] Add test to prevent the deletion of references to moved objects
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/services/EditingContextCrossReferenceAdapter.java
  packages/emf/backend/sirius-components-emf/src/test/java/org/eclipse/sirius/components/emf/services/EditingContextCrossReferenceAdapterTest.java
Labels: pr: to review soon, priority: high

#2603 [2608] Improve the layout of edge handles on the left and right side of nodes
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/handles/ConnectionHandles.tsx
Labels: pr: to review soon, priority: high

#2617 [2614] Remember the last tool invoked in a tool section
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/DiagramPaletteContext.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/DiagramPaletteContext.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/tool-section/ToolSection.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/useDiagramPalette.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/useDiagramPalette.types.ts
Labels: pr: to review soon, priority: high

#2557 [doc] Add an ADR about dynamic handles
  CHANGELOG.adoc
  doc/adrs/118_use_dynamic_handles_to_connect_edges_between_nodes.adoc
Labels: pr: to review soon, priority: high

#2554 [doc] Add shape for handles improvements
  CHANGELOG.adoc
  doc/iterations/2023.12/shapes/handles.adoc
  doc/iterations/2023.12/shapes/images/handles_initial_state.png
  doc/iterations/2023.12/shapes/images/rotatable_border_node_01.gif
  doc/iterations/2023.12/shapes/images/rotatable_border_node_02.png
  doc/iterations/2023.12/shapes/images/rotatable_border_node_03.png
  doc/iterations/2023.12/shapes/images/support_custom_nodes_01.png
  doc/iterations/2023.12/shapes/rotatable_border_node.adoc
  doc/iterations/2023.12/shapes/support_custom_nodes.adoc
Labels: pr: to review soon, priority: high

#2622 [2621] Set ConnectionLineType to SmoothStep
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramRenderer.tsx
Labels: pr: to review later, priority: low

#2594 [2593] Set updatable edge to false by default
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/converter/convertDiagram.ts
Labels: pr: to review soon, priority: high

#2548 [doc] Add an ADR about arrange all action improvements
  CHANGELOG.adoc
  doc/adrs/120_improve_arrange_all_action.adoc
Labels: pr: to review soon, priority: high

#2629 [2624] Fix Edge Arrows positions and shapes
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/edge/MarkerDefinitions.tsx
Labels: pr: to review soon, priority: high

#2626 [2625] Fix the line style computation on edge and border node
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/converter/RectangleNodeConverterHandler.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/converter/convertDiagram.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/index.ts
  packages/sirius-web/frontend/sirius-web-application/src/nodes/EllipseNodeConverterHandler.ts
Labels: pr: to review soon, priority: high

#2630 [cleanup] Remove the absolute import in OnboardArea.tsx
  packages/sirius-web/frontend/sirius-web-application/src/onboarding/OnboardArea.tsx
Labels: pr: to review soon, priority: high

#2636 [2633] Make sure the grid is visible when enabled, even when moving a non-droppable node
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/dropNode/useDropNode.ts
Labels: pr: to review soon, priority: high

#2631 [2614] Add Cypress test for "remember the last tool used in a tool section"
  integration-tests/cypress/e2e/project/react-flow/diagram-contextual-palette.cy.js
Labels: pr: to review later, priority: low

#2637 [2635] Fix an error when switching between react flow representations
  CHANGELOG.adoc
  packages/core/frontend/sirius-components-core/src/workbench/Workbench.tsx
Labels: pr: to review soon, priority: high

#2623 [2618] Add pre and post-process around input processing
  CHANGELOG.adoc
  doc/adrs/121_add_process_before_and_after_input_handling.adoc
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/api/IInputPostProcessor.java
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/api/IInputPreProcessor.java
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/EditingContextEventProcessor.java
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/EditingContextEventProcessorFactory.java
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/EditingContextEventProcessorFactoryParameters.java
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/EditingContextEventProcessorParameters.java
Labels: pr: to review later, priority: low

#2632 [2581] Allow custom tools to control their creation position
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/index.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/usePaletteReferencePosition.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/usePaletteReferencePosition.types.ts
Labels: pr: to review soon, priority: high

#2643 [2642] Only hide the palette if it's open
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/DiagramElementPaletteContext.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/DiagramPaletteContext.tsx
Labels: pr: to review soon, priority: high

#2653 [cleanup] Revert the commit "Order handles on each side to reduce edges crossing"
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/converter/convertHandles.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/edge/EdgeLayout.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/handles/ConnectionHandles.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/handles/ConnectionHandles.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/handles/useHandleChange.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/handles/useHandleChange.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/handles/useRefreshConnectionHandles.tsx
Labels: pr: to review soon, priority: high

#2641 [2640] Compute handle position on diagram conversion
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/converter/convertDiagram.ts
Labels: pr: to review soon, priority: high

#2634 [2624] Fix Edge Arrows positions, shapes and colors
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/edge/MarkerDefinitions.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/edge/MultiLabelEdge.tsx
Labels: pr: to review soon, priority: high

#2656 [2647] Fix CSS error displayed in the console
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/converter/ListNodeConverterHandler.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/ListNodeLayoutHandler.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/node/ListNode.tsx
Labels: pr: to review soon, priority: high

#2651 [2646] Avoid rerendering the palette if not necessary
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/DiagramElementPalette.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/DiagramPalette.tsx
Labels: pr: to review soon, priority: high

#2702 [2685] Fix direct edit of edge labels with F2
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/direct-edit/useDiagramDirectEdit.tsx
Labels: pr: to review soon, priority: high

#2652 [2552] Close the palettes on Escape
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/react-flow/diagram-contextual-palette.cy.js
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramRenderer.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/useDiagramElementPalette.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/useDiagramPalette.tsx
Labels: pr: to review soon, priority: low
