Repository eclipse-sirius/sirius-web, pull requests merged in 2023-06, with the labels that each got.

#2009 [2008] Fix edge tool target list for applications with a custom IView…
  CHANGELOG.adoc
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewToolSectionsProvider.java
Labels: pr: to review soon, priority: high

#1974 [1966] Add Selection Description in the View DSL
  CHANGELOG.adoc
  packages/core/backend/sirius-components-core/src/main/resources/.gitkeep
  packages/core/backend/sirius-components-core/src/main/resources/icons/svg/Default.svg
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/services/ObjectService.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/NodeToolBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/SelectionDescriptionBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/ViewBuilders.java
  packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/NodeToolItemProvider.java
  packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/SelectionDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/ViewItemProviderAdapterFactory.java
  packages/view/backend/sirius-components-view-edit/src/main/resources/plugin.properties
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/ViewConverter.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ToolConverter.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewToolSectionsProvider.java
  packages/view/backend/sirius-components-view-emf/src/test/java/org/eclipse/sirius/components/view/emf/view/DynamicDiagramsTests.java
  packages/view/backend/sirius-components-view-emf/src/test/java/org/eclipse/sirius/components/view/emf/view/DynamicFormsTests.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/NodeTool.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/SelectionDescription.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/ViewFactory.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/ViewPackage.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/impl/NodeToolImpl.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/impl/SelectionDescriptionImpl.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/impl/ViewFactoryImpl.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/impl/ViewPackageImpl.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/util/ViewAdapterFactory.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/util/ViewSwitch.java
  packages/view/backend/sirius-components-view/src/main/resources/model/view.ecore
  packages/view/backend/sirius-components-view/src/main/resources/model/view.genmodel
Labels: pr: to review soon, priority: high

#2007 [cleanup] Fix the expected presence of the feedback message service
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/configuration/ViewReconnectionToolsExecutorParameters.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/DiagramOperationInterpreter.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewReconnectionToolsExecutor.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewToolSectionsProvider.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/form/ViewFormDescriptionConverter.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/form/ViewFormDescriptionConverterSwitch.java
Labels: pr: to review soon, priority: high

#2028 [2027] Support both versions of the ITool interface in the imageURL data fetchers
  CHANGELOG.adoc
  packages/diagrams/backend/sirius-components-diagrams-graphql/src/main/java/org/eclipse/sirius/components/diagrams/graphql/datafetchers/diagram/SingleClickOnDiagramElementToolImageURLDataFetcher.java
  packages/diagrams/backend/sirius-components-diagrams-graphql/src/main/java/org/eclipse/sirius/components/diagrams/graphql/datafetchers/diagram/SingleClickOnTwoDiagramElementsToolImageURLDataFetcher.java
Labels: pr: to review soon, priority: high

#2033 [fix] Fix syntax error in AQL expression
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/configuration/DomainPropertiesConfigurer.java
Labels: pr: to review later, priority: low

#2029 [2026] Add the children layout strategy as a node children features
  CHANGELOG.adoc
  packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/ColorPaletteItemProvider.java
  packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/NodeDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/UserColorItemProvider.java
  packages/view/backend/sirius-components-view/src/main/resources/model/view.genmodel
Labels: pr: to review soon, priority: high

#2025 [2018] Displays the page of the first element selected
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/edit/formdescriptioneditor.cy.js
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/MultiSelectWidget.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/PageList.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/SelectWidget.tsx
Labels: pr: to review soon, priority: high

#2035 Integrate the workbench selection with react-flow
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/converter/convertDiagram.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramRenderer.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramRenderer.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/ImageNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/ImageNode.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/ListNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/ListNode.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/RectangularNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/RectangularNode.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/representation/DiagramRepresentation.tsx
Labels: pr: to review later, priority: low

#2017 [releng] Upgrade JaCoCo Maven Plug-in from 0.8.8 to 0.8.10
  CHANGELOG.adoc
  packages/charts/backend/sirius-components-charts/pom.xml
  packages/charts/backend/sirius-components-collaborative-charts/pom.xml
  packages/compatibility/backend/sirius-components-compatibility-emf/pom.xml
  packages/compatibility/backend/sirius-components-compatibility/pom.xml
  packages/core/backend/sirius-components-annotations-spring/pom.xml
  packages/core/backend/sirius-components-annotations/pom.xml
  packages/core/backend/sirius-components-collaborative/pom.xml
  packages/core/backend/sirius-components-core/pom.xml
  packages/core/backend/sirius-components-graphql-api/pom.xml
  packages/core/backend/sirius-components-representations/pom.xml
  packages/diagrams/backend/sirius-components-collaborative-diagrams/pom.xml
  packages/diagrams/backend/sirius-components-diagrams-graphql/pom.xml
  packages/diagrams/backend/sirius-components-diagrams-layout-api/pom.xml
  packages/diagrams/backend/sirius-components-diagrams-layout/pom.xml
  packages/diagrams/backend/sirius-components-diagrams-tests/pom.xml
  packages/diagrams/backend/sirius-components-diagrams/pom.xml
  packages/domain/backend/sirius-components-domain-emf/pom.xml
  packages/emf/backend/sirius-components-emf/pom.xml
  packages/emf/backend/sirius-components-interpreter/pom.xml
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/pom.xml
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors-graphql/pom.xml
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors/pom.xml
  packages/forms/backend/sirius-components-collaborative-forms/pom.xml
  packages/forms/backend/sirius-components-forms-graphql/pom.xml
  packages/forms/backend/sirius-components-forms-tests/pom.xml
  packages/forms/backend/sirius-components-forms/pom.xml
  packages/releng/backend/sirius-components-test-coverage/pom.xml
  packages/selection/backend/sirius-components-collaborative-selection/pom.xml
  packages/selection/backend/sirius-components-selection-graphql/pom.xml
  packages/selection/backend/sirius-components-selection/pom.xml
  packages/sirius-web/backend/sirius-web-graphql/pom.xml
  packages/sirius-web/backend/sirius-web-persistence/pom.xml
  packages/sirius-web/backend/sirius-web-sample-application/pom.xml
  packages/sirius-web/backend/sirius-web-services-api/pom.xml
  packages/sirius-web/backend/sirius-web-services/pom.xml
  packages/sirius-web/backend/sirius-web-spring/pom.xml
  packages/starters/backend/sirius-components-starter/pom.xml
  packages/tests/backend/sirius-components-spring-tests/pom.xml
  packages/tests/backend/sirius-components-tests/pom.xml
  packages/trees/backend/sirius-components-collaborative-trees/pom.xml
  packages/trees/backend/sirius-components-trees-graphql/pom.xml
  packages/trees/backend/sirius-components-trees/pom.xml
  packages/validation/backend/sirius-components-collaborative-validation/pom.xml
  packages/validation/backend/sirius-components-validation-graphql/pom.xml
  packages/validation/backend/sirius-components-validation/pom.xml
  packages/view/backend/sirius-components-view-emf/pom.xml
  packages/web/backend/sirius-components-graphql/pom.xml
  packages/web/backend/sirius-components-web/pom.xml
Labels: pr: to review later, priority: low

#2059 [2058] Fix default icon for List widget candidates
  CHANGELOG.adoc
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/form/ViewFormDescriptionConverterSwitch.java
Labels: pr: to review soon, priority: low

#2062 Remove table-layout from ListPropertySection
  CHANGELOG.adoc
  packages/forms/frontend/sirius-components-forms/src/propertysections/ListPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/ListPropertySection.test.tsx.snap
Labels: pr: to review soon, priority: low

#2037 [2036] Add page actions in form
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/edit/formdescriptioneditor.cy.js
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/AddToolbarActionEventHandler.java
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/MoveToolbarActionEventHandler.java
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/test/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/AddToolbarActionEventHandlerTests.java
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/test/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/DeleteToolbarActionEventHandlerTests.java
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/test/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/MoveToolbarActionEventHandlerTests.java
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/formdescriptioneditors/components/FormDescriptionEditorPageComponent.java
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/Group.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/PageList.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/ToolbarActionWidget.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/ToolbarActionWidget.types.ts
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/ToolbarActions.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/ToolbarActions.types.ts
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/__tests__/ToolbarActions.test.tsx
  packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/FormQueryService.java
  packages/forms/backend/sirius-components-collaborative-forms/src/test/java/org/eclipse/sirius/components/collaborative/forms/FormQueryServiceTests.java
  packages/forms/backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/components/PageComponent.java
  packages/forms/backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/description/PageDescription.java
  packages/forms/frontend/sirius-components-forms/src/form/Form.tsx
  packages/forms/frontend/sirius-components-forms/src/form/FormEventFragments.ts
  packages/forms/frontend/sirius-components-forms/src/representations/FormRepresentation.tsx
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/PageDescriptionBuilder.java
  packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/GroupDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/PageDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-edit/src/main/resources/plugin.properties
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/form/ViewFormDescriptionConverter.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/PageDescription.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/ViewPackage.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/impl/PageDescriptionImpl.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/impl/ViewPackageImpl.java
  packages/view/backend/sirius-components-view/src/main/resources/model/view.ecore
  packages/view/backend/sirius-components-view/src/main/resources/model/view.genmodel
Labels: pr: to review soon, priority: low

#2054 [doc] Add shape for reference widgets
  CHANGELOG.adoc
  doc/iterations/2023.8/shapes/reference-widgets.adoc
Labels: pr: to review soon, priority: high

#2012 [2010] Add a palette for node with reactflow
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/contexts/DiagramContext.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/contexts/DiagramContext.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/ImageNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/ListNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/Palette.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/Palette.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/RectangularNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/Tool.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/Tool.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/representation/DiagramRepresentation.tsx
Labels: pr: to review soon, priority: high

#2078 [2076] Fix a spring service declaration to add interface implementation.
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/editingcontext/EditingContextSearchService.java
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/editingcontext/EditingDomainFactoryService.java
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/editingcontext/api/IEditingDomainFactoryService.java
  packages/sirius-web/backend/sirius-web-services/src/test/java/org/eclipse/sirius/web/services/editingcontext/EditingContextSearchServiceTests.java
  packages/sirius-web/backend/sirius-web-services/src/test/java/org/eclipse/sirius/web/services/editingcontext/EditingDomainFactoryServiceTests.java
Labels: pr: to review soon, priority: high

#2051 [cleanup] Use IEditingContextDispatcher in CompletionProposals data fetcher
  packages/forms/backend/sirius-components-forms-graphql/src/main/java/org/eclipse/sirius/components/forms/graphql/datafetchers/form/FormDescriptionCompletionProposalsDataFetcher.java
Labels: pr: to review later, priority: low

#2052 Add a basic support for node resize
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/converter/convertDiagram.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/ImageNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/ListNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/RectangularNode.tsx
Labels: pr: to review later, priority: low

#2068 [2067] Fix completion support for custom widgets' expression fields
  CHANGELOG.adoc
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/ViewPropertiesDescriptionRegistryConfigurer.java
Labels: pr: to review later, priority: low

#2053 [1989] Contribute a server to compute the layout of the diagram
  packages/diagrams/backend/sirius-components-diagrams-layout-server/.eslintrc.cjs
  packages/diagrams/backend/sirius-components-diagrams-layout-server/.gitignore
  packages/diagrams/backend/sirius-components-diagrams-layout-server/.prettierrc
  packages/diagrams/backend/sirius-components-diagrams-layout-server/electron/httpServer.ts
  packages/diagrams/backend/sirius-components-diagrams-layout-server/electron/main.ts
  packages/diagrams/backend/sirius-components-diagrams-layout-server/index.html
  packages/diagrams/backend/sirius-components-diagrams-layout-server/package-lock.json
  packages/diagrams/backend/sirius-components-diagrams-layout-server/package.json
  packages/diagrams/backend/sirius-components-diagrams-layout-server/public/vite.svg
  packages/diagrams/backend/sirius-components-diagrams-layout-server/src/App.css
  packages/diagrams/backend/sirius-components-diagrams-layout-server/src/App.tsx
  packages/diagrams/backend/sirius-components-diagrams-layout-server/src/index.css
  packages/diagrams/backend/sirius-components-diagrams-layout-server/src/main.tsx
  packages/diagrams/backend/sirius-components-diagrams-layout-server/src/vite-env.d.ts
  packages/diagrams/backend/sirius-components-diagrams-layout-server/tsconfig.json
  packages/diagrams/backend/sirius-components-diagrams-layout-server/tsconfig.node.json
  packages/diagrams/backend/sirius-components-diagrams-layout-server/vite.config.ts
Labels: pr: to review soon, priority: high

#2005 [2004] Add an optional icon to select widget options
  CHANGELOG.adoc
  doc/screenshots/ShowIconOptionSelectWidget.jpg
  packages/compatibility/backend/sirius-components-compatibility-emf/src/main/java/org/eclipse/sirius/components/compatibility/emf/properties/MonoValuedNonContainmentReferenceIfDescriptionProvider.java
  packages/compatibility/backend/sirius-components-compatibility-emf/src/main/java/org/eclipse/sirius/components/compatibility/emf/properties/MultiValuedNonContainmentReferenceIfDescriptionProvider.java
  packages/compatibility/backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/forms/WidgetDescriptionConverter.java
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/services/ObjectService.java
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/formdescriptioneditors/components/MultiSelectStyleProvider.java
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/formdescriptioneditors/components/SelectStyleProvider.java
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/formdescriptioneditors/components/ViewFormDescriptionEditorConverterSwitch.java
  packages/forms/backend/sirius-components-collaborative-forms/src/main/resources/schema/form.graphqls
  packages/forms/backend/sirius-components-forms-graphql/pom.xml
  packages/forms/backend/sirius-components-forms-graphql/src/main/java/org/eclipse/sirius/components/forms/graphql/datafetchers/form/SelectOptionIconURLDataFetcher.java
  packages/forms/backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/MultiSelectStyle.java
  packages/forms/backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/SelectOption.java
  packages/forms/backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/SelectStyle.java
  packages/forms/backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/components/MultiSelectComponent.java
  packages/forms/backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/components/SelectComponent.java
  packages/forms/backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/description/MultiSelectDescription.java
  packages/forms/backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/description/SelectDescription.java
  packages/forms/frontend/sirius-components-forms/src/form/FormEventFragments.ts
  packages/forms/frontend/sirius-components-forms/src/form/FormEventFragments.types.ts
  packages/forms/frontend/sirius-components-forms/src/propertysections/MultiSelectPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/SelectPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/MultiSelectPropertySection.test.tsx.snap
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/SelectPropertySection.test.tsx.snap
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/ConditionalMultiSelectDescriptionStyleBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/ConditionalSelectDescriptionStyleBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/MultiSelectDescriptionStyleBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/SelectDescriptionStyleBuilder.java
  packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/ConditionalMultiSelectDescriptionStyleItemProvider.java
  packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/ConditionalSelectDescriptionStyleItemProvider.java
  packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/MultiSelectDescriptionStyleItemProvider.java
  packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/SelectDescriptionStyleItemProvider.java
  packages/view/backend/sirius-components-view-edit/src/main/resources/plugin.properties
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/NodeStylePropertiesConfigurer.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/form/MultiSelectStyleProvider.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/form/SelectStyleProvider.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/form/ViewFormDescriptionConverterSwitch.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/MultiSelectDescriptionStyle.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/SelectDescriptionStyle.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/ViewPackage.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/impl/ConditionalMultiSelectDescriptionStyleImpl.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/impl/ConditionalSelectDescriptionStyleImpl.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/impl/MultiSelectDescriptionStyleImpl.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/impl/SelectDescriptionStyleImpl.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/impl/ViewPackageImpl.java
  packages/view/backend/sirius-components-view/src/main/resources/model/view.ecore
  packages/view/backend/sirius-components-view/src/main/resources/model/view.genmodel
Labels: pr: to review later, priority: low

#2093 [2092] Fix support for help expressions on FlexboxContainer
  CHANGELOG.adoc
  packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/FormQueryService.java
  packages/forms/backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/components/FlexboxContainerComponent.java
Labels: pr: to review soon, priority: high

#2089 [2088] Fix initial value of the Tree Filter Bar
  CHANGELOG.adoc
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItem.tsx
Labels: pr: to review soon, priority: high

#2100 [fix] Prevent overflow to be displayed on form description editor
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FormDescriptionEditorRepresentation.tsx
Labels: pr: to review soon, priority: high

#2101 [cleanup] Remove auto-generated EMF icons
  packages/forms/backend/sirius-components-widget-reference-view-edit/src/main/java/org/eclipse/sirius/components/widgets/reference/provider/ReferenceWidgetDescriptionItemProvider.java
  packages/forms/backend/sirius-components-widget-reference-view-edit/src/main/resources/icons/full/ctool16/CreateFlexboxContainerDescription_children_ReferenceWidgetDescription.gif
  packages/forms/backend/sirius-components-widget-reference-view-edit/src/main/resources/icons/full/ctool16/CreateGroupDescription_widgets_ReferenceWidgetDescription.gif
  packages/forms/backend/sirius-components-widget-reference-view-edit/src/main/resources/icons/full/obj16/ReferenceWidgetDescription.gif
  packages/forms/backend/sirius-components-widget-reference-view/src/main/resources/model/reference.genmodel
Labels: pr: to review soon, priority: high

#2109 [fix] Properties from Diagram & Form ecore are also View properties
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/ViewPropertiesDescriptionRegistryConfigurer.java
Labels: pr: to review soon, priority: high

#2108 [fix] Fix Reference Widget child extender registration
  packages/forms/backend/sirius-components-widget-reference/pom.xml
  packages/forms/backend/sirius-components-widget-reference/src/main/java/org/eclipse/sirius/components/widget/reference/ReferenceEMFConfiguration.java
Labels: pr: to review soon, priority: high

#2119 [2115] Add label placement for checkbox
  CHANGELOG.adoc
  doc/screenshots/checkboxLabelPlacementAfter.png
  doc/screenshots/checkboxLabelPlacementBefore.png
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/formdescriptioneditors/components/CheckboxStyleProvider.java
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/CheckboxWidget.tsx
  packages/forms/backend/sirius-components-collaborative-forms/src/main/resources/schema/form.graphqls
  packages/forms/backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/CheckboxStyle.java
  packages/forms/frontend/sirius-components-forms/src/form/FormEventFragments.ts
  packages/forms/frontend/sirius-components-forms/src/form/FormEventFragments.types.ts
  packages/forms/frontend/sirius-components-forms/src/propertysections/CheckboxPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/CheckboxPropertySection.test.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/CheckboxPropertySection.test.tsx.snap
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/form/CheckboxStyleProvider.java
  packages/view/backend/sirius-components-view-form-edit/src/main/java/org/eclipse/sirius/components/view/form/provider/CheckboxDescriptionStyleItemProvider.java
  packages/view/backend/sirius-components-view-form-edit/src/main/java/org/eclipse/sirius/components/view/form/provider/ConditionalCheckboxDescriptionStyleItemProvider.java
  packages/view/backend/sirius-components-view-form-edit/src/main/resources/plugin.properties
  packages/view/backend/sirius-components-view-form/src/main/java/org/eclipse/sirius/components/view/form/CheckboxDescriptionStyle.java
  packages/view/backend/sirius-components-view-form/src/main/java/org/eclipse/sirius/components/view/form/FormPackage.java
  packages/view/backend/sirius-components-view-form/src/main/java/org/eclipse/sirius/components/view/form/LabelPlacement.java
  packages/view/backend/sirius-components-view-form/src/main/java/org/eclipse/sirius/components/view/form/impl/CheckboxDescriptionStyleImpl.java
  packages/view/backend/sirius-components-view-form/src/main/java/org/eclipse/sirius/components/view/form/impl/ConditionalCheckboxDescriptionStyleImpl.java
  packages/view/backend/sirius-components-view-form/src/main/java/org/eclipse/sirius/components/view/form/impl/FormFactoryImpl.java
  packages/view/backend/sirius-components-view-form/src/main/java/org/eclipse/sirius/components/view/form/impl/FormPackageImpl.java
  packages/view/backend/sirius-components-view-form/src/main/resources/model/form.ecore
  packages/view/backend/sirius-components-view-form/src/main/resources/model/form.genmodel
Labels: pr: to review later, priority: low

#2082 [doc] Contribute a shape for the container border style customization.
  CHANGELOG.adoc
  doc/iterations/2023.8/shapes/customize_containers_with_border.adoc
  doc/iterations/2023.8/shapes/images/customize_containers_with_border_01.png
  doc/iterations/2023.8/shapes/images/customize_containers_with_border_02.png
  doc/iterations/2023.8/shapes/images/customize_containers_with_border_03.png
Labels: pr: to review soon, priority: high

#2134 [2133] Fix NPE in Related Elements view
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/edit/related-elements-view.cy.js
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/relatedelements/DefaultRelatedElementsDescriptionProvider.java
Labels: pr: to review soon, priority: high

#2113 [2112] Fix the pages filtering in form editor
  CHANGELOG.adoc
  packages/forms/backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/components/FormComponent.java
  packages/forms/frontend/sirius-components-forms/src/form/Form.tsx
  packages/forms/frontend/sirius-components-forms/src/form/Form.types.ts
  packages/forms/frontend/sirius-components-forms/src/representations/FormRepresentation.tsx
Labels: pr: to review soon, priority: high

#2107 [2098] Enable vertical scrolling on the Reference widget's when showing more than a few values
  CHANGELOG.adoc
  packages/forms/frontend/sirius-components-widget-reference/src/ReferencePropertySection.tsx
Labels: pr: to review soon, priority: low

#2110 [enh] Make isViewElement test more generic
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/ViewPropertiesDescriptionRegistryConfigurer.java
Labels: pr: to review later, priority: low
