Repository eclipse-sirius/sirius-web, pull requests merged in 2023-02, with the labels that each got.

#1609 [doc] Add ADR about layout improvement
  CHANGELOG.adoc
  doc/adrs/090_improve_support_for_compartment.adoc
  doc/adrs/images/090/090_children_laid_out_data_delta_position.png
  doc/adrs/images/090/090_layout_children_area.png
  doc/adrs/images/090/090_node_division.png
  doc/adrs/images/090/090_node_height_children_aware.png
  doc/adrs/images/090/090_node_height_excluding_children.png
  doc/adrs/images/090/090_node_with_compartments.png
Labels: pr: to review soon, priority: high

#1641 [doc] Add ADR about the support for node expand/collapse
  CHANGELOG.adoc
  doc/adrs/091_add_support_for_compartment_expand-collapse.adoc
Labels: pr: to review later, priority: low

#1610 [1522] Make node with header resizable
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/sprotty/convertDiagram.tsx
Labels: pr: to review later, priority: low

#1659 [fix] Add a SuccessPayload to replace most basic payloads
  CHANGELOG.adoc
  packages/core/frontend/sirius-components/src/modals/new-document/NewDocumentModal.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/representation/operations.ts
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FlexboxContainerWidget.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FormDescriptionEditorEventFragment.types.ts
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FormDescriptionEditorRepresentation.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/Group.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/ToolbarActionWidget.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/ToolbarActions.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/WidgetEntry.tsx
Labels: pr: to review soon, priority: low

#1655 [1563] Add the missing default tools to the Studio template
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/configuration/StudioProjectTemplatesInitializer.java
Labels: pr: to review soon, priority: high

#1619 [1615] Remove the unused DiagramDescription.getTools()
  CHANGELOG.adoc
  packages/compatibility/backend/sirius-components-compatibility-emf/src/test/java/org/eclipse/sirius/components/compatibility/emf/compatibility/operations/CreateViewOperationHandlerTests.java
  packages/compatibility/backend/sirius-components-compatibility-emf/src/test/java/org/eclipse/sirius/components/compatibility/emf/compatibility/operations/DeleteViewOperationHandlerTests.java
  packages/compatibility/backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/services/diagrams/DiagramDescriptionNodeAndEdgeDescriptionsPopulator.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/test/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/CreateDiagramEventHandlerTests.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/test/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/GetConnectorToolsEventHandlerTests.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/services/DefaultTestDiagramDescriptionProvider.java
  packages/diagrams/backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/TestDiagramDescriptionBuilder.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/description/DiagramDescription.java
  packages/diagrams/backend/sirius-components-diagrams/src/test/java/org/eclipse/sirius/components/diagrams/renderer/DiagramElementChangeVisibilityTests.java
  packages/diagrams/backend/sirius-components-diagrams/src/test/java/org/eclipse/sirius/components/diagrams/renderer/DiagramRendererEdgeTests.java
  packages/diagrams/backend/sirius-components-diagrams/src/test/java/org/eclipse/sirius/components/diagrams/renderer/DiagramRendererNodeTests.java
  packages/diagrams/backend/sirius-components-diagrams/src/test/java/org/eclipse/sirius/components/diagrams/renderer/UnsynchronizedDiagramTests.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewDiagramDescriptionConverter.java
Labels: pr: to review later, priority: low

#1589 [1588] Deactivate link with editor
  CHANGELOG.adoc
  integration-tests/cypress/integration/project/edit/explorer-toolbar_spec.js
  integration-tests/cypress/integration/project/edit/project-context-menu_spec.js
  packages/core/frontend/sirius-components/src/index.ts
  packages/sirius-web/frontend/sirius-web/src/views/edit-project/EditProjectNavbar/EditProjectNavbar.tsx
  packages/trees/frontend/sirius-components-trees/src/common/sendFile.ts
  packages/trees/frontend/sirius-components-trees/src/core/file-upload/FileUpload.tsx
  packages/trees/frontend/sirius-components-trees/src/core/file-upload/FileUpload.types.ts
  packages/trees/frontend/sirius-components-trees/src/modals/new-document/NewDocumentModal.tsx
  packages/trees/frontend/sirius-components-trees/src/modals/new-document/NewDocumentModal.types.ts
  packages/trees/frontend/sirius-components-trees/src/modals/new-document/NewDocumentModalMachine.ts
  packages/trees/frontend/sirius-components-trees/src/modals/upload-document/UploadDocumentModal.tsx
  packages/trees/frontend/sirius-components-trees/src/modals/upload-document/UploadDocumentModal.types.ts
  packages/trees/frontend/sirius-components-trees/src/modals/upload-document/UploadDocumentModalMachine.ts
  packages/trees/frontend/sirius-components-trees/src/toolbar/TreeToolBar.tsx
  packages/trees/frontend/sirius-components-trees/src/toolbar/TreeToolBar.types.ts
  packages/trees/frontend/sirius-components-trees/src/views/ExplorerView.tsx
  packages/trees/frontend/sirius-components-trees/src/views/ExplorerViewMachine.ts
Labels: pr: to review later, priority: low

#1687 [1686] Fix SVG export of the wrapped labels
  CHANGELOG.adoc
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/export/api/IImageRegistry.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/export/svg/DiagramElementExportService.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/export/svg/EdgeExportService.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/export/svg/NodeExportService.java
  packages/web/backend/sirius-components-web/src/main/java/org/eclipse/sirius/components/web/images/ImageRegistry.java
Labels: pr: to review soon, priority: high

#1693 [1692] Add support for images with .jpg extension (in addition to .jpeg)
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-spring/src/main/java/org/eclipse/sirius/web/spring/controllers/ImagesController.java
Labels: pr: to review later, priority: low

#1704 [1583] Use a (much) smaller buffer to avoid performance issues
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/TextBoundsProvider.java
Labels: pr: to review soon, priority: high

#1742 [1741] Fix ELK border node placement not taken into account anymore
  CHANGELOG.adoc
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/ELKDiagramConverter.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/ELKLayoutedDiagramProvider.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/ELKPropertiesService.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/IncrementalLayoutDiagramConverter.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/incremental/BorderNodePositionTests.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/services/DiagramConverterTests.java
Labels: pr: to review soon, priority: high

#1750 [1720] Fix drop position handling
  CHANGELOG.adoc
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/ImageIncrementalLayoutEngine.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/ParametricSVGIncrementalLayoutEngine.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/RectangleIncrementalLayoutEngine.java
Labels: pr: to review soon, priority: high

#1754 [doc] Mention the APIs needed to create project templates in the CHANGELOG
  CHANGELOG.adoc
Labels: pr: to review soon, priority: high

#1696 [1695] Add a precondition expression on node descriptions in view DSL
  CHANGELOG.adoc
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/DiagramComponent.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/DiagramComponentProps.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/NodeComponent.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/description/NodeDescription.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/events/IDiagramEvent.java
  packages/tests/backend/sirius-components-tests/src/test/java/org/eclipse/sirius/components/tests/GeneralPurposeTests.java
  packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/DiagramElementDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/EdgeDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-edit/src/main/resources/plugin.properties
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewDiagramDescriptionConverter.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/DiagramElementDescription.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/EdgeDescription.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/ViewPackage.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/impl/BarChartDescriptionImpl.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/impl/CheckboxDescriptionImpl.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/impl/DiagramElementDescriptionImpl.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/impl/EdgeDescriptionImpl.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/impl/MultiSelectDescriptionImpl.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/impl/PieChartDescriptionImpl.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/impl/TextAreaDescriptionImpl.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/impl/TextfieldDescriptionImpl.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/impl/ViewPackageImpl.java
  packages/view/backend/sirius-components-view/src/main/resources/model/view.ecore
  packages/view/backend/sirius-components-view/src/main/resources/model/view.genmodel
Labels: pr: to review soon, priority: high

#1735 [releng] Disable Maven debug output during the build
  .github/workflows/build.yml
Labels: pr: to review later, priority: low

#1743 [1674] Fix fade/hide tools are available on the diagram background
  CHANGELOG.adoc
  integration-tests/cypress/integration/project/edit/diagram-contextual-palette_spec.js
  packages/diagrams/frontend/sirius-components-diagrams/src/palette/ContextualPalette.tsx
Labels: pr: to review soon, priority: high

#1731 [1710] Fix edit box of empty edge label is located at the wrong position
  CHANGELOG.adoc
  integration-tests/cypress/integration/project/edit/studio_spec.js
  integration-tests/cypress/support/serverCommands.js
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/ELKDiagramConverter.java
Labels: pr: to review soon, priority: high

#1705 [1643] Remove the dependency from Sirius Web to Spring security
  CHANGELOG.adoc
  integration-tests/cypress/support/serverCommands.js
  packages/sirius-web/backend/sirius-web-graphql-schema/src/main/java/org/eclipse/sirius/web/graphql/schema/ProjectTypeProvider.java
  packages/sirius-web/backend/sirius-web-graphql/src/main/resources/schema/siriusweb.graphqls
  packages/sirius-web/backend/sirius-web-persistence/src/main/java/org/eclipse/sirius/web/persistence/entities/AccessLevelEntity.java
  packages/sirius-web/backend/sirius-web-persistence/src/main/java/org/eclipse/sirius/web/persistence/entities/AccountEntity.java
  packages/sirius-web/backend/sirius-web-persistence/src/main/java/org/eclipse/sirius/web/persistence/entities/ProjectEntity.java
  packages/sirius-web/backend/sirius-web-persistence/src/main/java/org/eclipse/sirius/web/persistence/entities/VisibilityEntity.java
  packages/sirius-web/backend/sirius-web-persistence/src/main/java/org/eclipse/sirius/web/persistence/repositories/IAccountRepository.java
  packages/sirius-web/backend/sirius-web-persistence/src/main/java/org/eclipse/sirius/web/persistence/repositories/IProjectRepository.java
  packages/sirius-web/backend/sirius-web-persistence/src/main/java/org/eclipse/sirius/web/persistence/util/AccessLevelEnumType.java
  packages/sirius-web/backend/sirius-web-persistence/src/main/java/org/eclipse/sirius/web/persistence/util/VisibilityEnumType.java
  packages/sirius-web/backend/sirius-web-persistence/src/main/resources/db/changelog/sirius-web-schema.sql
  packages/sirius-web/backend/sirius-web-persistence/src/main/resources/db/sirius-web-named-queries.properties
  packages/sirius-web/backend/sirius-web-persistence/src/test/java/org/eclipse/sirius/web/persistence/repositories/AccountRepositoryIntegrationTests.java
  packages/sirius-web/backend/sirius-web-persistence/src/test/java/org/eclipse/sirius/web/persistence/repositories/DocumentRepositoryIntegrationTests.java
  packages/sirius-web/backend/sirius-web-persistence/src/test/java/org/eclipse/sirius/web/persistence/repositories/ProjectRepositoryIntegrationTests.java
  packages/sirius-web/backend/sirius-web-persistence/src/test/java/org/eclipse/sirius/web/persistence/repositories/RepresentationRepositoryIntegrationTests.java
  packages/sirius-web/backend/sirius-web-sample-application/pom.xml
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/configuration/GraphQLWebSocketConfiguration.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/configuration/SpringWebSecurityConfiguration.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/services/ProjectAccessPolicy.java
  packages/sirius-web/backend/sirius-web-services-api/src/main/java/org/eclipse/sirius/web/services/api/projects/AccessLevel.java
  packages/sirius-web/backend/sirius-web-services-api/src/main/java/org/eclipse/sirius/web/services/api/projects/CreateProjectInput.java
  packages/sirius-web/backend/sirius-web-services-api/src/main/java/org/eclipse/sirius/web/services/api/projects/IProjectAccessPolicy.java
  packages/sirius-web/backend/sirius-web-services-api/src/main/java/org/eclipse/sirius/web/services/api/projects/Project.java
  packages/sirius-web/backend/sirius-web-services-api/src/main/java/org/eclipse/sirius/web/services/api/projects/Visibility.java
  packages/sirius-web/backend/sirius-web-services/pom.xml
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/documents/DocumentMapper.java
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/editingcontext/EditingContextSearchService.java
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/projects/ProjectImportService.java
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/projects/ProjectMapper.java
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/projects/ProjectService.java
  packages/sirius-web/backend/sirius-web-services/src/test/java/org/eclipse/sirius/web/services/documents/CreateDocumentEventHandlerTests.java
  packages/sirius-web/backend/sirius-web-services/src/test/java/org/eclipse/sirius/web/services/documents/DeleteDocumentEventHandlerTests.java
  packages/sirius-web/backend/sirius-web-services/src/test/java/org/eclipse/sirius/web/services/documents/RenameDocumentEventHandlerTests.java
  packages/sirius-web/backend/sirius-web-services/src/test/java/org/eclipse/sirius/web/services/documents/UploadDocumentEventHandlerTests.java
  packages/sirius-web/backend/sirius-web-services/src/test/java/org/eclipse/sirius/web/services/editingcontext/EditingContextPersistenceServiceTests.java
  packages/sirius-web/backend/sirius-web-services/src/test/java/org/eclipse/sirius/web/services/editingcontext/NoOpProjectRepository.java
  packages/sirius-web/backend/sirius-web-services/src/test/java/org/eclipse/sirius/web/services/projects/NoOpAccountRepository.java
  packages/sirius-web/backend/sirius-web-services/src/test/java/org/eclipse/sirius/web/services/projects/NoOpProjectRepository.java
  packages/sirius-web/backend/sirius-web-services/src/test/java/org/eclipse/sirius/web/services/projects/ProjectServiceTests.java
  packages/sirius-web/backend/sirius-web-services/src/test/java/org/eclipse/sirius/web/services/projects/RenameProjectEventHandlerTests.java
  packages/sirius-web/backend/sirius-web-spring/src/test/java/org/eclipse/sirius/web/spring/controllers/DocumentControllerTests.java
  packages/sirius-web/backend/sirius-web-spring/src/test/java/org/eclipse/sirius/web/spring/controllers/ProjectControllerTests.java
  packages/sirius-web/frontend/sirius-web/src/views/new-project/NewProjectView.tsx
  packages/sirius-web/frontend/sirius-web/src/views/projects/ProjectsView.tsx
  vscode-extension/src/data/ProjectData.ts
  vscode-extension/src/data/ServerData.ts
  vscode-extension/src/viewsContainer/views/projectsView.ts
Labels: pr: to review soon, priority: high

#1756 [1591] Objects may be created using multiple strategies which can cre…
  CHANGELOG.adoc
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/services/EditService.java
Labels: pr: to review soon, priority: low

#1747 [1746] Rich-text toolbar items on forms are not grayed when read-only
  CHANGELOG.adoc
  packages/core/frontend/sirius-components/package.json
  packages/forms/frontend/sirius-components-forms/src/richtexteditor/ToolbarPlugin.tsx
Labels: pr: to review later, priority: low

#1640 [1639] Support schemaLocation and extendedMetaData for JSON resource
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/editingcontext/EditingContextPersistenceService.java
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/editingcontext/EditingContextSearchService.java
Labels: pr: to review later, priority: low
