Repository eclipse-sirius/sirius-web, pull requests merged in 2023-03, with the labels that each got.

#1779 [1675] Align tree items without children with their siblings
  CHANGELOG.adoc
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItemArrow.tsx
Labels: pr: to review later, priority: low

#1782 [619] Fix order of the models in the explorer
  CHANGELOG.adoc
  integration-tests/cypress/integration/project/edit/explorer_spec.js
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/explorer/ExplorerDescriptionProvider.java
  packages/trees/frontend/sirius-components-trees/src/trees/Tree.tsx
Labels: pr: to review later, priority: low

#1764 [1632] Start documenting the variables available for all the operations
  CHANGELOG.adoc
  doc/adrs/087_provide_the_variables_available_for_each_operation.adoc
  doc/reference/variables.adoc
  packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/api/variables/CommonVariables.java
  packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/api/variables/IOperationProvider.java
  packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/api/variables/IVariableProvider.java
  packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/api/variables/Operation.java
  packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/api/variables/Variable.java
  packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/services/OperationValidator.java
  packages/core/backend/sirius-components-representations/src/main/java/org/eclipse/sirius/components/representations/IOperationValidator.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/DiagramCreationService.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/variables/DiagramOperationProvider.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/variables/DiagramVariableProvider.java
  packages/diagrams/backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/services/TestDiagramCreationService.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/DiagramComponent.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/DiagramComponentProps.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/EdgeComponent.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/EdgeComponentProps.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/NodeComponent.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/NodeComponentProps.java
  packages/diagrams/backend/sirius-components-diagrams/src/test/java/org/eclipse/sirius/components/diagrams/renderer/DiagramElementChangeVisibilityTests.java
  packages/diagrams/backend/sirius-components-diagrams/src/test/java/org/eclipse/sirius/components/diagrams/renderer/DiagramRendererEdgeTests.java
  packages/diagrams/backend/sirius-components-diagrams/src/test/java/org/eclipse/sirius/components/diagrams/renderer/DiagramRendererNodeTests.java
  packages/diagrams/backend/sirius-components-diagrams/src/test/java/org/eclipse/sirius/components/diagrams/renderer/UnsynchronizedDiagramTests.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/services/VariableDocumentationGenerator.java
  packages/view/backend/sirius-components-view-emf/src/test/java/org/eclipse/sirius/components/view/emf/view/DynamicDiagramsTests.java
Labels: pr: to review soon, priority: low

#1772 [1604] Fix Fade does not work on border nodes
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/sprotty/__tests__/borderNodes.test.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/sprotty/__tests__/siriusWebDiagram.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/sprotty/convertDiagram.tsx
Labels: pr: to review later, priority: low

#1774 [1773] Fix editors area tab title may hide close button
  CHANGELOG.adoc
  packages/core/frontend/sirius-components-core/src/workbench/RepresentationNavigation.tsx
Labels: pr: to review later, priority: low

#1767 [1541] Editors area can overflow on Details view
  CHANGELOG.adoc
  packages/core/frontend/sirius-components-core/src/workbench/Site.tsx
  packages/core/frontend/sirius-components-core/src/workbench/Workbench.tsx
Labels: pr: to review later, priority: low

#1823 [1761] Remove leftover reference to sirius-web-graphql-schema
  packages/releng/backend/sirius-components-test-coverage/pom.xml
Labels: pr: to review soon, priority: high

#1826 [1825] Distinguish the containment kind of view creation requests
  CHANGELOG.adoc
  doc/adrs/096_distinguish_the_containment_kind_of_view_creation_requests.adoc
  packages/compatibility/backend/sirius-components-compatibility-emf/src/main/java/org/eclipse/sirius/components/compatibility/emf/modeloperations/CreateViewOperationHandler.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/ViewCreationRequest.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/NodeComponent.java
  packages/diagrams/backend/sirius-components-diagrams/src/test/java/org/eclipse/sirius/components/diagrams/renderer/UnsynchronizedDiagramTests.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/services/PapayaService.java
  packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/CreateViewItemProvider.java
  packages/view/backend/sirius-components-view-edit/src/main/resources/plugin.properties
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/DiagramOperationInterpreterViewSwitch.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/CreateView.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/NodeContainmentKind.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/ViewPackage.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/impl/CreateViewImpl.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/impl/ViewFactoryImpl.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/impl/ViewPackageImpl.java
  packages/view/backend/sirius-components-view/src/main/resources/model/view.ecore
  packages/view/backend/sirius-components-view/src/main/resources/model/view.genmodel
Labels: pr: to review soon, priority: high

#1777 [enh] Add a template for Papaya Studio
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/PapayaStudioTemplateProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/PapayaStudioTemplatesInitializer.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/resources/images/Papaya-Template.svg
Labels: pr: to review later, priority: low

#1781 [releng] Upgrade lexical from 0.6.0 to 0.8.1
  CHANGELOG.adoc
  package-lock.json
  packages/forms/frontend/sirius-components-forms/package.json
  packages/forms/frontend/sirius-components-forms/src/richtexteditor/ListPlugin.tsx
  packages/forms/frontend/sirius-components-forms/src/richtexteditor/RichTextEditor.tsx
  packages/forms/frontend/sirius-components-forms/src/richtexteditor/ToolbarPlugin.tsx
Labels: pr: to review later, priority: low

#1709 [1708] Fix move a toolbar action from a group to another
  CHANGELOG.adoc
  integration-tests/cypress/integration/project/edit/formdescriptioneditor_spec.js
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/ToolbarActions.tsx
Labels: pr: to review soon, priority: high

#1834 [releng] Improve the continuous deployment of Sirius Web
  .github/workflows/build.yml
Labels: pr: to review soon, priority: high

#1749 [1748] Underline and strike-through not taken into account for BarCharts
  CHANGELOG.adoc
  packages/charts/frontend/sirius-components-charts/src/bar/BarChart.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/ChartWidgetPropertySection.test.tsx.snap
Labels: pr: to review later, priority: low

#1832 [1527] Add the new layout data structure
  CHANGELOG.adoc
  packages/diagrams/backend/sirius-components-diagrams-graphql/src/main/java/org/eclipse/sirius/components/diagrams/graphql/datafetchers/diagram/DiagramEdgesDataFetcher.java
  packages/diagrams/backend/sirius-components-diagrams-graphql/src/main/java/org/eclipse/sirius/components/diagrams/graphql/datafetchers/diagram/DiagramNodesDataFetcher.java
  packages/diagrams/backend/sirius-components-diagrams-graphql/src/main/java/org/eclipse/sirius/components/diagrams/graphql/datafetchers/diagram/EdgeRoutingPointsDataFetcher.java
  packages/diagrams/backend/sirius-components-diagrams-graphql/src/main/java/org/eclipse/sirius/components/diagrams/graphql/datafetchers/diagram/EdgeSourceAnchorRelativePositionDataFetcher.java
  packages/diagrams/backend/sirius-components-diagrams-graphql/src/main/java/org/eclipse/sirius/components/diagrams/graphql/datafetchers/diagram/EdgeTargetAnchorRelativePositionDataFetcher.java
  packages/diagrams/backend/sirius-components-diagrams-graphql/src/main/java/org/eclipse/sirius/components/diagrams/graphql/datafetchers/diagram/LabelAlignmentDataFetcher.java
  packages/diagrams/backend/sirius-components-diagrams-graphql/src/main/java/org/eclipse/sirius/components/diagrams/graphql/datafetchers/diagram/LabelPositionDataFetcher.java
  packages/diagrams/backend/sirius-components-diagrams-graphql/src/main/java/org/eclipse/sirius/components/diagrams/graphql/datafetchers/diagram/LabelSizeDataFetcher.java
  packages/diagrams/backend/sirius-components-diagrams-graphql/src/main/java/org/eclipse/sirius/components/diagrams/graphql/datafetchers/diagram/NodeBorderNodesDataFetcher.java
  packages/diagrams/backend/sirius-components-diagrams-graphql/src/main/java/org/eclipse/sirius/components/diagrams/graphql/datafetchers/diagram/NodeChildNodesDataFetcher.java
  packages/diagrams/backend/sirius-components-diagrams-graphql/src/main/java/org/eclipse/sirius/components/diagrams/graphql/datafetchers/diagram/NodePositionDataFetcher.java
  packages/diagrams/backend/sirius-components-diagrams-graphql/src/main/java/org/eclipse/sirius/components/diagrams/graphql/datafetchers/diagram/NodeSizeDataFetcher.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/Diagram.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/layoutdata/DiagramLayoutData.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/layoutdata/EdgeLayoutData.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/layoutdata/LabelLayoutData.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/layoutdata/NodeLayoutData.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/layoutdata/Position.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/layoutdata/Ratio.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/layoutdata/Size.java
Labels: pr: to review soon, priority: high

#1766 [1688] Details View tab title can be displayed on many lines
  CHANGELOG.adoc
  packages/forms/frontend/sirius-components-forms/src/form/Form.tsx
Labels: pr: to review later, priority: low

#1706 [1602] The connector tool does not work with descriptions from the View DSL
  CHANGELOG.adoc
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ConnectorToolsProviderDiagram.java
Labels: pr: to review soon, priority: high

#1837 [doc] Update the README
  README.adoc
  doc/images/ProjectEditor.png
Labels: pr: to review soon, priority: low

#1843 [1667] Make the contextual palette self contained
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/palette/ContextualPalette.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/palette/ContextualPalette.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/representation/DiagramRepresentation.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/representation/DiagramRepresentation.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/representation/DiagramRepresentationMachine.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/representation/operations.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/toolbar/Toolbar.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/toolbar/Toolbar.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/toolbar/ToolbarMachine.ts
Labels: pr: to review later, priority: low

#1827 [840] Add the ability to create multiple nested views at once
  CHANGELOG.adoc
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/NodeComponent.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/NodeIdProvider.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/DiagramOperationInterpreterViewSwitch.java
Labels: pr: to review soon, priority: high

#1776 [1775] Handle representation/document with a name length > 50 characters
  CHANGELOG.adoc
  packages/core/frontend/sirius-components/src/modals/rename-project/RenameProjectModalMachine.ts
  packages/forms/frontend/sirius-components-forms/src/propertysections/ListPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/ListPropertySection.test.tsx.snap
  packages/sirius-web/backend/sirius-web-persistence/src/main/resources/db/changelog/sirius-web-schema.sql
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/projects/ProjectService.java
  packages/sirius-web/frontend/sirius-web/src/views/edit-project/EditProjectNavbar/EditProjectNavbar.tsx
  packages/sirius-web/frontend/sirius-web/src/views/new-project/NewProjectViewMachine.ts
  packages/sirius-web/frontend/sirius-web/src/views/projects/ProjectsView.tsx
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItem.tsx
  scripts/restart-postgresql.sh
Labels: pr: to review later, priority: low

#1850 [1667] Fix toolbar's zoomLevel value when diagram has been deleted
  packages/diagrams/frontend/sirius-components-diagrams/src/representation/DiagramRepresentationMachine.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/toolbar/ToolbarMachine.ts
Labels: pr: to review later, priority: low

#1849 [1829] Fix view DSL's node description cannot reference outside concepts
  CHANGELOG.adoc
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/DiagramCreationService.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/GetToolSectionsEventHandler.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/resources/schema/diagram.graphqls
  packages/diagrams/backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/services/TestDiagramCreationService.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/DiagramComponent.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/DiagramComponentProps.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/NodeDescriptionRequestor.java
  packages/diagrams/backend/sirius-components-diagrams/src/test/java/org/eclipse/sirius/components/diagrams/renderer/DiagramElementChangeVisibilityTests.java
  packages/diagrams/backend/sirius-components-diagrams/src/test/java/org/eclipse/sirius/components/diagrams/renderer/DiagramRendererEdgeTests.java
  packages/diagrams/backend/sirius-components-diagrams/src/test/java/org/eclipse/sirius/components/diagrams/renderer/DiagramRendererNodeTests.java
  packages/diagrams/backend/sirius-components-diagrams/src/test/java/org/eclipse/sirius/components/diagrams/renderer/UnsynchronizedDiagramTests.java
  packages/diagrams/frontend/sirius-components-diagrams/src/palette/ContextualPalette.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/palette/ContextualPaletteMachine.ts
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/representations/DynamicRepresentationDescriptionService.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/IRepresentationDescriptionConverter.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/IViewConverter.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/ViewConverter.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewDiagramDescriptionConverter.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/form/ViewFormDescriptionConverter.java
  packages/view/backend/sirius-components-view-emf/src/test/java/org/eclipse/sirius/components/view/emf/view/DynamicDiagramsTests.java
  packages/view/backend/sirius-components-view-emf/src/test/java/org/eclipse/sirius/components/view/emf/view/DynamicFormsTests.java
Labels: pr: to review later, priority: low

#1871 [releng] Update package-lock.json
  package-lock.json
Labels: pr: to review later, priority: low

#1873 [1851] Fix an issue where the explorer could be expanded while not synchronized
  CHANGELOG.adoc
  integration-tests/cypress/integration/project/edit/explorer-toolbar_spec.js
  packages/trees/frontend/sirius-components-trees/src/toolbar/TreeToolBar.tsx
  packages/trees/frontend/sirius-components-trees/src/views/ExplorerView.tsx
  packages/trees/frontend/sirius-components-trees/src/views/ExplorerViewMachine.ts
Labels: pr: to review soon, priority: high

#1859 [1858] Improve project template cards layout
  CHANGELOG.adoc
  packages/sirius-web/frontend/sirius-web/src/views/project-template-card/ProjectTemplateCard.tsx
  packages/sirius-web/frontend/sirius-web/src/views/projects/ProjectsView.tsx
Labels: pr: to review later, priority: low

#1878 [cleanup] Check the presence of javadoc on type
  packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/incremental/ChildrenAreaLayoutContext.java
  packages/releng/backend/sirius-components-resources/checkstyle/CheckstyleConfiguration.xml
Labels: pr: to review soon, priority: high

#1855 [1785] Fix name collision on labelFields GraphQL fragment
  CHANGELOG.adoc
  packages/forms/frontend/sirius-components-forms/src/form/FormEventFragments.ts
Labels: pr: to review later, priority: low

#1881 [1879] Update our ArchUnit tests to allow builders in records
  CHANGELOG.adoc
  packages/core/backend/sirius-components-annotations/src/main/java/org/eclipse/sirius/components/annotations/Builder.java
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/EditingContextEventProcessor.java
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/EditingContextEventProcessorParameters.java
  packages/tests/backend/sirius-components-tests/src/main/java/org/eclipse/sirius/components/tests/architecture/AbstractCodingRulesTests.java
Labels: pr: to review soon, priority: low

#1882 [fix] Remove duplicated widget in FormDescriptionEditor
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FormDescriptionEditorRepresentation.tsx
Labels: pr: to review later, priority: low

#1887 [doc] Add some documentation on Sirius Web
  CONTRIBUTING
  doc/reference/01_overview.adoc
  doc/reference/02_backend.adoc
  doc/reference/images/relations.png
  doc/reference/images/topics.png
Labels: pr: to review soon, priority: low
