Repository eclipse-sirius/sirius-web, pull requests merged in 2023-09, with the labels that each got.

#2326 [2198] Add a default Color Palette on View creation
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/configuration/StereotypeDescriptionRegistryConfigurer.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/services/EditingContextActionHandler.java
Labels: pr: to review soon, priority: high

#2327 [2228] Creating a domain from the onboard area now initialize its name
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/services/EditingContextActionHandler.java
Labels: pr: to review soon, priority: low

#2321 [2118] Add a modal to create new objects on a widget reference
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/edit/widget-reference.cy.js
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/dto/EditingContextChildObjectCreationDescriptionsInput.java
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/dto/EditingContextRootObjectCreationDescriptionsInput.java
  packages/core/backend/sirius-components-collaborative/src/main/resources/schema/core.graphqls
  packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/URLParser.java
  packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/api/IEditService.java
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/handlers/EditingContextChildObjectCreationDescriptionsEventHandler.java
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/handlers/EditingContextRootObjectCreationDescriptionsEventHandler.java
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/services/EditService.java
  packages/forms/backend/sirius-components-widget-reference/src/main/java/org/eclipse/sirius/components/widget/reference/Reference.java
  packages/forms/backend/sirius-components-widget-reference/src/main/java/org/eclipse/sirius/components/widget/reference/browser/ModelBrowserTreePathProvider.java
  packages/forms/backend/sirius-components-widget-reference/src/main/java/org/eclipse/sirius/components/widget/reference/browser/ModelBrowsersDescriptionProvider.java
  packages/forms/backend/sirius-components-widget-reference/src/main/java/org/eclipse/sirius/components/widget/reference/datafetchers/ReferenceWidgetReferenceDataFetcher.java
  packages/forms/backend/sirius-components-widget-reference/src/main/resources/schema/reference.graphqls
  packages/forms/frontend/sirius-components-widget-reference/src/ReferencePropertySection.tsx
  packages/forms/frontend/sirius-components-widget-reference/src/ReferenceWidgetFragment.types.ts
  packages/forms/frontend/sirius-components-widget-reference/src/components/ModelBrowserTreeView.tsx
  packages/forms/frontend/sirius-components-widget-reference/src/components/ModelBrowserTreeView.types.ts
  packages/forms/frontend/sirius-components-widget-reference/src/components/ValuedReferenceAutocomplete.tsx
  packages/forms/frontend/sirius-components-widget-reference/src/components/ValuedReferenceAutocomplete.types.ts
  packages/forms/frontend/sirius-components-widget-reference/src/modals/BrowseModal.tsx
  packages/forms/frontend/sirius-components-widget-reference/src/modals/CreateModal.tsx
  packages/forms/frontend/sirius-components-widget-reference/src/modals/CreateModal.types.ts
  packages/forms/frontend/sirius-components-widget-reference/src/modals/CreateModalMachine.ts
  packages/forms/frontend/sirius-components-widget-reference/src/modals/TransferModal.tsx
  packages/sirius-web/backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/editingcontext/EditingContextChildCreationDescriptionsDataFetcher.java
  packages/sirius-web/backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/editingcontext/EditingContextRootObjectCreationDescriptionsDataFetcher.java
  packages/sirius-web/frontend/sirius-web/src/index.tsx
  packages/sirius-web/frontend/sirius-web/src/modals/new-object/NewObjectModal.types.ts
  packages/sirius-web/frontend/sirius-web/src/modals/new-root-object/NewRootObjectModal.types.ts
Labels: pr: to review later, priority: low

#2293 [doc] Contribute a shape to add sections for tool in the view DSL
  CHANGELOG.adoc
  doc/iterations/2023.10/shapes/add_tool_sections_in_view_dsl.adoc
  doc/iterations/2023.10/shapes/images/add_tool_sections_in_view_dsl_01.png
Labels: pr: to review later, priority: low

#2284 [doc] Contribute a shape for precondition support for tools.
  CHANGELOG.adoc
  doc/iterations/2023.10/shapes/add_precondition_on_tool.adoc
  doc/iterations/2023.10/shapes/images/add_precondition_on_tool_01.png
Labels: pr: to review later, priority: low

#2334 [2333] Add a key on toolSection in palette
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/Palette.tsx
Labels: pr: to review later, priority: low

#2322 Add support for For/If in FormDescriptionEditor
  integration-tests/cypress/e2e/project/edit/formdescriptioneditor.cy.js
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/AddWidgetEventHandler.java
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/MoveWidgetEventHandler.java
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/main/resources/schema/formdescriptioneditor.graphqls
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/formdescriptioneditors/FormDescriptionEditorFor.java
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/formdescriptioneditors/FormDescriptionEditorIf.java
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/formdescriptioneditors/components/FormDescriptionEditorComponent.java
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/formdescriptioneditors/components/FormDescriptionEditorComponentProps.java
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/formdescriptioneditors/components/FormDescriptionEditorFlexboxContainerComponent.java
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/formdescriptioneditors/components/FormDescriptionEditorFlexboxContainerComponentProps.java
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/formdescriptioneditors/components/FormDescriptionEditorForComponent.java
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/formdescriptioneditors/components/FormDescriptionEditorForComponentProps.java
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/formdescriptioneditors/components/FormDescriptionEditorGroupComponent.java
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/formdescriptioneditors/components/FormDescriptionEditorGroupComponentProps.java
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/formdescriptioneditors/components/FormDescriptionEditorIfComponent.java
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/formdescriptioneditors/components/FormDescriptionEditorIfComponentProps.java
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/formdescriptioneditors/components/FormDescriptionEditorWidgetComponent.java
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/formdescriptioneditors/components/FormDescriptionEditorWidgetComponentProps.java
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/formdescriptioneditors/components/ViewFormDescriptionEditorConverterSwitch.java
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/formdescriptioneditors/description/FormDescriptionEditorForDescription.java
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/formdescriptioneditors/description/FormDescriptionEditorIfDescription.java
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/formdescriptioneditors/elements/FormDescriptionEditorForElementProps.java
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/formdescriptioneditors/elements/FormDescriptionEditorIfElementProps.java
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/formdescriptioneditors/renderer/FormDescriptionEditorComponentPropsValidator.java
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/formdescriptioneditors/renderer/FormDescriptionEditorElementFactory.java
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/formdescriptioneditors/renderer/FormDescriptionEditorInstancePropsValidator.java
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FlexboxContainerWidget.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FormDescriptionEditorEventFragment.ts
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FormDescriptionEditorRepresentation.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FormDescriptionEditorRepresentation.types.ts
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/WidgetEntry.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/WidgetOperations.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/icons/ForIcon.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/icons/IfIcon.tsx
  packages/forms/frontend/sirius-components-forms/src/form/FormEventFragments.types.ts
Labels: pr: to review later, priority: low

#2346 [2345] Fix an issue when opening a palette on React Flow
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/Palette.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/tool-section/ToolSection.tsx
Labels: pr: to review later, priority: low

#2338 [2192] Add an error message for missing Shape of ImageNodeStyle
  CHANGELOG.adoc
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/DiagramDescriptionValidator.java
Labels: pr: to review soon, priority: high

#2319 [2314] Add feedback on edge selection on react-flow diagrams
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/converter/convertDiagram.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramRenderer.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramRenderer.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/edge/MarkerDefinitions.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/edge/MarkerDefinitions.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/edge/MultiLabelEdge.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/edge/MultiLabelEdge.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/representation/DiagramRepresentation.tsx
Labels: pr: to review soon, priority: high

#2351 [2350] Reduce default tab width to fit page label length
  CHANGELOG.adoc
  packages/forms/frontend/sirius-components-forms/src/form/Form.tsx
Labels: pr: to review later, priority: low

#2337 [2254] Add precondition on diagram tools
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/edit/studio.cy.js
  packages/compatibility/backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/services/diagrams/CompatibilityPaletteProvider.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/api/IPaletteProvider.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/GetPaletteEventHandler.java
  packages/diagrams/frontend/sirius-components-diagrams/src/representation/DiagramRepresentation.tsx
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/DeleteToolBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/DropToolBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/EdgeReconnectionToolBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/EdgeToolBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/LabelEditToolBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/NodeToolBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/SourceEdgeEndReconnectionToolBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/TargetEdgeEndReconnectionToolBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/ToolBuilder.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/ToolItemProvider.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/resources/plugin.properties
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/DiagramPackage.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/Tool.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/DiagramPackageImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/ToolImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/resources/model/diagram.ecore
  packages/view/backend/sirius-components-view-diagram/src/main/resources/model/diagram.genmodel
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/configuration/ViewPaletteToolsConfiguration.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewPaletteProvider.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewReconnectionToolsExecutor.java
  packages/view/backend/sirius-components-view-emf/src/test/java/org/eclipse/sirius/components/view/emf/diagram/ViewPaletteProviderTests.java
Labels: pr: to review soon, priority: high

#2353 [doc] Add missing breaking change information
  CHANGELOG.adoc
Labels: pr: to review later, priority: low

#2361 [2360] Fix an issue on widget ref creation modal
  CHANGELOG.adoc
  packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/datafetchers/ReferenceWidgetReferenceDataFetcher.java
Labels: pr: to review soon, priority: high

#2349 [doc] Improve README with Windows specific guidance, direct URL to dependencies and a warning on port
  README.adoc
Labels: pr: to review soon, priority: high

#2354 [releng] Fix mismatch in pom.xml for sirius-components-collaborative-…
  CHANGELOG.adoc
  packages/forms/backend/sirius-components-collaborative-widget-reference/pom.xml
  packages/forms/backend/sirius-components-collaborative-widget-reference/src/test/java/org/eclipse/sirius/components/collaborative/widget/reference/architecture/ArchitectureConstants.java
  packages/forms/backend/sirius-components-collaborative-widget-reference/src/test/java/org/eclipse/sirius/components/collaborative/widget/reference/architecture/CodingRulesTests.java
  packages/forms/backend/sirius-components-collaborative-widget-reference/src/test/java/org/eclipse/sirius/components/collaborative/widget/reference/architecture/SpringCodingRulesTests.java
  packages/forms/backend/sirius-components-widget-reference/src/test/java/org/eclipse/sirius/components/widget/reference/architecture/ArchitectureConstants.java
  packages/forms/backend/sirius-components-widget-reference/src/test/java/org/eclipse/sirius/components/widget/reference/architecture/CodingRulesTests.java
  packages/forms/backend/sirius-components-widget-reference/src/test/java/org/eclipse/sirius/components/widget/reference/architecture/ImmutableTests.java
Labels: pr: to review soon, priority: high

#2356 [enh] Add noUncheckedIndexedAccess to strict mode
  packages/core/frontend/sirius-components-core/src/workbench/Site.tsx
  packages/core/frontend/sirius-components-core/src/workbench/WorkbenchMachine.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramRenderer.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/connector/ConnectorContextualMenu.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/edge/MarkerDefinitions.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/layout.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/tool-section/ToolSection.tsx
  packages/releng/frontend/sirius-components-tsconfig/strict-react-library.json
Labels: pr: to review soon, priority: high

#2359 [2357] Remove Color property from Details View for ImageNodeStyle
  CHANGELOG.adoc
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/NodeStylePropertiesConfigurer.java
Labels: pr: to review soon, priority: low

#2344 [2343] Add icons on new object modals
  CHANGELOG.adoc
  packages/core/backend/sirius-components-collaborative/src/main/resources/schema/core.graphqls
  packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/api/ChildCreationDescription.java
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/services/EditService.java
  packages/forms/frontend/sirius-components-widget-reference/src/modals/CreateModal.tsx
  packages/forms/frontend/sirius-components-widget-reference/src/modals/CreateModal.types.ts
  packages/sirius-web/backend/sirius-web-customwidgets-edit/src/main/java/org/eclipse/sirius/web/customwidgets/provider/SliderDescriptionItemProvider.java
  packages/sirius-web/backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/ChildCreationDescriptionIconURLDataFetcher.java
  packages/sirius-web/frontend/sirius-web/src/modals/new-object/NewObjectModal.tsx
  packages/sirius-web/frontend/sirius-web/src/modals/new-object/NewObjectModal.types.ts
  packages/sirius-web/frontend/sirius-web/src/modals/new-root-object/NewRootObjectModal.tsx
  packages/sirius-web/frontend/sirius-web/src/modals/new-root-object/NewRootObjectModal.types.ts
Labels: pr: to review soon, priority: high

#2364 [2162] Unable to perform two chained direct-edit
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/Label.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/Label.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/direct-edit/DiagramDirectEditInput.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/edge/MultiLabelEdge.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/layout.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/node/ImageNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/node/ListNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/node/RectangularNode.tsx
Labels: pr: to review later, priority: low

#2366 [2365] Support key down/F2 direct edit on edges on react-flow diagrams
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/direct-edit/useDiagramDirectEdit.tsx
Labels: pr: to review soon, priority: low

#2362 [2358] Adds diagnostic messages to the reference widget
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/edit/widget-reference.cy.js
  packages/compatibility/backend/sirius-components-compatibility-emf/src/main/java/org/eclipse/sirius/components/compatibility/emf/properties/NonContainmentReferenceIfDescriptionProvider.java
  packages/compatibility/backend/sirius-components-compatibility-emf/src/main/java/org/eclipse/sirius/components/compatibility/emf/properties/PropertiesDefaultDescriptionProvider.java
  packages/compatibility/backend/sirius-components-compatibility-emf/src/main/java/org/eclipse/sirius/components/compatibility/emf/properties/PropertiesValidationProvider.java
  packages/forms/backend/sirius-components-widget-reference/src/main/java/org/eclipse/sirius/components/widget/reference/ReferenceElementProps.java
  packages/forms/backend/sirius-components-widget-reference/src/main/java/org/eclipse/sirius/components/widget/reference/ReferenceWidgetComponent.java
  packages/forms/backend/sirius-components-widget-reference/src/main/java/org/eclipse/sirius/components/widget/reference/ReferenceWidgetDescriptor.java
  packages/forms/frontend/sirius-components-widget-reference/src/components/ValuedReferenceAutocomplete.tsx
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/ViewPropertiesDescriptionRegistryConfigurer.java
Labels: pr: to review later, priority: low

#2382 [2381] Update edge's handle id
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/edge/MultiLabelEdge.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/node/ImageNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/node/ListNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/node/RectangularNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/reconnect-edge/useReconnectEdge.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/reconnect-edge/useReconnectEdge.types.ts
Labels: pr: to review soon, priority: high

#2281 [2044] Custom icons to edges and nodes label in view dsl
  CHANGELOG.adoc
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/ConditionalEdgeStyleBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/EdgeStyleBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/IconLabelNodeStyleDescriptionBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/ImageNodeStyleDescriptionBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/NodeStyleDescriptionBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/RectangularNodeStyleDescriptionBuilder.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/ConditionalEdgeStyleItemProvider.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/EdgeStyleItemProvider.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/IconLabelNodeStyleDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/ImageNodeStyleDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/RectangularNodeStyleDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/DiagramPackage.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/EdgeStyle.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/NodeStyleDescription.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/ConditionalEdgeStyleImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/DiagramPackageImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/EdgeStyleImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/IconLabelNodeStyleDescriptionImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/ImageNodeStyleDescriptionImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/RectangularNodeStyleDescriptionImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/resources/model/diagram.ecore
  packages/view/backend/sirius-components-view-diagram/src/main/resources/model/diagram.genmodel
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/ViewPropertiesDescriptionRegistryConfigurer.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/compatibility/IPropertiesConfigurerService.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/compatibility/IPropertiesWidgetCreationService.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/compatibility/PropertiesConfigurerService.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/compatibility/PropertiesWidgetCreationService.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/EdgeStylePropertiesConfigurer.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/NodeStylePropertiesConfigurer.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/StylesFactory.java
Labels: pr: to review later, priority: low

#2404 [2260] Keep the layout stable over time
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/converter/convertDiagram.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramRenderer.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramRenderer.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/edge/EdgeTypes.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/edge/EdgeTypes.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/ImageNodeLayoutHandler.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/LayoutEngine.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/LayoutEngine.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/ListNodeLayoutHandler.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/RectangleNodeLayoutHandler.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/layout.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/useLayout.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/useLayout.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/node/NodeTypes.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/node/NodeTypes.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/representation/DiagramRepresentation.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/representation/DiagramRepresentation.types.ts
Labels: pr: to review soon, priority: high

#2206 [doc] Shape for color management in View
  CHANGELOG.adoc
  doc/iterations/2023.10/shapes/color_management_in_view.adoc
Labels: type: enhancement, package: view

#2398 [doc] Contribute a shape to support image overlay
  CHANGELOG.adoc
  doc/iterations/2023.10/shapes/image_overlay.adoc
  doc/iterations/2023.10/shapes/images/image_overlay_01.svg
  doc/iterations/2023.10/shapes/images/image_overlay_02.svg
  doc/iterations/2023.10/shapes/images/image_overlay_03.png
Labels: pr: to review later, priority: low

#2379 [cleanup] Removed unused SVG in stylesheets
  packages/sirius-web/frontend/sirius-web/src/variables.css
  vscode-extension/src/view/app/variables.css
Labels: pr: to review later, priority: low

#2230 [doc] Contribute an ADR on transient data manipulation using forms
  CHANGELOG.adoc
  doc/adrs/109_add_support_for_transient_data_in_forms.adoc
Labels: pr: to review later, priority: low

#2347 [doc] Add ADR for color management in View
  CHANGELOG.adoc
  doc/adrs/109_add_support_for_transient_data_in_forms.adoc
  doc/adrs/110_color_management_in_view.adoc
Labels: package: view, type: documentation

#2408 [enh] Do not fail project import if (some) representations could not be imported
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/projects/ProjectImporter.java
Labels: pr: to review soon, priority: high

#2339 [2191] Remove Color property on ImageNodeStyle
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/logicalarchitecture/ProvidedServiceNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/logicalarchitecture/RequiredServiceNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/operationalanalysis/OperationalActorNodeDescriptionProvider.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/ImageNodeStyleDescriptionBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/NodeStyleDescriptionBuilder.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/EdgePaletteItemProvider.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/ImageNodeStyleDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/DiagramPackage.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/DiagramToolSection.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/IconLabelNodeStyleDescription.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/NodeStyleDescription.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/NodeToolSection.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/RectangularNodeStyleDescription.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/ToolSection.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/adapters/DiagramColorAdapter.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/DiagramPackageImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/IconLabelNodeStyleDescriptionImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/ImageNodeStyleDescriptionImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/RectangularNodeStyleDescriptionImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/util/DiagramSwitch.java
  packages/view/backend/sirius-components-view-diagram/src/main/resources/model/diagram.ecore
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/DiagramDescriptionValidator.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ImageNodeStyleProvider.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/StylesFactory.java
  packages/view/backend/sirius-components-view-emf/src/test/java/org/eclipse/sirius/components/view/emf/validation/ViewValidatorTests.java
  packages/view/backend/sirius-components-view-emf/src/test/java/org/eclipse/sirius/components/view/emf/view/DynamicDiagramsTests.java
Labels: pr: to review soon, priority: high
