Repository eclipse-sirius/sirius-web, pull requests merged in 2024-12, with the labels that each got.

#4191 [4190] Display the icon of the representation in the workbench tab
  CHANGELOG.adoc
  packages/core/backend/sirius-components-collaborative/src/main/resources/schema/core.graphqls
  packages/core/frontend/sirius-components-core/src/representationmetadata/useRepresentationMetadata.tsx
  packages/core/frontend/sirius-components-core/src/representationmetadata/useRepresentationMetadata.types.tsx
  packages/core/frontend/sirius-components-core/src/workbench/RepresentationNavigation.tsx
  packages/core/frontend/sirius-components-core/src/workbench/Workbench.types.ts
  packages/portals/frontend/sirius-components-portals/src/representations/PortalRepresentation.tsx
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/representation/controllers/EditingContextRepresentationDataFetcher.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/representation/dto/RepresentationMetadataDTO.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/representation/services/RepresentationMetadataMapper.java
  packages/sirius-web/backend/sirius-web-tests/src/main/java/org/eclipse/sirius/web/tests/graphql/RepresentationMetadataQueryRunner.java
  packages/sirius-web/backend/sirius-web-tests/src/main/java/org/eclipse/sirius/web/tests/graphql/RepresentationsMetadataQueryRunner.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/representations/RepresentationControllerIntegrationTests.java
  packages/sirius-web/frontend/sirius-web-application/src/onboarding/OnboardArea.tsx
  packages/sirius-web/frontend/sirius-web-application/src/onboarding/OnboardArea.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/onboarding/RepresentationsArea.tsx
  packages/sirius-web/frontend/sirius-web-application/src/onboarding/RepresentationsArea.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/EditProjectViewMachine.ts
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/useProjectAndRepresentationMetadata.fragment.ts
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/useProjectAndRepresentationMetadata.types.ts
  packages/tests/backend/sirius-components-graphql-tests/src/main/java/org/eclipse/sirius/components/graphql/tests/AllRepresentationMetadataQueryRunner.java
  packages/tests/backend/sirius-components-graphql-tests/src/main/java/org/eclipse/sirius/components/graphql/tests/RepresentationDescriptionsQueryRunner.java
Labels: pr: to review soon, priority: low

#4251 [4250] Add icons to table column headers
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/table/PackageTableRepresentationDescriptionProvider.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/tables/TableIconURLControllerTests.java
  packages/tables/backend/sirius-components-collaborative-tables/src/main/resources/schema/table.graphqls
  packages/tables/backend/sirius-components-tables-graphql/src/main/java/org/eclipse/sirius/components/tables/graphql/datafetchers/ColumnIconURLsDataFetcher.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/Column.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/components/ColumnComponent.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/descriptions/ColumnDescription.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/elements/ColumnElementProps.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/renderer/TableElementFactory.java
  packages/tables/frontend/sirius-components-tables/src/representation/useTableSubscription.ts
  packages/tables/frontend/sirius-components-tables/src/table/TableContent.types.ts
  packages/tables/frontend/sirius-components-tables/src/table/useTableColumns.tsx
Labels: pr: to review soon, priority: low

#4243 [4242] Add support to stub location for row in table
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/table/PackageTableRepresentationDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/table/ProjectTableRepresentationDescriptionProvider.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/tables/TableIconURLControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/forms/FormWithTableEditingContextDescriptionProvider.java
  packages/tables/backend/sirius-components-collaborative-tables/src/main/resources/schema/table.graphqls
  packages/tables/backend/sirius-components-tables-graphql/src/main/java/org/eclipse/sirius/components/tables/graphql/datafetchers/LineHeaderIconURLsDataFetcher.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/Line.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/components/LineComponent.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/descriptions/LineDescription.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/elements/LineElementProps.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/renderer/TableElementFactory.java
  packages/tables/frontend/sirius-components-tables/src/representation/useTableSubscription.ts
  packages/tables/frontend/sirius-components-tables/src/rows/RowHeader.tsx
  packages/tables/frontend/sirius-components-tables/src/rows/RowHeader.types.ts
  packages/tables/frontend/sirius-components-tables/src/table/TableContent.tsx
  packages/tables/frontend/sirius-components-tables/src/table/TableContent.types.ts
Labels: pr: to review soon, priority: low

#4245 [4244] Add support to stripe rows in table
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/table/PackageTableRepresentationDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/table/ProjectTableRepresentationDescriptionProvider.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/forms/FormWithTableEditingContextDescriptionProvider.java
  packages/tables/backend/sirius-components-collaborative-tables/src/main/resources/schema/table.graphqls
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/Table.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/components/TableComponent.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/descriptions/TableDescription.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/elements/TableElementProps.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/renderer/TableElementFactory.java
  packages/tables/frontend/sirius-components-tables/src/representation/useTableSubscription.ts
  packages/tables/frontend/sirius-components-tables/src/table/TableContent.tsx
  packages/tables/frontend/sirius-components-tables/src/table/TableContent.types.ts
Labels: pr: to review soon, priority: low

#4232 [4231] Make table's column resizable
  CHANGELOG.adoc
  packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/FormEventProcessor.java
  packages/forms/backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/components/TableWidgetComponent.java
  packages/forms/backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/components/TableWidgetComponentProps.java
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/table/PackageTableRepresentationDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/table/ProjectTableRepresentationDescriptionProvider.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/tables/PapayaTableColumnControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/tables/PapayaTableControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/forms/FormWithTableEditingContextDescriptionProvider.java
  packages/tables/backend/sirius-components-collaborative-tables/src/main/java/org/eclipse/sirius/components/collaborative/tables/TableChangeKind.java
  packages/tables/backend/sirius-components-collaborative-tables/src/main/java/org/eclipse/sirius/components/collaborative/tables/TableContext.java
  packages/tables/backend/sirius-components-collaborative-tables/src/main/java/org/eclipse/sirius/components/collaborative/tables/TableEventProcessor.java
  packages/tables/backend/sirius-components-collaborative-tables/src/main/java/org/eclipse/sirius/components/collaborative/tables/TableEventProcessorFactory.java
  packages/tables/backend/sirius-components-collaborative-tables/src/main/java/org/eclipse/sirius/components/collaborative/tables/api/ITableContext.java
  packages/tables/backend/sirius-components-collaborative-tables/src/main/java/org/eclipse/sirius/components/collaborative/tables/api/ITableEventHandler.java
  packages/tables/backend/sirius-components-collaborative-tables/src/main/java/org/eclipse/sirius/components/collaborative/tables/dto/ResizeTableColumnInput.java
  packages/tables/backend/sirius-components-collaborative-tables/src/main/java/org/eclipse/sirius/components/collaborative/tables/handlers/EditCellEventHandler.java
  packages/tables/backend/sirius-components-collaborative-tables/src/main/java/org/eclipse/sirius/components/collaborative/tables/handlers/ResizeTableColumnEventHandler.java
  packages/tables/backend/sirius-components-collaborative-tables/src/main/java/org/eclipse/sirius/components/collaborative/tables/services/TableCreationService.java
  packages/tables/backend/sirius-components-collaborative-tables/src/main/resources/schema/table.graphqls
  packages/tables/backend/sirius-components-tables-graphql/src/main/java/org/eclipse/sirius/components/tables/graphql/datafetchers/mutation/MutationResizeTableColumnDataFetcher.java
  packages/tables/backend/sirius-components-tables-tests/src/main/java/org/eclipse/sirius/components/tables/tests/graphql/ResizeTableColumnMutationRunner.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/Column.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/components/ColumnComponent.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/components/ColumnComponentProps.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/components/ITableElementRequestor.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/components/TableComponent.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/components/TableComponentProps.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/components/TableElementRequestor.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/descriptions/ColumnDescription.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/elements/ColumnElementProps.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/events/ITableEvent.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/events/ResizeTableColumnEvent.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/renderer/TableElementFactory.java
  packages/tables/frontend/sirius-components-tables/src/columns/useTableColumnSizing.ts
  packages/tables/frontend/sirius-components-tables/src/columns/useTableColumnSizing.types.ts
  packages/tables/frontend/sirius-components-tables/src/representation/useTableSubscription.ts
  packages/tables/frontend/sirius-components-tables/src/table/TableContent.tsx
  packages/tables/frontend/sirius-components-tables/src/table/TableContent.types.ts
  packages/tables/frontend/sirius-components-tables/src/table/useTableColumns.tsx
Labels: pr: to review soon, priority: low

#4239 [4238] Make table's column hideable
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/tables/PapayaTableColumnControllerIntegrationTests.java
  packages/tables/backend/sirius-components-collaborative-tables/src/main/java/org/eclipse/sirius/components/collaborative/tables/dto/ChangeTableColumnVisibilityInput.java
  packages/tables/backend/sirius-components-collaborative-tables/src/main/java/org/eclipse/sirius/components/collaborative/tables/dto/ColumnVisibility.java
  packages/tables/backend/sirius-components-collaborative-tables/src/main/java/org/eclipse/sirius/components/collaborative/tables/handlers/ChangeTableColumnVisibilityEventHandler.java
  packages/tables/backend/sirius-components-collaborative-tables/src/main/resources/schema/table.graphqls
  packages/tables/backend/sirius-components-tables-graphql/src/main/java/org/eclipse/sirius/components/tables/graphql/datafetchers/mutation/MutationChangeTableColumnVisibilityDataFetcher.java
  packages/tables/backend/sirius-components-tables-tests/src/main/java/org/eclipse/sirius/components/tables/tests/graphql/ChangeTableColumnVisibilityMutationRunner.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/Column.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/components/ColumnComponent.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/elements/ColumnElementProps.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/events/ChangeTableColumnVisibilityEvent.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/renderer/TableElementFactory.java
  packages/tables/frontend/sirius-components-tables/src/columns/useTableColumnVisibility.ts
  packages/tables/frontend/sirius-components-tables/src/columns/useTableColumnVisibility.types.ts
  packages/tables/frontend/sirius-components-tables/src/representation/useTableSubscription.ts
  packages/tables/frontend/sirius-components-tables/src/table/TableContent.tsx
  packages/tables/frontend/sirius-components-tables/src/table/TableContent.types.ts
Labels: pr: to review soon, priority: low

#4256 [4254] Make explorer services reusable
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/representations/DomainExplorerServices.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/ExplorerChildrenProvider.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/ExplorerDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/ExplorerElementsProvider.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/ExplorerServices.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/api/IExplorerServices.java
Labels: pr: to review soon, priority: high

#4276 [fix] Fix sirius-web-table .project name
  packages/sirius-web/backend/sirius-web-table/.project
  packages/sirius-web/backend/sirius-web-table/.settings/org.eclipse.core.resources.prefs
  packages/sirius-web/backend/sirius-web-table/src/test/java/.gitkeep
  packages/sirius-web/backend/sirius-web-table/src/test/resources/.gitkeep
Labels: pr: to review soon, priority: high

#4084 [1062] Allow expand/collapse of tree items without selecting them
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/details/widget-reference.cy.ts
  integration-tests/cypress/e2e/project/diagrams/arrange-all.cy.ts
  integration-tests/cypress/e2e/project/diagrams/collapse.cy.ts
  integration-tests/cypress/e2e/project/diagrams/direct-edit-label.cy.ts
  integration-tests/cypress/e2e/project/diagrams/drop-on-diagram.cy.ts
  integration-tests/cypress/e2e/project/diagrams/edges.cy.ts
  integration-tests/cypress/e2e/project/diagrams/graphical-dnd.cy.ts
  integration-tests/cypress/e2e/project/diagrams/group-palette.cy.ts
  integration-tests/cypress/e2e/project/diagrams/node-aspect-ratio.cy.ts
  integration-tests/cypress/e2e/project/explorer/explorer-dnd.cy.ts
  integration-tests/cypress/e2e/project/explorer/explorer-selection.cy.ts
  integration-tests/cypress/e2e/project/explorer/explorer.cy.ts
  integration-tests/cypress/e2e/project/forms/widget-reference.cy.ts
  integration-tests/cypress/e2e/project/tables/table.cy.ts
  integration-tests/cypress/workbench/Deck.ts
  integration-tests/cypress/workbench/Explorer.ts
  integration-tests/cypress/workbench/Gantt.ts
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItem.tsx
Labels: pr: to review soon, priority: low

#4198 [3980] Re-enable selection after the execution of a tool on diagrams
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/connector/ConnectorContextualMenu.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/connector/ConnectorContextualMenu.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/usePalette.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/usePalette.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/selection/useDiagramSelection.ts
Labels: pr: to review later, priority: low

#4281 [4280] Restore direct edit with f2
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/Palette.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/search/PaletteSearchField.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/search/PaletteSearchField.types.ts
Labels: pr: to review soon, priority: high

#4174 [doc] Add Shape for forking view of table representation
  CHANGELOG.adoc
  doc/iterations/2025.1/update_table_description_from_representation.adoc
Labels: pr: to review soon, priority: high

#4175 [doc] Add ADR on support for forking table description
  CHANGELOG.adoc
  doc/adrs/173_add_support_for_forking_table_description_from_representation.adoc
Labels: pr: to review soon, priority: high

#4121 [doc] Add ADR on table description in view DSL
  CHANGELOG.adoc
  doc/adrs/174_add_table_description_in_view_dsl.adoc
Labels: pr: to review soon, priority: high

#4199 [doc] Add ADR on support for pagination in REST APIs
  CHANGELOG.adoc
  doc/adrs/175_support_pagination_in_rest_apis.adoc
Labels: pr: to review soon, priority: high

#4267 [cleanup] Remove empty frontend test
  packages/forms/frontend/sirius-components-widget-reference/package.json
  packages/forms/frontend/sirius-components-widget-reference/src/__tests__/ReferenceWidget.test.tsx
Labels: pr: to review later, priority: low

#4129 [doc] Add ADR about undo and redo on Portal
  CHANGELOG.adoc
  doc/adrs/176_add_support_for_undo_redo_on_portal_representation.adoc
Labels: pr: to review soon, priority: high

#4127 [doc] ADR about undo redo on Diagram
  CHANGELOG.adoc
  doc/adrs/177_add_support_for_undo_redo_on_diagram_representation.adoc
Labels: pr: to review soon, priority: high

#4298 [4297] Docker image size optimisation
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web/Dockerfile
Labels: pr: to review soon, priority: high

#4262 [4261] Enable image cache
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/images/controllers/ImagesController.java
Labels: pr: to review later, priority: low

#4304 [4302] Fix edges label flashing
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/MultiLabelEditableEdge.tsx
Labels: pr: to review soon, priority: high

#4226 [4225] Add support for localized enumeration literals in EMF property forms
  CHANGELOG.adoc
  packages/emf/backend/sirius-components-emf-forms/src/main/java/org/eclipse/sirius/components/emf/forms/EEnumIfDescriptionProvider.java
  packages/emf/backend/sirius-components-emf-forms/src/main/java/org/eclipse/sirius/components/emf/forms/EEnumLiteralLabelProvider.java
Labels: pr: to review soon, priority: low

#4228 [4227] Add support for custom numeric and boolean types in property forms
  CHANGELOG.adoc
  packages/emf/backend/sirius-components-emf-forms/src/main/java/org/eclipse/sirius/components/emf/forms/EBooleanIfDescriptionProvider.java
  packages/emf/backend/sirius-components-emf-forms/src/main/java/org/eclipse/sirius/components/emf/forms/EMFFormDescriptionProvider.java
  packages/emf/backend/sirius-components-emf-forms/src/main/java/org/eclipse/sirius/components/emf/forms/NumberIfDescriptionProvider.java
Labels: pr: to review soon, priority: low

#4289 [fix] Fix palette size on Firefox
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/Palette.tsx
Labels: pr: to review soon, priority: high

#4309 [releng] Simplify the build process
  .github/workflows/build.yml
Labels: pr: to review soon, priority: high

#4314 [4312] Update the Details view when its input is deselected
  CHANGELOG.adoc
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/DetailsView.tsx
Labels: pr: to review later, priority: low

#4279 [4278] Always use onData callback for useSubscription
  CHANGELOG.adoc
  packages/core/frontend/sirius-components-core/src/workbench/Workbench.tsx
  packages/deck/frontend/sirius-components-deck/src/representation/DeckRepresentation.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/representation/DiagramRepresentation.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FormDescriptionEditorRepresentation.tsx
  packages/forms/frontend/sirius-components-forms/src/representations/useFormSubscription.tsx
  packages/forms/frontend/sirius-components-forms/src/representations/useFormSubscription.types.ts
  packages/forms/frontend/sirius-components-widget-reference/src/components/useModelBrowserSubscription.tsx
  packages/gantt/frontend/sirius-components-gantt/src/representation/GanttRepresentation.tsx
  packages/portals/frontend/sirius-components-portals/src/hooks/usePortal.ts
  packages/selection/frontend/sirius-components-selection/src/useSelectionDialogTreeSubscription.tsx
  packages/sirius-web/frontend/sirius-web-application/src/diagrams/useDiagramFilterSubscription.tsx
  packages/sirius-web/frontend/sirius-web-application/src/diagrams/useDiagramFilterSubscription.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/EditProjectNavbar/EditProjectNavbar.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/useDetailsViewSubscription.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/useRelatedElementsViewSubscription.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/useRelatedElementsViewSubscription.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/useRepresentationsViewSubscription.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/explorer/useExplorerSubscription.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/explorer/useExplorerSubscription.types.ts
  packages/tables/frontend/sirius-components-tables/src/representation/useTableSubscription.ts
  packages/trees/frontend/sirius-components-trees/src/trees/useTreeSubscription.tsx
  packages/validation/frontend/sirius-components-validation/src/useValidationViewSubscription.tsx
  packages/validation/frontend/sirius-components-validation/src/useValidationViewSubscription.types.ts
Labels: pr: to review soon, priority: high

#4320 [4319] Rename "Hide/Show Tool Section" to "Show/Hide"
  CHANGELOG.adoc
  packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/DefaultToolsFactory.java
Labels: pr: to review soon, priority: high

#4318 [4317] Export NewObject, NewRootObject, and NewRepresentation modals
  CHANGELOG.adoc
  packages/sirius-web/frontend/sirius-web-application/src/index.ts
Labels: pr: to review soon, priority: high

#4322 [4291] Implement API documentation with openAPI v3 and swagger
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/pom.xml
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/object/controllers/ObjectRestController.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/controllers/ProjectRestController.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/data/versioning/controllers/CommitRestController.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/data/versioning/dto/RestBranch.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/data/versioning/dto/RestCommit.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/data/versioning/dto/RestDataIdentity.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/data/versioning/dto/RestDataVersion.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/dto/RestProject.java
  packages/sirius-web/backend/sirius-web-infrastructure/pom.xml
  packages/sirius-web/backend/sirius-web-infrastructure/src/main/java/org/eclipse/sirius/web/infrastructure/configuration/openapi/OpenApiConfiguration.java
Labels: pr: to review soon, priority: high

#4315 [4301] Fix Extension VSCode extension regressions
  CHANGELOG.adoc
  packages/sirius-web/frontend/sirius-web-application/src/extension/DefaultExtensionRegistry.tsx
  packages/sirius-web/frontend/sirius-web-application/src/extension/EllipseNodeDocumentTransform.ts
  packages/sirius-web/frontend/sirius-web-application/src/index.ts
  vscode-extension/src/data/ProjectData.ts
  vscode-extension/src/data/getTreeEventSubscription.ts
  vscode-extension/src/view/app/App.tsx
  vscode-extension/src/view/app/index.tsx
  vscode-extension/src/view/app/nodes/EllipseNode.tsx
  vscode-extension/src/view/app/nodes/EllipseNode.types.ts
  vscode-extension/src/view/app/nodes/EllipseNodeConverter.ts
  vscode-extension/src/view/app/nodes/EllipseNodeLayoutHandler.ts
Labels: pr: to review soon, priority: high

#4328 [4305] Allow the deactivation of table features useless in some contexts
  CHANGELOG.adoc
  packages/forms/frontend/sirius-components-forms/src/form/FormEventFragments.ts
  packages/forms/frontend/sirius-components-forms/src/propertysections/TableWidgetPropertySection.tsx
  packages/tables/frontend/sirius-components-tables/src/columns/useTableColumnFiltering.ts
  packages/tables/frontend/sirius-components-tables/src/columns/useTableColumnFiltering.types.ts
  packages/tables/frontend/sirius-components-tables/src/columns/useTableColumnSizing.ts
  packages/tables/frontend/sirius-components-tables/src/columns/useTableColumnSizing.types.ts
  packages/tables/frontend/sirius-components-tables/src/columns/useTableColumnVisibility.ts
  packages/tables/frontend/sirius-components-tables/src/columns/useTableColumnVisibility.types.ts
  packages/tables/frontend/sirius-components-tables/src/representation/TableRepresentation.tsx
  packages/tables/frontend/sirius-components-tables/src/rows/useResetRows.ts
  packages/tables/frontend/sirius-components-tables/src/table/TableContent.tsx
  packages/tables/frontend/sirius-components-tables/src/table/TableContent.types.ts
  packages/tables/frontend/sirius-components-tables/src/table/useGlobalFilter.ts
  packages/tables/frontend/sirius-components-tables/src/table/useGlobalFilter.types.ts
  packages/tables/frontend/sirius-components-tables/src/table/useTableColumns.tsx
Labels: pr: to review soon, priority: high

#4339 [doc] Prepare the CHANGELOG for 2025.2.0
  CHANGELOG.adoc
Labels: pr: to review soon, priority: high
