Repository eclipse-sirius/sirius-web, pull requests merged in 2024-11, with the labels that each got.

#4162 [4149] Fix the synchronization on group tool layout
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/useDistributeElements.ts
Labels: pr: to review soon, priority: low

#4160 [4148] Fix dragged node absolute position evaluation
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/dropNode/useDropNode.ts
Labels: pr: to review soon, priority: high

#4168 [4154] Restore feedback while resizing a list container
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/resize/useResizeChange.tsx
Labels: pr: to review soon, priority: high

#4136 [doc] Add ADR on representation details view
  CHANGELOG.adoc
  doc/adrs/168_display_the_icon_of_the_representations_in_the_workbench_tab.adoc
  doc/adrs/169_compute_the_icon_of_a_representation.adoc
  doc/adrs/170_support_representation_details_view.adoc
Labels: pr: to review soon, priority: low

#4085 [doc] Add shape to improve form property section layout
  CHANGELOG.adoc
  doc/iterations/2024.11/add_support_for_form_property_section_layout.adoc
Labels: type: enhancement, difficulty: starter, package: forms

#4172 [releng] Improve the pull request check to validate frontend dependencies
  .github/workflows/pull-request.yml
  package-lock.json
  packages/core/frontend/sirius-components-omnibox/package.json
  packages/diagrams/frontend/sirius-components-diagrams/package.json
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/package.json
  packages/forms/frontend/sirius-components-forms/package.json
  packages/forms/frontend/sirius-components-widget-reference/package.json
  packages/portals/frontend/sirius-components-portals/package.json
  packages/selection/frontend/sirius-components-selection/package.json
  packages/sirius-web/frontend/sirius-web-application/package.json
  packages/sirius-web/frontend/sirius-web-papaya/package.json
  packages/validation/frontend/sirius-components-validation/package.json
  scripts/check-frontend-dependencies.js
Labels: pr: to review soon, priority: high

#4194 [doc] Add ADR on Project Data Versioning REST APIs
  CHANGELOG.adoc
  doc/adrs/172_support_project_data_versioning_rest_apis.adoc
  doc/adrs/images/172/projectDataVersioningAPIModel.png
  doc/adrs/images/172/projectDataVersioningAPIModel2.png
Labels: pr: to review soon, priority: high

#4196 [4195] Prevent objects disappearing when dropped on themselves in the Explorer
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/ExplorerDropTreeItemHandler.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/trees/ExplorerDropTreeItemControllerTests.java
Labels: pr: to review soon, priority: low

#4215 [fix] Remove unused parameters
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/services/DefaultLabelService.java
  packages/emf/backend/sirius-components-emf/src/test/java/org/eclipse/sirius/components/emf/services/DefaultLabelServiceTests.java
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/services/PapayaLabelProvider.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/tree/EcoreSampleStyledLabelService.java
  packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/services/TaskLabelServiceDelegate.java
Labels: pr: to review soon, priority: low

#4220 [4219] Memoize table component
  CHANGELOG.adoc
  packages/tables/frontend/sirius-components-tables/src/cells/Cell.tsx
  packages/tables/frontend/sirius-components-tables/src/table/TableContent.tsx
Labels: pr: to review soon, priority: low

#4224 [test] Add first cypress test on table representation
  integration-tests/cypress/e2e/project/tables/table.cy.ts
  integration-tests/cypress/usecases/Papaya.ts
  packages/sirius-web/backend/sirius-web-e2e-tests/pom.xml
  packages/sirius-web/backend/sirius-web-e2e-tests/src/main/java/org/eclipse/sirius/web/e2e/tests/templates/TablePapayaProjectTemplateInitializer.java
  packages/sirius-web/backend/sirius-web-e2e-tests/src/main/java/org/eclipse/sirius/web/e2e/tests/templates/TablePapayaTemplatesProvider.java
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/table/TableLabelProvider.java
  packages/tables/frontend/sirius-components-tables/src/representation/TableRepresentation.tsx
Labels: pr: to review soon, priority: low

#4062 [4241] Add the last used tool entry in the palette
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/contexts/DiagramPaletteContext.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/contexts/DiagramPaletteContext.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/tool-list-item/ToolListItem.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/tool-list-item/ToolListItem.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/tool-list/PaletteToolList.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/tool-list/PaletteToolSectionList.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/useDiagramPalette.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/usePalette.tsx
Labels: pr: to review later, priority: low
