Repository eclipse-sirius/sirius-web, pull requests merged in 2024-08, with the labels that each got.

#3822 [3821] Allow to filter some Resources in RewriteProxiesEventHandler
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/services/DefaultRewriteProxiesResourceFilter.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/services/RewriteProxiesEventHandler.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/services/api/IRewriteProxiesResourceFilter.java
  packages/sirius-web/backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/services/api/IMessageService.java
  packages/sirius-web/backend/sirius-web-domain/src/test/java/org/eclipse/sirius/web/domain/services/api/MessageServiceTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/project/RewriteProxiesEventHandlerTests.java
Labels: pr: to review soon, priority: high

#3825 [3824] Fix representation migration participant execution
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/representation/services/RepresentationPersistenceService.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/AbstractIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/data/MigrationIdentifiers.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/migration/MigrationParticipantOrderTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/migration/MigrationParticipantOrderTestsConfiguration.java
Labels: pr: to review soon, priority: high

#3838 [releng] Upgrade some GitHub Actions
  .github/workflows/build.yml
  .github/workflows/ip-verify.yml
  .github/workflows/pull-request.yml
Labels: pr: to review later, priority: low

#3841 [3702] Improve the API used to extend the navigation bar menu
  packages/sirius-web/frontend/sirius-web-application/src/navigationBar/NavigationBarMenu.tsx
  packages/sirius-web/frontend/sirius-web-application/src/navigationBar/NavigationBarMenu.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/navigationBar/NavigationBarMenuExtensionPoints.tsx
Labels: pr: to review soon, priority: high

#3559 [3557] Add ProjectSettings tab extension point
  CHANGELOG.adoc
  packages/sirius-web/frontend/sirius-web-application/src/extension/DefaultExtensionRegistry.tsx
  packages/sirius-web/frontend/sirius-web-application/src/index.ts
  packages/sirius-web/frontend/sirius-web-application/src/views/project-settings/ProjectSettingsView.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/project-settings/ProjectSettingsView.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/views/project-settings/ProjectSettingsViewExtensionPoints.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/project-settings/images/ProjectImagesSettings.tsx
Labels: pr: to review later, priority: low

#3848 [enh] Remove Mui overrides for Select and TextField Mui components
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/direct-edit/DiagramDirectEditInput.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/DateTimeWidget.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/MultiSelectWidget.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/SelectWidget.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/TextAreaWidget.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/TextfieldWidget.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/DateTimeWidgetPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/MultiSelectPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/SelectPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/TextfieldPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/MultiSelectPropertySection.test.tsx.snap
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/SelectPropertySection.test.tsx.snap
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/TextfieldPropertySection.test.tsx.snap
  packages/forms/frontend/sirius-components-widget-reference/src/components/ModelBrowserFilterBar.tsx
  packages/forms/frontend/sirius-components-widget-reference/src/modals/CreateModal.tsx
  packages/gantt/frontend/sirius-components-gantt/src/toolbar/Toolbar.tsx
  packages/sirius-web/frontend/sirius-web-application/src/modals/new-document/NewDocumentModal.tsx
  packages/sirius-web/frontend/sirius-web-application/src/modals/new-object/NewObjectModal.tsx
  packages/sirius-web/frontend/sirius-web-application/src/modals/new-representation/NewRepresentationModal.tsx
  packages/sirius-web/frontend/sirius-web-application/src/modals/new-root-object/NewRootObjectModal.tsx
  packages/sirius-web/frontend/sirius-web-application/src/modals/rename-project/RenameProjectModal.tsx
  packages/sirius-web/frontend/sirius-web-application/src/theme/siriusWebTheme.ts
  packages/sirius-web/frontend/sirius-web-application/src/views/new-project/NewProjectView.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/project-settings/images/rename-image/RenameImageModal.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/project-settings/images/upload-image/UploadImageModal.tsx
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItemDirectEditInput.tsx
  packages/trees/frontend/sirius-components-trees/src/trees/FilterBar.tsx
Labels: pr: to review soon, priority: high

#3852 [3851] Fix the display of Explorer Filters menu items
  CHANGELOG.adoc
  packages/trees/frontend/sirius-components-trees/src/views/TreeFiltersMenu.tsx
Labels: pr: to review soon, priority: high

#3858 [3808] Fix interactions with `TreeItemContextMenu` modal
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItem.tsx
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItemAction.tsx
Labels: pr: to review later, priority: low

#3780 [3777] Support any object as semantic element in the tree representation
  CHANGELOG.adoc
  packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/browser/ModelBrowsersDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/DeleteDocumentTreeItemEventHandler.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/DeleteObjectTreeItemEventHandler.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/DeleteRepresentationTreeItemEventHandler.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/ExpandAllTreePathProvider.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/ExplorerChildrenProvider.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/ExplorerDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/ExplorerNavigationService.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/ExplorerTreePathProvider.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/RenameDocumentTreeItemHandler.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/RenameObjectTreeItemEventHandler.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/RenameRepresentationTreeItemHandler.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/api/IDeleteTreeItemHandler.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/api/IExplorerNavigationService.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/api/IRenameTreeItemHandler.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/trees/ExplorerNonSemanticElementControllerTests.java
  packages/trees/backend/sirius-components-collaborative-trees/src/main/java/org/eclipse/sirius/components/collaborative/trees/handlers/DeleteTreeItemEventHandler.java
  packages/trees/backend/sirius-components-collaborative-trees/src/main/java/org/eclipse/sirius/components/collaborative/trees/handlers/RenameTreeItemEventHandler.java
  packages/trees/backend/sirius-components-trees/src/main/java/org/eclipse/sirius/components/trees/description/TreeDescription.java
Labels: pr: to review soon, priority: high

#3872 [doc] Add some documentation on testing custom datafetchers with subscriptions
  doc/how-to/test-sirius-web-based-applications.adoc
Labels: pr: to review soon, priority: high

#3857 [3763] Split the SelectionDialogDescription to prepare the Tree support
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/migration/participants/SelectionDialogDescriptionSelectionCandidatesExpressionMigrationParticipant.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/data/MigrationIdentifiers.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/diagrams/ModelOperationDiagramDescriptionProvider.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/migration/SelectionDialogDescriptionSelectionCandidatesExpressionMigrationParticipantTests.java
  packages/sirius-web/backend/sirius-web/src/test/resources/scripts/migration.sql
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/SelectionDialogTreeDescriptionBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/diagram/DiagramBuilders.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/diagram/SelectionDialogDescriptionBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/diagram/SelectionDialogTreeDescriptionBuilder.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/DiagramItemProviderAdapterFactory.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/SelectionDialogDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/SelectionDialogTreeDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/resources/icons/full/obj16/SelectionDialogTreeDescription.svg
  packages/view/backend/sirius-components-view-diagram-edit/src/main/resources/plugin.properties
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/DiagramFactory.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/DiagramPackage.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/SelectionDialogDescription.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/SelectionDialogTreeDescription.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/DiagramFactoryImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/DiagramPackageImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/SelectionDialogDescriptionImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/SelectionDialogTreeDescriptionImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/util/DiagramAdapterFactory.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/util/DiagramSwitch.java
  packages/view/backend/sirius-components-view-diagram/src/main/resources/model/diagram.ecore
  packages/view/backend/sirius-components-view-diagram/src/main/resources/model/diagram.genmodel
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/ViewConverter.java
Labels: pr: to review soon, priority: high

#3796 [3793] Add a way to get the parent object in the tree representation
  CHANGELOG.adoc
  packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/browser/ModelBrowserExpandAllTreePathProvider.java
  packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/browser/ModelBrowserNavigationService.java
  packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/browser/ModelBrowsersDescriptionProvider.java
  packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/browser/api/IModelBrowserNavigationService.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/ExpandAllTreePathProvider.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/ExplorerDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/ExplorerNavigationService.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/ExplorerTreePathProvider.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/api/IExplorerNavigationService.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/configuration/ExplorerDescriptionProviderConfiguration.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/trees/ExplorerNonSemanticElementControllerTests.java
  packages/trees/backend/sirius-components-trees/src/main/java/org/eclipse/sirius/components/trees/description/TreeDescription.java
Labels: pr: to review soon, priority: high

#3874 [doc] Add shape to extend the explorer to support multiple presentations
  CHANGELOG.adoc
  doc/iterations/2024.9/extend_explorer_to support_multiple_presentations.adoc
  doc/iterations/2024.9/images/multiple_explorers_action.png
  doc/iterations/2024.9/images/multiple_explorers_menu.png
Labels: pr: to review soon, priority: high

#3837 [3815] Child creation descriptions are locale independent
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/deck/deck.cy.ts
  integration-tests/cypress/e2e/project/details/form.cy.ts
  integration-tests/cypress/e2e/project/diagrams/collapse.cy.ts
  integration-tests/cypress/e2e/project/diagrams/custom-shape.cy.ts
  integration-tests/cypress/e2e/project/diagrams/diagram-contextual-palette.cy.js
  integration-tests/cypress/e2e/project/diagrams/diagram-label.cy.ts
  integration-tests/cypress/e2e/project/diagrams/direct-edit-label.cy.ts
  integration-tests/cypress/e2e/project/diagrams/edges.cy.ts
  integration-tests/cypress/e2e/project/diagrams/graphical-dnd.cy.ts
  integration-tests/cypress/e2e/project/diagrams/group-palette.cy.ts
  integration-tests/cypress/e2e/project/diagrams/list-node.cy.ts
  integration-tests/cypress/e2e/project/diagrams/node-aspect-ratio.cy.ts
  integration-tests/cypress/e2e/project/explorer/document-context-menu.cy.js
  integration-tests/cypress/e2e/project/explorer/object-context-menu.cy.js
  integration-tests/cypress/e2e/project/formdescriptioneditor/formdescriptioneditor.cy.js
  integration-tests/cypress/e2e/project/forms/widget-reference.cy.ts
  integration-tests/cypress/e2e/project/studio/color-palette.cy.js
  integration-tests/cypress/e2e/project/studio/studio.cy.ts
  integration-tests/cypress/workbench/Deck.ts
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/services/DefaultEditService.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/objects/ObjectCreationControllerIntegrationTests.java
Labels: pr: to review later, priority: low

#3881 [3880] Make some tests methods more generic
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-tests/src/main/java/org/eclipse/sirius/web/tests/services/api/IGivenCreatedDeckSubscription.java
  packages/sirius-web/backend/sirius-web-tests/src/main/java/org/eclipse/sirius/web/tests/services/api/IGivenCreatedDiagramSubscription.java
  packages/sirius-web/backend/sirius-web-tests/src/main/java/org/eclipse/sirius/web/tests/services/api/IGivenCreatedFormDescriptionEditorSubscription.java
  packages/sirius-web/backend/sirius-web-tests/src/main/java/org/eclipse/sirius/web/tests/services/api/IGivenCreatedFormSubscription.java
  packages/sirius-web/backend/sirius-web-tests/src/main/java/org/eclipse/sirius/web/tests/services/api/IGivenCreatedGanttSubscription.java
  packages/sirius-web/backend/sirius-web-tests/src/main/java/org/eclipse/sirius/web/tests/services/deck/GivenCreatedDeckSubscription.java
  packages/sirius-web/backend/sirius-web-tests/src/main/java/org/eclipse/sirius/web/tests/services/diagrams/GivenCreatedDiagramSubscription.java
  packages/sirius-web/backend/sirius-web-tests/src/main/java/org/eclipse/sirius/web/tests/services/formdescriptioneditors/GivenCreatedFormDescriptionEditorSubscription.java
  packages/sirius-web/backend/sirius-web-tests/src/main/java/org/eclipse/sirius/web/tests/services/forms/GivenCreatedFormSubscription.java
  packages/sirius-web/backend/sirius-web-tests/src/main/java/org/eclipse/sirius/web/tests/services/gantt/GivenCreatedGanttSubscription.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/deck/PapayaDeckControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/CustomImageDiagramControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/CustomNodesDiagramControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/DiagramFilterControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/DomainDiagramControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/DropNodeControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/EdgeControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/EditLabelDiagramControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/ExpandCollapseDiagramControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/ModelOperationDiagramControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/PaletteControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/UnsynchronizedDiagramControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/VisibilityDiagramControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/formdescriptioneditors/FormDescriptionEditorControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/formdescriptioneditors/FormDescriptionEditorLifecycleControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/forms/CheckboxControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/forms/DateTimeControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/forms/FormControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/forms/HelpTextControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/forms/LinkControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/forms/ListControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/forms/RadioControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/forms/ReferenceWidgetControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/forms/RichTextControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/forms/SliderControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/forms/TextfieldControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/forms/TitleExpressionControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/gantt/GanttLifecycleControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/gantt/PapayaGanttControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/hierarchy/HierarchyLifecycleControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/portal/PortalControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/selection/SelectionControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/api/IGivenCreatedHierarchySubscription.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/api/IGivenCreatedPortalSubscription.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/hierarchy/GivenCreatedHierarchySubscription.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/portals/GivenCreatedPortalSubscription.java
Labels: pr: to review soon, priority: high

#3883 [3849] Trees in forms can display the same element many times
  CHANGELOG.adoc
  packages/forms/frontend/sirius-components-forms/src/propertysections/TreePropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/TreePropertySection.types.ts
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/TreePropertySection.test.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/TreePropertySection.test.tsx.snap
Labels: pr: to review soon, priority: high

#3890 [3878] Unmount ReactFlowProvider after layout
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/layout.tsx
Labels: pr: to review soon, priority: high

#3891 [3869] Close form-based views when the underlying element no longer exists
  CHANGELOG.adoc
  packages/sirius-web/frontend/sirius-web-application/src/diagrams/DiagramFilterForm.tsx
  packages/sirius-web/frontend/sirius-web-application/src/diagrams/useDiagramFilterSubscription.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/DetailsView.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/RelatedElementsView.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/RepresentationsView.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/useDetailsViewSubscription.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/useRelatedElementsViewSubscription.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/useRepresentationsViewSubscription.tsx
Labels: pr: to review soon, priority: low

#3723 [doc] Add initial ADR for the selection dialog as a tree
  CHANGELOG.adoc
  doc/adrs/155_make_it_possible_to_display_the_semantic_elements_as_a_tree_in_the_selection_dialog.adoc
  doc/adrs/156_make_it_possible_to_display_the_semantic_elements_as_a_tree_in_the_selection_dialog.adoc
  doc/adrs/images/155/currentSelectionDialog.png
  doc/adrs/images/155/referenceWidgetSemanticBrowser.png
Labels: pr: to review later, priority: high, type: documentation

#3901 [cleanup] Dispose editing context immediately when a project is deleted
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/controllers/MutationDeleteProjectDataFetcher.java
Labels: pr: to review later, priority: low

#3903 [3902] Move the Help menu entry at the last position
  CHANGELOG.adoc
  packages/sirius-web/frontend/sirius-web-application/src/navigationBar/NavigationBarMenu.tsx
Labels: pr: to review later, priority: low

#3940 [fix] Fix the svg id for some flow svg
  packages/starters/backend/sirius-components-flow-starter/src/main/java/org/eclipse/sirius/components/flow/starter/view/FlowViewBuilder.java
Labels: pr: to review soon, priority: low
