Repository eclipse-sirius/sirius-web, pull requests merged in 2024-02, with the labels that each got.

#2876 [2875] Make the Representations view a plain FormBasedView
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/related-elements/related-elements-view.cy.js
  packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/RepresentationsEventProcessorFactory.java
  packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/api/RepresentationsConfiguration.java
  packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/dto/RepresentationsEventInput.java
  packages/forms/backend/sirius-components-collaborative-forms/src/main/resources/schema/form.graphqls
  packages/forms/backend/sirius-components-forms-graphql/src/main/java/org/eclipse/sirius/components/forms/graphql/datafetchers/subscription/SubscriptionRepresentationsEventDataFetcher.java
  packages/forms/frontend/sirius-components-forms/src/views/FormBasedView.tsx
  packages/forms/frontend/sirius-components-forms/src/views/FormBasedView.types.tsx
  packages/forms/frontend/sirius-components-forms/src/views/RelatedElementsView.tsx
  packages/forms/frontend/sirius-components-forms/src/views/RepresentationsView.tsx
  packages/forms/frontend/sirius-components-forms/src/views/RepresentationsViewMachine.ts
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/representations/RepresentationsDescriptionProvider.java
Labels: pr: to review later, priority: low

#2742 [2732] Add support for success messages feedback on tool actions
  CHANGELOG.adoc
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/FadeDiagramElementEventHandler.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/HideDiagramElementEventHandler.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/test/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/ChangeVisibilityEventHandlerTests.java
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/connector/ConnectorContextualMenu.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/connector/ConnectorContextualMenu.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/fade/useFadeDiagramElements.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/fade/useFadeDiagramElements.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/hide/useHideDiagramElements.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/hide/useHideDiagramElements.types.ts
Labels: pr: to review later, priority: low

#3025 [3024] Contribute a new Papaya Diagram
  CHANGELOG.adoc
  doc/screenshots/deploymenDiagram.png
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/EdgeComponent.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/domain/PapayaDomainProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/PapayaViewProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/logicalarchitecture/exchange/CEDComponentExchangeEdgeProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/logicalarchitecture/exchange/CEDComponentNodeProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/logicalarchitecture/exchange/CEDComponentPortNodeProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/logicalarchitecture/exchange/ComponentExchangeDiagramProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/services/PapayaService.java
Labels: pr: to review later, priority: low

#3071 [doc] Fix recent ADR number duplicate
  CHANGELOG.adoc
  doc/adrs/044_use_border_node_snap_to_container_algorithm.adoc
  doc/adrs/125_common_share_representation_modal.adoc
  doc/adrs/126_add_the_ability_to_reuse_both_the_sirius_web_frontend_and_backend_easily.adoc
  doc/adrs/127_add_the_ability_to_extend_the_sirius_web_frontend.adoc
  doc/adrs/128_add_the_ability_to_extend_the_sirius_web_backend.adoc
Labels: pr: to review soon, priority: low

#3054 [3052] ConnectionTargetHandle renders when reconnecting
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/connector/useConnector.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/connector/useConnector.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/handles/ConnectionTargetHandle.tsx
Labels: pr: to review soon, priority: low

#3060 [3030] Fix palette position when multiple diagrams are open
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/PalettePortal.tsx
Labels: pr: to review later, priority: low

#3039 [3033] Implement the Lane DnD on Deck representation
  CHANGELOG.adoc
  packages/deck/backend/sirius-components-collaborative-deck/src/main/java/org/eclipse/sirius/components/collaborative/deck/api/IDeckLaneService.java
  packages/deck/backend/sirius-components-collaborative-deck/src/main/java/org/eclipse/sirius/components/collaborative/deck/dto/input/DropDeckLaneInput.java
  packages/deck/backend/sirius-components-collaborative-deck/src/main/java/org/eclipse/sirius/components/collaborative/deck/handlers/DropDeckLaneEventHandler.java
  packages/deck/backend/sirius-components-collaborative-deck/src/main/java/org/eclipse/sirius/components/collaborative/deck/service/DeckLaneService.java
  packages/deck/backend/sirius-components-collaborative-deck/src/main/resources/schema/deck.graphqls
  packages/deck/backend/sirius-components-deck-graphql/src/main/java/org/eclipse/sirius/components/deck/graphql/datafetchers/mutation/MutationDropDeckLaneDataFetcher.java
  packages/deck/backend/sirius-components-deck/src/main/java/org/eclipse/sirius/components/deck/description/DeckDescription.java
  packages/deck/frontend/sirius-components-deck/src/Deck.tsx
  packages/deck/frontend/sirius-components-deck/src/Deck.types.ts
  packages/deck/frontend/sirius-components-deck/src/representation/DeckRepresentation.tsx
  packages/deck/frontend/sirius-components-deck/src/representation/deckMutation.ts
  packages/deck/frontend/sirius-components-deck/src/representation/deckMutation.types.ts
  packages/deck/frontend/sirius-components-deck/src/utils/deckGQLHelper.tsx
  packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/configuration/view/TaskJavaService.java
  packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/configuration/view/ViewDeckDescriptionBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/DeckBuilders.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/DeckDescriptionBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/LaneDropToolBuilder.java
  packages/view/backend/sirius-components-view-deck-edit/src/main/java/org/eclipse/sirius/components/view/deck/provider/CardDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-deck-edit/src/main/java/org/eclipse/sirius/components/view/deck/provider/DeckDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-deck-edit/src/main/java/org/eclipse/sirius/components/view/deck/provider/DeckItemProviderAdapterFactory.java
  packages/view/backend/sirius-components-view-deck-edit/src/main/java/org/eclipse/sirius/components/view/deck/provider/LaneDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-deck-edit/src/main/java/org/eclipse/sirius/components/view/deck/provider/LaneDropToolItemProvider.java
  packages/view/backend/sirius-components-view-deck-edit/src/main/resources/icons/full/obj16/LaneDropTool.svg
  packages/view/backend/sirius-components-view-deck-edit/src/main/resources/plugin.properties
  packages/view/backend/sirius-components-view-deck/src/main/java/org/eclipse/sirius/components/view/deck/DeckDescription.java
  packages/view/backend/sirius-components-view-deck/src/main/java/org/eclipse/sirius/components/view/deck/DeckFactory.java
  packages/view/backend/sirius-components-view-deck/src/main/java/org/eclipse/sirius/components/view/deck/DeckPackage.java
  packages/view/backend/sirius-components-view-deck/src/main/java/org/eclipse/sirius/components/view/deck/LaneDropTool.java
  packages/view/backend/sirius-components-view-deck/src/main/java/org/eclipse/sirius/components/view/deck/impl/DeckDescriptionImpl.java
  packages/view/backend/sirius-components-view-deck/src/main/java/org/eclipse/sirius/components/view/deck/impl/DeckFactoryImpl.java
  packages/view/backend/sirius-components-view-deck/src/main/java/org/eclipse/sirius/components/view/deck/impl/DeckPackageImpl.java
  packages/view/backend/sirius-components-view-deck/src/main/java/org/eclipse/sirius/components/view/deck/impl/LaneDropToolImpl.java
  packages/view/backend/sirius-components-view-deck/src/main/java/org/eclipse/sirius/components/view/deck/util/DeckAdapterFactory.java
  packages/view/backend/sirius-components-view-deck/src/main/java/org/eclipse/sirius/components/view/deck/util/DeckSwitch.java
  packages/view/backend/sirius-components-view-deck/src/main/resources/model/deck.ecore
  packages/view/backend/sirius-components-view-deck/src/main/resources/model/deck.genmodel
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/task/ViewDeckDescriptionConverter.java
Labels: pr: to review later, priority: low

#2845 [2823] Add the possibility to resize node smaller than its default size
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/diagrams/graphical-dnd.cy.ts
  integration-tests/cypress/e2e/project/diagrams/node-aspect-ratio.cy.js
  integration-tests/cypress/e2e/project/diagrams/node-aspect-ratio.cy.ts
  integration-tests/cypress/workbench/Diagram.ts
  integration-tests/cypress/workbench/Explorer.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/ImageNodeLayoutHandler.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/ListNodeLayoutHandler.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/RectangleNodeLayoutHandler.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/bounds.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/layoutNode.ts
  packages/sirius-web/frontend/sirius-web/src/nodes/EllipseNodeLayoutHandler.ts
Labels: pr: to review soon, priority: high

#3067 [1844] Unload resources by default when the EMF based editing context is disposed
  CHANGELOG.adoc
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/services/api/IEMFEditingContext.java
Labels: pr: to review soon, priority: high

#3072 [3020] Improve the creation of the Apollo GraphQL client
  CHANGELOG.adoc
  packages/sirius-web/frontend/sirius-web-application/src/ApolloGraphQLClient.tsx
  packages/sirius-web/frontend/sirius-web-application/src/application/SiriusWebApplication.tsx
  packages/sirius-web/frontend/sirius-web-application/src/graphql/ApolloGraphQLProvider.tsx
  packages/sirius-web/frontend/sirius-web-application/src/graphql/ApolloGraphQLProvider.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/graphql/useCreateApolloClient.ts
  packages/sirius-web/frontend/sirius-web-application/src/graphql/useCreateApolloClient.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/graphql/useCreateApolloClientExtensionPoints.tsx
  packages/sirius-web/frontend/sirius-web-application/src/index.ts
Labels: pr: to review soon, priority: high

#3026 [2606] Simplify the addition of elements to a filled list node
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/diagrams/list-node.cy.ts
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/resources/schema/diagram.graphqls
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/ListLayoutStrategy.java
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/ListNodeConverter.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/graphql/subscription/nodeFragment.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/graphql/subscription/nodeFragment.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/ListNodeLayoutHandler.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/node/ListNode.types.ts
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/ListLayoutStrategyDescriptionBuilder.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/ListLayoutStrategyDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/resources/plugin.properties
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/DiagramPackage.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/ListLayoutStrategyDescription.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/DiagramPackageImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/ListLayoutStrategyDescriptionImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/resources/model/diagram.ecore
  packages/view/backend/sirius-components-view-diagram/src/main/resources/model/diagram.genmodel
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewDiagramDescriptionConverter.java
Labels: pr: to review soon, priority: low

#3046 [doc] Add shape and ADR about the confirmation dialog on delete
  CHANGELOG.adoc
  doc/adrs/129_add_support_for_confirmation_dialogs.adoc
  doc/iterations/2024.3/shapes/confirmation_dialog_on_delete.adoc
  doc/iterations/2024.3/shapes/images/delete_dialog/delete_dialog.svg
Labels: pr: to review soon, priority: high

#3058 [doc] Contribute an ADR to support outside and inside node labels
  CHANGELOG.adoc
  doc/adrs/130_add_support_for_outside_inside_node_labels.adoc
Labels: pr: to review soon, priority: low

#3055 [doc] Contribute ADR on filtering diagram elements
  CHANGELOG.adoc
  doc/adrs/131_add_more_filtering_capabilities_on_diagram.adoc
  doc/iterations/2024.3/shapes/filter_diagram_elements.adoc
  doc/iterations/2024.3/shapes/images/filter_diagram_elements/filterElementPalette.png
  doc/iterations/2024.3/shapes/images/filter_diagram_elements/filterElementRepresentation.png
Labels: pr: to review soon, priority: low

#3049 [doc] Add shape and ADR about filters in Explorer view
  CHANGELOG.adoc
  doc/adrs/132_add_support_for_filters_in_explorer_view.adoc
  doc/iterations/2024.3/shapes/add_filters_on_explorer_view.adoc
  doc/iterations/2024.3/shapes/images/explorer_view_filters/explorer_view_filters.svg
Labels: pr: to review soon, priority: high

#3043 [3042] Split EObjectServices in smaller services
  CHANGELOG.adoc
  doc/adrs/134_split_IObjectService in smaller services.adoc
  packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/api/IContentService.java
  packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/api/IContentServiceDelegate.java
  packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/api/IDefaultContentService.java
  packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/api/IDefaultIdentityService.java
  packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/api/IDefaultLabelService.java
  packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/api/IDefaultObjectSearchService.java
  packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/api/IIdentityService.java
  packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/api/IIdentityServiceDelegate.java
  packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/api/ILabelService.java
  packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/api/ILabelServiceDelegate.java
  packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/api/IObjectSearchService.java
  packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/api/IObjectSearchServiceDelegate.java
  packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/services/ComposedContentService.java
  packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/services/ComposedIdentityService.java
  packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/services/ComposedLabelService.java
  packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/services/ComposedObjectSearchService.java
  packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/services/ComposedObjectService.java
  packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/services/ObjectService.java
  packages/core/backend/sirius-components-core/src/test/java/org/eclipse/sirius/components/core/architecture/ComposedIdentityServiceTests.java
  packages/core/backend/sirius-components-core/src/test/java/org/eclipse/sirius/components/core/architecture/ComposedObjectServiceTests.java
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/services/DefaultContentService.java
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/services/DefaultIdentityService.java
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/services/DefaultLabelService.java
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/services/DefaultObjectSearchService.java
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/services/DefaultObjectService.java
  packages/emf/backend/sirius-components-emf/src/test/java/org/eclipse/sirius/components/emf/services/DefaultIdentityServiceTests.java
  packages/emf/backend/sirius-components-emf/src/test/java/org/eclipse/sirius/components/emf/services/DefaultLabelServiceTests.java
  packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/browser/ModelBrowsersDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/object/ObjectIdDataFetcher.java
  packages/sirius-web/backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/object/ObjectKindDataFetcher.java
  packages/sirius-web/backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/object/ObjectLabelDataFetcher.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/services/PapayaService.java
  packages/sirius-web/backend/sirius-web-sample-application/src/test/java/org/eclipse/sirius/web/sample/tests/DynamicWidgetsTests.java
  packages/sirius-web/backend/sirius-web-sample-application/src/test/java/org/eclipse/sirius/web/sample/tests/ViewDetailsRenderingIntegrationTests.java
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/explorer/DeleteObjectTreeItemEventHandler.java
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/explorer/ExpandAllTreePathProvider.java
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/explorer/ExplorerDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/representations/RepresentationService.java
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/representations/ViewRepresentationDescriptionSearchService.java
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/representations/ViewRepresentationDescriptionSearchServiceParameters.java
  packages/sirius-web/backend/sirius-web-services/src/test/java/org/eclipse/sirius/web/services/explorer/ExpandAllTreePathProviderTests.java
  packages/starters/backend/sirius-components-flow-starter/src/main/java/org/eclipse/sirius/components/flow/starter/services/FlowService.java
  packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/configuration/TaskLabelServiceDelegate.java
Labels: pr: to review later, priority: low

#3097 [doc] Fix image location in CHANGELOG
  CHANGELOG.adoc
Labels: pr: to review later, priority: low

#3068 [3066] Add support for representations in DefaultObjectService
  CHANGELOG.adoc
  doc/adrs/135_representations_in_object_related_services.adoc
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/api/IRepresentationSearchService.java
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/services/DefaultIdentityService.java
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/services/DefaultLabelService.java
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/services/DefaultObjectSearchService.java
  packages/emf/backend/sirius-components-emf/src/test/java/org/eclipse/sirius/components/emf/services/DefaultLabelServiceTests.java
  packages/sirius-web/backend/sirius-web-sample-application/src/test/java/org/eclipse/sirius/web/sample/tests/DynamicWidgetsTests.java
  packages/sirius-web/backend/sirius-web-sample-application/src/test/java/org/eclipse/sirius/web/sample/tests/ViewDetailsRenderingIntegrationTests.java
  packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/configuration/TaskLabelServiceDelegate.java
Labels: pr: to review soon, priority: high

#3040 [enh] Use MUI tooltips for Portal toolbar elements
  CHANGELOG.adoc
  packages/portals/frontend/sirius-components-portals/src/representations/PortalToolbar.tsx
Labels: pr: to review later, priority: low

#3092 [3089] Add Confirmation Dialog on delete
  CHANGELOG.adoc
  doc/screenshots/showDeletionConfirmation.png
  integration-tests/cypress/e2e/project/diagrams/custom-shape.cy.ts
  integration-tests/cypress/e2e/project/diagrams/diagram-context-menu.cy.js
  integration-tests/cypress/e2e/project/diagrams/diagram-contextual-palette.cy.js
  integration-tests/cypress/e2e/project/diagrams/diagram.reactflow.cy.js
  integration-tests/cypress/e2e/project/diagrams/direct-edit-label.cy.ts
  integration-tests/cypress/e2e/project/explorer/document-context-menu.cy.js
  integration-tests/cypress/e2e/project/explorer/explorer-filterbar.cy.js
  integration-tests/cypress/e2e/project/explorer/object-context-menu.cy.js
  integration-tests/cypress/e2e/project/formdescriptioneditor/formdescriptioneditor.cy.js
  integration-tests/cypress/e2e/project/forms/widget-reference.cy.ts
  integration-tests/cypress/e2e/project/portals/portals.cy.ts
  integration-tests/cypress/e2e/project/representations.cy.ts
  integration-tests/cypress/e2e/project/studio/studio.cy.ts
  integration-tests/cypress/pages/Project.ts
  integration-tests/cypress/workbench/Deck.ts
  packages/core/frontend/sirius-components-core/src/index.ts
  packages/core/frontend/sirius-components-core/src/modals/confirmation/ConfirmationDialog.tsx
  packages/core/frontend/sirius-components-core/src/modals/confirmation/ConfirmationDialog.types.ts
  packages/core/frontend/sirius-components-core/src/modals/confirmation/ConfirmationDialogContext.tsx
  packages/core/frontend/sirius-components-core/src/modals/confirmation/ConfirmationDialogContext.types.ts
  packages/core/frontend/sirius-components-core/src/modals/confirmation/useConfirmationDialog.tsx
  packages/core/frontend/sirius-components-core/src/modals/confirmation/useConfirmationDialog.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/delete/useDiagramDelete.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/Palette.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/Group.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/PageList.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/WidgetEntry.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/__tests__/Group.test.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/__tests__/Page.test.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/__tests__/WidgetEntry.test.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/ListPropertySection.tsx
  packages/forms/frontend/sirius-components-widget-reference/src/ReferencePropertySection.tsx
  packages/sirius-web/frontend/sirius-web-application/src/application/SiriusWebApplication.tsx
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItemContextMenu.tsx
Labels: pr: to review soon, priority: high

#3104 [3100] Add support for drop on IconLabelNode
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/node/IconLabelNode.tsx
Labels: pr: to review soon, priority: high

#3080 [3079] Add a name attribute on deck view descriptions
  CHANGELOG.adoc
  packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/configuration/view/ViewDeckDescriptionBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/CardDescriptionBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/DeckElementDescriptionBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/LaneDescriptionBuilder.java
  packages/view/backend/sirius-components-view-deck-edit/src/main/java/org/eclipse/sirius/components/view/deck/provider/CardDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-deck-edit/src/main/java/org/eclipse/sirius/components/view/deck/provider/DeckElementDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-deck-edit/src/main/java/org/eclipse/sirius/components/view/deck/provider/LaneDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-deck-edit/src/main/resources/plugin.properties
  packages/view/backend/sirius-components-view-deck/src/main/java/org/eclipse/sirius/components/view/deck/CardDescription.java
  packages/view/backend/sirius-components-view-deck/src/main/java/org/eclipse/sirius/components/view/deck/DeckElementDescription.java
  packages/view/backend/sirius-components-view-deck/src/main/java/org/eclipse/sirius/components/view/deck/DeckPackage.java
  packages/view/backend/sirius-components-view-deck/src/main/java/org/eclipse/sirius/components/view/deck/LaneDescription.java
  packages/view/backend/sirius-components-view-deck/src/main/java/org/eclipse/sirius/components/view/deck/impl/CardDescriptionImpl.java
  packages/view/backend/sirius-components-view-deck/src/main/java/org/eclipse/sirius/components/view/deck/impl/DeckElementDescriptionImpl.java
  packages/view/backend/sirius-components-view-deck/src/main/java/org/eclipse/sirius/components/view/deck/impl/DeckPackageImpl.java
  packages/view/backend/sirius-components-view-deck/src/main/java/org/eclipse/sirius/components/view/deck/impl/LaneDescriptionImpl.java
  packages/view/backend/sirius-components-view-deck/src/main/java/org/eclipse/sirius/components/view/deck/util/DeckAdapterFactory.java
  packages/view/backend/sirius-components-view-deck/src/main/java/org/eclipse/sirius/components/view/deck/util/DeckSwitch.java
  packages/view/backend/sirius-components-view-deck/src/main/resources/model/deck.ecore
  packages/view/backend/sirius-components-view-deck/src/main/resources/model/deck.genmodel
Labels: pr: to review soon, priority: low

#3108 [fix] Fix initial schema configuration script
  packages/sirius-web/backend/sirius-web-infrastructure/src/main/resources/db/changelog/2024.01/01-initial-schema.xml
Labels: pr: to review soon, priority: high

#3125 [3124] Fix an issue that prevents manual line break in a node label
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/Label.tsx
  packages/sirius-web/frontend/sirius-web-application/src/index.ts
Labels: pr: to review soon, priority: high

#3131 [fix] Fix absolute import in sirius-web-application
  packages/sirius-web/frontend/sirius-web-application/src/diagrams/DiagramRepresentationConfiguration.tsx
Labels: pr: to review later, priority: low

#3106 [3105] Upgrade react-trello to 2.4.11
  CHANGELOG.adoc
  package-lock.json
  packages/deck/frontend/sirius-components-deck/package.json
  packages/sirius-web/frontend/sirius-web/package.json
Labels: pr: to review soon, priority: high

#3130 [fix] Standardize font size for every OnboardArea cards
  packages/sirius-web/frontend/sirius-web-application/src/onboarding/NewDocumentArea.tsx
  packages/sirius-web/frontend/sirius-web-application/src/onboarding/NewRepresentationArea.tsx
  packages/sirius-web/frontend/sirius-web-application/src/onboarding/RepresentationsArea.tsx
Labels: pr: to review later, priority: low

#3142 [3141] Make the header of portal-embedded representations sticky
  CHANGELOG.adoc
  packages/portals/frontend/sirius-components-portals/src/representations/RepresentationFrame.tsx
Labels: pr: to review soon, priority: low

#3146 [doc] Update README with token instructions for frontend part
  .github/workflows/build.yml
  .github/workflows/pull-request.yml
  README.adoc
Labels: pr: to review soon, priority: high

#3148 [3143] Use Icon URLs Expression to provide EdgeTool icon
  CHANGELOG.adoc
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ToolConverter.java
Labels: pr: to review later, priority: low

#3139 [fix] Export Sirius Web Application props
  packages/sirius-web/frontend/sirius-web-application/src/index.ts
Labels: pr: to review soon, priority: high

#3129 [releng] Remove sirius-components-diagrams-reactflow from build.yml
  .github/workflows/build.yml
Labels: pr: to review later, priority: low

#3167 [3166] Fix Label Edit Tool on outside Labels
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/direct-edit/useDiagramDirectEdit.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/node/FreeFormNode.tsx
Labels: pr: to review soon, priority: high

#3172 [1707] Fix click while editing tree item label ends the edition
  CHANGELOG.adoc
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItem.tsx
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItem.types.ts
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItemDirectEditInput.tsx
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItemDirectEditInput.types.ts
Labels: pr: to review soon, priority: high
