Repository eclipse-sirius/sirius-web, pull requests merged in 2024-04, with the labels that each got.

#3299 [3298] Avoid unnecessary rendering
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/group-tool/useGroupPalette.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/reconnect-edge/useReconnectEdge.tsx
Labels: pr: to review soon, priority: high

#3316 [releng] Use docker compose v2
  .github/workflows/build.yml
  CHANGELOG.adoc
Labels: pr: to review soon, priority: high

#3311 [3309] Hide header border-bottom when the node is collapsed
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/diagrams/collapse.cy.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/ImageNodeConverter.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/ListNodeConverter.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/RectangleNodeConverter.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/convertLabel.ts
Labels: pr: to review soon, priority: low

#3266 [3265] Fix an error on console when moving a node with an opened palette
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/diagrams/diagram.reactflow.cy.js
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx
Labels: pr: to review later, priority: low

#3332 [3285] Change icons color to match Sirius Web default theme
  CHANGELOG.adoc
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/resources/diagram-images/collapse.svg
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/resources/diagram-images/edit.svg
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/resources/diagram-images/expand.svg
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/resources/diagram-images/graphicalDelete.svg
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/resources/diagram-images/semanticDelete.svg
Labels: pr: to review soon, priority: high

#3270 [3269] Disables node dragging during multi selection
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/dropNode/useDropNode.ts
Labels: pr: to review later, priority: low

#3345 [test] Fix some flaky Cypress tests
  integration-tests/cypress/e2e/project/diagrams/group-palette.cy.ts
  integration-tests/cypress/e2e/project/diagrams/node-aspect-ratio.cy.ts
Labels: pr: to review soon, priority: high

#3294 Add support for task dependency creation tool
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/gantt/gantt-task.cy.ts
  package-lock.json
  packages/gantt/backend/sirius-components-collaborative-gantt/src/main/java/org/eclipse/sirius/components/collaborative/gantt/api/IGanttTaskService.java
  packages/gantt/backend/sirius-components-collaborative-gantt/src/main/java/org/eclipse/sirius/components/collaborative/gantt/dto/input/CreateGanttTaskDependencyInput.java
  packages/gantt/backend/sirius-components-collaborative-gantt/src/main/java/org/eclipse/sirius/components/collaborative/gantt/handlers/CreateTaskDependencyEventHandler.java
  packages/gantt/backend/sirius-components-collaborative-gantt/src/main/java/org/eclipse/sirius/components/collaborative/gantt/service/GanttTaskService.java
  packages/gantt/backend/sirius-components-collaborative-gantt/src/main/resources/schema/gantt.graphqls
  packages/gantt/backend/sirius-components-gantt-graphql/src/main/java/org/eclipse/sirius/components/gantt/graphql/datafetchers/mutation/MutationCreateTaskDependencyDataFetcher.java
  packages/gantt/backend/sirius-components-gantt/src/main/java/org/eclipse/sirius/components/gantt/Task.java
  packages/gantt/backend/sirius-components-gantt/src/main/java/org/eclipse/sirius/components/gantt/description/GanttDescription.java
  packages/gantt/backend/sirius-components-gantt/src/main/java/org/eclipse/sirius/components/gantt/description/TaskDescription.java
  packages/gantt/backend/sirius-components-gantt/src/main/java/org/eclipse/sirius/components/gantt/renderer/component/TaskDescriptionComponent.java
  packages/gantt/frontend/sirius-components-gantt/package.json
  packages/gantt/frontend/sirius-components-gantt/src/graphql/mutation/GanttMutation.types.ts
  packages/gantt/frontend/sirius-components-gantt/src/graphql/mutation/ganttMutation.ts
  packages/gantt/frontend/sirius-components-gantt/src/graphql/mutation/useGanttMutations.ts
  packages/gantt/frontend/sirius-components-gantt/src/graphql/subscription/GanttSubscription.types.ts
  packages/gantt/frontend/sirius-components-gantt/src/graphql/subscription/ganttSubscription.ts
  packages/gantt/frontend/sirius-components-gantt/src/helper/helper.tsx
  packages/gantt/frontend/sirius-components-gantt/src/representation/Gantt.tsx
  packages/gantt/frontend/sirius-components-gantt/src/representation/Gantt.types.ts
  packages/gantt/frontend/sirius-components-gantt/src/representation/GanttRepresentation.tsx
  packages/sirius-web/frontend/sirius-web/package.json
  packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/configuration/view/ViewGanttDescriptionBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/CreateTaskDependencyToolBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/CreateTaskToolBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/DeleteTaskToolBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/DropTaskToolBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/EditTaskToolBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/GanttBuilders.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/GanttDescriptionBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/TaskDescriptionBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/TaskToolBuilder.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/task/ViewGanttDescriptionConverter.java
  packages/view/backend/sirius-components-view-gantt-edit/src/main/java/org/eclipse/sirius/components/view/gantt/provider/CreateTaskDependencyToolItemProvider.java
  packages/view/backend/sirius-components-view-gantt-edit/src/main/java/org/eclipse/sirius/components/view/gantt/provider/GanttDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-gantt-edit/src/main/java/org/eclipse/sirius/components/view/gantt/provider/GanttItemProviderAdapterFactory.java
  packages/view/backend/sirius-components-view-gantt-edit/src/main/java/org/eclipse/sirius/components/view/gantt/provider/TaskDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-gantt-edit/src/main/java/org/eclipse/sirius/components/view/gantt/provider/TaskToolItemProvider.java
  packages/view/backend/sirius-components-view-gantt-edit/src/main/resources/icons/full/obj16/CreateTaskDependencyTool.svg
  packages/view/backend/sirius-components-view-gantt-edit/src/main/resources/plugin.properties
  packages/view/backend/sirius-components-view-gantt/src/main/java/org/eclipse/sirius/components/view/gantt/CreateTaskDependencyTool.java
  packages/view/backend/sirius-components-view-gantt/src/main/java/org/eclipse/sirius/components/view/gantt/GanttDescription.java
  packages/view/backend/sirius-components-view-gantt/src/main/java/org/eclipse/sirius/components/view/gantt/GanttFactory.java
  packages/view/backend/sirius-components-view-gantt/src/main/java/org/eclipse/sirius/components/view/gantt/GanttPackage.java
  packages/view/backend/sirius-components-view-gantt/src/main/java/org/eclipse/sirius/components/view/gantt/TaskDescription.java
  packages/view/backend/sirius-components-view-gantt/src/main/java/org/eclipse/sirius/components/view/gantt/TaskTool.java
  packages/view/backend/sirius-components-view-gantt/src/main/java/org/eclipse/sirius/components/view/gantt/impl/CreateTaskDependencyToolImpl.java
  packages/view/backend/sirius-components-view-gantt/src/main/java/org/eclipse/sirius/components/view/gantt/impl/GanttDescriptionImpl.java
  packages/view/backend/sirius-components-view-gantt/src/main/java/org/eclipse/sirius/components/view/gantt/impl/GanttFactoryImpl.java
  packages/view/backend/sirius-components-view-gantt/src/main/java/org/eclipse/sirius/components/view/gantt/impl/GanttPackageImpl.java
  packages/view/backend/sirius-components-view-gantt/src/main/java/org/eclipse/sirius/components/view/gantt/impl/TaskDescriptionImpl.java
  packages/view/backend/sirius-components-view-gantt/src/main/java/org/eclipse/sirius/components/view/gantt/impl/TaskToolImpl.java
  packages/view/backend/sirius-components-view-gantt/src/main/java/org/eclipse/sirius/components/view/gantt/util/GanttAdapterFactory.java
  packages/view/backend/sirius-components-view-gantt/src/main/java/org/eclipse/sirius/components/view/gantt/util/GanttSwitch.java
  packages/view/backend/sirius-components-view-gantt/src/main/resources/model/gantt.ecore
  packages/view/backend/sirius-components-view-gantt/src/main/resources/model/gantt.genmodel
  scripts/check-coverage.jsh
Labels: pr: to review soon, priority: low

#3350 [3349] Add a default insideLabel when creating a NodeDescription
  CHANGELOG.adoc
  packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/DefaultToolsFactory.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/DiagramDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/NodeDescriptionItemProvider.java
Labels: pr: to review soon, priority: low

#3357 [3279] Restore support for document download
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/controllers/DocumentDownloadController.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/services/XMLDocumentExporter.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/services/api/IDocumentExporter.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/documents/DocumentDownloadControllerIntegrationTests.java
  scripts/check-coverage.jsh
Labels: pr: to review soon, priority: high

#3353 [3352] Check previousNode to determine pin status
  CHANGELOG.adoc
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/NodeComponent.java
  packages/diagrams/backend/sirius-components-diagrams/src/test/java/org/eclipse/sirius/components/diagrams/renderer/DiagramRendererNodeTests.java
Labels: pr: to review soon, priority: low

#3343 Update Deck views
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/deck/deck-lane.cy.ts
  packages/deck/backend/sirius-components-deck/src/main/java/org/eclipse/sirius/components/deck/description/CardDescription.java
  packages/deck/backend/sirius-components-deck/src/main/java/org/eclipse/sirius/components/deck/description/LaneDescription.java
  packages/deck/backend/sirius-components-deck/src/main/java/org/eclipse/sirius/components/deck/renderer/component/CardComponent.java
  packages/deck/backend/sirius-components-deck/src/main/java/org/eclipse/sirius/components/deck/renderer/component/LaneComponent.java
  packages/gantt/backend/sirius-components-gantt/src/main/java/org/eclipse/sirius/components/gantt/description/TaskDescription.java
  packages/gantt/backend/sirius-components-gantt/src/main/java/org/eclipse/sirius/components/gantt/renderer/component/TaskDescriptionComponent.java
  packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/configuration/TaskExampleBuilder.java
  packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/configuration/view/TaskJavaService.java
  packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/configuration/view/ViewDeckDescriptionBuilder.java
  packages/starters/backend/sirius-components-task-starter/src/test/java/org/eclipse/sirius/components/task/starter/configuration/view/TaskJavaServiceTests.java
  packages/task/backend/sirius-components-task-edit/src/main/java/org/eclipse/sirius/components/task/provider/KeyResultItemProvider.java
  packages/task/backend/sirius-components-task-edit/src/main/java/org/eclipse/sirius/components/task/provider/ObjectiveItemProvider.java
  packages/task/backend/sirius-components-task-edit/src/main/resources/icons/full/obj16/KeyResult.svg
  packages/task/backend/sirius-components-task-edit/src/main/resources/icons/full/obj16/Objective.svg
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/CardDescriptionBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/LaneDescriptionBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/TaskDescriptionBuilder.java
  packages/view/backend/sirius-components-view-deck-edit/.classpath
  packages/view/backend/sirius-components-view-deck-edit/src/main/java/org/eclipse/sirius/components/view/deck/provider/CardDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-deck-edit/src/main/java/org/eclipse/sirius/components/view/deck/provider/LaneDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-deck-edit/src/main/resources/plugin.properties
  packages/view/backend/sirius-components-view-deck/.classpath
  packages/view/backend/sirius-components-view-deck/src/main/java/org/eclipse/sirius/components/view/deck/CardDescription.java
  packages/view/backend/sirius-components-view-deck/src/main/java/org/eclipse/sirius/components/view/deck/DeckPackage.java
  packages/view/backend/sirius-components-view-deck/src/main/java/org/eclipse/sirius/components/view/deck/LaneDescription.java
  packages/view/backend/sirius-components-view-deck/src/main/java/org/eclipse/sirius/components/view/deck/impl/CardDescriptionImpl.java
  packages/view/backend/sirius-components-view-deck/src/main/java/org/eclipse/sirius/components/view/deck/impl/DeckPackageImpl.java
  packages/view/backend/sirius-components-view-deck/src/main/java/org/eclipse/sirius/components/view/deck/impl/LaneDescriptionImpl.java
  packages/view/backend/sirius-components-view-deck/src/main/resources/model/deck.ecore
  packages/view/backend/sirius-components-view-deck/src/main/resources/model/deck.genmodel
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/deck/ViewDeckDescriptionConverter.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/task/ViewGanttDescriptionConverter.java
  packages/view/backend/sirius-components-view-gantt-edit/src/main/java/org/eclipse/sirius/components/view/gantt/provider/TaskDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-gantt-edit/src/main/resources/plugin.properties
  packages/view/backend/sirius-components-view-gantt/.classpath
  packages/view/backend/sirius-components-view-gantt/.project
  packages/view/backend/sirius-components-view-gantt/src/main/java/org/eclipse/sirius/components/view/gantt/GanttPackage.java
  packages/view/backend/sirius-components-view-gantt/src/main/java/org/eclipse/sirius/components/view/gantt/TaskDescription.java
  packages/view/backend/sirius-components-view-gantt/src/main/java/org/eclipse/sirius/components/view/gantt/impl/GanttPackageImpl.java
  packages/view/backend/sirius-components-view-gantt/src/main/java/org/eclipse/sirius/components/view/gantt/impl/TaskDescriptionImpl.java
  packages/view/backend/sirius-components-view-gantt/src/main/resources/model/gantt.ecore
  packages/view/backend/sirius-components-view-gantt/src/main/resources/model/gantt.genmodel
Labels: pr: to review soon, priority: low

#3358 [doc] Add ADRs about improving the document upload
  CHANGELOG.adoc
  doc/adrs/142_add_report_on_document_upload.adoc
  doc/adrs/143_handle_documents_upload_with_other_formats_than_json_and_xmi.adoc
Labels: pr: to review soon, priority: high

#3295 [doc] Add ADR for updating nodes in ReactFlow
  CHANGELOG.adoc
  doc/adrs/145_add_a_hook_to_update_nodes_in_reactflow.adoc
Labels: pr: to review soon, priority: high

#3368 [3279] Add support for icons in child creation dialog
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/images/ChildCreationDescriptionIconURLDataFetcher.java
  packages/sirius-web/backend/sirius-web-tests/src/main/java/org/eclipse/sirius/web/tests/graphql/ChildCreationDescriptionsQueryRunner.java
  packages/sirius-web/backend/sirius-web-tests/src/main/java/org/eclipse/sirius/web/tests/graphql/RootObjectCreationDescriptionsQueryRunner.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/objects/ObjectCreationControllerIntegrationTests.java
Labels: pr: to review soon, priority: high

#3347 [3346] Make the Explorer panel wider by default
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/gantt/gantt.cy.ts
  packages/core/frontend/sirius-components-core/src/workbench/Workbench.tsx
Labels: pr: to review later, priority: low

#3330 [3303] Add ADR for contributing representation metadata for transient representations
  CHANGELOG.adoc
  doc/adrs/146_contribute_representation_metadata_for_transient_representations.adoc
Labels: pr: to review soon, priority: high

#3339 [releng] Make tar quiet when archiving test coverage results
  .github/workflows/build.yml
Labels: pr: to review later, priority: low

#3315 [3313] Avoid sending domain events for no-op updates
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/boundedcontexts/project/Project.java
  packages/sirius-web/backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/boundedcontexts/representationdata/RepresentationData.java
  packages/sirius-web/backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/boundedcontexts/semanticdata/SemanticData.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/representations/RepresentationLifecycleControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/domain/DomainEventsTest.java
Labels: pr: to review later, priority: low

#3331 [doc] Add ADR to manage the overlapping nodes
  CHANGELOG.adoc
  doc/adrs/147_overlapping_nodes.adoc
  doc/adrs/images/147/disable_node_overlapping.png
  doc/adrs/images/147/enable_node_overlapping.png
Labels: pr: to review soon, priority: low

#3302 [3301] Use outsideLabel during directEdit if there is no insideLabel
  CHANGELOG.adoc
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/DiagramQueryService.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/test/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/InitialDirectEditElementLabelEventHandlerTests.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/test/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/TestDiagramBuilder.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/providers/ViewInitialDirectEditElementLabelProvider.java
Labels: pr: to review soon, priority: high

#3370 [doc] Add ADR to improve edge layout
  CHANGELOG.adoc
  doc/adrs/148_improves_edge_layout.adoc
  doc/adrs/images/148/edge_paths_example_with_existing.png
  doc/adrs/images/148/edge_paths_example_with_smart_edge.png
Labels: pr: to review soon, priority: low

#3365 [3360] Handle documents upload with other formats than JSON and XMI
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/services/DocumentSanitizedJsonContentProvider.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/services/JSONExternalResourceLoaderService.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/services/UploadDocumentEventHandler.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/services/XMIExternalResourceLoaderService.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/services/api/IExternalResourceLoaderService.java
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/documents/JSONResourceLoaderService.java
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/documents/UploadDocumentEventHandler.java
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/documents/XMIExternalResourceLoaderService.java
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/documents/api/IExternalResourceLoaderService.java
  packages/sirius-web/backend/sirius-web-services/src/test/java/org/eclipse/sirius/web/services/documents/UploadDocumentEventHandlerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/documents/DocumentControllerIntegrationTests.java
Labels: pr: to review soon, priority: high

#3355 [doc] Add shape on default visibility and visibility configuration
  CHANGELOG.adoc
  doc/adrs/149_add_default_visibility_fields_in_view_dsl.adoc
  doc/adrs/150_add_hide_reveal_fade_unfade_services.adoc
  doc/iterations/2024.5/shapes/configurable_visibility.adoc
Labels: pr: to review soon, priority: high

#3375 [3373] Fix potential IllegalArgumentException with non uuid shape
  CHANGELOG.adoc
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ImageNodeStyleProvider.java
  scripts/check-coverage.jsh
Labels: pr: to review later, priority: low

#3378 [3371] Add support to specify the default visibility state of a node
  CHANGELOG.adoc
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/NodeComponent.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/description/NodeDescription.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/VisibilityDiagramControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/diagrams/VisibilityDiagramDescriptionProvider.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/NodeDescriptionBuilder.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/DiagramItemProviderAdapterFactory.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/NodeDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/resources/plugin.properties
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/ConditionalInsideLabelStyle.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/ConditionalOutsideLabelStyle.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/DiagramElementDescription.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/DiagramFactory.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/DiagramPackage.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/EdgeDescription.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/InsideLabelDescription.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/InsideLabelPosition.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/InsideLabelStyle.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/NodeDescription.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/NodeLabelStyle.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/NodeStyleDescription.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/OutsideLabelDescription.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/OutsideLabelPosition.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/RectangularNodeStyleDescription.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/ConditionalInsideLabelStyleImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/ConditionalOutsideLabelStyleImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/DiagramElementDescriptionImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/DiagramFactoryImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/DiagramPackageImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/EdgeDescriptionImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/IconLabelNodeStyleDescriptionImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/ImageNodeStyleDescriptionImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/InsideLabelDescriptionImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/InsideLabelStyleImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/NodeDescriptionImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/OutsideLabelDescriptionImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/OutsideLabelStyleImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/RectangularNodeStyleDescriptionImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/util/DiagramAdapterFactory.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/util/DiagramSwitch.java
  packages/view/backend/sirius-components-view-diagram/src/main/resources/model/diagram.ecore
  packages/view/backend/sirius-components-view-diagram/src/main/resources/model/diagram.genmodel
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewDiagramDescriptionConverter.java
Labels: pr: to review soon, priority: high

#3379 [3372] Add hide, reveal, fade, unfade diagram element services
  CHANGELOG.adoc
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/DiagramServices.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/api/IDiagramServices.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/test/java/org/eclipse/sirius/components/collaborative/diagrams/DiagramServicesTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/VisibilityDiagramControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/diagrams/VisibilityDiagramDescriptionProvider.java
  scripts/check-coverage.jsh
Labels: pr: to review soon, priority: high

#3380 [3376] Avoid computing node creation handle during multi-selection
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/diagrams/group-palette.cy.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/handles/ConnectionCreationHandles.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/handles/useConnectionCandidatesQuery.ts
Labels: pr: to review soon, priority: low

#3098 [doc] Contribute a shape to support different overflow label strategies
  CHANGELOG.adoc
  doc/iterations/2024.3/shapes/images/auto_wrap_label/node_with_small_label.png
  doc/iterations/2024.3/shapes/images/auto_wrap_label/overflowStrategy_ellipsis_option.png
  doc/iterations/2024.3/shapes/images/auto_wrap_label/overflowStrategy_none_option.png
  doc/iterations/2024.3/shapes/images/auto_wrap_label/overflowStrategy_wrap_option.png
  doc/iterations/2024.3/shapes/overflow_label_strategy.adoc
Labels: pr: to review later, priority: low

#3037 [doc] Contribute a shape to improve resizing support for list node
  CHANGELOG.adoc
  doc/iterations/2024.3/shapes/images/list_node/container_resizing.gif
  doc/iterations/2024.3/shapes/images/list_node/list_layout_resize.gif
  doc/iterations/2024.3/shapes/images/list_node/list_smallest_size.gif
  doc/iterations/2024.3/shapes/images/list_node/sub_container_resizing.gif
  doc/iterations/2024.3/shapes/improve_resizing_support_for_list_nodes.adoc
Labels: pr: to review soon, priority: low

#3381 [3377] Only synchronize selection with explorer at the end of the pro…
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/diagrams/group-palette.cy.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/handles/useConnectionCandidatesQuery.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/selection/useDiagramSelection.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/selection/useShiftSelection.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/selection/useShiftSelection.types.ts
Labels: pr: to review soon, priority: low

#3403 [releng] Check backend test coverage after e2e tests
  .github/workflows/build.yml
Labels: pr: to review later, priority: low

#3406 [3405] Display layout tools in group palette vertically
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/diagrams/group-palette.cy.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/group-tool/GroupPalette.tsx
Labels: pr: to review soon, priority: low

#3396 [3383] Fix an issue where the first resizing after node creation was …
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout-events/useLayoutOnBoundsChange.ts
Labels: pr: to review soon, priority: low

#3385 [3360] Make JSON and XMI ExternalResourceLoaderServices more precise
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/services/JSONExternalResourceLoaderService.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/services/XMIExternalResourceLoaderService.java
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/documents/JSONExternalResourceLoaderService.java
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/documents/UploadDocumentEventHandler.java
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/documents/XMIExternalResourceLoaderService.java
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/documents/api/IExternalResourceLoaderService.java
  packages/sirius-web/backend/sirius-web-services/src/test/java/org/eclipse/sirius/web/services/documents/UploadDocumentEventHandlerTests.java
Labels: pr: to review soon, priority: high

#3334 [3333] Add support for the migration of semantic data
  CHANGELOG.adoc
  packages/emf/backend/sirius-components-emf/pom.xml
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/ResourceMetadataAdapter.java
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/migration/MigrationService.java
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/migration/api/IMigrationParticipant.java
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/migration/api/MigrationData.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/services/DocumentSanitizedJsonContentProvider.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/services/JSONExternalResourceLoaderService.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/migration/participants/NodeDescriptionLabelExpressionMigrationParticipant.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/services/ResourceLoader.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/services/ResourceToDocumentService.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/data/MigrationIdentifiers.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/migration/MigrationParticipantTests.java
  packages/sirius-web/backend/sirius-web/src/test/resources/scripts/migration.sql
  scripts/check-coverage.jsh
Labels: pr: to review soon, priority: high

#3410 [3409] Make border node movement smoother
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/border/useBorderChange.tsx
Labels: pr: to review soon, priority: low

#3412 [3411] Allow border node to be moved even if AreChildNodesDraggableEx…
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/move/useMoveChange.tsx
Labels: pr: to review soon, priority: low

#3395 [3382] Improve hide capabilities in the palette
  CHANGELOG.adoc
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/DiagramServices.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/api/IDiagramServices.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/test/java/org/eclipse/sirius/components/collaborative/diagrams/DiagramServicesTests.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/NodeComponent.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/events/ResetViewModifiersEvent.java
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/Palette.tsx
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/representations/EntityNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/representations/InheritanceEdgeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/representations/RelationEdgeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/classdiagram/CDClassNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/classdiagram/CDExtendsClassEdgeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/classdiagram/CDExtendsInterfaceEdgeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/classdiagram/CDImplementsInterfaceEdgeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/classdiagram/CDInterfaceNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/classdiagram/CDPackageNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/logicalarchitecture/ClassNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/logicalarchitecture/ComponentNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/logicalarchitecture/DataTypeNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/logicalarchitecture/DependsOnEdgeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/logicalarchitecture/EnumNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/logicalarchitecture/ExtendsClassEdgeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/logicalarchitecture/ExtendsInterfaceEdgeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/logicalarchitecture/FulfillsContractEdgeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/logicalarchitecture/ImplementsInterfaceEdgeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/logicalarchitecture/InterfaceNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/logicalarchitecture/PackageNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/logicalarchitecture/ProvidedServiceNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/logicalarchitecture/RealizedByEdgeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/logicalarchitecture/ReferencesClassEdgeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/logicalarchitecture/RequiredServiceNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/logicalarchitecture/exchange/CEDComponentExchangeEdgeProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/logicalarchitecture/exchange/CEDComponentNodeProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/logicalarchitecture/exchange/CEDComponentPortNodeProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/operationalanalysis/InteractionEdgeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/operationalanalysis/OperationalActivityNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/operationalanalysis/OperationalActorNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/operationalanalysis/OperationalEntityNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/papaya/view/operationalanalysis/OperationalPerimeterNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/VisibilityDiagramControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/diagrams/VisibilityDiagramDescriptionProvider.java
  packages/starters/backend/sirius-components-flow-starter/pom.xml
  packages/starters/backend/sirius-components-flow-starter/src/main/java/org/eclipse/sirius/components/flow/starter/view/descriptions/DataSourceDescriptionProvider.java
  packages/starters/backend/sirius-components-flow-starter/src/main/java/org/eclipse/sirius/components/flow/starter/view/descriptions/DataSourceToProcessorEdgeDescriptionProvider.java
  packages/starters/backend/sirius-components-flow-starter/src/main/java/org/eclipse/sirius/components/flow/starter/view/descriptions/FanDescriptionProvider.java
  packages/starters/backend/sirius-components-flow-starter/src/main/java/org/eclipse/sirius/components/flow/starter/view/descriptions/PowerInputDescriptionProvider.java
  packages/starters/backend/sirius-components-flow-starter/src/main/java/org/eclipse/sirius/components/flow/starter/view/descriptions/PowerOutputDescriptionProvider.java
  packages/starters/backend/sirius-components-flow-starter/src/main/java/org/eclipse/sirius/components/flow/starter/view/descriptions/ProcessorDescriptionProvider.java
  packages/starters/backend/sirius-components-flow-starter/src/main/java/org/eclipse/sirius/components/flow/starter/view/descriptions/ProcessorToProcessorEdgeDescriptionProvider.java
  packages/starters/backend/sirius-components-flow-starter/src/main/java/org/eclipse/sirius/components/flow/starter/view/descriptions/SystemDescriptionProvider.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/DefaultToolsFactory.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/resources/icons/full/obj16/HideTool.svg
  packages/view/backend/sirius-components-view-diagram-edit/src/main/resources/icons/full/obj16/ShowTool.svg
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/ViewAQLInterpreterFactory.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/ViewConverter.java
Labels: pr: to review soon, priority: high

#3417 [3416] Add tooltip for Filter menu in Explorer view
  CHANGELOG.adoc
  packages/trees/frontend/sirius-components-trees/src/views/TreeFiltersMenu.tsx
Labels: pr: to review soon, priority: high

#3421 [3420] Restore position reset after a rejected drag&drop on node
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout-events/useLayoutOnBoundsChange.ts
Labels: pr: to review soon, priority: low

#3418 [releng] Switch to actions/upload-artifact v4
  .github/workflows/build.yml
Labels: pr: to review later, priority: low

#3423 [3422] Restore selection for element not present on diagram
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/diagrams/diagram-selection.cy.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/selection/useDiagramSelection.ts
Labels: pr: to review soon, priority: high

#3398 [3397] Add helper lines when resizing nodes
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/helper-lines/useHelperLines.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/layoutParams.ts
Labels: pr: to review soon, priority: low

#3433 [3304] Fix typo in explorer id
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/ExplorerDescriptionProvider.java
Labels: pr: to review soon, priority: high

#3408 [3407] Store nodeDrop datas in nodes
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/IconLabelNodeConverter.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/ImageNodeConverter.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/ListNodeConverter.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/RectangleNodeConverter.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/dropNode/useDropNode.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/dropNode/useDropNodeStyle.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/hover/useNodeHover.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout-events/useLayoutOnBoundsChange.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/node/FreeFormNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/node/IconLabelNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/node/ListNode.tsx
  packages/sirius-web/frontend/sirius-web/src/nodes/EllipseNode.tsx
  packages/sirius-web/frontend/sirius-web/src/nodes/EllipseNodeConverter.ts
Labels: pr: to review soon, priority: high

#3439 Revert "[3392] Prevents edge from passing through another node"
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/diagrams/edges.cy.ts
  package-lock.json
  packages/diagrams/frontend/sirius-components-diagrams/package.json
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/convertDiagram.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/EdgeLayout.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/EdgeTypes.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/EdgeWrapper.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/EdgeWrapper.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/MultiLabelEdge.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/MultiLabelEdge.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/handles/ConnectionHandles.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/layoutNode.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/useArrangeAll.ts
  packages/sirius-web/frontend/sirius-web/package.json
Labels: pr: to review soon, priority: high
