Repository eclipse-sirius/sirius-web, pull requests merged in 2024-05, with the labels that each got.

#3428 [doc] Add shape on creating a representation from another representation
  CHANGELOG.adoc
  doc/iterations/2024.5/shapes/create_representation_using_content_of_another_representation.adoc
Labels: pr: to review soon, priority: high

#3427 [3424] Fix document migration data during creation
  CHANGELOG.adoc
  doc/adrs/144_add_support_for_emf_models_migration.adoc
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/migration/MigrationService.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/migration/participants/NodeDescriptionLabelExpressionMigrationParticipant.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/DefaultDomainResourceProvider.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/DefaultViewResourceProvider.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/StudioStereotypeHandler.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/migration/MigrationParticipantTests.java
Labels: pr: to review soon, priority: high

#3445 [3443] Prevent outside label to be truncated
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/diagrams/diagram-label.cy.ts
  integration-tests/cypress/workbench/Diagram.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/Label.tsx
Labels: pr: to review soon, priority: low

#3442 [3440] Compute the position of a border node after each of its moves
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/border/useBorderChange.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout-events/useLayoutOnBoundsChange.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/layoutNode.ts
Labels: pr: to review soon, priority: high

#3434 [2655] Calculate custom node edge handle position to follow the real …
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/diagrams/edges.cy.ts
  integration-tests/cypress/workbench/Details.ts
  integration-tests/cypress/workbench/Diagram.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/EdgeLayout.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/EdgeLayout.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/MultiLabelEdge.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/LayoutEngine.types.ts
  packages/sirius-web/frontend/sirius-web/src/nodes/EllipseNodeLayoutHandler.ts
Labels: pr: to review soon, priority: low

#3457 [3456] Fix ConnectionTargetHandle re-render
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/handles/ConnectionTargetHandle.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/handles/ConnectionTargetHandle.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/handles/useRefreshTargetHandles.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/node/FreeFormNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/node/ListNode.tsx
  packages/sirius-web/frontend/sirius-web/src/nodes/EllipseNode.tsx
Labels: pr: to review soon, priority: high

#3449 [3214] Apply theme colors in the VS Code Extension
  CHANGELOG.adoc
  vscode-extension/src/view/app/App.tsx
  vscode-extension/src/view/app/theme/siriusWebTheme.ts
Labels: pr: to review later, priority: low

#3454 [3453] Memoizing edges and nodes style
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/connector/useConnectorNodeStyle.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/dropNode/useDropDiagramStyle.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/dropNode/useDropNodeStyle.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/MultiLabelEdge.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/handles/ConnectionHandles.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/handles/useHandleChange.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/node/FreeFormNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/node/IconLabelNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/node/ListNode.tsx
Labels: pr: to review soon, priority: high

#3451 [3450] Calculate custom node border node position to follow the real layout
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/border/useBorderChange.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/LayoutEngine.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/layoutNode.ts
  packages/sirius-web/frontend/sirius-web/src/nodes/EllipseNodeLayoutHandler.ts
Labels: pr: to review later, priority: low

#3461 [3460] Improve edge handle position computing to follow the arrange l…
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/diagrams/edges.cy.ts
  integration-tests/cypress/e2e/project/studio/studio.cy.ts
  integration-tests/cypress/workbench/Details.ts
  packages/compatibility/backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/services/diagrams/DiagramDescriptionConverter.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/resources/schema/diagram.graphqls
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/ArrangeLayoutDirection.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/description/DiagramDescription.java
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/convertDiagram.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/connector/useConnector.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/EdgeLayout.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/EdgeLayout.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/handles/useHandleChange.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/layoutHandles.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/useArrangeAll.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/representation/DiagramRepresentation.types.ts
  packages/view/backend/sirius-components-view-diagram-edit/src/main/resources/plugin.properties
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/ArrangeLayoutDirection.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/DiagramDescription.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/DiagramDescriptionImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/DiagramPackageImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/resources/model/diagram.ecore
  packages/view/backend/sirius-components-view-diagram/src/main/resources/model/diagram.genmodel
Labels: pr: to review soon, priority: low

#3473 [3472] Prevent arrange-all action to mark nodes as resizedByUser
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/diagrams/arrange-all.cy.ts
  integration-tests/cypress/e2e/project/diagrams/edges.cy.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/useArrangeAll.ts
Labels: pr: to review soon, priority: low

#3482 [3366] Trigger the zoom in gantt on Ctrl+MouseWheel
  CHANGELOG.adoc
  packages/gantt/frontend/sirius-components-gantt/src/representation/Gantt.tsx
Labels: pr: to review soon, priority: low

#3501 [3499] Fix label positioning in portal representation
  CHANGELOG.adoc
  packages/portals/frontend/sirius-components-portals/src/representations/RepresentationFrame.tsx
Labels: pr: to review soon, priority: low

#3513 [3511] Improve edge handle position for border nodes
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/diagrams/edges.cy.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/convertDiagram.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/EdgeLayout.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/handles/useHandleChange.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/layoutNode.ts
Labels: pr: to review soon, priority: low

#3502 [2837] Enhance gantt scroll bar management
  CHANGELOG.adoc
  package-lock.json
  packages/gantt/frontend/sirius-components-gantt/package.json
  packages/sirius-web/frontend/sirius-web/package.json
Labels: pr: to review soon, priority: low

#3518 [3517] Prevent edge path for rotatable border node to be inconsistent
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/EdgeLayout.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/node/FreeFormNode.tsx
Labels: pr: to review soon, priority: low

#3521 [test] Fix a random bug introduced in some integration tests
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/forms/TitleExpressionControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/resources/scripts/papaya.sql
Labels: pr: to review soon, priority: high

#3467 [3441] Use a DateTime widget for AbstractTask entity
  CHANGELOG.adoc
  packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/configuration/AbstractTaskPropertiesConfigurer.java
Labels: pr: to review soon, priority: low

#3522 [fix] Add data-testid on ToolSection
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/tool-section/ToolSection.tsx
Labels: pr: to review soon, priority: high

#3508 [3466] Persist gantt table columns
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/gantt/gantt.cy.ts
  package-lock.json
  packages/gantt/backend/sirius-components-collaborative-gantt/src/main/java/org/eclipse/sirius/components/collaborative/gantt/api/IGanttTaskService.java
  packages/gantt/backend/sirius-components-collaborative-gantt/src/main/java/org/eclipse/sirius/components/collaborative/gantt/dto/input/ChangeGanttColumnInput.java
  packages/gantt/backend/sirius-components-collaborative-gantt/src/main/java/org/eclipse/sirius/components/collaborative/gantt/handlers/ChangeGanttColumnEventHandler.java
  packages/gantt/backend/sirius-components-collaborative-gantt/src/main/java/org/eclipse/sirius/components/collaborative/gantt/service/GanttTaskService.java
  packages/gantt/backend/sirius-components-collaborative-gantt/src/main/resources/schema/gantt.graphqls
  packages/gantt/backend/sirius-components-gantt-graphql/src/main/java/org/eclipse/sirius/components/gantt/graphql/datafetchers/mutation/MutationGanttColumnDataFetcher.java
  packages/gantt/backend/sirius-components-gantt-tests/src/main/java/org/eclipse/sirius/components/gantt/tests/graphql/ChangeColumnMutationRunner.java
  packages/gantt/backend/sirius-components-gantt/src/main/java/org/eclipse/sirius/components/gantt/Gantt.java
  packages/gantt/backend/sirius-components-gantt/src/main/java/org/eclipse/sirius/components/gantt/GanttColumn.java
  packages/gantt/backend/sirius-components-gantt/src/main/java/org/eclipse/sirius/components/gantt/renderer/GanttElementFactory.java
  packages/gantt/backend/sirius-components-gantt/src/main/java/org/eclipse/sirius/components/gantt/renderer/component/GanttComponent.java
  packages/gantt/backend/sirius-components-gantt/src/main/java/org/eclipse/sirius/components/gantt/renderer/elements/GanttElementProps.java
  packages/gantt/backend/sirius-components-gantt/src/main/java/org/eclipse/sirius/components/gantt/renderer/events/ChangeGanttColumnEvent.java
  packages/gantt/frontend/sirius-components-gantt/package.json
  packages/gantt/frontend/sirius-components-gantt/src/graphql/mutation/GanttMutation.types.ts
  packages/gantt/frontend/sirius-components-gantt/src/graphql/mutation/ganttMutation.ts
  packages/gantt/frontend/sirius-components-gantt/src/graphql/mutation/useGanttMutations.ts
  packages/gantt/frontend/sirius-components-gantt/src/graphql/subscription/GanttSubscription.types.ts
  packages/gantt/frontend/sirius-components-gantt/src/graphql/subscription/ganttSubscription.ts
  packages/gantt/frontend/sirius-components-gantt/src/helper/helper.tsx
  packages/gantt/frontend/sirius-components-gantt/src/representation/Gantt.tsx
  packages/gantt/frontend/sirius-components-gantt/src/representation/Gantt.types.ts
  packages/gantt/frontend/sirius-components-gantt/src/representation/GanttRepresentation.tsx
  packages/gantt/frontend/sirius-components-gantt/src/toolbar/Toolbar.tsx
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/gantt/PapayaGanttControllerIntegrationTests.java
  packages/sirius-web/frontend/sirius-web/package.json
  packages/view/backend/sirius-components-view-deck-edit/src/main/java/org/eclipse/sirius/components/view/deck/provider/DeckItemProviderAdapterFactory.java
  packages/view/backend/sirius-components-view-gantt-edit/src/main/java/org/eclipse/sirius/components/view/gantt/provider/GanttItemProviderAdapterFactory.java
Labels: pr: to review later, priority: low

#3525 [2908] Homogenize delete icons
  CHANGELOG.adoc
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/resources/diagram-images/semanticDelete.svg
  packages/gantt/frontend/sirius-components-gantt/src/palette/ContextualPalette.tsx
Labels: pr: to review soon, priority: low

#3506 [3485] Add a validation error message when background value is missing
  CHANGELOG.adoc
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/DiagramDescriptionValidator.java
  packages/view/backend/sirius-components-view-emf/src/test/java/org/eclipse/sirius/components/view/emf/validation/ViewValidatorTests.java
Labels: pr: to review later, priority: low
