Repository eclipse-sirius/sirius-web, pull requests merged in 2024-10, with the labels that each got.

#4015 [3958] Prevent Stackoverflow when rendering a twice an expanded TreeItem
  CHANGELOG.adoc
  packages/trees/backend/sirius-components-trees/src/main/java/org/eclipse/sirius/components/trees/renderer/TreeRenderer.java
  packages/trees/backend/sirius-components-trees/src/test/java/org/eclipse/sirius/components/trees/renderer/TreeRendererTests.java
Labels: pr: to review soon, priority: high

#4054 [4050] Give a chance to report an error on document upload
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/services/UploadDocumentEventHandler.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/services/UploadFileLoader.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/services/api/IUploadFileLoader.java
Labels: pr: to review soon, priority: high

#4052 [4051] Container feature should not be removed during resource deletion
  CHANGELOG.adoc
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/services/EditingContextCrossReferenceAdapter.java
Labels: pr: to review soon, priority: high

#4078 [4077] Remove metadata from Charts widgets
  CHANGELOG.adoc
  packages/charts/backend/sirius-components-charts/src/main/java/org/eclipse/sirius/components/charts/barchart/BarChart.java
  packages/charts/backend/sirius-components-charts/src/main/java/org/eclipse/sirius/components/charts/barchart/components/BarChartComponent.java
  packages/charts/backend/sirius-components-charts/src/main/java/org/eclipse/sirius/components/charts/barchart/descriptions/BarChartDescription.java
  packages/charts/backend/sirius-components-charts/src/main/java/org/eclipse/sirius/components/charts/barchart/elements/BarChartElementProps.java
  packages/charts/backend/sirius-components-collaborative-charts/src/main/resources/schema/charts.graphqls
  packages/charts/frontend/sirius-components-charts/src/bar/BarChart.tsx
  packages/charts/frontend/sirius-components-charts/src/bar/BarChart.types.ts
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/formdescriptioneditors/components/ViewFormDescriptionEditorConverterSwitch.java
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/BarChartWidget.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/PieChartWidget.tsx
  packages/forms/backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/renderer/FormElementFactory.java
  packages/forms/frontend/sirius-components-forms/src/form/FormEventFragments.ts
  packages/forms/frontend/sirius-components-forms/src/form/FormEventFragments.types.ts
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/ChartWidgetPropertySection.test.tsx
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/form/ViewFormDescriptionConverterSwitch.java
  packages/view/backend/sirius-components-view-emf/src/test/java/org/eclipse/sirius/components/view/emf/view/DynamicFormsTests.java
Labels: pr: to review soon, priority: high

#4030 [4029] Added custom Images element to the exported APi of sirius-web-application
  CHANGELOG.adoc
  packages/sirius-web/frontend/sirius-web-application/src/index.ts
Labels: pr: to review soon, priority: high

#4035 [releng] Switch to AQL 8.0.2 final
  CHANGELOG.adoc
  packages/emf/backend/sirius-components-interpreter/pom.xml
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/ViewAQLInterpreterFactory.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/ViewConverter.java
Labels: pr: to review soon, priority: low

#4072 [4037] Allow the selection of list items even in read-only mode
  CHANGELOG.adoc
  packages/forms/frontend/sirius-components-forms/src/propertysections/ListPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/ListPropertySection.test.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/ListPropertySection.test.tsx.snap
Labels: pr: to review later, priority: low

#4090 [doc] Add shape for editable edges
  CHANGELOG.adoc
  doc/iterations/2024.11/editable-edge.adoc
  doc/iterations/2024.11/images/complex-edge-path.png
  doc/iterations/2024.11/images/edge-with-bend-points.png
Labels: pr: to review later, priority: low

#4093 [doc] Complete documentation to add extension point support
  doc/how-to/contribute-custom-node.adoc
  doc/how-to/contribute-custom-widget.adoc
  doc/how-to/extend-the-frontend.adoc
Labels: pr: to review soon, priority: high

#4089 [4088] Change tree item context menu entries internal management
  CHANGELOG.adoc
  packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/browser/ModelBrowsersDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/ExplorerDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/tree/DomainExplorerRepresentationDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/tree/DomainTreeRepresentationDescriptionProvider.java
  packages/trees/backend/sirius-components-collaborative-trees/src/main/java/org/eclipse/sirius/components/collaborative/trees/api/IFetchTreeItemContextMenuEntryDataProvider.java
  packages/trees/backend/sirius-components-collaborative-trees/src/main/java/org/eclipse/sirius/components/collaborative/trees/api/ISingleClickTreeItemContextMenuEntryExecutor.java
  packages/trees/backend/sirius-components-collaborative-trees/src/main/java/org/eclipse/sirius/components/collaborative/trees/api/ITreeItemContextMenuEntryProvider.java
  packages/trees/backend/sirius-components-collaborative-trees/src/main/java/org/eclipse/sirius/components/collaborative/trees/handlers/FetchTreeItemContextMenuEntryDataEventHandler.java
  packages/trees/backend/sirius-components-collaborative-trees/src/main/java/org/eclipse/sirius/components/collaborative/trees/handlers/InvokeSingleClickTreeItemContextMenuEntryEventHandler.java
  packages/trees/backend/sirius-components-collaborative-trees/src/main/java/org/eclipse/sirius/components/collaborative/trees/handlers/TreeItemContextMenuEventHandler.java
  packages/trees/backend/sirius-components-collaborative-trees/src/main/java/org/eclipse/sirius/components/collaborative/trees/services/CollaborativeTreeMessageService.java
  packages/trees/backend/sirius-components-collaborative-trees/src/main/java/org/eclipse/sirius/components/collaborative/trees/services/api/ICollaborativeTreeMessageService.java
  packages/trees/backend/sirius-components-collaborative-trees/src/main/resources/messages/sirius-web-spring-collaborative-trees.properties
  packages/trees/backend/sirius-components-collaborative-trees/src/test/java/org/eclipse/sirius/components/collaborative/trees/architecture/handlers/DefaultExpandAllTreePathHandlerTests.java
  packages/trees/backend/sirius-components-trees/src/main/java/org/eclipse/sirius/components/trees/FetchTreeItemContextMenuEntry.java
  packages/trees/backend/sirius-components-trees/src/main/java/org/eclipse/sirius/components/trees/ITreeItemContextMenuEntry.java
  packages/trees/backend/sirius-components-trees/src/main/java/org/eclipse/sirius/components/trees/SingleClickTreeItemContextMenuEntry.java
  packages/trees/backend/sirius-components-trees/src/main/java/org/eclipse/sirius/components/trees/description/TreeDescription.java
  packages/trees/backend/sirius-components-trees/src/test/java/org/eclipse/sirius/components/trees/renderer/TreeRendererTests.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/SelectionDialogDescriptionConverter.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/tree/ViewFetchTreeItemContextMenuEntryDataProvider.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/tree/ViewSingleClickTreeItemContextMenuEntryExecutor.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/tree/ViewTreeDescriptionConverter.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/tree/ViewTreeItemContextMenuEntryProvider.java
Labels: pr: to review soon, priority: low

#4046 [doc] Add shape on draggable labels
  CHANGELOG.adoc
  doc/iterations/2024.11/draggable_labels.adoc
Labels: pr: to review later, priority: low

#3989 [doc] Add support for styled labels in view model for trees
  CHANGELOG.adoc
  doc/adrs/162_add_support_for_styled_labels_in_view_model_for_trees.adoc
  doc/adrs/images/160/simple_operation_style.png
Labels: pr: to review soon, priority: high

#4026 [doc] Add ADR about Diagram Palette API changes
  CHANGELOG.adoc
  doc/adrs/162_add_support_for_styled_labels_in_view_model_for_trees.adoc
  doc/adrs/163_diagram_new_palette_api.adoc
  doc/adrs/images/162/simple_operation_style.png
  doc/adrs/images/163/newPalette.png
Labels: pr: to review later, priority: low

#4111 [releng] Exclude src/test/resources from checkstyle
  packages/charts/backend/sirius-components-charts-graphql/.checkstyle
  packages/charts/backend/sirius-components-charts/.checkstyle
  packages/compatibility/backend/sirius-components-compatibility/.checkstyle
  packages/core/backend/sirius-components-collaborative/.checkstyle
  packages/core/backend/sirius-components-core/.checkstyle
  packages/diagrams/backend/sirius-components-collaborative-diagrams/.checkstyle
  packages/diagrams/backend/sirius-components-diagrams-graphql/.checkstyle
  packages/diagrams/backend/sirius-components-diagrams/.checkstyle
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors-widget-reference/.checkstyle
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/.checkstyle
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors-graphql/.checkstyle
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors/.checkstyle
  packages/forms/backend/sirius-components-collaborative-forms/.checkstyle
  packages/forms/backend/sirius-components-collaborative-widget-reference/.checkstyle
  packages/forms/backend/sirius-components-forms-graphql/.checkstyle
  packages/forms/backend/sirius-components-forms/.checkstyle
  packages/forms/backend/sirius-components-widget-reference-graphql/.checkstyle
  packages/forms/backend/sirius-components-widget-reference/.checkstyle
  packages/gantt/backend/sirius-components-collaborative-gantt/.checkstyle
  packages/gantt/backend/sirius-components-gantt-graphql/.checkstyle
  packages/gantt/backend/sirius-components-gantt/.checkstyle
  packages/portals/backend/sirius-components-collaborative-portals/.checkstyle
  packages/portals/backend/sirius-components-portals-graphql/.checkstyle
  packages/portals/backend/sirius-components-portals/.checkstyle
  packages/selection/backend/sirius-components-collaborative-selection/.checkstyle
  packages/selection/backend/sirius-components-selection-graphql/.checkstyle
  packages/selection/backend/sirius-components-selection/.checkstyle
  packages/sirius-web/backend/sirius-web-application/.checkstyle
  packages/sirius-web/backend/sirius-web-domain/.checkstyle
  packages/sirius-web/backend/sirius-web-e2e-tests/.checkstyle
  packages/sirius-web/backend/sirius-web-infrastructure/.checkstyle
  packages/sirius-web/backend/sirius-web-papaya/.checkstyle
  packages/sirius-web/backend/sirius-web-starter/.checkstyle
  packages/sirius-web/backend/sirius-web/.checkstyle
  packages/tests/backend/sirius-components-spring-tests/.checkstyle
  packages/tests/backend/sirius-components-tests/.checkstyle
  packages/trees/backend/sirius-components-collaborative-trees/.checkstyle
  packages/trees/backend/sirius-components-trees-graphql/.checkstyle
  packages/trees/backend/sirius-components-trees/.checkstyle
  packages/validation/backend/sirius-components-collaborative-validation/.checkstyle
  packages/validation/backend/sirius-components-validation-graphql/.checkstyle
  packages/validation/backend/sirius-components-validation/.checkstyle
  packages/view/backend/sirius-components-view-diagram-customnodes-edit/.checkstyle
  packages/view/backend/sirius-components-view-emf-widget-reference/.checkstyle
  packages/view/backend/sirius-components-view/.checkstyle
  packages/web/backend/sirius-components-graphql/.checkstyle
  packages/web/backend/sirius-components-web/.checkstyle
Labels: pr: to review later, priority: low

#4004 [doc] Add ADR for selection of newly created diagram elements
  CHANGELOG.adoc
  doc/adrs/164_select_new_diagram_elements.adoc
Labels: pr: to review soon, priority: low

#3905 [3904] Fix textfield update to reflect backend-set value even if it m…
  CHANGELOG.adoc
  packages/forms/frontend/sirius-components-forms/src/propertysections/TextfieldPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/TextfieldPropertySectionMachine.ts
Labels: pr: to review soon, priority: low

#4120 [3836] Prevent task.description from resetting after gantt task change
  CHANGELOG.adoc
  package-lock.json
  packages/gantt/frontend/sirius-components-gantt/package.json
  packages/gantt/frontend/sirius-components-gantt/src/helper/helper.tsx
  packages/gantt/frontend/sirius-components-gantt/src/representation/GanttRepresentation.tsx
  packages/sirius-web/frontend/sirius-web/package.json
  vscode-extension/package.json
Labels: pr: to review soon, priority: high

#4083 [2399] Keep the same execution context for successive operations at the same level
  CHANGELOG.adoc
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/OperationInterpreter.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/DiagramOperationInterpreter.java
Labels: pr: to review later, priority: low

#4025 [3983] Add drag and drop support for explorer
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/explorer/explorer-dnd.cy.ts
  integration-tests/cypress/workbench/Explorer.ts
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/ExplorerDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/ExplorerDropTreeItemHandler.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/tree/DomainTreeRepresentationDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/services/api/IMessageService.java
  packages/sirius-web/backend/sirius-web-infrastructure/src/main/java/org/eclipse/sirius/web/infrastructure/i18n/MessageService.java
  packages/sirius-web/backend/sirius-web-infrastructure/src/main/resources/i18n/messages.properties
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/projects/ProjectDownloadControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/trees/ExplorerDropTreeItemControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/trees/TreeNonSemanticElementControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/services/MessageServiceTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/data/StudioIdentifiers.java
  packages/sirius-web/backend/sirius-web/src/test/resources/scripts/studio.sql
  packages/trees/backend/sirius-components-collaborative-trees/src/main/java/org/eclipse/sirius/components/collaborative/trees/api/IDropTreeItemHandler.java
  packages/trees/backend/sirius-components-collaborative-trees/src/main/java/org/eclipse/sirius/components/collaborative/trees/dto/DropTreeItemInput.java
  packages/trees/backend/sirius-components-collaborative-trees/src/main/java/org/eclipse/sirius/components/collaborative/trees/handlers/DropTreeItemEventHandler.java
  packages/trees/backend/sirius-components-collaborative-trees/src/main/java/org/eclipse/sirius/components/collaborative/trees/services/CollaborativeTreeMessageService.java
  packages/trees/backend/sirius-components-collaborative-trees/src/main/java/org/eclipse/sirius/components/collaborative/trees/services/api/ICollaborativeTreeMessageService.java
  packages/trees/backend/sirius-components-collaborative-trees/src/main/resources/messages/sirius-web-spring-collaborative-trees.properties
  packages/trees/backend/sirius-components-collaborative-trees/src/main/resources/schema/tree.graphqls
  packages/trees/backend/sirius-components-trees-graphql/src/main/java/org/eclipse/sirius/components/trees/graphql/datafetchers/mutation/MutationDropTreeItemDataFetcher.java
  packages/trees/backend/sirius-components-trees-tests/src/main/java/org/eclipse/sirius/components/trees/tests/graphql/DropTreeItemMutationRunner.java
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItem.tsx
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItem.types.ts
  packages/trees/frontend/sirius-components-trees/src/treeitems/useDropTreeItem.ts
  packages/trees/frontend/sirius-components-trees/src/treeitems/useDropTreeItem.types.ts
  packages/trees/frontend/sirius-components-trees/src/trees/Tree.tsx
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/SelectionDialogDescriptionConverter.java
Labels: pr: to review soon, priority: low

#4126 [doc] Add ADR on pagination for table representation
  CHANGELOG.adoc
  doc/adrs/166_support-server-side-pagination-for-table.adoc
Labels: pr: to review soon, priority: high

#4119 [4113] Make the EditProjectNavbar menu extensible
  CHANGELOG.adoc
  packages/sirius-web/frontend/sirius-web-application/src/extension/DefaultExtensionRegistry.tsx
  packages/sirius-web/frontend/sirius-web-application/src/index.ts
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/EditProjectNavbar/DownloadProjectMenuEntryContribution.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/EditProjectNavbar/EditProjectNavbar.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/EditProjectNavbar/EditProjectNavbar.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/EditProjectNavbar/EditProjectNavbarMenuExtensionPoints.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/EditProjectView.tsx
Labels: pr: to review soon, priority: high

#4116 [4114] Make the ProjectActionButton's menu more extensible
  CHANGELOG.adoc
  packages/sirius-web/frontend/sirius-web-application/src/extension/DefaultExtensionRegistry.tsx
  packages/sirius-web/frontend/sirius-web-application/src/index.ts
  packages/sirius-web/frontend/sirius-web-application/src/views/project-browser/list-projects-area/ProjectActionButton.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/project-browser/list-projects-area/ProjectActionButton.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/views/project-browser/list-projects-area/ProjectActionButtonExtensionPoints.ts
  packages/sirius-web/frontend/sirius-web-application/src/views/project-browser/list-projects-area/ProjectContextMenuExtensionPoints.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/project-browser/list-projects-area/ProjectDownloadMenuItemExtension.tsx
Labels: pr: to review soon, priority: high

#4133 [4130] Export useExplorerSubscription and useRelatedElementsViewSubscription for downstream applications
  CHANGELOG.adoc
  packages/sirius-web/frontend/sirius-web-application/src/index.ts
Labels: pr: to review soon, priority: low

#4041 [3980] Add the ability to select newly created nodes
  CHANGELOG.adoc
  packages/compatibility/backend/sirius-components-compatibility-emf/src/main/java/org/eclipse/sirius/components/compatibility/emf/modeloperations/ModelOperationHandlerSwitch.java
  packages/compatibility/backend/sirius-components-compatibility-emf/src/main/java/org/eclipse/sirius/components/compatibility/emf/modeloperations/NavigationOperationHandler.java
  packages/core/backend/sirius-components-collaborative/src/main/resources/schema/core.graphqls
  packages/core/backend/sirius-components-representations/src/main/java/org/eclipse/sirius/components/representations/Success.java
  packages/core/backend/sirius-components-representations/src/main/java/org/eclipse/sirius/components/representations/WorkbenchSelectionEntry.java
  packages/core/frontend/sirius-components-core/src/selection/useSelection.tsx
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/test/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/InvokeSingleClickOnDiagramElementToolEventHandlerTests.java
  packages/diagrams/backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/graphql/InvokeSingleClickOnDiagramElementToolMutationRunner.java
  packages/diagrams/backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/graphql/InvokeSingleClickOnTwoDiagramElementsToolMutationRunner.java
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/connector/ConnectorContextualMenu.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/connector/ConnectorContextualMenu.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/Palette.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/Palette.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/selection/useDiagramSelection.ts
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/ModelOperationDiagramControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/diagrams/ModelOperationDiagramDescriptionProvider.java
  packages/tests/backend/sirius-components-tests/src/test/java/org/eclipse/sirius/components/tests/GitCommitMessageTests.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/diagram/EdgeToolBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/diagram/NodeToolBuilder.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/EdgeToolItemProvider.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/NodeToolItemProvider.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/resources/plugin.properties
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/DiagramPackage.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/EdgeTool.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/NodeTool.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/DiagramPackageImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/EdgeToolImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/NodeToolImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/resources/model/diagram.ecore
  packages/view/backend/sirius-components-view-diagram/src/main/resources/model/diagram.genmodel
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/OperationInterpreterViewSwitch.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/DiagramOperationInterpreter.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ToolConverter.java
Labels: pr: to review soon, priority: high
