Repository eclipse-sirius/sirius-web, pull requests merged in 2024-06, with the labels that each got.

#3448 [3447] Add support for For construct in the operations DSL
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/ModelOperationDiagramControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/diagrams/ModelOperationDiagramDescriptionProvider.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/ForBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/ViewBuilders.java
  packages/view/backend/sirius-components-view-deck-edit/src/main/java/org/eclipse/sirius/components/view/deck/provider/DeckToolItemProvider.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/ToolItemProvider.java
  packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/ForItemProvider.java
  packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/OperationItemProvider.java
  packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/ViewItemProviderAdapterFactory.java
  packages/view/backend/sirius-components-view-edit/src/main/resources/icons/full/obj16/For.svg
  packages/view/backend/sirius-components-view-edit/src/main/resources/plugin.properties
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/OperationInterpreterViewSwitch.java
  packages/view/backend/sirius-components-view-emf/src/test/java/org/eclipse/sirius/components/view/emf/view/form/FormIdProviderTests.java
  packages/view/backend/sirius-components-view-form-edit/src/main/java/org/eclipse/sirius/components/view/form/provider/RichTextDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-form-edit/src/main/java/org/eclipse/sirius/components/view/form/provider/SliderDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-form-edit/src/main/java/org/eclipse/sirius/components/view/form/provider/TreeDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-gantt-edit/src/main/java/org/eclipse/sirius/components/view/gantt/provider/TaskToolItemProvider.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/For.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/ViewFactory.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/ViewPackage.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/impl/ForImpl.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/impl/ViewFactoryImpl.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/impl/ViewPackageImpl.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/util/ViewAdapterFactory.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/util/ViewSwitch.java
  packages/view/backend/sirius-components-view/src/main/resources/model/view.ecore
  packages/view/backend/sirius-components-view/src/main/resources/model/view.genmodel
  scripts/check-coverage.jsh
Labels: pr: to review soon, priority: low

#3540 [3539] Add editing context variable in diagram delete tool
  CHANGELOG.adoc
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/DeleteFromDiagramEventHandler.java
Labels: pr: to review soon, priority: high

#3530 [3529] Improve edge path when a layout direction is defined
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/diagrams/edges.cy.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/EdgeLayout.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/layoutParams.ts
Labels: pr: to review soon, priority: low

#3504 [3489] Apply a fit to screen after an arrange all
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/diagrams/edges.cy.ts
  integration-tests/cypress/workbench/Diagram.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/useArrangeAll.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/useArrangeAll.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/panel/DiagramPanel.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/panel/DiagramPanel.types.ts
Labels: pr: to review soon, priority: low

#3505 [3480] Fix an error that prevents border color to be properly applied
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/diagrams/node-style.cy.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/node/FreeFormNode.tsx
Labels: pr: to review later, priority: low

#3547 [fix] Fix edge decorator position in the new Domain diagram definition
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/representations/RelationEdgeDescriptionProvider.java
Labels: pr: to review later, priority: low

#3549 [3548] Cache the list of applicable migration participants
  CHANGELOG.adoc
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/migration/MigrationService.java
Labels: pr: to review later, priority: low

#3569 [3538] Register the Details view description in the editing context
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/details/services/DetailsDescriptionProvider.java
Labels: pr: to review soon, priority: high

#3576 [3575] Restore support for studio palette colors
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/EditingContextInitializer.java
Labels: pr: to review later, priority: low

#3567 [3566] Replace draggedNodeIdSelector
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/dropNode/DropNodeContext.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/dropNode/DropNodeContext.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/dropNode/useDropNode.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/dropNode/useDropNodeStyle.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/hover/useNodeHover.ts
Labels: pr: to review soon, priority: high

#3524 [doc] Add an ADR about diagram subscripton lifecycle
  CHANGELOG.adoc
  doc/adrs/151_improve_diagram_subscription_lifecycle.adoc
Labels: pr: to review soon, priority: high

#3568 [3562] Update displayed default model creation action
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/services/DefaultEditingContextActionProvider.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/StudioEditingContextActionProvider.java
Labels: pr: to review soon, priority: high

#3564 [3563] Improve NavigationBar extensibility
  CHANGELOG.adoc
  packages/sirius-web/frontend/sirius-web-application/src/index.ts
  packages/sirius-web/frontend/sirius-web-application/src/navigationBar/NavigationBar.tsx
  packages/sirius-web/frontend/sirius-web-application/src/navigationBar/NavigationBar.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/navigationBar/NavigationBarExtensionPoints.tsx
Labels: pr: to review soon, priority: high

#3600 [3582] Fix the initial direct edit tree item label for the explorer view
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/ExplorerInitialDirectEditTreeItemLabelProvider.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/EditLabelDiagramControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/trees/TreeControllerIntegrationTests.java
  packages/trees/backend/sirius-components-trees-tests/src/main/java/org/eclipse/sirius/components/trees/tests/graphql/InitialDirectEditTreeItemLabelQueryRunner.java
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItemDirectEditInput.tsx
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItemDirectEditInput.types.ts
  scripts/check-coverage.jsh
Labels: pr: to review soon, priority: high

#3599 [3553] Add RepresentationFactory extension point
  CHANGELOG.adoc
  packages/core/frontend/sirius-components-core/src/index.ts
  packages/core/frontend/sirius-components-core/src/workbench/RepresentationContext.ts
  packages/core/frontend/sirius-components-core/src/workbench/RepresentationContext.types.ts
  packages/core/frontend/sirius-components-core/src/workbench/RepresentationNavigation.tsx
  packages/core/frontend/sirius-components-core/src/workbench/RepresentationNavigation.types.ts
  packages/core/frontend/sirius-components-core/src/workbench/Workbench.tsx
  packages/core/frontend/sirius-components-core/src/workbench/Workbench.types.ts
  packages/core/frontend/sirius-components-core/src/workbench/WorkbenchExtensionPoints.ts
  packages/core/frontend/sirius-components-core/src/workbench/WorkbenchMachine.ts
  packages/portals/frontend/sirius-components-portals/src/representations/RepresentationFrame.tsx
  packages/portals/frontend/sirius-components-portals/src/representations/RepresentationFrame.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/application/SiriusWebApplication.tsx
  packages/sirius-web/frontend/sirius-web-application/src/extension/DefaultExtensionRegistry.tsx
  packages/sirius-web/frontend/sirius-web-application/src/onboarding/NewRepresentationArea.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/representations/RepresentationContextProvider.tsx
  packages/sirius-web/frontend/sirius-web-application/src/representations/RepresentationContextProvider.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/EditProjectView.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/EditProjectViewMachine.ts
Labels: pr: to review soon, priority: high

#3598 [3597] Remove representationEventProcessorClass from IRepresentation…
  CHANGELOG.adoc
  packages/charts/backend/sirius-components-charts-graphql/src/main/java/org/eclipse/sirius/components/charts/graphql/subscription/SubscriptionHierarchyEventDataFetcher.java
  packages/charts/backend/sirius-components-collaborative-charts/src/main/java/org/eclipse/sirius/components/collaborative/charts/HierarchyEventProcessorFactory.java
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/api/IEditingContextEventProcessor.java
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/api/IRepresentationEventProcessorComposedFactory.java
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/api/IRepresentationEventProcessorFactory.java
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/EditingContextEventProcessor.java
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/RepresentationEventProcessorComposedFactory.java
  packages/core/backend/sirius-components-graphql-api/src/main/java/org/eclipse/sirius/components/graphql/api/IEventProcessorSubscriptionProvider.java
  packages/deck/backend/sirius-components-collaborative-deck/src/main/java/org/eclipse/sirius/components/collaborative/deck/DeckEventProcessorFactory.java
  packages/deck/backend/sirius-components-collaborative-deck/src/main/java/org/eclipse/sirius/components/collaborative/deck/handlers/CreateDeckCardEventHandler.java
  packages/deck/backend/sirius-components-deck-graphql/src/main/java/org/eclipse/sirius/components/deck/graphql/datafetchers/mutation/MutationDeckCreateCardDataFetcher.java
  packages/deck/backend/sirius-components-deck-graphql/src/main/java/org/eclipse/sirius/components/deck/graphql/datafetchers/subscription/SubscriptionDeckDiagramEventDataFetcher.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/DiagramEventProcessorFactory.java
  packages/diagrams/backend/sirius-components-diagrams-graphql/src/main/java/org/eclipse/sirius/components/diagrams/graphql/datafetchers/subscription/SubscriptionDiagramEventDataFetcher.java
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/FormDescriptionEditorEventProcessorFactory.java
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors-graphql/src/main/java/org/eclipse/sirius/components/formdescriptioneditors/graphql/datafetchers/subscription/SubscriptionFormDescriptionEditorEventDataFetcher.java
  packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/FormEventProcessorFactory.java
  packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/PropertiesEventProcessorFactory.java
  packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/RelatedElementsEventProcessorFactory.java
  packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/RepresentationsEventProcessorFactory.java
  packages/forms/backend/sirius-components-collaborative-forms/src/test/java/org/eclipse/sirius/components/collaborative/forms/handlers/EditTextfieldEventHandlerTests.java
  packages/forms/backend/sirius-components-forms-graphql/src/main/java/org/eclipse/sirius/components/forms/graphql/datafetchers/subscription/SubscriptionFormEventDataFetcher.java
  packages/forms/backend/sirius-components-forms-graphql/src/main/java/org/eclipse/sirius/components/forms/graphql/datafetchers/subscription/SubscriptionPropertiesEventDataFetcher.java
  packages/forms/backend/sirius-components-forms-graphql/src/main/java/org/eclipse/sirius/components/forms/graphql/datafetchers/subscription/SubscriptionRelatedElementsEventDataFetcher.java
  packages/forms/backend/sirius-components-forms-graphql/src/main/java/org/eclipse/sirius/components/forms/graphql/datafetchers/subscription/SubscriptionRepresentationsEventDataFetcher.java
  packages/forms/backend/sirius-components-forms-tests/src/main/java/org/eclipse/sirius/components/forms/tests/assertions/TextareaAssert.java
  packages/gantt/backend/sirius-components-collaborative-gantt/src/main/java/org/eclipse/sirius/components/collaborative/gantt/GanttEventProcessorFactory.java
  packages/gantt/backend/sirius-components-gantt-graphql/src/main/java/org/eclipse/sirius/components/gantt/graphql/datafetchers/subscription/SubscriptionGanttDiagramEventDataFetcher.java
  packages/portals/backend/sirius-components-collaborative-portals/src/main/java/org/eclipse/sirius/components/collaborative/portals/PortalEventProcessorFactory.java
  packages/portals/backend/sirius-components-portals-graphql/src/main/java/org/eclipse/sirius/components/portals/graphql/datafetchers/subscription/SubscriptionPortalEventDataFetcher.java
  packages/selection/backend/sirius-components-collaborative-selection/src/main/java/org/eclipse/sirius/components/collaborative/selection/SelectionEventProcessorFactory.java
  packages/selection/backend/sirius-components-selection-graphql/src/main/java/org/eclipse/sirius/components/selection/graphql/datafetchers/subscription/SubscriptionSelectionEventDataFetcher.java
  packages/sirius-web/backend/sirius-web-sample-application/src/test/java/org/eclipse/sirius/web/sample/tests/integration/formdescritpioneditors/FormDescriptionEditorPageIntegrationTests.java
  packages/sirius-web/backend/sirius-web-sample-application/src/test/java/org/eclipse/sirius/web/sample/tests/integration/view/ReferenceWidgetIntegrationTests.java
  packages/sirius-web/backend/sirius-web-sample-application/src/test/java/org/eclipse/sirius/web/sample/tests/integration/view/SliderWidgetIntegrationTests.java
  packages/sirius-web/backend/sirius-web-sample-application/src/test/java/org/eclipse/sirius/web/sample/tests/integration/view/ViewDiagramIntegrationTests.java
  packages/sirius-web/backend/sirius-web-sample-application/src/test/java/org/eclipse/sirius/web/sample/tests/integration/view/ViewFormIntegrationTests.java
  packages/sirius-web/backend/sirius-web-sample-application/src/test/java/org/eclipse/sirius/web/sample/tests/integration/view/ViewInitialDirectEditElementLabelProviderIntegrationTests.java
  packages/sirius-web/backend/sirius-web-starter/src/main/java/org/eclipse/sirius/web/starter/SiriusWebStarterConfiguration.java
  packages/sirius-web/backend/sirius-web-tests/src/main/java/org/eclipse/sirius/web/tests/services/deck/CreateDeckCardMutationRunner.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/deck/PapayaDeckControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/formdescriptioneditors/FormDescriptionEditorControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/selection/SelectionControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/validation/ValidationControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/deck/PapayaDeckDescriptionProvider.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/diagrams/ModelOperationDiagramDescriptionProvider.java
  packages/starters/backend/sirius-components-starter/src/main/java/org/eclipse/sirius/components/starter/SiriusWebStarterConfiguration.java
  packages/trees/backend/sirius-components-collaborative-trees/src/main/java/org/eclipse/sirius/components/collaborative/trees/TreeEventProcessorFactory.java
  packages/trees/backend/sirius-components-trees-graphql/src/main/java/org/eclipse/sirius/components/trees/graphql/datafetchers/subscription/SubscriptionTreeEventDataFetcher.java
  packages/validation/backend/sirius-components-collaborative-validation/src/main/java/org/eclipse/sirius/components/collaborative/validation/ValidationEventProcessorFactory.java
  packages/validation/backend/sirius-components-validation-graphql/src/main/java/org/eclipse/sirius/components/validation/graphql/datafetchers/subscription/SubscriptionValidationEventDataFetcher.java
  scripts/check-coverage.jsh
Labels: pr: to review soon, priority: high

#3605 [enh] Improve the navigation within a diagram
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/drag/useNodesDraggable.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/drag/useNodesDraggable.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/useDiagramElementPalette.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/useDiagramPalette.tsx
Labels: pr: to review soon, priority: low

#3613 [3611] Fix missing creation tools icons in the palette
  CHANGELOG.adoc
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/ViewEMFImagePathService.java
Labels: pr: to review soon, priority: low

#3620 [test] Fix some flaky Cypress tests
  integration-tests/cypress/e2e/project/portals/portals.cy.ts
Labels: pr: to review soon, priority: high

#3546 [3544] Add missing positions for inside label
  CHANGELOG.adoc
  doc/screenshots/insideLabelPositions.png
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/resources/schema/diagram.graphqls
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/InsideLabelLocation.java
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/convertDiagram.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/convertLabel.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/graphql/subscription/labelFragment.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/node/FreeFormNode.tsx
  packages/view/backend/sirius-components-view-diagram-edit/src/main/resources/plugin.properties
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/InsideLabelPosition.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/DiagramPackageImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/resources/model/diagram.ecore
  packages/view/backend/sirius-components-view-diagram/src/main/resources/model/diagram.genmodel
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewDiagramDescriptionConverter.java
Labels: pr: to review soon, priority: low

#3577 [3574] Add a loading indicator during execution of an arrange-all
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/diagrams/arrange-all.cy.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/panel/DiagramPanel.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/panel/DiagramPanel.types.ts
Labels: pr: to review soon, priority: low

#3629 [3628] Restore support for expand all and reveal in the explorer
  CHANGELOG.adoc
  packages/emf/backend/sirius-components-emf-forms/src/main/java/org/eclipse/sirius/components/emf/forms/EMFFormDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/ExpandAllTreePathProvider.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/ExplorerNavigationService.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/ExplorerTreePathProvider.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/api/IExplorerNavigationService.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/trees/ExplorerExpandAllControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/trees/ExplorerTreeFilterControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/trees/ExplorerTreePathControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/PapayaViewInjector.java
  packages/trees/backend/sirius-components-trees-tests/src/main/java/org/eclipse/sirius/components/trees/tests/graphql/ExpandAllTreePathQueryRunner.java
  packages/trees/backend/sirius-components-trees-tests/src/main/java/org/eclipse/sirius/components/trees/tests/graphql/TreePathQueryRunner.java
  scripts/check-coverage.jsh
Labels: pr: to review soon, priority: high

#3621 [enh] Switch to a 12px default font size
  packages/core/frontend/sirius-components-core/src/theme.ts
  packages/sirius-web/frontend/sirius-web-application/src/views/project-browser/create-projects-area/ProjectTemplateCard.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/project-settings/images/ProjectImagesSettings.tsx
Labels: pr: to review soon, priority: high

#3594 [3586] Correctly attach useKeyPress to the palette
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/connector/ConnectorContextualMenu.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/connector/useConnector.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/connector/useConnector.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/handles/ConnectionTargetHandle.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/DiagramElementPalette.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/DiagramPalette.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/useDiagramElementPalette.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/useDiagramPalette.tsx
Labels: pr: to review soon, priority: high

#3607 [3606] Improve error handling for ExecuteEditingContextFunction
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/documents/DocumentControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/trees/ExplorerExpandAllControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/trees/ExplorerTreePathControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/PapayaViewInjector.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/migration/NodeDescriptionLabelExpressionMigrationParticipantTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/migration/NodeStyleDescriptionColorMigrationParticipantTests.java
  packages/tests/backend/sirius-components-graphql-tests/src/main/java/org/eclipse/sirius/components/graphql/tests/ExecuteEditingContextFunctionEventHandler.java
  packages/tests/backend/sirius-components-graphql-tests/src/main/java/org/eclipse/sirius/components/graphql/tests/ExecuteEditingContextFunctionInput.java
  packages/tests/backend/sirius-components-graphql-tests/src/main/java/org/eclipse/sirius/components/graphql/tests/ExecuteEditingContextFunctionRunner.java
  packages/tests/backend/sirius-components-graphql-tests/src/main/java/org/eclipse/sirius/components/graphql/tests/api/IExecuteEditingContextFunctionRunner.java
Labels: pr: to review soon, priority: high

#3615 [3614] Add IRepresentationEventProcessorFluxCustomizer
  CHANGELOG.adoc
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/api/IRepresentationEventProcessorFluxCustomizer.java
  packages/forms/backend/sirius-components-forms-tests/src/main/java/org/eclipse/sirius/components/forms/tests/assertions/CheckboxAssert.java
  packages/forms/backend/sirius-components-forms-tests/src/main/java/org/eclipse/sirius/components/forms/tests/assertions/FormAssertions.java
  packages/forms/backend/sirius-components-forms-tests/src/main/java/org/eclipse/sirius/components/forms/tests/assertions/LinkAssert.java
  packages/forms/backend/sirius-components-forms-tests/src/main/java/org/eclipse/sirius/components/forms/tests/graphql/EditCheckboxMutationRunner.java
  packages/sirius-web/backend/sirius-web-starter/src/main/java/org/eclipse/sirius/web/starter/SiriusWebStarterConfiguration.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/forms/CheckboxControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/forms/LinkControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/representations/RepresentationEventProcessorFluxCustomizerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/forms/FormWithCheckboxDescriptionProvider.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/forms/FormWithLinkDescriptionProvider.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/representations/OnCustomizedRepresentationEventProcessor.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/representations/TestPayload.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/representations/TestRepresentationEventProcessorFluxCustomizer.java
Labels: pr: to review soon, priority: high

#3640 [test] Fix some flaky Cypress tests
  integration-tests/cypress/e2e/project/diagrams/collapse.cy.ts
  integration-tests/cypress/e2e/project/diagrams/group-palette.cy.ts
Labels: pr: to review soon, priority: high

#3626 [3624] Fix issue with header separator not spanning entire node width
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/diagrams/collapse.cy.ts
  integration-tests/cypress/e2e/project/diagrams/diagram-label.cy.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/IconLabelNodeConverter.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/convertLabel.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/Label.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/FreeFormNodeLayoutHandler.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/layoutNode.ts
  packages/sirius-web/frontend/sirius-web/src/nodes/EllipseNodeLayoutHandler.ts
Labels: pr: to review soon, priority: low

#3635 [3604] Make node overlap resolution faster during "Arrange All"
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/EdgeLayout.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/helper-lines/useHelperLines.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/overlap/useOverlap.ts
Labels: pr: to review later, priority: low

#3617 [3523] Support rounding dates when changing dates from gantt
  CHANGELOG.adoc
  package-lock.json
  packages/gantt/backend/sirius-components-collaborative-gantt/src/main/resources/schema/gantt.graphqls
  packages/gantt/backend/sirius-components-gantt/src/main/java/org/eclipse/sirius/components/gantt/Gantt.java
  packages/gantt/backend/sirius-components-gantt/src/main/java/org/eclipse/sirius/components/gantt/GanttDateRounding.java
  packages/gantt/backend/sirius-components-gantt/src/main/java/org/eclipse/sirius/components/gantt/GanttDateRoundingTimeUnit.java
  packages/gantt/backend/sirius-components-gantt/src/main/java/org/eclipse/sirius/components/gantt/Task.java
  packages/gantt/backend/sirius-components-gantt/src/main/java/org/eclipse/sirius/components/gantt/description/GanttDescription.java
  packages/gantt/backend/sirius-components-gantt/src/main/java/org/eclipse/sirius/components/gantt/renderer/GanttElementFactory.java
  packages/gantt/backend/sirius-components-gantt/src/main/java/org/eclipse/sirius/components/gantt/renderer/component/GanttComponent.java
  packages/gantt/backend/sirius-components-gantt/src/main/java/org/eclipse/sirius/components/gantt/renderer/elements/GanttElementProps.java
  packages/gantt/frontend/sirius-components-gantt/package.json
  packages/gantt/frontend/sirius-components-gantt/src/graphql/subscription/GanttSubscription.types.ts
  packages/gantt/frontend/sirius-components-gantt/src/graphql/subscription/ganttSubscription.ts
  packages/gantt/frontend/sirius-components-gantt/src/helper/helper.tsx
  packages/gantt/frontend/sirius-components-gantt/src/representation/Gantt.tsx
  packages/gantt/frontend/sirius-components-gantt/src/representation/Gantt.types.ts
  packages/gantt/frontend/sirius-components-gantt/src/representation/GanttRepresentation.tsx
  packages/gantt/frontend/sirius-components-gantt/src/toolbar/Toolbar.tsx
  packages/sirius-web/frontend/sirius-web/package.json
  packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/configuration/TaskExampleBuilder.java
  packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/configuration/view/TaskJavaService.java
  packages/starters/backend/sirius-components-task-starter/src/test/java/org/eclipse/sirius/components/task/starter/configuration/view/TaskJavaServiceTests.java
  packages/task/backend/sirius-components-task/src/main/java/org/eclipse/sirius/components/task/AbstractTask.java
  packages/task/backend/sirius-components-task/src/main/java/org/eclipse/sirius/components/task/impl/AbstractTaskImpl.java
  packages/task/backend/sirius-components-task/src/main/java/org/eclipse/sirius/components/task/impl/TaskPackageImpl.java
  packages/task/backend/sirius-components-task/src/main/resources/model/task.ecore
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/ConditionalTaskStyleBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/GanttBuilders.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/GanttDescriptionBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/TaskDescriptionBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/TaskStyleDescriptionBuilder.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/gantt/ViewGanttDescriptionConverter.java
  packages/view/backend/sirius-components-view-gantt-edit/src/main/java/org/eclipse/sirius/components/view/gantt/provider/ConditionalTaskStyleItemProvider.java
  packages/view/backend/sirius-components-view-gantt-edit/src/main/java/org/eclipse/sirius/components/view/gantt/provider/GanttDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-gantt-edit/src/main/java/org/eclipse/sirius/components/view/gantt/provider/GanttItemProviderAdapterFactory.java
  packages/view/backend/sirius-components-view-gantt-edit/src/main/java/org/eclipse/sirius/components/view/gantt/provider/TaskDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-gantt-edit/src/main/java/org/eclipse/sirius/components/view/gantt/provider/TaskStyleDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-gantt-edit/src/main/resources/icons/full/obj16/ConditionalTaskStyle.gif
  packages/view/backend/sirius-components-view-gantt-edit/src/main/resources/icons/full/obj16/TaskStyleDescription.gif
  packages/view/backend/sirius-components-view-gantt-edit/src/main/resources/plugin.properties
  packages/view/backend/sirius-components-view-gantt/src/main/java/org/eclipse/sirius/components/view/gantt/ConditionalTaskStyle.java
  packages/view/backend/sirius-components-view-gantt/src/main/java/org/eclipse/sirius/components/view/gantt/GanttDescription.java
  packages/view/backend/sirius-components-view-gantt/src/main/java/org/eclipse/sirius/components/view/gantt/GanttFactory.java
  packages/view/backend/sirius-components-view-gantt/src/main/java/org/eclipse/sirius/components/view/gantt/GanttPackage.java
  packages/view/backend/sirius-components-view-gantt/src/main/java/org/eclipse/sirius/components/view/gantt/TaskDescription.java
  packages/view/backend/sirius-components-view-gantt/src/main/java/org/eclipse/sirius/components/view/gantt/TaskStyleDescription.java
  packages/view/backend/sirius-components-view-gantt/src/main/java/org/eclipse/sirius/components/view/gantt/impl/ConditionalTaskStyleImpl.java
  packages/view/backend/sirius-components-view-gantt/src/main/java/org/eclipse/sirius/components/view/gantt/impl/GanttDescriptionImpl.java
  packages/view/backend/sirius-components-view-gantt/src/main/java/org/eclipse/sirius/components/view/gantt/impl/GanttFactoryImpl.java
  packages/view/backend/sirius-components-view-gantt/src/main/java/org/eclipse/sirius/components/view/gantt/impl/GanttPackageImpl.java
  packages/view/backend/sirius-components-view-gantt/src/main/java/org/eclipse/sirius/components/view/gantt/impl/TaskDescriptionImpl.java
  packages/view/backend/sirius-components-view-gantt/src/main/java/org/eclipse/sirius/components/view/gantt/impl/TaskStyleDescriptionImpl.java
  packages/view/backend/sirius-components-view-gantt/src/main/java/org/eclipse/sirius/components/view/gantt/util/GanttAdapterFactory.java
  packages/view/backend/sirius-components-view-gantt/src/main/java/org/eclipse/sirius/components/view/gantt/util/GanttSwitch.java
  packages/view/backend/sirius-components-view-gantt/src/main/resources/model/gantt.ecore
  packages/view/backend/sirius-components-view-gantt/src/main/resources/model/gantt.genmodel
Labels: pr: to review soon, priority: high

#3532 [3531] Fix unnecessary edges label re render
  CHANGELOG.adoc
  packages/core/frontend/sirius-components-core/src/icon/IconOverlay.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/convertDiagram.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/convertLabel.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/Label.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/Label.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/MultiLabelEdge.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/node/FreeFormNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/node/IconLabelNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/node/ListNode.tsx
  packages/sirius-web/frontend/sirius-web/src/nodes/EllipseNode.tsx
Labels: pr: to review later, priority: low

#3654 [3653] Add documentation for Gantt
  CHANGELOG.adoc
  doc/specifier/images/gantt-description-overview.png
  doc/specifier/images/gantt-overview.png
  doc/specifier/images/gantt-task-handlers.png
  doc/specifier/images/gantt-task-relation-tool.png
  doc/specifier/images/gantt-task-tools.png
  doc/specifier/images/gantt-tools.png
  doc/specifier/representation-gantt.adoc
  doc/user/images/gantt-overview.png
  doc/user/images/gantt-task-dependencies.png
  doc/user/images/gantt-task-dependency-tool.png
  doc/user/images/gantt-task-dependency.png
  doc/user/images/gantt-task-dragdrop.png
  doc/user/images/gantt-task-group.png
  doc/user/images/gantt-task-handlers.png
  doc/user/images/gantt-task-milestone.png
  doc/user/images/gantt-task.png
  doc/user/images/gantt-toolbar.png
  doc/user/representation-gantt.adoc
Labels: pr: to review soon, priority: high

#3646 [3645] Revert earlier change in selection propagation which caused regressions
  CHANGELOG.adoc
  packages/core/frontend/sirius-components-core/src/selection/SelectionContext.tsx
Labels: pr: to review soon, priority: low

#3657 [3650] Fix potential NPE in DiagramNavigator and Node
  CHANGELOG.adoc
  packages/diagrams/backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/navigation/DiagramNavigator.java
  packages/diagrams/backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/navigation/NavigatorCache.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/Node.java
Labels: pr: to review soon, priority: high

#3652 [3651] Improve isDescendantOf used in diagram
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/convertDiagram.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/connector/useConnector.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/dropNode/useDropNode.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/EdgeLayout.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/EdgeLayout.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/handles/useHandleChange.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/helper-lines/useHelperLines.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/layoutHandles.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/layoutNode.ts
Labels: pr: to review later, priority: low

#3667 [3666] Enable EMF's intrinsicIDToEObjectMap for JSON resources
  CHANGELOG.adoc
  packages/emf/backend/sirius-components-emf/pom.xml
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/services/JSONResourceFactory.java
Labels: pr: to review soon, priority: high

#3665 [3664] Fix missing default images
  CHANGELOG.adoc
  packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/services/CoreImagePathService.java
Labels: pr: to review soon, priority: high
