Repository eclipse-sirius/sirius-web, pull requests merged in 2024-03, with the labels that each got.

#3171 [2825] Fix click on the text behavior during direct edit
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/diagrams/direct-edit-label.cy.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/direct-edit/DiagramDirectEditInput.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/DiagramElementPalette.tsx
Labels: pr: to review soon, priority: high

#3137 [3084] Add SplitButton widget
  CHANGELOG.adoc
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/AddWidgetEventHandler.java
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/formdescriptioneditors/components/ViewFormDescriptionEditorConverterSwitch.java
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FormDescriptionEditorRepresentation.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/SplitButtonWidget.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/SplitButtonWidget.type.ts
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/WidgetEntry.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/WidgetEntry.types.ts
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/WidgetOperations.tsx
  packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/FormQueryService.java
  packages/forms/backend/sirius-components-collaborative-forms/src/main/resources/schema/form.graphqls
  packages/forms/backend/sirius-components-forms-graphql/src/main/java/org/eclipse/sirius/components/forms/graphql/datafetchers/form/WidgetHasHelpTextDataFetcher.java
  packages/forms/backend/sirius-components-forms-graphql/src/main/java/org/eclipse/sirius/components/forms/graphql/datafetchers/form/WidgetIconURLDataFetcher.java
  packages/forms/backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/SplitButton.java
  packages/forms/backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/components/SplitButtonComponent.java
  packages/forms/backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/components/SplitButtonComponentProps.java
  packages/forms/backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/components/WidgetComponent.java
  packages/forms/backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/description/SplitButtonDescription.java
  packages/forms/backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/elements/SplitButtonElementProps.java
  packages/forms/backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/renderer/FormComponentPropsValidator.java
  packages/forms/backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/renderer/FormElementFactory.java
  packages/forms/backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/renderer/FormInstancePropsValidator.java
  packages/forms/backend/sirius-components-forms/src/test/java/org/eclipse/sirius/components/forms/render/RenderSplitButtonTest.java
  packages/forms/frontend/sirius-components-forms/src/form/FormEventFragments.ts
  packages/forms/frontend/sirius-components-forms/src/form/FormEventFragments.types.ts
  packages/forms/frontend/sirius-components-forms/src/propertysections/PropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/SplitButtonPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/SplitButtonPropertySection.types.ts
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/SplitButtonPropertySection.test.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/SplitButtonPropertySection.test.tsx.snap
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/form/ViewFormDescriptionConverterSwitch.java
  packages/view/backend/sirius-components-view-emf/src/test/java/org/eclipse/sirius/components/view/emf/view/DynamicFormsTests.java
  packages/view/backend/sirius-components-view-form-edit/src/main/java/org/eclipse/sirius/components/view/form/provider/FlexboxContainerDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-form-edit/src/main/java/org/eclipse/sirius/components/view/form/provider/FormElementForItemProvider.java
  packages/view/backend/sirius-components-view-form-edit/src/main/java/org/eclipse/sirius/components/view/form/provider/FormElementIfItemProvider.java
  packages/view/backend/sirius-components-view-form-edit/src/main/java/org/eclipse/sirius/components/view/form/provider/FormItemProviderAdapterFactory.java
  packages/view/backend/sirius-components-view-form-edit/src/main/java/org/eclipse/sirius/components/view/form/provider/GroupDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-form-edit/src/main/java/org/eclipse/sirius/components/view/form/provider/SplitButtonDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-form-edit/src/main/resources/plugin.properties
  packages/view/backend/sirius-components-view-form/src/main/java/org/eclipse/sirius/components/view/form/FormFactory.java
  packages/view/backend/sirius-components-view-form/src/main/java/org/eclipse/sirius/components/view/form/FormPackage.java
  packages/view/backend/sirius-components-view-form/src/main/java/org/eclipse/sirius/components/view/form/SplitButtonDescription.java
  packages/view/backend/sirius-components-view-form/src/main/java/org/eclipse/sirius/components/view/form/adapters/FormColorAdapter.java
  packages/view/backend/sirius-components-view-form/src/main/java/org/eclipse/sirius/components/view/form/impl/FormFactoryImpl.java
  packages/view/backend/sirius-components-view-form/src/main/java/org/eclipse/sirius/components/view/form/impl/FormPackageImpl.java
  packages/view/backend/sirius-components-view-form/src/main/java/org/eclipse/sirius/components/view/form/impl/SplitButtonDescriptionImpl.java
  packages/view/backend/sirius-components-view-form/src/main/java/org/eclipse/sirius/components/view/form/util/FormAdapterFactory.java
  packages/view/backend/sirius-components-view-form/src/main/java/org/eclipse/sirius/components/view/form/util/FormSwitch.java
  packages/view/backend/sirius-components-view-form/src/main/resources/model/form.ecore
  packages/view/backend/sirius-components-view-form/src/main/resources/model/form.genmodel
Labels: pr: to review later, priority: low

#3175 [fix] Add missing view builders
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/ConditionalDeckElementDescriptionStyleBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/DeckElementDescriptionStyleBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/FormBuilders.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/SplitButtonDescriptionBuilder.java
Labels: pr: to review soon, priority: high

#3196 [doc] Contribute and ADR about variables in the view form dsl
  CHANGELOG.adoc
  doc/adrs/136_add_variables_to_view_form_dsl.adoc
Labels: pr: to review soon, priority: high

#3189 [3185] Fix helper lines computation by excluding child nodes
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/dropNode/useDropNode.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/helper-lines/useHelperLines.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/layoutNode.ts
Labels: pr: to review soon, priority: low

#3188 [3187] Fix borderNode creation to use click position for border place…
  CHANGELOG.adoc
  doc/screenshots/borderNodeCreationArea.png
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/layout.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/layoutBorderNodes.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/layoutParams.ts
Labels: pr: to review soon, priority: low

#3151 [3149] Improve newly created border node position
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/layoutNode.ts
Labels: pr: to review later, priority: low

#3202 [3201] Add support for tools on multiple diagram elements (hide, fade…
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/diagrams/diagram-contextual-palette.cy.js
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/Palette.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/group-tool/GroupPalette.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/group-tool/GroupPalette.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/group-tool/useGroupPalette.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/group-tool/useGroupPalette.types.ts
Labels: pr: to review soon, priority: low

#3211 [fix] Adapt VS Code extension to recent GraphQL Schema changes
  vscode-extension/src/data/ProjectData.ts
  vscode-extension/src/data/ServerData.ts
Labels: pr: to review soon, priority: high

#3203 [fix] Fix typo in error message
  packages/emf/backend/sirius-components-emf/src/main/resources/messages/sirius-web-emf.properties
Labels: pr: to review soon, priority: high

#3199 [3019] Improve the reusability of the reference widget
  CHANGELOG.adoc
  packages/formdescriptioneditors/backend/pom.xml
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors-widget-reference/.checkstyle
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors-widget-reference/.classpath
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors-widget-reference/.project
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors-widget-reference/.settings/org.eclipse.core.resources.prefs
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors-widget-reference/.settings/org.eclipse.core.runtime.prefs
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors-widget-reference/.settings/org.eclipse.jdt.apt.core.prefs
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors-widget-reference/.settings/org.eclipse.jdt.core.prefs
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors-widget-reference/.settings/org.eclipse.jdt.ui.prefs
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors-widget-reference/.settings/org.eclipse.m2e.core.prefs
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors-widget-reference/.settings/org.springframework.ide.eclipse.prefs
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors-widget-reference/README.adoc
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors-widget-reference/pom.xml
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors-widget-reference/src/main/java/org/eclipse/sirius/components/formdescriptioneditors/widget/reference/ReferenceWidgetDescriptionProvider.java
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors-widget-reference/src/main/java/org/eclipse/sirius/components/formdescriptioneditors/widget/reference/ReferenceWidgetPreviewConverterProvider.java
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors-widget-reference/src/main/resources/.gitkeep
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors-widget-reference/src/test/java/org/eclipse/sirius/components/formdescriptioneditors/widget/reference/architecture/ArchitectureConstants.java
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors-widget-reference/src/test/java/org/eclipse/sirius/components/formdescriptioneditors/widget/reference/architecture/CodingRulesTests.java
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors-widget-reference/src/test/java/org/eclipse/sirius/components/formdescriptioneditors/widget/reference/architecture/ImmutableTests.java
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors-widget-reference/src/test/resources/logback-test.xml
  packages/formdescriptioneditors/backend/sirius-components-formdescriptioneditors/README.adoc
  packages/forms/backend/pom.xml
  packages/forms/backend/sirius-components-collaborative-widget-reference/pom.xml
  packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/ReferenceWidgetDefaultCreateElementHandler.java
  packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/ReferenceWidgetDescriptor.java
  packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/api/IReferenceWidgetCreateElementHandler.java
  packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/api/IReferenceWidgetRootCandidateSearchProvider.java
  packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/browser/ModelBrowsersDescriptionProvider.java
  packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/browser/ReferenceWidgetDefaultCandidateSearchProvider.java
  packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/handlers/CreateElementEventHandler.java
  packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/handlers/ReferenceWidgetChildCreationDescriptionsEventHandler.java
  packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/handlers/ReferenceWidgetRootCreationDescriptionsEventHandler.java
  packages/forms/backend/sirius-components-collaborative-widget-reference/src/test/java/org/eclipse/sirius/components/collaborative/widget/reference/handlers/CreateElementEventHandlerTests.java
  packages/forms/backend/sirius-components-widget-reference/pom.xml
  packages/releng/backend/sirius-components-test-coverage/pom.xml
  packages/sirius-web/backend/sirius-web-sample-application/pom.xml
  packages/view/backend/pom.xml
  packages/view/backend/sirius-components-view-emf-widget-reference/.checkstyle
  packages/view/backend/sirius-components-view-emf-widget-reference/.classpath
  packages/view/backend/sirius-components-view-emf-widget-reference/.project
  packages/view/backend/sirius-components-view-emf-widget-reference/.settings/org.eclipse.core.resources.prefs
  packages/view/backend/sirius-components-view-emf-widget-reference/.settings/org.eclipse.core.runtime.prefs
  packages/view/backend/sirius-components-view-emf-widget-reference/.settings/org.eclipse.jdt.apt.core.prefs
  packages/view/backend/sirius-components-view-emf-widget-reference/.settings/org.eclipse.jdt.core.prefs
  packages/view/backend/sirius-components-view-emf-widget-reference/.settings/org.eclipse.jdt.ui.prefs
  packages/view/backend/sirius-components-view-emf-widget-reference/.settings/org.eclipse.m2e.core.prefs
  packages/view/backend/sirius-components-view-emf-widget-reference/.settings/org.springframework.ide.eclipse.prefs
  packages/view/backend/sirius-components-view-emf-widget-reference/README.adoc
  packages/view/backend/sirius-components-view-emf-widget-reference/pom.xml
  packages/view/backend/sirius-components-view-emf-widget-reference/src/main/java/org/eclipse/sirius/components/view/emf/widget/reference/ReferenceEMFConfiguration.java
  packages/view/backend/sirius-components-view-emf-widget-reference/src/main/java/org/eclipse/sirius/components/view/emf/widget/reference/ReferenceWidgetDescriptionConverterProvider.java
  packages/view/backend/sirius-components-view-emf-widget-reference/src/main/java/org/eclipse/sirius/components/view/emf/widget/reference/ReferenceWidgetDescriptionConverterSwitch.java
  packages/view/backend/sirius-components-view-emf-widget-reference/src/main/java/org/eclipse/sirius/components/view/emf/widget/reference/ReferenceWidgetStyleProvider.java
  packages/view/backend/sirius-components-view-emf-widget-reference/src/main/resources/.gitkeep
  packages/view/backend/sirius-components-view-emf-widget-reference/src/test/java/org/eclipse/sirius/components/view/emf/widget/reference/architecture/ArchitectureConstants.java
  packages/view/backend/sirius-components-view-emf-widget-reference/src/test/java/org/eclipse/sirius/components/view/emf/widget/reference/architecture/CodingRulesTests.java
  packages/view/backend/sirius-components-view-emf-widget-reference/src/test/java/org/eclipse/sirius/components/view/emf/widget/reference/architecture/SpringCodingRulesTests.java
  packages/view/backend/sirius-components-view-emf-widget-reference/src/test/resources/logback-test.xml
Labels: pr: to review soon, priority: high

#3162 Add cypress tests for Gantt
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/gantt/gantt-task.cy.ts
  integration-tests/cypress/e2e/project/gantt/gantt.cy.ts
  integration-tests/cypress/workbench/Deck.ts
  integration-tests/cypress/workbench/Explorer.ts
  integration-tests/cypress/workbench/Gantt.ts
  package-lock.json
  packages/gantt/backend/sirius-components-collaborative-gantt/src/main/java/org/eclipse/sirius/components/collaborative/gantt/GanttEventProcessor.java
  packages/gantt/frontend/sirius-components-gantt/package.json
  packages/gantt/frontend/sirius-components-gantt/src/helper/helper.tsx
  packages/gantt/frontend/sirius-components-gantt/src/icons/TaskIcon.tsx
  packages/gantt/frontend/sirius-components-gantt/src/palette/ContextualPalette.tsx
  packages/gantt/frontend/sirius-components-gantt/src/representation/Gantt.tsx
  packages/gantt/frontend/sirius-components-gantt/src/representation/Gantt.types.ts
  packages/gantt/frontend/sirius-components-gantt/src/representation/GanttRepresentation.tsx
  packages/gantt/frontend/sirius-components-gantt/src/toolbar/Toolbar.tsx
  packages/gantt/frontend/sirius-components-gantt/src/toolbar/Toolbar.types.ts
  packages/gantt/frontend/sirius-components-gantt/src/toolbar/useFullScreen.ts
  packages/gantt/frontend/sirius-components-gantt/src/toolbar/useFullscreen.types.ts
  packages/sirius-web/frontend/sirius-web-application/package.json
  packages/sirius-web/frontend/sirius-web-application/src/modals/new-document/NewDocumentModal.tsx
  packages/sirius-web/frontend/sirius-web/package.json
  packages/starters/backend/sirius-components-task-starter/pom.xml
  packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/configuration/TaskExampleBuilder.java
  packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/configuration/view/ViewGanttDescriptionBuilder.java
  packages/starters/backend/sirius-components-task-starter/src/test/java/org/eclipse/sirius/components/task/starter/configuration/TaskExampleBuilderTests.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/TaskDescriptionBuilder.java
  packages/view/backend/sirius-components-view-gantt-edit/src/main/java/org/eclipse/sirius/components/view/gantt/provider/TaskDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-gantt-edit/src/main/resources/plugin.properties
  packages/view/backend/sirius-components-view-gantt/src/main/java/org/eclipse/sirius/components/view/gantt/GanttPackage.java
  packages/view/backend/sirius-components-view-gantt/src/main/java/org/eclipse/sirius/components/view/gantt/TaskDescription.java
  packages/view/backend/sirius-components-view-gantt/src/main/java/org/eclipse/sirius/components/view/gantt/impl/GanttPackageImpl.java
  packages/view/backend/sirius-components-view-gantt/src/main/java/org/eclipse/sirius/components/view/gantt/impl/TaskDescriptionImpl.java
  packages/view/backend/sirius-components-view-gantt/src/main/resources/model/gantt.ecore
  packages/view/backend/sirius-components-view-gantt/src/main/resources/model/gantt.genmodel
Labels: pr: to review soon, priority: low

#3224 [3215] Fix deletion tool on a diagram element from the VSCode extension
  CHANGELOG.adoc
  vscode-extension/src/view/app/App.tsx
Labels: pr: to review soon, priority: high

#3238 [3235] Only display diagram element palette during a single selection
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/group-tool/GroupPalette.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/useDiagramElementPalette.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/useDiagramElementPalette.types.ts
Labels: pr: to review soon, priority: low

#3226 [3225] Handle not available local storage in deletion dialog
  CHANGELOG.adoc
  packages/core/frontend/sirius-components-core/src/modals/confirmation/ConfirmationDialog.tsx
  packages/core/frontend/sirius-components-core/src/modals/confirmation/ConfirmationDialog.types.ts
  packages/core/frontend/sirius-components-core/src/modals/confirmation/ConfirmationDialogContext.tsx
  packages/core/frontend/sirius-components-core/src/modals/confirmation/ConfirmationDialogContext.types.ts
Labels: pr: to review soon, priority: high

#3242 [3035] Hide diagram palette if an element is clicked
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/diagrams/diagram-contextual-palette.cy.js
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/group-tool/useGroupPalette.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/group-tool/useGroupPalette.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/useDiagramPalette.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/useDiagramPalette.types.ts
Labels: pr: to review soon, priority: low

#3248 [3246] Make the ViewRepresentationDescriptionSearchService independent from specific representations
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-sample-application/src/test/java/org/eclipse/sirius/web/sample/tests/ViewDetailsRenderingIntegrationTests.java
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/representations/ViewRepresentationDescriptionSearchService.java
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/representations/ViewRepresentationDescriptionSearchServiceParameters.java
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/representations/ViewRepresentationIdParameters.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/IViewRepresentationDescriptionSearchService.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/ViewAQLInterpreterFactory.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/ViewPropertiesDescriptionRegistryConfigurer.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/api/IViewAQLInterpreterFactory.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/compatibility/PropertiesWidgetCreationService.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/configuration/ViewPaletteToolsConfiguration.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/configuration/ViewPropertiesDescriptionServiceConfiguration.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewDiagramDescriptionSearchService.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewPaletteProvider.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewReconnectionToolsExecutor.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/api/IViewDiagramDescriptionSearchService.java
  packages/view/backend/sirius-components-view-emf/src/test/java/org/eclipse/sirius/components/view/emf/diagram/ViewPaletteProviderTests.java
Labels: pr: to review soon, priority: high

#3247 [3044] Fix an issue that caused the selection between the diagram and…
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/diagrams/diagram-selection.cy.ts
  integration-tests/cypress/workbench/Explorer.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/selection/useDiagramSelection.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/selection/useDiagramSelection.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/selection/useDiagramSelection.types.ts
Labels: pr: to review soon, priority: low

#3249 [2956] Change style declaration in IconOverlay
  CHANGELOG.adoc
  packages/core/frontend/sirius-components-core/src/icon/IconOverlay.tsx
  packages/core/frontend/sirius-components-core/src/icon/IconOverlay.types.ts
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/ListPropertySection.test.tsx.snap
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/TreePropertySection.test.tsx.snap
Labels: pr: to review soon, priority: high

#3233 [3220] Add documentation for Deck
  CHANGELOG.adoc
  doc/specifier/images/deck-card.png
  doc/specifier/images/deck-description-overview.png
  doc/specifier/images/deck-lane.png
  doc/specifier/images/deck-overview.png
  doc/specifier/representation-deck.adoc
  doc/user/images/deck-overview.png
  doc/user/images/deck-show-hide.png
  doc/user/images/deck-toolbar.png
  doc/user/representation-deck.adoc
  integration-tests/cypress/workbench/Deck.ts
  integration-tests/cypress/workbench/Gantt.ts
  packages/deck/backend/sirius-components-deck/src/main/java/org/eclipse/sirius/components/deck/renderer/component/CardComponent.java
  packages/deck/backend/sirius-components-deck/src/main/java/org/eclipse/sirius/components/deck/renderer/component/LaneComponent.java
  packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/configuration/TaskExampleBuilder.java
  packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/configuration/TaskStereotypeDescriptionRegistryConfigurer.java
  packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/configuration/view/ViewDeckDescriptionBuilder.java
  packages/starters/backend/sirius-components-task-starter/src/test/java/org/eclipse/sirius/components/task/starter/configuration/view/ViewDeckDescriptionBuilderTests.java
  packages/starters/backend/sirius-components-task-starter/src/test/java/org/eclipse/sirius/components/task/starter/configuration/view/ViewGanttDescriptionBuilderTests.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/CardDropToolBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/CreateCardToolBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/DeckDescriptionBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/DeckElementDescriptionBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/DeckToolBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/DeleteCardToolBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/EditCardToolBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/EditLaneToolBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/LaneDropToolBuilder.java
  packages/view/backend/sirius-components-view-deck-edit/src/main/java/org/eclipse/sirius/components/view/deck/provider/CardDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-deck-edit/src/main/java/org/eclipse/sirius/components/view/deck/provider/DeckDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-deck-edit/src/main/java/org/eclipse/sirius/components/view/deck/provider/DeckElementDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-deck-edit/src/main/java/org/eclipse/sirius/components/view/deck/provider/DeckToolItemProvider.java
  packages/view/backend/sirius-components-view-deck-edit/src/main/java/org/eclipse/sirius/components/view/deck/provider/LaneDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-deck-edit/src/main/resources/plugin.properties
  packages/view/backend/sirius-components-view-deck/src/main/java/org/eclipse/sirius/components/view/deck/CardDescription.java
  packages/view/backend/sirius-components-view-deck/src/main/java/org/eclipse/sirius/components/view/deck/DeckDescription.java
  packages/view/backend/sirius-components-view-deck/src/main/java/org/eclipse/sirius/components/view/deck/DeckElementDescription.java
  packages/view/backend/sirius-components-view-deck/src/main/java/org/eclipse/sirius/components/view/deck/DeckPackage.java
  packages/view/backend/sirius-components-view-deck/src/main/java/org/eclipse/sirius/components/view/deck/DeckTool.java
  packages/view/backend/sirius-components-view-deck/src/main/java/org/eclipse/sirius/components/view/deck/LaneDescription.java
  packages/view/backend/sirius-components-view-deck/src/main/java/org/eclipse/sirius/components/view/deck/impl/CardDescriptionImpl.java
  packages/view/backend/sirius-components-view-deck/src/main/java/org/eclipse/sirius/components/view/deck/impl/DeckDescriptionImpl.java
  packages/view/backend/sirius-components-view-deck/src/main/java/org/eclipse/sirius/components/view/deck/impl/DeckElementDescriptionImpl.java
  packages/view/backend/sirius-components-view-deck/src/main/java/org/eclipse/sirius/components/view/deck/impl/DeckPackageImpl.java
  packages/view/backend/sirius-components-view-deck/src/main/java/org/eclipse/sirius/components/view/deck/impl/DeckToolImpl.java
  packages/view/backend/sirius-components-view-deck/src/main/java/org/eclipse/sirius/components/view/deck/impl/LaneDescriptionImpl.java
  packages/view/backend/sirius-components-view-deck/src/main/resources/model/deck.ecore
  packages/view/backend/sirius-components-view-deck/src/main/resources/model/deck.genmodel
Labels: pr: to review soon, priority: high

#3254 [3178] Add documentation for portals
  CHANGELOG.adoc
  doc/user/images/edit-portal-mode-button.png
  doc/user/images/edit-representation-mode-button.png
  doc/user/images/empty-portal.png
  doc/user/images/portal-add.png
  doc/user/images/portal-move.png
  doc/user/images/portal-remove.png
  doc/user/images/portal-resize.png
  doc/user/images/portal-sample.png
  doc/user/images/portal-setup.png
  doc/user/images/portal-toolbar.png
  doc/user/representation-portal.adoc
Labels: pr: to review soon, priority: high

#3255 [3253] Add a new tool to the group palette to apply same size on mult…
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/diagrams/group-palette.cy.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/useDistributeElements.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/useDistributeElements.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/group-tool/GroupPalette.tsx
Labels: pr: to review later, priority: low

#3232 [3228] Prevent list child to be moved outside its container
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/group-tool/useGroupPalette.tsx
Labels: pr: to review soon, priority: low

#3212 [3206] Add precondition check for edge tool and diagram tool section
  CHANGELOG.adoc
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewPaletteProvider.java
  packages/view/backend/sirius-components-view-emf/src/test/java/org/eclipse/sirius/components/view/emf/diagram/ViewPaletteProviderTests.java
Labels: pr: to review soon, priority: low

#3258 [3257] Improve useDiagramSelection to only call setSelection when sel…
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/selection/useDiagramSelection.ts
Labels: pr: to review soon, priority: high

#3263 [3145] Render HelperLines component only if helper lines is enabled
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx
Labels: pr: to review soon, priority: high

#3174 [test] Add test to avoid missing files
  .github/workflows/build.yml
  scripts/check-gitdiff.js
Labels: pr: to review soon, priority: low

#2897 [2890] Display the contents of a Portal in the Representations view
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/diagrams/diagram-readonly.cy.ts
  integration-tests/cypress/e2e/project/portals/portals.cy.ts
  integration-tests/cypress/workbench/Deck.ts
  integration-tests/cypress/workbench/Deck.types.ts
  integration-tests/cypress/workbench/Representations.ts
  packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/RepresentationsEventProcessorFactory.java
  packages/forms/frontend/sirius-components-forms/src/views/RepresentationsView.tsx
  packages/portals/backend/sirius-components-collaborative-portals/src/main/java/org/eclipse/sirius/components/collaborative/portals/PortalChangeKind.java
  packages/portals/backend/sirius-components-collaborative-portals/src/main/java/org/eclipse/sirius/components/collaborative/portals/PortalEventProcessor.java
  packages/portals/backend/sirius-components-collaborative-portals/src/main/java/org/eclipse/sirius/components/collaborative/portals/api/IPortalEventHandler.java
  packages/portals/backend/sirius-components-collaborative-portals/src/main/java/org/eclipse/sirius/components/collaborative/portals/handlers/AddPortalViewEventHandler.java
  packages/portals/backend/sirius-components-collaborative-portals/src/main/java/org/eclipse/sirius/components/collaborative/portals/handlers/LayoutPortalEventHandler.java
  packages/portals/backend/sirius-components-collaborative-portals/src/main/java/org/eclipse/sirius/components/collaborative/portals/handlers/RemovePortalViewEventHandler.java
  packages/portals/backend/sirius-components-collaborative-portals/src/main/java/org/eclipse/sirius/components/collaborative/portals/handlers/RenamePortalEventHandler.java
  packages/portals/backend/sirius-components-collaborative-portals/src/test/java/org/eclipse/sirius/components/collaborative/portals/services/PortalServicesTests.java
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/representations/RepresentationsDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/representations/RepresentationsRepresentationRefreshPolicyProvider.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/ConditionalReferenceWidgetDescriptionStyleBuilder.java
  scripts/check-coverage.jsh
Labels: pr: to review soon, priority: high

#3209 [doc] Contribute a shape for default collapse and collapse operation
  CHANGELOG.adoc
  doc/adrs/139_add_is_collapsed_by_default_in_view_dsl.adoc
  doc/adrs/140_add_collapse_and_expand_services.adoc
  doc/iterations/2024.5/configurable_collapse.adoc
Labels: pr: to review soon, priority: high

#3260 [doc] Add shapes for model migration
  CHANGELOG.adoc
  doc/iterations/2024.5/shapes/add_support_for_emf_models_migration.adoc
  doc/iterations/2024.5/shapes/add_support_for_representations_migration.adoc
  doc/iterations/2024.5/shapes/configurable_collapse.adoc
Labels: pr: to review soon, priority: high

#3256 [doc] Add ADR to factorize GraphQL queries in tests
  CHANGELOG.adoc
  doc/adrs/141_factorize-graphql_queries_in_tests.adoc
Labels: pr: to review soon, priority: high

#3264 [doc] Add shape on diagram assertions and navigators
  CHANGELOG.adoc
  doc/iterations/2024.5/shapes/add_assertions_and_navigator_to_improve_diagram_testability.adoc
Labels: pr: to review soon, priority: high

#3241 [3236] Add support to specify the default collapsing state of a node
  CHANGELOG.adoc
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/NodeComponent.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/description/NodeDescription.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/ExpandCollapseDiagramControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/diagrams/ExpandCollapseDiagramDescriptionProvider.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/diagrams/UnsynchronizedDiagramDescriptionProvider.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/NodeDescriptionBuilder.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/NodeDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/resources/plugin.properties
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/DiagramPackage.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/ListLayoutStrategyDescription.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/NodeDescription.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/DiagramPackageImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/ListLayoutStrategyDescriptionImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/NodeDescriptionImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/resources/model/diagram.ecore
  packages/view/backend/sirius-components-view-diagram/src/main/resources/model/diagram.genmodel
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewDiagramDescriptionConverter.java
Labels: pr: to review later, priority: high

#3288 [3287] Send the right label in the form refresh event payload
  CHANGELOG.adoc
  packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/FormEventProcessor.java
  packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/FormEventProcessorFactory.java
  packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/api/FormCreationParameters.java
  packages/forms/backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/description/FormDescription.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/TestIdentifiers.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/FormControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/resources/scripts/initialize.sql
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/form/ViewFormDescriptionConverter.java
Labels: pr: to review soon, priority: high

#3291 [doc] Add shape about improving upload document
  CHANGELOG.adoc
  doc/iterations/2024.5/shapes/improve_document_upload.adoc
Labels: type: documentation, package: sirius web

#3275 [doc] Update Sirius website URL
  CONTRIBUTING
  README.adoc
  doc/adrs/003_add_support_for_unsynchronised_diagrams.adoc
  doc/adrs/005_add_support_for_view_creation_request.adoc
  doc/adrs/034_add_support_for_drag_and_drop.adoc
  doc/adrs/078_add_support_for_toolbar_actions_in_form_and_formdescriptioneditor.adoc
  doc/reference/02_backend.adoc
  packages/sirius-web/frontend/sirius-web-application/src/footer/Footer.tsx
  vscode-extension/README.md
  vscode-extension/package.json
Labels: pr: to review later, priority: low

#3280 [3018] Fix Details view for AbstractTask
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/gantt/gantt.cy.ts
  packages/sirius-web/backend/sirius-web-sample-application/src/test/java/org/eclipse/sirius/web/sample/TestIdentifiers.java
  packages/sirius-web/backend/sirius-web-sample-application/src/test/java/org/eclipse/sirius/web/sample/tests/integration/task/AbstractTaskControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web-sample-application/src/test/java/org/eclipse/sirius/web/sample/tests/integration/task/DeckControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web-sample-application/src/test/java/org/eclipse/sirius/web/sample/tests/integration/task/GanttControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web-sample-application/src/test/resources/scripts/cleanup.sql
  packages/sirius-web/backend/sirius-web-sample-application/src/test/resources/scripts/initialize.sql
  packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/configuration/AbstractTaskPropertiesConfigurer.java
  packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/configuration/view/TaskJavaService.java
  packages/starters/backend/sirius-components-task-starter/src/test/java/org/eclipse/sirius/components/task/starter/configuration/view/TaskJavaServiceTests.java
  scripts/check-coverage.jsh
Labels: pr: to review soon, priority: high

#3262 [doc] Initialize documentation on diagram representation
  doc/user/images/adjust-size-icon.png
  doc/user/images/diagram-representation.png
  doc/user/images/group-palette-distribute-elements-tools.png
  doc/user/images/helper-lines-example.png
  doc/user/images/helper-lines-icon.png
  doc/user/representation-diagram.adoc
Labels: pr: to review later, priority: low
