Repository eclipse-sirius/sirius-web, pull requests merged in 2024-09, with the labels that each got.

#3948 [3911] Fix label overflow handling with proper wrapping and ellipsis
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/convertLabel.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/Label.tsx
Labels: pr: to review soon, priority: high

#3944 [3933] Fix explorer in vscode extension
  CHANGELOG.adoc
  vscode-extension/src/data/ProjectData.ts
  vscode-extension/src/data/ProjectData.types.ts
  vscode-extension/src/data/getTreeEventSubscription.ts
Labels: pr: to review soon, priority: high

#3955 [3934] Remove helper lines when moving pinned elements
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/handles/useHandleChange.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/helper-lines/useHelperLines.tsx
Labels: pr: to review soon, priority: low

#3952 [3951] Provide an error page to redirect users in case of error
  CHANGELOG.adoc
  packages/gantt/backend/sirius-components-gantt-tests/src/main/java/org/eclipse/sirius/components/gantt/tests/graphql/EditTaskMutationRunner.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/gantt/PapayaGanttControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/gantt/PapayaGanttDescriptionProvider.java
  packages/sirius-web/frontend/sirius-web-application/src/footer/SiriusWebFooter.tsx
  packages/sirius-web/frontend/sirius-web-application/src/index.ts
  packages/sirius-web/frontend/sirius-web-application/src/navigationBar/NavigationBar.tsx
  packages/sirius-web/frontend/sirius-web-application/src/router/Router.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/error/ErrorView.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/error/ErrorView.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/views/error/ErrorViewExtensionPoints.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/new-project/NewProjectView.tsx
Labels: pr: to review soon, priority: high

#3959 [doc] Fix recent ADR duplicate with wrong number
  doc/adrs/155_make_it_possible_to_display_the_semantic_elements_as_a_tree_in_the_selection_dialog.adoc
  doc/adrs/156_make_it_possible_to_display_the_semantic_elements_as_a_tree_in_the_selection_dialog.adoc
  doc/adrs/images/156/currentSelectionDialog.png
  doc/adrs/images/156/referenceWidgetSemanticBrowser.png
Labels: pr: to review soon, priority: low

#3847 [3846] Migrate to React 18
  CHANGELOG.adoc
  package-lock.json
  packages/charts/frontend/sirius-components-charts/package.json
  packages/core/frontend/sirius-components-core/package.json
  packages/core/frontend/sirius-components-core/src/workbench/Workbench.tsx
  packages/deck/frontend/sirius-components-deck/package.json
  packages/diagrams/backend/sirius-components-diagrams-layout-server/package.json
  packages/diagrams/frontend/sirius-components-diagrams/package.json
  packages/diagrams/frontend/sirius-components-diagrams/src/contexts/NodeContext.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/delete/useDiagramDelete.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/direct-edit/useDiagramDirectEdit.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/layout.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/useLayout.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/useLayout.types.ts
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/package.json
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FormDescriptionEditorRepresentation.tsx
  packages/forms/frontend/sirius-components-forms/package.json
  packages/forms/frontend/sirius-components-forms/src/propertysections/TextfieldPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/MultiSelectPropertySection.test.tsx.snap
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/SelectPropertySection.test.tsx.snap
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/TextfieldPropertySection.test.tsx.snap
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/TreePropertySection.test.tsx.snap
  packages/forms/frontend/sirius-components-widget-reference/package.json
  packages/forms/frontend/sirius-components-widget-reference/src/modals/CreateModal.tsx
  packages/gantt/frontend/sirius-components-gantt/package.json
  packages/portals/frontend/sirius-components-portals/package.json
  packages/selection/frontend/sirius-components-selection/package.json
  packages/selection/frontend/sirius-components-selection/src/SelectionDialog.tsx
  packages/sirius-web/frontend/sirius-web-application/package.json
  packages/sirius-web/frontend/sirius-web-application/src/modals/new-object/NewObjectModal.tsx
  packages/sirius-web/frontend/sirius-web-application/src/modals/new-representation/NewRepresentationModal.tsx
  packages/sirius-web/frontend/sirius-web-application/src/modals/new-root-object/NewRootObjectModal.tsx
  packages/sirius-web/frontend/sirius-web-application/src/router/Router.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/EditProjectNavbar/EditProjectNavbar.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/EditProjectView.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/EditProjectView.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/views/error/ErrorView.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/views/new-project/NewProjectView.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/project-browser/create-projects-area/CreateProjectArea.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/project-browser/create-projects-area/ProjectTemplatesModal.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/project-settings/ProjectSettingsView.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/project-settings/ProjectSettingsView.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/views/project-settings/images/ProjectImagesSettings.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/views/project-settings/images/delete-image/DeleteImageModal.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/project-settings/images/rename-image/RenameImageModal.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/project-settings/images/upload-image/UploadImageModal.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/upload-project/UploadProjectView.tsx
  packages/sirius-web/frontend/sirius-web-papaya/package.json
  packages/sirius-web/frontend/sirius-web/package.json
  packages/sirius-web/frontend/sirius-web/src/index.tsx
  packages/sirius-web/frontend/sirius-web/src/nodes/EllipseNode.tsx
  packages/tools/frontend/sirius-components-specification-layout/package.json
  packages/trees/frontend/sirius-components-trees/package.json
  packages/trees/frontend/sirius-components-trees/src/views/TreeView.tsx
  packages/validation/frontend/sirius-components-validation/package.json
  packages/validation/frontend/sirius-components-validation/src/ValidationView.tsx
  vscode-extension/package.json
  vscode-extension/webpack.config.js
Labels: pr: to review soon, priority: high

#3995 [doc] Add ADR to improve representation event handling
  CHANGELOG.adoc
  doc/adrs/158_support_delegating_representation_event_handling.adoc
Labels: pr: to review soon, priority: high

#3978 [doc] Add ADR for creating event processors with only representationId
  CHANGELOG.adoc
  doc/adrs/159_create_event_processors_from_representation_id.adoc
Labels: pr: to review later, priority: low

#3956 [3954] Display separator bar immediately after adding dynamic list child
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/ListNodeConverter.ts
Labels: pr: to review soon, priority: low

#3999 [doc] Add shape for automatic selection of newly created diagram elements
  CHANGELOG.adoc
  doc/iterations/2024.11/select_new_nodes.adoc
Labels: pr: to review soon, priority: low

#3966 [2604] Expand the tool section when the mouse is over
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/tool-section/ToolSection.tsx
Labels: pr: to review soon, priority: high

#3888 [3887] Memoize diagram representation
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/representation/DiagramRepresentation.tsx
Labels: pr: to review soon, priority: high

#3988 [3987] Transform widgetFields fragment to retrieve custom widget fields
  CHANGELOG.adoc
  packages/sirius-web/frontend/sirius-web-application/src/extension/ReferenceWidgetDocumentTransform.ts
Labels: pr: to review later, priority: low

#4003 [cleanup] Only log unknown representation ids at debug level
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/EditingContextEventProcessor.java
Labels: pr: to review later, priority: low

#3908 [3907] Fix bad state update in handleNodesChange
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx
Labels: pr: to review soon, priority: high

#4002 [4001] Fix icon overlapping label text
  CHANGELOG.adoc
  packages/core/frontend/sirius-components-core/src/icon/IconOverlay.tsx
Labels: pr: to review soon, priority: low

#3986 [3965] Evaluate label height to define node size on the first layout
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/IconLabelNodeConverter.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/ImageNodeConverter.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/ListNodeConverter.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/RectangleNodeConverter.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/index.ts
  packages/sirius-web/frontend/sirius-web/src/nodes/EllipseNodeConverter.ts
Labels: pr: to review later, priority: low

#3994 [doc] Add shape on undo redo
  CHANGELOG.adoc
  doc/iterations/2024.11/add_undo_redo_support.adoc
Labels: pr: to review soon, priority: high

#4017 [4014] Improve the performance of the reference widget
  CHANGELOG.adoc
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors-widget-reference/src/main/java/org/eclipse/sirius/components/formdescriptioneditors/widget/reference/ReferenceWidgetPreviewConverterProvider.java
  packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/browser/ModelBrowsersDescriptionProvider.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/trees/ModelBrowserControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/data/StudioIdentifiers.java
Labels: pr: to review soon, priority: high

#3973 [3972] Add option to force display of separator bar header
  CHANGELOG.adoc
  packages/compatibility/backend/sirius-components-compatibility-emf/src/test/java/org/eclipse/sirius/components/compatibility/emf/compatibility/diagrams/EdgeMappingConverterTests.java
  packages/compatibility/backend/sirius-components-compatibility-emf/src/test/java/org/eclipse/sirius/components/compatibility/emf/compatibility/diagrams/TestDiagramBuilder.java
  packages/compatibility/backend/sirius-components-compatibility-emf/src/test/java/org/eclipse/sirius/components/compatibility/emf/compatibility/operations/CreateViewOperationHandlerTests.java
  packages/compatibility/backend/sirius-components-compatibility-emf/src/test/java/org/eclipse/sirius/components/compatibility/emf/compatibility/operations/DeleteViewOperationHandlerTests.java
  packages/compatibility/backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/diagrams/AbstractNodeMappingConverter.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/resources/schema/diagram.graphqls
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/test/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/GetConnectorToolsEventHandlerTests.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/test/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/InvokeSingleClickOnDiagramElementToolEventHandlerTests.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/test/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/TestDiagramBuilder.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/test/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/TestDiagramDescriptionBuilder.java
  packages/diagrams/backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/assertions/InsideLabelAssert.java
  packages/diagrams/backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/builder/label/LabelBuilder.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/HeaderSeparatorDisplayMode.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/InsideLabel.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/InsideLabelComponent.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/description/InsideLabelDescription.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/elements/InsideLabelElementProps.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/renderer/DiagramElementFactory.java
  packages/diagrams/backend/sirius-components-diagrams/src/test/java/org/eclipse/sirius/components/diagrams/renderer/DiagramElementChangeVisibilityTests.java
  packages/diagrams/backend/sirius-components-diagrams/src/test/java/org/eclipse/sirius/components/diagrams/renderer/DiagramRendererEdgeTests.java
  packages/diagrams/backend/sirius-components-diagrams/src/test/java/org/eclipse/sirius/components/diagrams/renderer/DiagramRendererNodeTests.java
  packages/diagrams/backend/sirius-components-diagrams/src/test/java/org/eclipse/sirius/components/diagrams/renderer/UnsynchronizedDiagramTests.java
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/convertLabel.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/graphql/subscription/labelFragment.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/graphql/subscription/labelFragment.types.ts
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/migration/participants/InsideLabelStyleHeaderSeparatorDisplayMigrationParticipant.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/representations/EntityNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/classdiagram/nodedescriptions/ClassNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/classdiagram/nodedescriptions/EnumNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/classdiagram/nodedescriptions/InterfaceNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/classdiagram/nodedescriptions/RecordNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/data/MigrationIdentifiers.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/migration/InsideLabelStyleHeaderSeparatorDisplayMigrationParticipantTests.java
  packages/sirius-web/backend/sirius-web/src/test/resources/scripts/migration.sql
  packages/starters/backend/sirius-components-flow-starter/src/main/java/org/eclipse/sirius/components/flow/starter/view/FlowViewBuilder.java
  packages/starters/backend/sirius-components-flow-starter/src/main/java/org/eclipse/sirius/components/flow/starter/view/descriptions/SystemDescriptionProvider.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/diagram/InsideLabelStyleBuilder.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/DiagramEditPlugin.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/InsideLabelStyleItemProvider.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/resources/plugin.properties
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/DiagramPackage.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/HeaderSeparatorDisplayMode.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/InsideLabelStyle.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/DiagramFactoryImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/DiagramPackageImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/InsideLabelStyleImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/resources/model/diagram.ecore
  packages/view/backend/sirius-components-view-diagram/src/main/resources/model/diagram.genmodel
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/DiagramOperationInterpreterViewSwitch.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewDiagramDescriptionConverter.java
  packages/view/backend/sirius-components-view-emf/src/test/java/org/eclipse/sirius/components/view/emf/diagram/TestDiagramBuilder.java
  packages/view/backend/sirius-components-view-emf/src/test/java/org/eclipse/sirius/components/view/emf/diagram/ViewPaletteProviderTests.java
Labels: pr: to review soon, priority: low

#4009 [4008] Prevent detailsEvent to be triggered twice when selecting a mu…
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/selection/useDiagramSelection.ts
Labels: pr: to review soon, priority: high

#4018 [3972] Add missing breaking change entry
  CHANGELOG.adoc
Labels: pr: to review later, priority: low

#4007 [doc] Add shape on drag and drop for the explorer
  CHANGELOG.adoc
  doc/iterations/2024.11/drag_and_drop_in_explorer.adoc
Labels: pr: to review later, priority: low

#4020 [3979] Add Project related REST APIs in Sirius Web
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/dto/IRestRecord.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/controllers/ProjectRestController.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/data/versioning/dto/IRestCommitReference.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/data/versioning/dto/RestBranch.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/dto/RestProject.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/query/dto/RestQuery.java
  packages/sirius-web/backend/sirius-web/pom.xml
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/projects/ProjectRestControllerIntegrationTests.java
Labels: pr: to review soon, priority: high

#4022 [4021] Disable project menu edition actions when project is read-only
  CHANGELOG.adoc
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/EditProjectNavbar/EditProjectNavbar.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/EditProjectNavbar/EditProjectNavbar.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/EditProjectView.tsx
Labels: pr: to review soon, priority: low

#4023 [fix] Fix error reporting when project deletion fails
  packages/sirius-web/frontend/sirius-web-application/src/modals/delete-project/useDeleteProject.ts
  packages/sirius-web/frontend/sirius-web-application/src/modals/delete-project/useDeleteProject.types.ts
Labels: pr: to review later, priority: low

#4019 [fix] Fix a regression on the diagram selection
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/selection/useDiagramSelection.ts
Labels: pr: to review soon, priority: high

#3850 [3678] Rely on representation id to retrieve representation metadata
  CHANGELOG.adoc
  packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/api/IRepresentationMetadataSearchService.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/representation/controllers/RepresentationMetadataDataFetcher.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/representation/services/RepresentationMetadataSearchService.java
Labels: pr: to review soon, priority: high
