Repository eclipse-sirius/sirius-web, pull requests merged in 2024-01, with the labels that each got.

#2866 [2789] Increase the size of edgeupdater
  CHANGELOG.adoc
  packages/sirius-web/frontend/sirius-web/src/ReactFlow.css
  packages/sirius-web/frontend/sirius-web/src/index.tsx
Labels: pr: to review soon, priority: low

#2763 [enh] Switch sirius-components-widget-reference to TypeScript strict …
  integration-tests/cypress/e2e/project/diagrams/direct-edit-label.cy.ts
  integration-tests/cypress/workbench/Diagram.ts
  packages/forms/frontend/sirius-components-widget-reference/src/ReferencePreview.tsx
  packages/forms/frontend/sirius-components-widget-reference/src/ReferencePropertySection.tsx
  packages/forms/frontend/sirius-components-widget-reference/src/ReferenceWidgetFragment.types.ts
  packages/forms/frontend/sirius-components-widget-reference/src/components/FilterableSortableList.tsx
  packages/forms/frontend/sirius-components-widget-reference/src/components/ValuedReferenceAutocomplete.tsx
  packages/forms/frontend/sirius-components-widget-reference/src/components/ValuedReferenceAutocomplete.types.ts
  packages/forms/frontend/sirius-components-widget-reference/src/modals/BrowseModal.types.ts
  packages/forms/frontend/sirius-components-widget-reference/src/modals/CreateModal.tsx
  packages/forms/frontend/sirius-components-widget-reference/src/modals/CreateModal.types.ts
  packages/forms/frontend/sirius-components-widget-reference/src/modals/CreateModalMachine.ts
  packages/forms/frontend/sirius-components-widget-reference/tsconfig.json
Labels: pr: to review later, priority: low

#2855 [test] Make integration tests more robust
  integration-tests/cypress/e2e/project/diagrams/diagram-contextual-palette.cy.js
  integration-tests/cypress/e2e/project/diagrams/diagram.cy.js
  integration-tests/cypress/e2e/project/formdescriptioneditor/formdescriptioneditor.cy.js
  integration-tests/cypress/e2e/project/representations.cy.js
  packages/sirius-web/backend/sirius-web-sample-application/src/test/java/org/eclipse/sirius/web/sample/tests/integration/formdescritpioneditors/FormDescriptionEditorPageIntegrationTests.java
  packages/sirius-web/backend/sirius-web-sample-application/src/test/java/org/eclipse/sirius/web/sample/tests/integration/view/ViewDiagramIntegrationTests.java
  packages/sirius-web/backend/sirius-web-sample-application/src/test/java/org/eclipse/sirius/web/sample/tests/integration/view/ViewFormIntegrationTests.java
  packages/sirius-web/backend/sirius-web-sample-application/src/test/java/org/eclipse/sirius/web/sample/tests/integration/view/ViewInitialDirectEditElementLabelProviderIntegrationTests.java
Labels: pr: to review soon, priority: low

#2828 [2826] Fix invalid reference position used for nodes with a depth > 2
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/useLayout.ts
Labels: pr: to review later, priority: low

#2870 [2869] Add diagramContext variable to DiagramCreationService#doRender
  CHANGELOG.adoc
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/DiagramCreationService.java
Labels: pr: to review soon, priority: high

#2858 [2616] Add a temporary edge during connection
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/connector/ConnectorContextualMenu.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/connector/useConnector.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/connector/useConnector.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/handles/ConnectionCreationHandles.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/handles/ConnectionTargetHandle.tsx
Labels: pr: to review soon, priority: low

#2892 [fix] Fix gantt image name
  packages/gantt/backend/sirius-components-collaborative-gantt/src/main/java/org/eclipse/sirius/components/collaborative/gantt/service/GanttImageProvider.java
Labels: pr: to review soon, priority: low

#2824 [2797] Preserve diagram selection after changes in details view
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/diagrams/diagram-selection.cy.ts
  integration-tests/cypress/e2e/project/diagrams/diagram.reactflow.cy.js
  integration-tests/cypress/workbench/Details.ts
  integration-tests/cypress/workbench/Diagram.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramRenderer.tsx
Labels: pr: to review later, priority: low

#2843 [2842] Move to @ObeoNetwork/react-trello
  CHANGELOG.adoc
  package-lock.json
  packages/deck/frontend/sirius-components-deck/package.json
  packages/deck/frontend/sirius-components-deck/src/Deck.tsx
Labels: pr: to review soon, priority: low

#2902 [releng] Add missing frontend dependency to portals
  package-lock.json
  packages/sirius-web/frontend/sirius-web/package.json
Labels: pr: to review soon, priority: high

#2891 Stop applying more changes when resizing
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramRenderer.tsx
Labels: pr: to review soon, priority: high

#2914 [2912] Send all node descriptions to the frontend
  CHANGELOG.adoc
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/GetNodeDescriptionsEventHandler.java
Labels: pr: to review soon, priority: high

#2938 [2678] Put the PalettePortal higher in the dom tree
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/PalettePortal.tsx
Labels: pr: to review soon, priority: high

#2944 [fix] Register portals in RepresentationMetadataDataFetcher
  packages/sirius-web/backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/representation/RepresentationMetadataDataFetcher.java
Labels: pr: to review later, priority: low

#2946 [2943] Fix default colors for View sub-nodes and border nodes
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/studio/studio.cy.js
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/adapters/DiagramColorAdapter.java
Labels: pr: to review soon, priority: low

#2913 [2910] Make the initial drop area larger and more visible on empty portals
  CHANGELOG.adoc
  packages/portals/frontend/sirius-components-portals/src/representations/PortalRepresentation.tsx
Labels: pr: to review soon, priority: low

#2916 [test] Fix some flaky Cypress tests
  integration-tests/cypress/e2e/project/details/widget-reference.cy.js
  integration-tests/cypress/e2e/project/details/widget-reference.cy.ts
  integration-tests/cypress/e2e/project/diagrams/node-aspect-ratio.cy.js
  integration-tests/cypress/e2e/project/diagrams/pin_unpin.cy.ts
  integration-tests/cypress/e2e/project/forms/widget-reference.cy.ts
  integration-tests/cypress/usecases/Flow.ts
  integration-tests/cypress/usecases/Studio.ts
  integration-tests/cypress/workbench/Details.ts
  integration-tests/cypress/workbench/Form.ts
  packages/forms/frontend/sirius-components-forms/src/representations/FormRepresentation.tsx
Labels: pr: to review soon, priority: low

#2933 Improve NodeResizer style
  CHANGELOG.adoc
  doc/screenshots/biggerResizeHandles2.png
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/node/ImageNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/node/ListNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/node/RectangularNode.tsx
  packages/sirius-web/frontend/sirius-web/src/nodes/EllipseNode.tsx
Labels: pr: to review soon, priority: high

#2952 [2948] Use a better icon for the button to remove a view from a portal
  CHANGELOG.adoc
  packages/portals/frontend/sirius-components-portals/src/representations/RepresentationFrame.tsx
Labels: pr: to review later, priority: low

#2927 [2792] Add support to label for arrangeAll
  CHANGELOG.adoc
  packages/core/frontend/sirius-components-core/src/icon/IconOverlay.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramRenderer.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/Label.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/useArrangeAll.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/panel/DiagramPanel.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/panel/DiagramPanel.types.ts
Labels: pr: to review soon, priority: low

#2936 [2934] Fix the initial position of representations added into portals
  CHANGELOG.adoc
  packages/portals/backend/sirius-components-collaborative-portals/src/main/java/org/eclipse/sirius/components/collaborative/portals/dto/AddPortalViewInput.java
  packages/portals/backend/sirius-components-collaborative-portals/src/main/java/org/eclipse/sirius/components/collaborative/portals/handlers/AddPortalViewEventHandler.java
  packages/portals/backend/sirius-components-collaborative-portals/src/main/java/org/eclipse/sirius/components/collaborative/portals/services/PortalServices.java
  packages/portals/backend/sirius-components-collaborative-portals/src/main/resources/schema/portal.graphqls
  packages/portals/frontend/sirius-components-portals/src/hooks/usePortalMutations.ts
  packages/portals/frontend/sirius-components-portals/src/hooks/usePortalMutations.types.ts
  packages/portals/frontend/sirius-components-portals/src/representations/PortalRepresentation.tsx
Labels: pr: to review later, priority: low

#2915 [2907] Replace tools' default tooltip with mui Tooltip
  CHANGELOG.adoc
  packages/core/frontend/sirius-components-core/src/icon/IconOverlay.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/Palette.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/panel/DiagramPanel.tsx
  packages/sirius-web/frontend/sirius-web-application/src/theme/siriusWebTheme.ts
Labels: pr: to review later, priority: low

#2963 [releng] Force the use of snabdom 3.5.1
  package-lock.json
  packages/diagrams/frontend/sirius-components-diagrams/package.json
  vscode-extension/package.json
Labels: pr: to review soon, priority: high

#2921 [2920] [Deck] Add Cypress tests
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/deck/deck.cy.ts
  integration-tests/cypress/workbench/Deck.ts
  integration-tests/cypress/workbench/Details.ts
  integration-tests/cypress/workbench/Explorer.ts
  packages/deck/frontend/sirius-components-deck/src/Deck.tsx
  packages/deck/frontend/sirius-components-deck/src/Deck.types.ts
  packages/deck/frontend/sirius-components-deck/src/card/DeckCard.tsx
  packages/deck/frontend/sirius-components-deck/src/card/DeckCardInput.tsx
  packages/deck/frontend/sirius-components-deck/src/utils/deckGQLConverter.tsx
  packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/configuration/TaskExampleBuilder.java
  packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/configuration/view/TaskJavaService.java
  packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/configuration/view/ViewDeckDescriptionBuilder.java
  packages/view/backend/sirius-components-view-deck-edit/src/main/resources/plugin.properties
Labels: pr: to review soon, priority: low

#2962 [fix] add key to iconoverlay tooltip
  packages/core/frontend/sirius-components-core/src/icon/IconOverlay.tsx
Labels: pr: to review soon, priority: high

#2954 [2951] Set ConnectionLine color to palette.selected
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramRenderer.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/connector/useConnector.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/edge/ConnectionLine.tsx
Labels: pr: to review later, priority: low

#2924 [2909] Add support for read-only mode on portals
  CHANGELOG.adoc
  packages/portals/frontend/sirius-components-portals/src/representations/PortalRepresentation.tsx
  packages/portals/frontend/sirius-components-portals/src/representations/PortalRepresentation.types.ts
  packages/portals/frontend/sirius-components-portals/src/representations/PortalToolbar.tsx
  packages/portals/frontend/sirius-components-portals/src/representations/RepresentationFrame.tsx
  packages/portals/frontend/sirius-components-portals/src/representations/RepresentationFrame.types.ts
Labels: pr: to review later, priority: low

#2955 [2940] Stop rendering the diagram palette toolcount equal 0
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/Palette.tsx
Labels: pr: to review later, priority: low

#2990 [2986] Prevent a portal from containing itself
  CHANGELOG.adoc
  packages/portals/backend/sirius-components-collaborative-portals/src/main/java/org/eclipse/sirius/components/collaborative/portals/PortalEventProcessor.java
  packages/portals/backend/sirius-components-collaborative-portals/src/main/java/org/eclipse/sirius/components/collaborative/portals/PortalEventProcessorFactory.java
  packages/portals/backend/sirius-components-collaborative-portals/src/main/java/org/eclipse/sirius/components/collaborative/portals/api/PortalContext.java
  packages/portals/backend/sirius-components-collaborative-portals/src/main/java/org/eclipse/sirius/components/collaborative/portals/handlers/AddPortalViewEventHandler.java
  packages/portals/backend/sirius-components-collaborative-portals/src/main/java/org/eclipse/sirius/components/collaborative/portals/handlers/LayoutPortalEventHandler.java
  packages/portals/backend/sirius-components-collaborative-portals/src/main/java/org/eclipse/sirius/components/collaborative/portals/handlers/RemovePortalViewEventHandler.java
  packages/portals/backend/sirius-components-collaborative-portals/src/main/java/org/eclipse/sirius/components/collaborative/portals/services/CollaborativePortalMessageService.java
  packages/portals/backend/sirius-components-collaborative-portals/src/main/java/org/eclipse/sirius/components/collaborative/portals/services/ICollaborativePortalMessageService.java
  packages/portals/backend/sirius-components-collaborative-portals/src/main/java/org/eclipse/sirius/components/collaborative/portals/services/PortalServices.java
  packages/portals/backend/sirius-components-collaborative-portals/src/main/resources/messages/sirius-web-spring-collaborative-portals.properties
  packages/portals/backend/sirius-components-collaborative-portals/src/test/java/org/eclipse/sirius/components/collaborative/portals/services/PortalServicesTests.java
Labels: pr: to review soon, priority: high

#2987 [2983] Use the Strict mode for Deck
  CHANGELOG.adoc
  integration-tests/cypress/workbench/Explorer.ts
  packages/deck/frontend/sirius-components-deck/src/representation/DeckRepresentation.tsx
  packages/deck/frontend/sirius-components-deck/src/representation/DeckRepresentation.types.ts
  packages/deck/frontend/sirius-components-deck/tsconfig.json
Labels: pr: to review soon, priority: low

#2996 [releng] Fix repositories for sirirus-components-flow-starter
  packages/sirius-web/backend/sirius-web-sample-application/pom.xml
  packages/starters/backend/sirius-components-flow-starter/pom.xml
Labels: pr: to review soon, priority: high

#2992 [2984] Handle succesPayload messages in Deck
  CHANGELOG.adoc
  packages/core/frontend/sirius-components-core/src/index.ts
  packages/deck/frontend/sirius-components-deck/src/representation/DeckRepresentation.tsx
  packages/deck/frontend/sirius-components-deck/src/representation/deckMutation.ts
  packages/deck/frontend/sirius-components-deck/src/representation/deckMutation.types.ts
  packages/deck/frontend/sirius-components-deck/src/representation/deckSubscription.types.ts
  packages/gantt/frontend/sirius-components-gantt/graphql/subscription/GanttSubscription.types.ts
Labels: pr: to review soon, priority: low

#3009 [doc] Contribute the shape and ADRs on the improvements of the Sirius Web architecture
  CHANGELOG.adoc
  doc/adrs/125_add_the_ability_to_reuse_both_the_sirius_web_frontend_and_backend_easily.adoc
  doc/adrs/126_add_the_ability_to_extend_the_sirius_web_frontend.adoc
  doc/adrs/127_add_the_ability_to_extend_the_sirius_web_backend.adoc
  doc/iterations/2024.3/shapes/transform_sirius_web_into_an_extensible_platform.adoc
Labels: pr: to review soon, priority: high

#3002 [3001] Preserve list layouted order on arrangeAll
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/useArrangeAll.ts
Labels: pr: to review later, priority: low

#3011 [3010] Bind Reference Widget's body operations on set/add
  CHANGELOG.adoc
  packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/ReferenceWidgetDescriptionConverterSwitch.java
  packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/handlers/ClickReferenceValueEventHandler.java
  packages/forms/backend/sirius-components-collaborative-widget-reference/src/test/java/org/eclipse/sirius/components/collaborative/widget/reference/handlers/ClickReferenceValueEventHandlerTests.java
  packages/forms/backend/sirius-components-widget-reference-graphql/src/main/java/org/eclipse/sirius/components/widget/reference/graphql/datafetchers/form/ReferenceValueHasClickActionDataFetcher.java
  packages/forms/backend/sirius-components-widget-reference-graphql/src/main/java/org/eclipse/sirius/components/widget/reference/graphql/datafetchers/mutation/MutationClickReferenceValueDataFetcher.java
  packages/forms/backend/sirius-components-widget-reference/src/main/java/org/eclipse/sirius/components/widget/reference/ReferenceValue.java
  packages/forms/backend/sirius-components-widget-reference/src/main/java/org/eclipse/sirius/components/widget/reference/ReferenceWidgetComponent.java
  packages/forms/backend/sirius-components-widget-reference/src/main/java/org/eclipse/sirius/components/widget/reference/ReferenceWidgetDescription.java
  packages/forms/backend/sirius-components-widget-reference/src/main/java/org/eclipse/sirius/components/widget/reference/ReferenceWidgetPreviewConverterProvider.java
  packages/forms/backend/sirius-components-widget-reference/src/main/resources/schema/reference.graphqls
  packages/forms/frontend/sirius-components-widget-reference/src/ReferencePropertySection.tsx
  packages/forms/frontend/sirius-components-widget-reference/src/ReferenceWidgetFragment.types.ts
  packages/sirius-web/frontend/sirius-web/src/index.tsx
Labels: pr: to review soon, priority: high

#2738 [2666] Change widget reference preview to match its new look
  CHANGELOG.adoc
  packages/forms/frontend/sirius-components-widget-reference/src/ReferencePreview.tsx
Labels: pr: to review later, priority: low

#2994 [2982] Fix the drop position on container
  CHANGELOG.adoc
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/providers/GenericDiagramToolReferencePositionProvider.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/test/java/org/eclipse/sirius/components/collaborative/diagrams/providers/GenericDiagramToolReferencePositionProviderTests.java
Labels: pr: to review soon, priority: low

#3007 Handle TypeScript strict mode for Gantt
  CHANGELOG.adoc
  packages/gantt/frontend/sirius-components-gantt/src/graphql/mutation/GanttMutation.types.ts
  packages/gantt/frontend/sirius-components-gantt/src/graphql/mutation/ganttMutation.ts
  packages/gantt/frontend/sirius-components-gantt/src/graphql/subscription/GanttSubscription.types.ts
  packages/gantt/frontend/sirius-components-gantt/src/graphql/subscription/ganttSubscription.ts
  packages/gantt/frontend/sirius-components-gantt/src/helper/helper.tsx
  packages/gantt/frontend/sirius-components-gantt/src/representation/Gantt.tsx
  packages/gantt/frontend/sirius-components-gantt/src/representation/Gantt.types.ts
  packages/gantt/frontend/sirius-components-gantt/src/representation/GanttRepresentation.tsx
  packages/gantt/frontend/sirius-components-gantt/src/representation/GanttRepresentation.types.ts
  packages/gantt/frontend/sirius-components-gantt/src/toolbar/Toolbar.tsx
  packages/gantt/frontend/sirius-components-gantt/tsconfig.json
Labels: pr: to review soon, priority: low

#3008 [3004] Fix part of errors in console on Deck
  CHANGELOG.adoc
  package-lock.json
  packages/deck/frontend/sirius-components-deck/package.json
  packages/deck/frontend/sirius-components-deck/src/representation/deckSubscription.ts
  packages/deck/frontend/sirius-components-deck/src/representation/deckSubscription.types.ts
  packages/deck/frontend/sirius-components-deck/src/utils/deckGQLConverter.tsx
  packages/sirius-web/frontend/sirius-web/package.json
Labels: pr: to review soon, priority: low

#3006 [test] Add Cypress tests for portals
  integration-tests/cypress/e2e/project/portals/portals.cy.ts
  integration-tests/cypress/workbench/Explorer.ts
  integration-tests/cypress/workbench/Portal.ts
  packages/portals/frontend/sirius-components-portals/src/representations/PortalRepresentation.tsx
  packages/portals/frontend/sirius-components-portals/src/representations/PortalToolbar.tsx
  packages/portals/frontend/sirius-components-portals/src/representations/RepresentationFrame.tsx
Labels: pr: to review later, priority: low

#3017 [doc] Contribute a shape to facilitate the insertion of elements into…
  CHANGELOG.adoc
  doc/iterations/2024.3/shapes/facilitate_insertion_of_elements_into_list node.adoc
  doc/iterations/2024.3/shapes/images/list_node/list_node_with_bottom_free_space.png
  doc/iterations/2024.3/shapes/images/list_node/list_node_with_top_free_space.png
  doc/iterations/2024.3/shapes/images/list_node/list_node_without_free_space.png
Labels: pr: to review soon, priority: low

#2976 [2975] Add useCallback to ReactFlow pane events
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramRenderer.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/useDiagramElementPalette.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/useDiagramPalette.tsx
Labels: pr: to review later, priority: low

#2979 [2978] Add useCallback to ReactFlow edge & drag events
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/connector/useConnector.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/drop/useDrop.tsx
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/dropNode/useDropNode.ts
Labels: pr: to review later, priority: low

#2998 [2799] Fix node style in diagram pre-layout
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/layout/layout.tsx
Labels: pr: to review soon, priority: low

#3041 [fix] Fix TaskObjectServiceDelegate.canHandle(IEditingContext)
  packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/configuration/TaskObjectServiceDelegate.java
Labels: pr: to review later, priority: low

#2991 [2822] Disable direct edit on edge without edit tool
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/diagrams/direct-edit-label.cy.ts
  integration-tests/cypress/e2e/project/diagrams/pin_unpin.cy.ts
  packages/compatibility/backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/diagrams/EdgeMappingConverter.java
  packages/compatibility/backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/diagrams/ToolConverter.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/EditLabelEventHandler.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/resources/schema/diagram.graphqls
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/Edge.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/EdgeComponent.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/description/EdgeDescription.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/elements/EdgeElementProps.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/renderer/DiagramElementFactory.java
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/converter/convertDiagram.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/graphql/subscription/edgeFragment.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/graphql/subscription/edgeFragment.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramRenderer.types.ts
  packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/direct-edit/useDiagramDirectEdit.tsx
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ToolFinder.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewDiagramDescriptionConverter.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewPaletteProvider.java
Labels: pr: to review later, priority: low

#3034 [3000] Make portals with representations open in "direct" mode
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/portals/portals.cy.ts
  integration-tests/cypress/workbench/Explorer.ts
  packages/portals/frontend/sirius-components-portals/src/representations/PortalRepresentation.tsx
Labels: pr: to review soon, priority: low
