Repository eclipse-sirius/sirius-web, pull requests merged in 2024-07, with the labels that each got.

#3663 [3662] Add an extension point to contribute props to ReactFlow renderer
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/index.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRendererExtensionPoints.ts
  packages/sirius-web/frontend/sirius-web-papaya/src/PapayaExtensionRegistry.tsx
  packages/sirius-web/frontend/sirius-web-papaya/src/diagrams/PapayaDiagramInformationPanel.tsx
  packages/sirius-web/frontend/sirius-web-papaya/src/diagrams/PapayaDiagramLegendPanel.tsx
Labels: pr: to review soon, priority: high

#3698 [releng] Fix invalid dependency version for the sirius-web-frontend
  packages/sirius-web/backend/sirius-web/pom.xml
Labels: pr: to review soon, priority: high

#3699 [3697] Improve arrange-all performance by reducing overlap management…
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/useArrangeAll.ts
Labels: pr: to review soon, priority: high

#3705 [3589] Add missing migration participant for diagram representation
  CHANGELOG.adoc
  packages/compatibility/backend/sirius-components-compatibility/src/test/java/org/eclipse/sirius/components/compatibility/diagrams/DomainBasedSourceNodesProviderTests.java
  packages/compatibility/backend/sirius-components-compatibility/src/test/java/org/eclipse/sirius/components/compatibility/diagrams/RelationBasedSourceNodesProviderTests.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/UpdateNodeBoundsEventHandler.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/resources/schema/diagram.graphqls
  packages/diagrams/backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/builder/node/RectangleNodeBuilder.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/Node.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/NodeComponent.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/elements/NodeElementProps.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/renderer/DiagramElementFactory.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/migration/participants/representation/DiagramUserResizableAttributeMigrationParticipant.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/data/MigrationIdentifiers.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/migration/DiagramUserResizableAttributeMigrationParticipantTests.java
  packages/sirius-web/backend/sirius-web/src/test/resources/scripts/migration.sql
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/DiagramOperationInterpreterViewSwitch.java
Labels: pr: to review soon, priority: high

#3689 [3668] Fix an issue that prevents wrapped label from overflow its con…
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/IconLabelNodeConverter.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/ListNodeConverter.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/convertLabel.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/ListNodeLayoutHandler.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/layout.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/node/IconLabelNode.tsx
Labels: pr: to review soon, priority: low

#3683 [3669] Add migration participant to hide label borders by default
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/migration/participants/DiagramLabelStyleBorderSizeMigrationParticipant.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/data/MigrationIdentifiers.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/migration/DiagramLabelStyleBorderSizeMigrationParticipantTests.java
  packages/sirius-web/backend/sirius-web/src/test/resources/scripts/migration.sql
  packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/DefaultToolsFactory.java
Labels: pr: to review soon, priority: high

#3728 [3711] Add read-only mode for filter elements button
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/diagrams/diagram-readonly.cy.ts
  packages/sirius-web/frontend/sirius-web-application/src/diagrams/DiagramFilter.tsx
Labels: pr: to review soon, priority: high

#3733 [releng] Fix version in pom.xml for sirius-web-application module
  packages/sirius-web/backend/sirius-web-application/pom.xml
Labels: pr: to review soon, priority: high

#3685 [3684] Replace form & tree converters configurations with extensions
  CHANGELOG.adoc
  packages/forms/frontend/sirius-components-forms/src/index.ts
  packages/forms/frontend/sirius-components-forms/src/views/DetailsView.tsx
  packages/forms/frontend/sirius-components-forms/src/views/DetailsViewConfiguration.tsx
  packages/forms/frontend/sirius-components-forms/src/views/DetailsViewConfiguration.types.ts
  packages/forms/frontend/sirius-components-forms/src/views/DetailsViewContext.tsx
  packages/forms/frontend/sirius-components-forms/src/views/DetailsViewContext.types.ts
  packages/forms/frontend/sirius-components-forms/src/views/FormBasedView.tsx
  packages/forms/frontend/sirius-components-forms/src/views/FormBasedView.types.tsx
  packages/forms/frontend/sirius-components-forms/src/views/FormBasedViewExtensionPoints.tsx
  packages/trees/frontend/sirius-components-trees/src/index.ts
  packages/trees/frontend/sirius-components-trees/src/views/ExplorerView.tsx
  packages/trees/frontend/sirius-components-trees/src/views/ExplorerViewConfiguration.tsx
  packages/trees/frontend/sirius-components-trees/src/views/ExplorerViewConfiguration.types.ts
  packages/trees/frontend/sirius-components-trees/src/views/ExplorerViewContext.tsx
  packages/trees/frontend/sirius-components-trees/src/views/TreeConverter.types.ts
  packages/trees/frontend/sirius-components-trees/src/views/TreeView.tsx
  packages/trees/frontend/sirius-components-trees/src/views/TreeView.types.ts
  packages/trees/frontend/sirius-components-trees/src/views/TreeViewExtensionPoints.tsx
Labels: pr: to review soon, priority: high

#3519 [doc] Add some documentation on our testing strategy
  doc/testing.adoc
Labels: pr: to review soon, priority: low

#3736 [3700] Prevent edge selection from being lost after a diagram refresh
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/diagrams/diagram-selection.cy.ts
  integration-tests/cypress/workbench/Diagram.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx
Labels: pr: to review soon, priority: high

#3734 [3701] Add node and edge tools to domain diagram
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/representations/EntityNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/representations/InheritanceEdgeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/representations/RelationEdgeDescriptionProvider.java
Labels: pr: to review soon, priority: high

#3692 [3691] Prevent border nodes to be overlap after the first layout
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/layoutNode.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/useArrangeAll.ts
Labels: pr: to review soon, priority: high

#3761 [fix] Fix an issue with the download of documents from the explorer
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/controllers/DocumentDownloadController.java
Labels: pr: to review soon, priority: high

#3745 [3744] Add support for helper lines during multi selection move
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/diagrams/helper-lines.cy.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/helper-lines/useHelperLines.tsx
Labels: pr: to review later, priority: low

#3764 [doc] Add shape for adding tree description in view dsl
  CHANGELOG.adoc
  doc/iterations/2024.9/add_tree_representation_view_model.adoc
Labels: pr: to review soon, priority: high

#3772 [doc] Add the ADR for adding object provider in tree description
  CHANGELOG.adoc
  doc/adrs/137_use_a_common_identification_strategy_for_transient_representations.adoc
  doc/adrs/138_allow_consumers_to_reuse_smaller_parts_of_the_sirius_web_backend.adoc
  doc/adrs/141_factorize-graphql_queries_in_tests.adoc
  doc/adrs/142_add_report_on_document_upload.adoc
  doc/adrs/143_handle_documents_upload_with_other_formats_than_json_and_xmi.adoc
  doc/adrs/145_add_a_hook_to_update_nodes_in_reactflow.adoc
  doc/adrs/146_contribute_representation_metadata_for_transient_representations.adoc
  doc/adrs/147_overlapping_nodes.adoc
  doc/adrs/148_improves_edge_layout.adoc
  doc/adrs/151_improve_diagram_subscription_lifecycle.adoc
  doc/adrs/152_add_support_for_any_kind_of_object_as_semantic_element_in_the_tree_description.adoc
Labels: pr: to review soon, priority: high

#3622 [doc] Contribute an ADR to reactivate the selection dialog
  CHANGELOG.adoc
  doc/adrs/153_restore_the_selection_dialog_support_in_diagrams.adoc
Labels: pr: to review soon, priority: high

#3686 [3675] Remove label from selection
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/diagrams/custom-shape.cy.ts
  integration-tests/cypress/e2e/project/diagrams/diagram.reactflow.cy.js
  integration-tests/cypress/e2e/project/gantt/gantt-task.cy.ts
  integration-tests/cypress/e2e/project/gantt/gantt.cy.ts
  integration-tests/cypress/workbench/Details.ts
  packages/core/backend/sirius-components-collaborative/src/main/resources/schema/core.graphqls
  packages/core/frontend/sirius-components-core/src/index.ts
  packages/core/frontend/sirius-components-core/src/representationmetadata/useRepresentationMetadata.tsx
  packages/core/frontend/sirius-components-core/src/representationmetadata/useRepresentationMetadata.types.tsx
  packages/core/frontend/sirius-components-core/src/selection/SelectionContext.types.ts
  packages/core/frontend/sirius-components-core/src/workbench/Workbench.tsx
  packages/deck/frontend/sirius-components-deck/src/representation/DeckRepresentation.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/Group.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/PageList.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/ToolbarActionWidget.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/WidgetEntry.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/ListPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/TreePropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/TreePropertySection.test.tsx
  packages/forms/frontend/sirius-components-widget-reference/src/ReferencePropertySection.tsx
  packages/forms/frontend/sirius-components-widget-reference/src/components/FilterableSortableList.types.ts
  packages/forms/frontend/sirius-components-widget-reference/src/modals/TransferModal.tsx
  packages/forms/frontend/sirius-components-widget-reference/src/modals/TransferModal.types.ts
  packages/gantt/frontend/sirius-components-gantt/src/representation/Gantt.tsx
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/representation/controllers/EditingContextRepresentationsDataFetcher.java
  packages/sirius-web/backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/editingcontext/EditingContextRepresentationsDataFetcher.java
  packages/sirius-web/frontend/sirius-web-application/src/diagrams/DiagramFilter.tsx
  packages/sirius-web/frontend/sirius-web-application/src/modals/new-representation/NewRepresentationModal.tsx
  packages/sirius-web/frontend/sirius-web-application/src/onboarding/NewRepresentationArea.tsx
  packages/sirius-web/frontend/sirius-web-application/src/onboarding/RepresentationsArea.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/EditProjectView.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/useProjectAndRepresentationMetadata.ts
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItem.tsx
  vscode-extension/package.json
  vscode-extension/src/view/app/App.tsx
Labels: pr: to review later, priority: low

#3739 [doc] Add shape for object duplication from Explorer
  CHANGELOG.adoc
  doc/iterations/2024.9/add_support_for_object_duplication.adoc
  doc/iterations/2024.9/images/duplicate_object_dialog.png
Labels: pr: to review soon, priority: high

#3762 [doc] Add shape for diagram tool shortcuts
  CHANGELOG.adoc
  doc/iterations/2024.9/add_support_for_diagram_tool_shortcuts.adoc
Labels: pr: to review soon, priority: high

#3769 [3676] Remove label from frontend representation types
  CHANGELOG.adoc
  packages/charts/backend/sirius-components-collaborative-charts/src/main/java/org/eclipse/sirius/components/collaborative/charts/CreateHierarchyEventHandler.java
  packages/charts/frontend/sirius-components-charts/src/bar/BarChart.tsx
  packages/charts/frontend/sirius-components-charts/src/bar/BarChart.types.ts
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/dto/CreateRepresentationSuccessPayload.java
  packages/deck/backend/sirius-components-collaborative-deck/src/main/java/org/eclipse/sirius/components/collaborative/deck/handlers/CreateDeckEventHandler.java
  packages/deck/frontend/sirius-components-deck/src/representation/deckSubscription.ts
  packages/deck/frontend/sirius-components-deck/src/representation/deckSubscription.types.ts
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/CreateDiagramEventHandler.java
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/convertDiagram.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/graphql/subscription/diagramFragment.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.types.ts
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/CreateFormDescriptionEditorEventHandler.java
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/BarChartWidget.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/PieChartWidget.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/WidgetEntry.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/__tests__/WidgetEntry.test.tsx
  packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/handlers/CreateFormEventHandler.java
  packages/forms/frontend/sirius-components-forms/src/form/FormEventFragments.ts
  packages/forms/frontend/sirius-components-forms/src/form/FormEventFragments.types.ts
  packages/forms/frontend/sirius-components-forms/src/propertysections/ChartWidgetPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/HelpTooltip.types.ts
  packages/forms/frontend/sirius-components-forms/src/propertysections/TextfieldPropertySection.types.ts
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/ChartWidgetPropertySection.test.tsx
  packages/gantt/backend/sirius-components-collaborative-gantt/src/main/java/org/eclipse/sirius/components/collaborative/gantt/handlers/CreateGanttEventHandler.java
  packages/gantt/frontend/sirius-components-gantt/src/graphql/subscription/GanttSubscription.types.ts
  packages/portals/backend/sirius-components-collaborative-portals/src/main/java/org/eclipse/sirius/components/collaborative/portals/handlers/CreatePortalEventHandler.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/TestCreateRepresentationEventHandler.java
  packages/sirius-web/frontend/sirius-web-application/src/modals/new-representation/NewRepresentationModal.tsx
  packages/sirius-web/frontend/sirius-web-application/src/modals/new-representation/NewRepresentationModal.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/modals/new-representation/NewRepresentationModalMachine.ts
  packages/sirius-web/frontend/sirius-web-application/src/onboarding/RepresentationsArea.types.ts
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItemDirectEditInput.types.ts
Labels: pr: to review soon, priority: high

#3786 [1470] Add EKeys to containment references in view metamodels
  CHANGELOG.adoc
  packages/diagrams/backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/graphql/DropNodeMutationRunner.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/DropNodeControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/forms/FormControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/trees/ExplorerExpandAllControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/TaskViewInjector.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/diagrams/DropNodeDiagramDescriptionProvider.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/forms/FormVariableViewPreEditingContextProcessor.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/forms/MasterDetailsFormDescriptionProvider.java
  packages/view/backend/sirius-components-view-deck/src/main/java/org/eclipse/sirius/components/view/deck/LaneDescription.java
  packages/view/backend/sirius-components-view-deck/src/main/java/org/eclipse/sirius/components/view/deck/impl/DeckPackageImpl.java
  packages/view/backend/sirius-components-view-deck/src/main/resources/model/deck.ecore
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/ArrangeLayoutDirection.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/DiagramDescription.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/DiagramPackage.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/DiagramPalette.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/DiagramToolSection.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/EdgePalette.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/EdgeStyle.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/EdgeToolSection.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/InsideLabelPosition.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/LabelDescription.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/LabelOverflowStrategy.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/LabelTextAlign.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/NodeDescription.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/NodeLabelStyle.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/NodePalette.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/NodeToolSection.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/UserResizableDirection.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/ConditionalEdgeStyleImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/DiagramDescriptionImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/DiagramFactoryImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/DiagramPackageImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/EdgeStyleImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/InsideLabelStyleImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/LabelDescriptionImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/NodeDescriptionImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/OutsideLabelStyleImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/util/DiagramSwitch.java
  packages/view/backend/sirius-components-view-diagram/src/main/resources/model/diagram.ecore
  packages/view/backend/sirius-components-view-diagram/src/main/resources/model/diagram.genmodel
  packages/view/backend/sirius-components-view-form-edit/src/main/java/org/eclipse/sirius/components/view/form/provider/FormEditPlugin.java
  packages/view/backend/sirius-components-view-form/src/main/java/org/eclipse/sirius/components/view/form/FormDescription.java
  packages/view/backend/sirius-components-view-form/src/main/java/org/eclipse/sirius/components/view/form/PageDescription.java
  packages/view/backend/sirius-components-view-form/src/main/java/org/eclipse/sirius/components/view/form/SplitButtonDescription.java
  packages/view/backend/sirius-components-view-form/src/main/java/org/eclipse/sirius/components/view/form/impl/FormPackageImpl.java
  packages/view/backend/sirius-components-view-form/src/main/resources/model/form.ecore
  packages/view/backend/sirius-components-view-gantt/src/main/java/org/eclipse/sirius/components/view/gantt/GanttDescription.java
  packages/view/backend/sirius-components-view-gantt/src/main/java/org/eclipse/sirius/components/view/gantt/impl/GanttPackageImpl.java
  packages/view/backend/sirius-components-view-gantt/src/main/resources/model/gantt.ecore
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/ColorPalette.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/View.java
  packages/view/backend/sirius-components-view/src/main/java/org/eclipse/sirius/components/view/impl/ViewPackageImpl.java
  packages/view/backend/sirius-components-view/src/main/resources/model/view.ecore
  packages/view/backend/sirius-components-view/src/main/resources/model/view.genmodel
  scripts/check-coverage.jsh
Labels: pr: to review soon, priority: high

#3779 [3778] Export EdgeData in sirius-components-diagrams/src/index.ts
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/index.ts
Labels: pr: to review soon, priority: high

#3768 [3767] Improves the robustness of the arrange all
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/useArrangeAll.ts
Labels: pr: to review soon, priority: low

#3788 [3784] Fix the click on a representation that is already selected
  CHANGELOG.adoc
  packages/core/frontend/sirius-components-core/src/workbench/Workbench.tsx
Labels: pr: to review soon, priority: high

#3792 [doc] Add an ADR for adding parent provider in tree representation
  CHANGELOG.adoc
  doc/adrs/154_add_support_for_finding_parent_in_tree_representation.adoc
Labels: pr: to review soon, priority: high

#3797 [enh] Export NavigationBar
  packages/sirius-web/frontend/sirius-web-application/src/index.ts
Labels: pr: to review soon, priority: high

#3795 [3794] Change showIcon by showIconExpression in Diagram View DSL
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/migration/participants/NodeLabelStyleShowIconMigrationParticipant.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/representations/EntityNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/classdiagram/nodedescriptions/ClassNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/classdiagram/nodedescriptions/EnumNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/classdiagram/nodedescriptions/InterfaceNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/classdiagram/nodedescriptions/RecordNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/componentdiagram/nodedescriptions/ComponentNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/data/MigrationIdentifiers.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/migration/NodeLabelStyleShowIconMigrationParticipantTests.java
  packages/sirius-web/backend/sirius-web/src/test/resources/scripts/migration.sql
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/InsideLabelStyleBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/NodeLabelStyleBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/OutsideLabelStyleBuilder.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/InsideLabelStyleItemProvider.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/NodeLabelStyleItemProvider.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/OutsideLabelStyleItemProvider.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/resources/plugin.properties
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/DiagramPackage.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/NodeLabelStyle.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/DiagramPackageImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/InsideLabelStyleImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/OutsideLabelStyleImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/resources/model/diagram.ecore
  packages/view/backend/sirius-components-view-diagram/src/main/resources/model/diagram.genmodel
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/StylesFactory.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewDiagramDescriptionConverter.java
Labels: pr: to review soon, priority: high

#3775 [3774] Add an extension point to contribute custom tools
  CHANGELOG.adoc
  doc/how-to/extend-the-frontend.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/index.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/Tool.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/DiagramPalette.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/Palette.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/PalettePortal.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/PaletteTool.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/group-tool/GroupPalette.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/tool-section/ToolSection.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/tool/DiagramPaletteTool.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/tool/DiagramPaletteToolExtensionPoints.ts
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/EditProjectView.tsx
  packages/sirius-web/frontend/sirius-web-papaya/src/PapayaExtensionRegistry.tsx
  packages/sirius-web/frontend/sirius-web-papaya/src/tools/PapayaComponentLabelDetailToolContribution.tsx
Labels: pr: to review soon, priority: high

#3787 [3785] Add an extension point to contribute custom tree item menu entry
  CHANGELOG.adoc
  packages/forms/frontend/sirius-components-widget-reference/src/components/ModelBrowserTreeView.tsx
  packages/sirius-web/frontend/sirius-web-application/src/extension/DefaultExtensionRegistry.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/DiagramTreeItemContextMenuContribution.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/DocumentTreeItemContextMenuContribution.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/EditProjectView.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/ObjectTreeItemContextMenuContribution.tsx
  packages/trees/frontend/sirius-components-trees/src/index.ts
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItem.tsx
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItem.types.ts
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItemAction.tsx
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItemAction.types.ts
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItemContextMenu.tsx
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItemContextMenu.types.ts
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItemContextMenuEntry.types.ts
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItemContextMenuEntryExtensionPoints.ts
  packages/trees/frontend/sirius-components-trees/src/trees/Tree.tsx
  packages/trees/frontend/sirius-components-trees/src/trees/Tree.types.ts
  packages/trees/frontend/sirius-components-trees/src/views/TreeView.tsx
  packages/trees/frontend/sirius-components-trees/src/views/TreeView.types.ts
Labels: pr: to review soon, priority: high

#3804 [releng] Switch from adduser to useradd in Dockerfile
  packages/sirius-web/backend/sirius-web/Dockerfile
Labels: pr: to review soon, priority: high

#3783 [3782] Add an extension point to contribute custom widgets
  CHANGELOG.adoc
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FlexboxContainerWidget.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FormDescriptionEditorEventFragment.ts
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FormDescriptionEditorRepresentation.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/Group.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/WidgetEntry.tsx
  packages/forms/frontend/sirius-components-forms/src/form/Form.types.ts
  packages/forms/frontend/sirius-components-forms/src/form/FormContext.ts
  packages/forms/frontend/sirius-components-forms/src/form/FormEventFragments.ts
  packages/forms/frontend/sirius-components-forms/src/form/WidgetContribution.types.ts
  packages/forms/frontend/sirius-components-forms/src/form/WidgetContributionExtensionPoints.ts
  packages/forms/frontend/sirius-components-forms/src/index.ts
  packages/forms/frontend/sirius-components-forms/src/propertysections/PropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/representations/FormRepresentation.tsx
  packages/forms/frontend/sirius-components-widget-reference/src/ReferencePreview.tsx
  packages/sirius-web/frontend/sirius-web-application/src/application/SiriusWebApplication.tsx
  packages/sirius-web/frontend/sirius-web-application/src/diagrams/useDiagramFilterSubscription.tsx
  packages/sirius-web/frontend/sirius-web-application/src/extension/DefaultExtensionRegistry.tsx
  packages/sirius-web/frontend/sirius-web-application/src/extension/ElipseNodeDocumentTransform.ts
  packages/sirius-web/frontend/sirius-web-application/src/extension/ReferenceWidgetDocumentTransform.ts
  packages/sirius-web/frontend/sirius-web-application/src/forms/defaultPropertySectionRegistry.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/useDetailsViewSubscription.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/useRelatedElementsViewSubscription.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/useRepresentationsViewSubscription.tsx
  packages/sirius-web/frontend/sirius-web/src/index.tsx
Labels: pr: to review soon, priority: high

#3803 [3766] Fix potential NPE in RewriteProxiesEventHandler#rewriteProxyURIs
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/services/RewriteProxiesEventHandler.java
Labels: pr: to review soon, priority: high

#3749 [3748] Store current diagram payload in DiagramContext
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/contexts/DiagramContext.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/contexts/DiagramContext.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/representation/DiagramRepresentation.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/representation/DiagramRepresentation.types.ts
Labels: pr: to review soon, priority: high

#3813 [test] Fix flaky backend coverage
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/test/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/DeleteGroupEventHandlerTests.java
Labels: pr: to review soon, priority: high

#3759 [3758] Store property and form payload in a context
  CHANGELOG.adoc
  packages/forms/frontend/sirius-components-forms/src/contexts/FormContext.ts
  packages/forms/frontend/sirius-components-forms/src/contexts/FormContext.types.ts
  packages/forms/frontend/sirius-components-forms/src/index.ts
  packages/forms/frontend/sirius-components-forms/src/representations/FormRepresentation.tsx
  packages/forms/frontend/sirius-components-forms/src/representations/FormRepresentation.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/index.ts
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/DetailsView.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/useDetailsViewSubscription.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/useDetailsViewSubscription.types.ts
Labels: pr: to review soon, priority: low

#3812 [3811] Fix issue with Reference widget not working when placed in a f…
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/forms/widget-reference.cy.ts
  integration-tests/cypress/usecases/Studio.ts
  packages/sirius-web/frontend/sirius-web-application/src/extension/ReferenceWidgetDocumentTransform.ts
Labels: pr: to review soon, priority: low

#3819 [3776] Restore expand all functionality for ref widget trees
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/pom.xml
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/ExpandAllTreePathProvider.java
Labels: pr: to review later, priority: low
