Repository eclipse-sirius/sirius-web, pull requests merged in 2025-04, with the labels that each got.

#4703 [doc] Add user and specifier documentations for the table representation
  doc/specifier/images/table-overview.png
  doc/specifier/images/table-table-description.png
  doc/specifier/representation-table.adoc
  doc/user/images/table-column-menu.png
  doc/user/images/table-columns-management-menu.png
  doc/user/images/table-overview.png
  doc/user/images/table-pagination-toolbar.png
  doc/user/images/table-row-action-example.png
  doc/user/images/table-selection.png
  doc/user/images/table-settings-menu.png
  doc/user/images/table-top-toolbar.png
  doc/user/representation-table.adoc
Labels: pr: to review soon, priority: low

#4730 [4687] Make table line header resizable
  CHANGELOG.adoc
  packages/tables/frontend/sirius-components-tables/src/table/useTableColumns.tsx
Labels: pr: to review soon, priority: low

#4716 [4709] Make the selection change when the cell is clicked
  CHANGELOG.adoc
  packages/forms/frontend/sirius-components-widget-table/src/TableWidgetPropertySection.tsx
  packages/tables/frontend/sirius-components-tables/src/cells/Cell.tsx
  packages/tables/frontend/sirius-components-tables/src/cells/Cell.types.ts
  packages/tables/frontend/sirius-components-tables/src/cells/CheckboxCell.tsx
  packages/tables/frontend/sirius-components-tables/src/cells/IconLabelCell.tsx
  packages/tables/frontend/sirius-components-tables/src/cells/MultiSelectCell.tsx
  packages/tables/frontend/sirius-components-tables/src/cells/SelectCell.tsx
  packages/tables/frontend/sirius-components-tables/src/cells/TextareaCell.tsx
  packages/tables/frontend/sirius-components-tables/src/cells/TextfieldCell.tsx
  packages/tables/frontend/sirius-components-tables/src/representation/TableRepresentation.tsx
  packages/tables/frontend/sirius-components-tables/src/rows/RowHeader.tsx
  packages/tables/frontend/sirius-components-tables/src/table/TableContent.tsx
  packages/tables/frontend/sirius-components-tables/src/table/TableContent.types.ts
  packages/tables/frontend/sirius-components-tables/src/table/useTableColumns.tsx
Labels: pr: to review soon, priority: high

#4738 [4707] Enable frontend rendering of edges that have another edge as s…
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/ImageNodeConverter.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/ListNodeConverter.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/RectangleNodeConverter.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/convertDiagram.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/convertHandles.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/edgeAnchorNodeFactory.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/MultiLabelEditableEdge.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/helper-lines/useHelperLines.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/node/EdgeAnchorNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/node/EdgeAnchorNode.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/node/NodeTypes.ts
  packages/sirius-web/frontend/sirius-web/src/nodes/EllipseNodeConverter.ts
  vscode-extension/src/view/app/nodes/EllipseNodeConverter.ts
Labels: pr: to review later, priority: high

#4747 [4744] Allow execution of SingleClickOnTwoDiagramElements with edge a…
  CHANGELOG.adoc
  packages/compatibility/backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/services/diagrams/ToolProvider.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/DiagramDescriptionService.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/DiagramQueryService.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/api/IDiagramDescriptionService.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/api/IDiagramQueryService.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/dto/SingleClickOnTwoDiagramElementsCandidate.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/GetConnectorToolsEventHandler.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/InvokeSingleClickOnTwoDiagramElementsToolEventHandler.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/resources/schema/diagram.graphqls
  packages/diagrams/backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/navigation/DiagramNavigator.java
  packages/diagrams/backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/navigation/EdgeNavigator.java
  packages/diagrams/backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/navigation/NavigatorCache.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/tools/SingleClickOnTwoDiagramElementsCandidate.java
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/convertDiagram.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/connector/useConnector.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/connector/useConnector.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/connector/useConnectorEdgeStyle.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/connector/useConnectorEdgeStyle.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/MultiLabelEditableEdge.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/hover/useEdgeHover.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/hover/useEdgeHover.types.ts
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/lifecyclediagram/nodedescriptions/ChannelNodeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/lifecyclediagram/tools/ChannelNodePaletteProvider.java
  packages/sirius-web/backend/sirius-web-tests-data/src/main/resources/sirius-web-scripts/papaya.sql
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/EdgeOnEdgeControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/data/PapayaIdentifiers.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ToolConverter.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ToolFinder.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewPaletteProvider.java
Labels: pr: to review later, priority: high

#4767 [doc] Add an adr about diagram elements custom appearance management
  CHANGELOG.adoc
  doc/adrs/191_add_diagram_elements_appearance_management.adoc
Labels: pr: to review soon, priority: low

#4776 [fix] Fix an issue where an edge was not reconnectable after a refresh
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/convertDiagram.ts
Labels: pr: to review soon, priority: high

#4778 [fix] Fix an issue where the palette of an edge was missing some tools
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/quick-access-tool/PaletteQuickAccessToolBar.tsx
Labels: pr: to review soon, priority: high

#4799 [4791] Fix an issue where loading representation indicator could be b…
  CHANGELOG.adoc
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/related-elements/RelatedElementsView.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/representations/RepresentationsView.tsx
Labels: pr: to review soon, priority: high

#4803 [4802] Make sure all hooks are always rendered in EditProjectView
  CHANGELOG.adoc
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/EditProjectView.tsx
Labels: pr: to review soon, priority: high

#4800 [4786] Fix an issue that prevent to navigate between library pages
  CHANGELOG.adoc
  packages/sirius-web/frontend/sirius-web-application/src/omnibox/LibrariesImportTable.tsx
  packages/sirius-web/frontend/sirius-web-application/src/omnibox/LibrariesImportTable.types.ts
Labels: pr: to review soon, priority: high

#4806 [4793] Handle 'transparent' background color in SVG Export
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/panel/experimental-svg-export/RectElementSVGExportHandler.ts
Labels: pr: to review soon, priority: high

#4809 [fix] Fix an issue where ConnectionLine could not snap on labels
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/handles/ConnectionTargetHandle.tsx
Labels: pr: to review soon, priority: high

#4801 [4783] Fix label layout of nodes
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/diagrams/diagram-label.cy.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/node/FreeFormNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/node/ListNode.tsx
Labels: pr: to review soon, priority: high

#4811 [4660] Fix the use of project image as a shape of image node style
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/CustomImageMetadataSearchService.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/services/CustomImageMetadataSearchServiceTests.java
Labels: pr: to review soon, priority: high

#4810 [fix] Fix an issue where you could not connect to an edge
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/connector/useConnector.tsx
Labels: pr: to review soon, priority: high

#4808 [4807] Fix table CSV export with LabelCell
  CHANGELOG.adoc
  packages/tables/frontend/sirius-components-tables/src/actions/ExportAllDataButton.tsx
Labels: pr: to review soon, priority: high

#4805 [4804] Avoid to reset the header width when another column is resized
  CHANGELOG.adoc
  packages/tables/frontend/sirius-components-tables/src/columns/useTableColumnSizing.ts
Labels: pr: to review soon, priority: high

#4819 [fix] Fix an issue where an EdgeAnchorNode position could be wrong
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/node/EdgeAnchorNode.tsx
Labels: pr: to review soon, priority: high

#4843 [4308] Handles now take bending points into account
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/connector/useConnector.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/EdgeLayout.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/EdgeLayout.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/layoutHandles.ts
Labels: pr: to review soon, priority: low

#4839 [4830] Add Edge Width property in edgeStyle details view
  CHANGELOG.adoc
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/EdgeStylePropertiesConfigurer.java
Labels: pr: to review soon, priority: low

#4845 [fix] Fix an issue where treem items could wrongly stay rendered as 'hovered'
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItem.tsx
Labels: pr: to review later, priority: low

#4824 [4823] Fix a potential ConcurrentModificationException on save
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/services/EditingContextPersistenceService.java
Labels: pr: to review later, priority: high

#4846 [enh] Avoid a database access if not necessary
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/StudioCapableEditingContextPredicate.java
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/services/PapayaCapableEditingContextPredicate.java
Labels: pr: to review later, priority: low

#4834 [4787] Prevent flow action to be available without the flow nature
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/StudioEditingContextActionProvider.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/EditingContextControllerIntegrationTests.java
  packages/starters/backend/sirius-components-flow-starter/src/main/java/org/eclipse/sirius/components/flow/starter/services/FlowEditingContextActionProvider.java
Labels: pr: to review soon, priority: high

#4833 [cleanup] Improve the separation between Sirius Components and Sirius…
  packages/core/backend/sirius-components-collaborative/src/main/resources/schema/core.graphqls
  packages/core/backend/sirius-components-core-graphql/src/main/java/org/eclipse/sirius/components/core/graphql/datafetchers/EditingContextRepresentationDataFetcher.java
  packages/core/backend/sirius-components-core-graphql/src/main/java/org/eclipse/sirius/components/core/graphql/datafetchers/EditingContextRepresentationDescriptionsDataFetcher.java
  packages/core/backend/sirius-components-core-graphql/src/main/java/org/eclipse/sirius/components/core/graphql/datafetchers/RepresentationMetadataDescriptionDataFetcher.java
  packages/core/backend/sirius-components-core-graphql/src/main/java/org/eclipse/sirius/components/core/graphql/datafetchers/RepresentationMetadataIconURLsDataFetcher.java
  packages/core/backend/sirius-components-core-graphql/src/main/java/org/eclipse/sirius/components/core/graphql/dto/RepresentationMetadataDTO.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/representation/controllers/EditingContextRepresentationsDataFetcher.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/representation/services/RepresentationApplicationService.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/representation/services/RepresentationMetadataMapper.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/representation/services/api/IRepresentationApplicationService.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/representation/services/api/IRepresentationMetadataMapper.java
  packages/sirius-web/backend/sirius-web-application/src/main/resources/schema/siriusweb.graphqls
Labels: pr: to review later, priority: low

#4890 [cleanup] Remove Guava dependency in sirius-components-emf
  packages/emf/backend/sirius-components-emf/pom.xml
Labels: pr: to review later, priority: low

#4889 [cleanup] Properly dispose the ChangeRecorder with its editing context
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/EditingContext.java
Labels: pr: to review later, priority: low

#4885 [4878] Fix an issue where edge paths could lose their rectilinearity
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/rectilinear-edge/RectilinearEdgeCalculation.ts
Labels: pr: to review soon, priority: high

#4872 [releng] Switch to MUI v7
  CHANGELOG.adoc
  package-lock.json
  packages/browser/frontend/sirius-components-browser/package.json
  packages/core/frontend/sirius-components-core/package.json
  packages/core/frontend/sirius-components-core/src/index.ts
  packages/core/frontend/sirius-components-omnibox/package.json
  packages/deck/frontend/sirius-components-deck/package.json
  packages/deck/frontend/sirius-components-deck/src/laneHeader/LaneContextMenu.tsx
  packages/diagrams/frontend/sirius-components-diagrams/package.json
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/package.json
  packages/forms/frontend/sirius-components-forms/package.json
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/ButtonPropertySection.test.tsx.snap
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/ChartWidgetPropertySection.test.tsx.snap
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/CheckboxPropertySection.test.tsx.snap
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/FlexboxContainerPropertySection.test.tsx.snap
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/ImagePropertySection.test.tsx.snap
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/LabelPropertySection.test.tsx.snap
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/LinkPropertySection.test.tsx.snap
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/ListPropertySection.test.tsx.snap
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/MultiSelectPropertySection.test.tsx.snap
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/RadioPropertySection.test.tsx.snap
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/SelectPropertySection.test.tsx.snap
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/SplitButtonPropertySection.test.tsx.snap
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/TextfieldPropertySection.test.tsx.snap
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/TreePropertySection.test.tsx.snap
  packages/forms/frontend/sirius-components-widget-reference/package.json
  packages/forms/frontend/sirius-components-widget-table/package.json
  packages/gantt/frontend/sirius-components-gantt/package.json
  packages/portals/frontend/sirius-components-portals/package.json
  packages/selection/frontend/sirius-components-selection/package.json
  packages/sirius-web/frontend/sirius-web-application/package.json
  packages/sirius-web/frontend/sirius-web-application/src/onboarding/NewDocumentArea.tsx
  packages/sirius-web/frontend/sirius-web-application/src/onboarding/NewRepresentationArea.tsx
  packages/sirius-web/frontend/sirius-web-application/src/onboarding/RepresentationsArea.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/library-browser/LibraryBrowserView.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/project-browser/ProjectBrowserView.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/project-browser/list-projects-area/useProjectsTableColumns.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/project-settings/images/ProjectImagesSettings.tsx
  packages/sirius-web/frontend/sirius-web-papaya/package.json
  packages/sirius-web/frontend/sirius-web-view-fork/package.json
  packages/sirius-web/frontend/sirius-web/package.json
  packages/tables/frontend/sirius-components-tables/package.json
  packages/tools/frontend/sirius-components-specification-layout/package.json
  packages/trees/frontend/sirius-components-trees/package.json
  packages/validation/frontend/sirius-components-validation/package.json
  vscode-extension/package.json
Labels: pr: to review later, priority: low
