Repository eclipse-sirius/sirius-web, pull requests merged in 2025-02, with the labels that each got.

#4497 [test] Add test for table selectedTargetObjectExpression
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/tables/PapayaViewTableControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/tables/ViewTableDescriptionProvider.java
Labels: pr: to review later, priority: low

#4505 [cleanup] Extract undoRedo apollo client option into its own configurer
  packages/sirius-web/frontend/sirius-web-application/src/extension/DefaultExtensionRegistry.tsx
  packages/sirius-web/frontend/sirius-web-application/src/extension/DefaultExtensionRegistryMergeStrategy.ts
Labels: pr: to review later, priority: low

#4515 [4514] Fix redo shortcut handling
  CHANGELOG.adoc
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/UndoRedo.tsx
Labels: pr: to review later, priority: low

#4537 [4536] Fix Undo/Redo
  CHANGELOG.adoc
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/UndoRedo.tsx
Labels: pr: to review soon, priority: high

#4543 [4498] Restore lost arrowheads on SVG export
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/panel/useExportToImage.tsx
Labels: pr: to review soon, priority: high

#4546 [4545] Ensure that widgets used to edit numbers are not created twice
  CHANGELOG.adoc
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/ViewPropertiesDescriptionRegistryConfigurer.java
Labels: pr: to review soon, priority: high

#4550 [4530] Ensure that the form description editor will not crash with nested structure
  CHANGELOG.adoc
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FlexboxContainerWidget.tsx
Labels: pr: to review soon, priority: high

#4548 [4544] Fix quicktools alignement
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/direct-edit/DiagramDirectEditInput.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/drop/useDrop.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/dropNode/useDropNode.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/fade/useFadeDiagramElements.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/hide/useHideDiagramElements.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/useSynchronizeLayoutData.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/quick-access-tool/AdjustSizeTool.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/quick-access-tool/FadeElementTool.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/quick-access-tool/PaletteQuickAccessToolBar.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/quick-access-tool/PinUnPinTool.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/quick-access-tool/ResetEditedEdgePathTool.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/quick-access-tool/Tool.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/quick-access-tool/Tool.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/usePalette.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/reconnect-edge/useReconnectEdge.types.ts
Labels: pr: to review soon, priority: high

#4542 [4523] Fix the interaction between the palette and fit view
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx
Labels: pr: to review soon, priority: high

#4558 [4557] Fix an issue where targetObjectURI was not set during the download of a project
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/services/ProjectRepresentationDataExportParticipant.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/projects/ProjectDownloadControllerIntegrationTests.java
Labels: pr: to review soon, priority: high

#4552 [4547] Adapt the VSCode extension to the use of SemanticData#id as editingContextId
  CHANGELOG.adoc
  vscode-extension/package.json
  vscode-extension/src/data/ModelData.ts
  vscode-extension/src/data/ProjectData.ts
  vscode-extension/src/data/RepresentationData.ts
  vscode-extension/src/data/ServerData.ts
  vscode-extension/src/viewsContainer/views/explorerView.ts
  vscode-extension/src/viewsContainer/views/representationsView.ts
Labels: pr: to review soon, priority: high

#4562 [4561] Display boolean values properly in the query view
  CHANGELOG.adoc
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/query/QueryView.tsx
Labels: pr: to review soon, priority: high

#4551 [4549] Filter edge tools from palette tool sections
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/tool-list/PaletteToolSectionList.tsx
Labels: pr: to review soon, priority: high

#4563 [4559] Wait until the pre-layout component has been mounted before co…
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/layout.tsx
Labels: pr: to review soon, priority: high

#4566 [4564] Add an arrow to close the palette on its header
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/DiagramElementPalette.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/DiagramPalette.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/Palette.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/Palette.types.ts
Labels: pr: to review later, priority: low

#4570 [4257] Fix label width compute on list node
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/ListNodeLayoutHandler.ts
Labels: pr: to review soon, priority: high

#4555 [4554] Stop synchronizing selection from the explorer if the correspondin…
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/selection/useDiagramSelection.ts
Labels: pr: to review soon, priority: high

#4480 [doc] ADR to add support of row hierarchy in tables
  CHANGELOG.adoc
  doc/adrs/183_add_support_of_row_hierarchy_in_tables.adoc
Labels: pr: to review soon, priority: high

#4519 [doc] Add an ADR to support project dependencies
  CHANGELOG.adoc
  doc/adrs/184_add_support_for_project_dependencies.adoc
Labels: pr: to review soon, priority: high

#4603 [test] Fix some flaky Cypress tests
  integration-tests/cypress/e2e/project/diagrams/direct-edit-label.cy.ts
Labels: pr: to review soon, priority: high

#4496 [4495] Add an user indicator when executing form actions
  CHANGELOG.adoc
  packages/forms/frontend/sirius-components-forms/src/index.ts
  packages/forms/frontend/sirius-components-forms/src/propertysections/ButtonPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/CheckboxPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/DateTimeWidgetPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/ListPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/LoadingIndicator.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/LoadingIndicator.types.ts
  packages/forms/frontend/sirius-components-forms/src/propertysections/MultiSelectPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/PropertySectionLabel.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/RadioPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/RichTextPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/SelectPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/SliderPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/SplitButtonPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/TextfieldPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/ButtonPropertySection.test.tsx.snap
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/ChartWidgetPropertySection.test.tsx.snap
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/CheckboxPropertySection.test.tsx.snap
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/FlexboxContainerPropertySection.test.tsx.snap
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/ImagePropertySection.test.tsx.snap
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/LabelPropertySection.test.tsx.snap
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/ListPropertySection.test.tsx.snap
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/MultiSelectPropertySection.test.tsx.snap
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/RadioPropertySection.test.tsx.snap
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/SelectPropertySection.test.tsx.snap
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/SplitButtonPropertySection.test.tsx.snap
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/TextfieldPropertySection.test.tsx.snap
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/__snapshots__/TreePropertySection.test.tsx.snap
  packages/forms/frontend/sirius-components-widget-reference/src/ReferencePropertySection.tsx
Labels: pr: to review later, priority: low

#4619 [cleanup] Reduce the use of IObjectService to minimize the impact of future changes
  packages/charts/backend/sirius-components-collaborative-charts/src/main/java/org/eclipse/sirius/components/collaborative/charts/CreateHierarchyEventHandler.java
  packages/charts/backend/sirius-components-collaborative-charts/src/main/java/org/eclipse/sirius/components/collaborative/charts/HierarchyCreationService.java
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/handlers/CreateChildEventHandler.java
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/handlers/DeleteObjectEventHandler.java
  packages/core/backend/sirius-components-collaborative/src/test/java/org/eclipse/sirius/components/collaborative/handlers/CreateChildEventHandlerTests.java
  packages/core/backend/sirius-components-collaborative/src/test/java/org/eclipse/sirius/components/collaborative/handlers/DeleteObjectEventHandlerTests.java
  packages/deck/backend/sirius-components-collaborative-deck/src/main/java/org/eclipse/sirius/components/collaborative/deck/handlers/CreateDeckEventHandler.java
  packages/deck/backend/sirius-components-collaborative-deck/src/main/java/org/eclipse/sirius/components/collaborative/deck/service/DeckCardService.java
  packages/deck/backend/sirius-components-collaborative-deck/src/main/java/org/eclipse/sirius/components/collaborative/deck/service/DeckCreationService.java
  packages/deck/backend/sirius-components-collaborative-deck/src/main/java/org/eclipse/sirius/components/collaborative/deck/service/DeckLaneService.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/DiagramCreationService.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/configuration/DiagramEventHandlerConfiguration.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/CreateDiagramEventHandler.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/DeleteFromDiagramEventHandler.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/DropNodeEventHandler.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/DropOnDiagramEventHandler.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/EditLabelEventHandler.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/GetPaletteEventHandler.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/InvokeSingleClickOnDiagramElementToolEventHandler.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/InvokeSingleClickOnTwoDiagramElementsToolEventHandler.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/ReconnectEdgeEventHandler.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/test/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/CreateDiagramEventHandlerTests.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/test/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/DeleteFromDiagramEventHandlerTests.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/test/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/DropNodeEventHandlerTests.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/test/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/InvokeSingleClickOnDiagramElementToolEventHandlerTests.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/test/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/ReconnectEdgeEventHandlerTests.java
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/FormDescriptionEditorCreationService.java
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/AddGroupEventHandler.java
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/AddPageEventHandler.java
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/AddToolbarActionEventHandler.java
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/AddWidgetEventHandler.java
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/CreateFormDescriptionEditorEventHandler.java
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/DeleteGroupEventHandler.java
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/DeletePageEventHandler.java
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/DeleteToolbarActionEventHandler.java
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/DeleteWidgetEventHandler.java
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/MoveGroupEventHandler.java
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/MovePageEventHandler.java
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/MoveToolbarActionEventHandler.java
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/MoveWidgetEventHandler.java
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/test/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/AddGroupEventHandlerTests.java
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/test/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/AddPageEventHandlerTests.java
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/test/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/AddToolbarActionEventHandlerTests.java
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/test/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/AddWidgetEventHandlerTests.java
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/test/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/CreateFormDescriptionEditorEventHandlerTests.java
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/test/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/DeleteGroupEventHandlerTests.java
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/test/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/DeletePageEventHandlerTests.java
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/test/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/DeleteToolbarActionEventHandlerTests.java
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/test/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/DeleteWidgetEventHandlerTests.java
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/test/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/MoveGroupEventHandlerTests.java
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/test/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/MovePageEventHandlerTests.java
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/test/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/MoveToolbarActionEventHandlerTests.java
  packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/test/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/MoveWidgetEventHandlerTests.java
  packages/view/backend/sirius-components-view-emf/src/test/java/org/eclipse/sirius/components/view/emf/view/DynamicDiagramsTests.java
Labels: pr: to review soon, priority: high

#4541 [4540] Do not invoke mutation layoutDiagram when in read-only mode
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx
Labels: pr: to review later, priority: low

#4624 [releng] Switch to PostgreSQL 15
  CHANGELOG.adoc
  README.adoc
  packages/sirius-web/backend/sirius-web/docker-compose.yml
Labels: pr: to review soon, priority: low

#4582 [4581] Make data fetchers go through IEditingContextDispatcher
  CHANGELOG.adoc
  packages/diagrams/backend/sirius-components-diagrams-graphql/src/main/java/org/eclipse/sirius/components/diagrams/graphql/datafetchers/diagram/DiagramDescriptionConnectorToolsDataFetcher.java
  packages/diagrams/backend/sirius-components-diagrams-graphql/src/main/java/org/eclipse/sirius/components/diagrams/graphql/datafetchers/diagram/DiagramDescriptionDropNodeCompatibilityDataFetcher.java
  packages/diagrams/backend/sirius-components-diagrams-graphql/src/main/java/org/eclipse/sirius/components/diagrams/graphql/datafetchers/diagram/DiagramDescriptionInitialDirectEditElementLabelDataFetcher.java
  packages/diagrams/backend/sirius-components-diagrams-graphql/src/main/java/org/eclipse/sirius/components/diagrams/graphql/datafetchers/diagram/DiagramDescriptionPaletteDataFetcher.java
  packages/forms/backend/sirius-components-widget-reference-graphql/src/main/java/org/eclipse/sirius/components/widget/reference/graphql/datafetchers/query/ReferenceWidgetChildCreationDescriptionsDataFetcher.java
  packages/forms/backend/sirius-components-widget-reference-graphql/src/main/java/org/eclipse/sirius/components/widget/reference/graphql/datafetchers/query/ReferenceWidgetRootCreationDescriptionsDataFetcher.java
  packages/selection/backend/sirius-components-selection-graphql/src/main/java/org/eclipse/sirius/components/selection/graphql/datafetchers/selection/SelectionDescriptionMessageDataFetcher.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/representation/controllers/EditingContextRepresentationDescriptionsDataFetcher.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/representation/controllers/MutationDeleteRepresentationDataFetcher.java
  packages/tables/backend/sirius-components-tables-graphql/src/main/java/org/eclipse/sirius/components/tables/graphql/datafetchers/TableDescriptionRowContextMenuDataFetcher.java
  packages/trees/backend/sirius-components-trees-graphql/src/main/java/org/eclipse/sirius/components/trees/graphql/datafetchers/editingcontext/EditingContextExpandAllTreePathDataFetcher.java
  packages/trees/backend/sirius-components-trees-graphql/src/main/java/org/eclipse/sirius/components/trees/graphql/datafetchers/editingcontext/EditingContextTreePathDataFetcher.java
  packages/trees/backend/sirius-components-trees-graphql/src/main/java/org/eclipse/sirius/components/trees/graphql/datafetchers/tree/TreeDescriptionContextMenuDataFetcher.java
  packages/trees/backend/sirius-components-trees-graphql/src/main/java/org/eclipse/sirius/components/trees/graphql/datafetchers/tree/TreeDescriptionFetchTreeItemContextMenuEntryDataDataFetcher.java
  packages/trees/backend/sirius-components-trees-graphql/src/main/java/org/eclipse/sirius/components/trees/graphql/datafetchers/tree/TreeItemInitialDirectEditLabelDataFetcher.java
Labels: pr: to review soon, priority: low

#4589 [doc] Add support for custom ordering of the representations in the creation modal
  CHANGELOG.adoc
  doc/adrs/185_order_representations_creation_modal.adoc
Labels: pr: to review soon, priority: high

#4602 [4588] Support custom ordering in representation creation modal
  CHANGELOG.adoc
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/handlers/EditingContextRepresentationDescriptionsEventHandler.java
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/services/api/IRepresentationDescriptionMetadataSorter.java
  packages/sirius-web/frontend/sirius-web-application/src/modals/new-representation/NewRepresentationModal.tsx
  packages/sirius-web/frontend/sirius-web-application/src/modals/new-representation/NewRepresentationModalMachine.ts
Labels: pr: to review soon, priority: high

#4633 [4629] Fix direct-edit-label flaky tests
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/diagrams/direct-edit-label.cy.ts
Labels: pr: to review soon, priority: high

#4632 [4631] Add support for textarea cell type in widget tables
  CHANGELOG.adoc
  packages/forms/frontend/sirius-components-forms/src/form/FormEventFragments.ts
Labels: pr: to review soon, priority: high

#4594 [4263] Add a button to reset table row heights to their initial value
  CHANGELOG.adoc
  packages/tables/backend/sirius-components-collaborative-tables/src/main/java/org/eclipse/sirius/components/collaborative/tables/handlers/ResetTableRowsHeightEventHandler.java
  packages/tables/backend/sirius-components-collaborative-tables/src/main/java/org/eclipse/sirius/components/collaborative/tables/handlers/ResizeTableRowEventHandler.java
  packages/tables/frontend/sirius-components-tables/src/table/TableContent.tsx
Labels: pr: to review soon, priority: low
