Repository eclipse-sirius/sirius-web, pull requests merged in 2025-06, with the labels that each got.

#4987 [fix] Fix the wrong icon url for delete from diagram migration partic…
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/migration/participants/NodePaletteDeleteFromDiagramMigrationParticipant.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/migration/NodePaletteDeleteFromDiagramMigrationParticipantTests.java
  packages/starters/backend/sirius-components-flow-starter/src/main/java/org/eclipse/sirius/components/flow/starter/view/FlowViewBuilder.java
  packages/starters/backend/sirius-components-flow-starter/src/main/java/org/eclipse/sirius/components/flow/starter/view/descriptions/DataSourceDescriptionProvider.java
  packages/starters/backend/sirius-components-flow-starter/src/main/java/org/eclipse/sirius/components/flow/starter/view/descriptions/DataSourceToProcessorEdgeDescriptionProvider.java
  packages/starters/backend/sirius-components-flow-starter/src/main/java/org/eclipse/sirius/components/flow/starter/view/descriptions/FanDescriptionProvider.java
  packages/starters/backend/sirius-components-flow-starter/src/main/java/org/eclipse/sirius/components/flow/starter/view/descriptions/PowerInputDescriptionProvider.java
  packages/starters/backend/sirius-components-flow-starter/src/main/java/org/eclipse/sirius/components/flow/starter/view/descriptions/PowerOutputDescriptionProvider.java
  packages/starters/backend/sirius-components-flow-starter/src/main/java/org/eclipse/sirius/components/flow/starter/view/descriptions/ProcessorDescriptionProvider.java
  packages/starters/backend/sirius-components-flow-starter/src/main/java/org/eclipse/sirius/components/flow/starter/view/descriptions/ProcessorToProcessorEdgeDescriptionProvider.java
  packages/starters/backend/sirius-components-flow-starter/src/main/java/org/eclipse/sirius/components/flow/starter/view/descriptions/SystemDescriptionProvider.java
Labels: pr: to review soon, priority: high

#4980 [4979] Make sure collapsed views are not mounted/rendered at all
  CHANGELOG.adoc
  packages/core/frontend/sirius-components-core/src/workbench/Panels.tsx
  packages/core/frontend/sirius-components-core/src/workbench/Panels.types.ts
Labels: pr: to review soon, priority: high

#5025 [3917] Disable edge reconnections when diagram is in read-only mode
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/DiagramElementPalette.tsx
Labels: pr: to review soon, priority: high

#5028 [releng] Prepare the CHANGELOG for 2025.8.0
  CHANGELOG.adoc
Labels: pr: to review soon, priority: high

#5031 [4723] Restore the behavior of the share representation modal
  CHANGELOG.adoc
  packages/core/frontend/sirius-components-core/src/contexts/RepresentationPathContext.types.ts
  packages/core/frontend/sirius-components-core/src/modals/share-representation/ShareRepresentationModal.tsx
  packages/core/frontend/sirius-components-core/src/modals/share-representation/ShareRepresentationModal.types.ts
  packages/deck/frontend/sirius-components-deck/src/Deck.tsx
  packages/deck/frontend/sirius-components-deck/src/toolbar/DeckToolbar.tsx
  packages/deck/frontend/sirius-components-deck/src/toolbar/Toolbar.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/panel/DiagramPanel.tsx
  packages/gantt/frontend/sirius-components-gantt/src/representation/Gantt.tsx
  packages/gantt/frontend/sirius-components-gantt/src/representation/Gantt.types.ts
  packages/gantt/frontend/sirius-components-gantt/src/representation/GanttRepresentation.tsx
  packages/gantt/frontend/sirius-components-gantt/src/toolbar/Toolbar.tsx
  packages/gantt/frontend/sirius-components-gantt/src/toolbar/Toolbar.types.ts
  packages/portals/frontend/sirius-components-portals/src/representations/PortalRepresentation.tsx
  packages/portals/frontend/sirius-components-portals/src/representations/PortalToolbar.tsx
  packages/portals/frontend/sirius-components-portals/src/representations/PortalToolbar.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/application/SiriusWebApplication.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/display-library/DisplayLibraryView.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/EditProjectView.tsx
Labels: pr: to review soon, priority: high

#5030 [5018] Fix a bug that remove node layout strategy after fork a repr…
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/migration/participants/NodeDescriptionLayoutStrategyMigrationParticipant.java
  packages/sirius-web/backend/sirius-web-tests-data/src/main/resources/sirius-web-scripts/migration.sql
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/data/MigrationIdentifiers.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/migration/DiagramNodeDescriptionLayoutStrategyMigrationParticipantTests.java
Labels: pr: to review soon, priority: low

#5033 [test] Fix group-palette cypress tests
  integration-tests/cypress/e2e/project/diagrams/group-palette.cy.ts
Labels: pr: to review soon, priority: high

#4961 [doc] Add shape for sharing the workbench state
  CHANGELOG.adoc
  doc/adrs/198_add_the_ability_to_share_a_url_containing_the_views_of_the_workbench.adoc
  doc/adrs/images/198/add_workbench_views_to_url_example1.png
  doc/adrs/images/198/add_workbench_views_to_url_example2.png
  doc/adrs/images/198/add_workbench_views_to_url_example3.png
  doc/adrs/images/198/add_workbench_views_to_url_example4.png
  doc/iterations/2025.8/add_ability_to_share_workbench_state.adoc
Labels: pr: to review soon, priority: high

#5100 [5099] Remove state machine from FormDescriptionEditor
  CHANGELOG.adoc
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FormDescriptionEditorEventFragment.types.ts
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FormDescriptionEditorRepresentation.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FormDescriptionEditorRepresentationMachine.ts
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/useFormDescriptionEditorEventSubscription.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/useFormDescriptionEditorEventSubscription.types.ts
Labels: pr: to review soon, priority: low

#5032 [releng] Update to node js 22.16.0
  .github/workflows/build.yml
  .github/workflows/pull-request.yml
  CHANGELOG.adoc
  integration-tests/package-lock.json
  package-lock.json
  package.json
  packages/browser/frontend/sirius-components-browser/vite.config.js
  packages/browser/frontend/sirius-components-browser/vitestSetup.js
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/vite.config.js
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/vitestSetup.js
  packages/forms/frontend/sirius-components-widget-reference/vite.config.js
  packages/forms/frontend/sirius-components-widget-reference/vitestSetup.js
  packages/forms/frontend/sirius-components-widget-table/vite.config.js
  packages/forms/frontend/sirius-components-widget-table/vitestSetup.js
  packages/portals/frontend/sirius-components-portals/vite.config.js
  packages/portals/frontend/sirius-components-portals/vitestSetup.js
  packages/sirius-web/frontend/sirius-web-papaya/vite.config.js
  packages/sirius-web/frontend/sirius-web-view-fork/vite.config.js
Labels: pr: to review later, priority: low

#5104 [5103] Export ExpandAllTreeItemContextMenuContribution
  CHANGELOG.adoc
  packages/sirius-web/frontend/sirius-web-application/src/index.ts
Labels: pr: to review soon, priority: high

#5129 [test] Improve diagram related tests
  packages/diagrams/backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/DiagramEventPayloadConsumer.java
  packages/diagrams/backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/graphql/InvokeSingleClickOnDiagramElementToolAssert.java
  packages/diagrams/backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/graphql/InvokeSingleClickOnDiagramElementToolExecutor.java
  packages/diagrams/backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/navigation/DiagramNavigator.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/ActionControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/AncestorsVariableDiagramControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/CustomImageDiagramControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/CustomNodesDiagramControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/DiagramFilterControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/DomainDiagramControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/DropNodeControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/EdgeControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/EdgeOnEdgeControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/EdgePaletteControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/EditLabelAppearanceControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/EditLabelDiagramControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/EditRectangularNodeAppearanceControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/ExpandCollapseDiagramControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/ManageVisibilityActionControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/ModelOperationDiagramControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/PaletteControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/UnsynchronizedDiagramControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/VisibilityDiagramControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/impactanalysis/ImpactAnalysisDiagramToolControllerTests.java
Labels: pr: to review soon, priority: high

#5081 [5080] Prevent border nodes from being resized during their parent resizing
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/resize/useResizeChange.tsx
Labels: pr: to review soon, priority: low

#5082 [5065] Prevent adding bendpoints on a simple click
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/diagrams/edges.cy.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/rectilinear-edge/useBendingPoints.ts
Labels: pr: to review soon, priority: low

#5038 [5011] Improve node with a list layout feedback when resizing and moving in…
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/resize/useResizeChange.tsx
Labels: pr: to review soon, priority: low

#5158 [cleanup] Remove leftover Eclipse .project files in the tools folder
  packages/tools/backend/sirius-components-graphiql/.project
  packages/tools/backend/sirius-components-graphql-voyager/.project
Labels: pr: to review later, priority: low

#5125 [4966] Fix an issue where ConnectionTargetHandle could not be rendere…
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/handles/ConnectionTargetHandle.tsx
Labels: pr: to review soon, priority: high
