Repository eclipse-sirius/sirius-web, pull requests merged in 2025-09, with the labels that each got.

#5239 [5140] Add support for the management of the appearance of custom nodes
  CHANGELOG.adoc
  packages/diagrams/backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/graphql/EditEllipseNodeAppearanceMutationRunner.java
  packages/diagrams/frontend/sirius-components-diagrams/src/index.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/PaletteAppearanceSection.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/extensions/PaletteAppearanceSectionContribution.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/extensions/PaletteAppearanceSectionExtensionPoints.tsx
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/diagram/EllipseNodeStyle.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/diagram/dto/EditEllipseNodeAppearanceInput.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/diagram/dto/EllipseNodeAppearanceInput.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/diagram/graphql/MutationEditEllipseNodeAppearanceDataFetcher.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/diagram/services/DiagramImporterEllipseNodeStyleAppearanceChangeHandler.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/diagram/services/EditEllipseNodeAppearanceEventHandler.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/diagram/services/EllipseNodeAppearanceHandler.java
  packages/sirius-web/backend/sirius-web-application/src/main/resources/schema/customnodes.graphqls
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/EditEllipseNodeAppearanceControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/diagrams/CustomNodesDiagramDescriptionProvider.java
  packages/sirius-web/frontend/sirius-web-application/src/extension/DefaultExtensionRegistry.tsx
  packages/sirius-web/frontend/sirius-web-application/src/extension/ellipsenode/EllipseNodeDocumentTransform.ts
  packages/sirius-web/frontend/sirius-web-application/src/extension/ellipsenode/EllipseNodePaletteAppearanceSection.tsx
  packages/sirius-web/frontend/sirius-web-application/src/extension/ellipsenode/EllipseNodePaletteAppearanceSection.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/extension/ellipsenode/EllipseNodePart.tsx
  packages/sirius-web/frontend/sirius-web-application/src/extension/ellipsenode/EllipseNodePart.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/extension/ellipsenode/useUpdateEllipseNodeAppearance.ts
  packages/sirius-web/frontend/sirius-web-application/src/extension/ellipsenode/useUpdateEllipseNodeAppearance.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/index.ts
Labels: pr: to review soon, priority: high

#5377 [5310] Prevent edge center label from blinking during node moves
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/rectilinear-edge/MultiLabelRectilinearEditableEdge.tsx
Labels: pr: to review soon, priority: low

#5390 [5063] Update custom edge algorithm to add bend points only when segm…
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/BendPoint.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/BendPoint.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/EdgeLayout.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/rectilinear-edge/MultiLabelRectilinearEditableEdge.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/rectilinear-edge/RectilinearEdgeCalculation.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/rectilinear-edge/useBendingPoints.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/rectilinear-edge/useBendingPoints.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/rectilinear-edge/useTemporaryLines.ts
Labels: pr: to review soon, priority: low

#5374 [5057] Add support for customizing the behavior of the Duplicate object operation
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/ComposedExplorerLabelService.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/ComposedObjectDuplicator.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/DefaultObjectDuplicator.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/DuplicateObjectEventHandler.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/api/DuplicationSettings.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/api/IDefaultObjectDuplicator.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/api/IObjectDuplicator.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/api/IObjectDuplicatorDelegate.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/objects/ObjectDuplicationControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/explorer/PapayaObjectDuplicatorDelegate.java
Labels: pr: to review later, priority: low

#5280 [enh] Improve the ViewerContext
  CHANGELOG.adoc
  doc/adrs/207_make_react_context_extensible.adoc
  packages/sirius-web/frontend/sirius-web-application/src/viewer/ViewerContext.tsx
  packages/sirius-web/frontend/sirius-web-application/src/viewer/ViewerContext.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/viewer/useCurrentViewer.ts
  packages/sirius-web/frontend/sirius-web-application/src/viewer/useCurrentViewer.types.ts
Labels: pr: to review soon, priority: high

#5282 [5045] Add support for the management of the appearance of all properties for image nodes
  CHANGELOG.adoc
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/ImageNodeAppearanceHandler.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/dto/EditImageNodeAppearanceInput.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/dto/ImageNodeAppearanceInput.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/appearance/EditImageNodeAppearanceEventHandler.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/resources/schema/appearance.graphqls
  packages/diagrams/backend/sirius-components-diagrams-graphql/src/main/java/org/eclipse/sirius/components/diagrams/graphql/datafetchers/mutation/MutationEditImageNodeAppearanceDataFetcher.java
  packages/diagrams/backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/graphql/EditImageNodeAppearanceMutationRunner.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/ImageNodeStyle.java
  packages/diagrams/frontend/sirius-components-diagrams/src/graphql/subscription/nodeFragment.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/ImageNodeAppearanceSection.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/ImageNodeAppearanceSection.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/PaletteAppearanceSection.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/image-node/ImageNodePart.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/image-node/ImageNodePart.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/image-node/useUpdateImageNodeAppearance.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/image-node/useUpdateImageNodeAppearance.types.ts
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/services/DiagramImporterImageNodeStyleAppearanceChangeHandler.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/EditImageNodeAppearanceControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/ProjectWithUnsynchronizedDiagramUploadControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/diagrams/ImageNodeDiagramDescriptionProvider.java
Labels: pr: to review soon, priority: high

#5421 [5420] Add support for customization of subscription scheduler
  CHANGELOG.adoc
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/representations/api/IEventProcessorSubscriptionSchedulerProvider.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/services/EventProcessorSubscriptionProvider.java
  packages/sirius-web/backend/sirius-web-starter/src/main/java/org/eclipse/sirius/web/starter/SiriusWebStarterConfiguration.java
Labels: pr: to review soon, priority: high

#5224 [5160] Fix an issue where nodes where updated without an updater func…
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/handles/useHandleChange.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/helper-lines/useHelperLines.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/helper-lines/useHelperLines.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout-events/useLayoutOnBoundsChange.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/move/useMoveChange.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/move/useMoveChange.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/resize/useResizeChange.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/resize/useResizeChange.types.ts
Labels: pr: to review later, priority: low

#5412 [4886] Remove 'workbenchConfiguration' parameter from URL after loading
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/workbench/workbench-configuration.cy.ts
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/EditProjectView.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/EditProjectView.types.ts
Labels: pr: to review soon, priority: high

#5426 [4886] Add opened representations to the shared URL
  CHANGELOG.adoc
  integration-tests-cypress/cypress/e2e/project/workbench/workbench-configuration.cy.ts
  integration-tests-cypress/cypress/e2e/project/workbench/workbench-configuration.data.ts
  integration-tests-cypress/cypress/e2e/project/workbench/workbench-configuration.data.types.ts
  integration-tests-cypress/cypress/pages/Project.ts
  integration-tests-cypress/cypress/workbench/Explorer.ts
  integration-tests-cypress/cypress/workbench/Workbench.ts
  packages/core/frontend/sirius-components-core/src/representationmetadata/useRepresentationMetadata.tsx
  packages/core/frontend/sirius-components-core/src/representationmetadata/useRepresentationMetadata.types.ts
  packages/core/frontend/sirius-components-core/src/workbench/RepresentationNavigation.tsx
  packages/core/frontend/sirius-components-core/src/workbench/Workbench.tsx
  packages/core/frontend/sirius-components-core/src/workbench/Workbench.types.ts
  packages/core/frontend/sirius-components-core/src/workbench/useSynchronizeRepresentationWithSelection.tsx
  packages/core/frontend/sirius-components-core/src/workbench/useSynchronizeRepresentationWithSelection.types.ts
  packages/core/frontend/sirius-components-core/src/workbench/useSynchronizeRepresentationWithWorkbenchConfiguration.tsx
  packages/core/frontend/sirius-components-core/src/workbench/useSynchronizeRepresentationWithWorkbenchConfiguration.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/navbar/context-menu/ShareProjectModal.tsx
Labels: pr: to review soon, priority: high

#5432 [5431] Support EObject-typed containments
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/ContainmentFeatureNamesEventHandler.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/ExplorerDropTreeItemExecutor.java
Labels: pr: to review soon, priority: high

#5443 [5440] Add support for a navigation bar menu header
  CHANGELOG.adoc
  packages/sirius-web/frontend/sirius-web-application/src/index.ts
  packages/sirius-web/frontend/sirius-web-application/src/navigationBar/NavigationBarMenu.tsx
  packages/sirius-web/frontend/sirius-web-application/src/navigationBar/NavigationBarMenuExtensionPoints.tsx
Labels: pr: to review soon, priority: high

#5435 [5427] Add ICustomNodeStyleDeserializer API to correctly deserialize …
  CHANGELOG.adoc
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/INodeStyleDeserializer.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/NodeStyleStdDeserializerProvider.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/api/ICustomNodeStyleDeserializer.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/diagram/services/EllipseNodeStyleDeserializer.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/ProjectWithUnsynchronizedDiagramWithCustomNodeUploadControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/diagrams/CustomNodesUnsynchonisedDiagramDescriptionProvider.java
Labels: pr: to review soon, priority: high

#5422 [5283] Add support for the management of the appearance of outside la…
  CHANGELOG.adoc
  integration-tests-playwright/playwright/e2e/appearance.spec.ts
  integration-tests-playwright/playwright/helpers/PlaywrightLabel.ts
  integration-tests-playwright/playwright/helpers/PlaywrightNode.ts
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/resources/schema/diagram.graphqls
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/test/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/InitialDirectEditElementLabelEventHandlerTests.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/OutsideLabel.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/InsideLabelComponent.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/LabelStyleComponentProvider.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/NodeChildrenComponent.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/OutsideLabelComponent.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/OutsideLabelComponentProps.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/elements/OutsideLabelElementProps.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/renderer/DiagramElementFactory.java
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/convertLabel.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/graphql/subscription/labelFragment.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/graphql/subscription/labelFragment.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/ImageNodeAppearanceSection.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/RectangularNodeAppearanceSection.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/property-component/TextFieldAppearanceProperty.tsx
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/services/DiagramImporterUpdateService.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/ProjectWithUnsynchronizedDiagramUploadControllerTests.java
Labels: pr: to review soon, priority: high

#5395 [5394] Update custom edge algorithm to position new bend points in the middle of borders
  CHANGELOG.adoc
  integration-tests-playwright/playwright/e2e/edge.spec.ts
  integration-tests-playwright/playwright/helpers/PlaywrightNode.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/rectilinear-edge/RectilinearEdgeCalculation.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/rectilinear-edge/useBendingPoints.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/rectilinear-edge/useTemporaryLines.ts
Labels: pr: to review soon, priority: low

#5472 [5471] Add support for the management of the appearance of edge labels
  CHANGELOG.adoc
  integration-tests-playwright/playwright/e2e/appearance.spec.ts
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/DiagramCreationService.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/DiagramQueryService.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/EditLabelEventHandler.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/resources/schema/diagram.graphqls
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/test/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/InitialDirectEditElementLabelEventHandlerTests.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/test/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/InvokeSingleClickOnDiagramElementToolEventHandlerTests.java
  packages/diagrams/backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/DiagramAssert.java
  packages/diagrams/backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/LabelAssert.java
  packages/diagrams/backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/assertions/LabelAssert.java
  packages/diagrams/backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/builder/edge/EdgeBuilder.java
  packages/diagrams/backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/builder/label/LabelBuilder.java
  packages/diagrams/backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/navigation/NavigatorCache.java
  packages/diagrams/backend/sirius-components-diagrams-tests/src/main/java/org/eclipse/sirius/components/diagrams/tests/navigation/NodeNavigator.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/Label.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/EdgeComponent.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/LabelComponent.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/LabelComponentProps.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/elements/LabelElementProps.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/renderer/DiagramElementFactory.java
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/convertDiagram.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/graphql/subscription/labelFragment.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/graphql/subscription/labelFragment.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/edge/EdgeAppearanceSection.tsx
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/services/DiagramImporterUpdateService.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/DomainDiagramControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/DropNodeControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/EdgeControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/EditEdgeAppearanceControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/EditLabelDiagramControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/ProjectWithUnsynchronizedDiagramUploadControllerTests.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/providers/ViewInitialDirectEditElementLabelProvider.java
Labels: pr: to review soon, priority: high

#5469 [5469] Nodes are not initialized correctly when converting to xyflow …
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/IconLabelNodeConverter.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/ImageNodeConverter.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/ListNodeConverter.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/RectangleNodeConverter.ts
  packages/sirius-web/frontend/sirius-web/src/nodes/EllipseNodeConverter.ts
  vscode-extension/src/view/app/nodes/EllipseNodeConverter.ts
Labels: pr: to review soon, priority: high

#5477 [5404] Fix an issue where resetting an appearance was not updating the corresponding input
  CHANGELOG.adoc
  integration-tests-playwright/playwright/e2e/appearance.spec.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/hooks/useGetUpdatedModalPosition.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/ImageNodeAppearanceSection.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/ImageNodeAppearanceSection.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/PaletteAppearanceSection.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/RectangularNodeAppearanceSection.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/RectangularNodeAppearanceSection.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/edge/EdgeAppearancePart.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/edge/EdgeAppearanceSection.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/edge/EdgeAppearanceSection.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/extensions/PaletteAppearanceSectionContribution.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/image-node/ImageNodePart.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/label/LabelAppearancePart.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/property-component/CheckboxAppearanceProperty.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/property-component/CheckboxAppearanceProperty.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/property-component/SelectAppearanceProperty.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/property-component/SelectAppearanceProperty.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/property-component/TextFieldAppearanceProperty.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/property-component/TextFieldAppearanceProperty.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/rectangular-node/RectangularNodePart.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/widget/AppearanceColorPicker.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/widget/AppearanceColorPicker.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/widget/AppearanceNumberTextfield .tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/widget/AppearanceNumberTextfield.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/widget/AppearanceSelect.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/widget/AppearanceSelect.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/extension/ellipsenode/EllipseNodePaletteAppearanceSection.tsx
  packages/sirius-web/frontend/sirius-web-application/src/extension/ellipsenode/EllipseNodePart.tsx
  packages/sirius-web/frontend/sirius-web-application/src/extension/ellipsenode/EllipseNodePart.types.ts
Labels: pr: to review soon, priority: high

#5505 [5504] Reduce the size of the creation handles when creating an edge …
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/handles/ConnectionCreationHandles.tsx
Labels: pr: to review soon, priority: high

#5498 [doc] Add shape for selection behavior changes
  CHANGELOG.adoc
  doc/iterations/2025.10/images/selection_details.png
  doc/iterations/2025.10/images/selection_diagram.png
  doc/iterations/2025.10/images/selection_explorer.png
  doc/iterations/2025.10/rework_selection.adoc
Labels: pr: to review soon, priority: high

#5515 [enh] Improve the consistency of the computation of the document identifier
  packages/browser/backend/sirius-components-collaborative-browser/src/main/java/org/eclipse/sirius/components/collaborative/browser/ModelBrowserDescriptionProvider.java
  packages/browser/backend/sirius-components-collaborative-browser/src/main/java/org/eclipse/sirius/components/collaborative/browser/ModelBrowserTreePathProvider.java
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/handlers/EditingContextObjectEventHandler.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/services/UploadDocumentEventHandler.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/services/EditingContextDependencyLoader.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/services/ResourceToDocumentService.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/object/services/DefaultObjectSearchService.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/services/ProjectSemanticDataExportParticipant.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/ExplorerServices.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/tree/DomainTreeRepresentationDescriptionProvider.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/trees/TreeControllerIntegrationTests.java
Labels: pr: to review soon, priority: high

#5517 [5516] Correctly update node style after canceling a connection
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/connector/useConnector.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/handles/ConnectionCreationHandles.tsx
Labels: pr: to review soon, priority: high

#5465 [5457] Fix a rendering issue where the tree filter menu could be partially obscured when a table is opened
  CHANGELOG.adoc
  packages/sirius-web/frontend/sirius-web-application/src/diagrams/DiagramFilter.tsx
  packages/trees/frontend/sirius-components-trees/src/views/TreeFiltersMenu.tsx
Labels: pr: to review later, priority: low

#5537 [5535] Prevent node style from remaining faded after drag-and-drop
  CHANGELOG.adoc
  integration-tests-playwright/playwright/e2e/dnd.spec.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/dropNode/useDropNode.ts
Labels: pr: to review soon, priority: high

#5506 [5222] Fix URL provided by 'Share Project' and 'Share Representation'
  CHANGELOG.adoc
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/EditProjectView.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/navbar/context-menu/EditProjectNavbarContextMenu.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/navbar/context-menu/ShareProjectMenuItem.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/navbar/context-menu/ShareProjectMenuItem.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/navbar/context-menu/ShareProjectModal.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/navbar/context-menu/ShareProjectModal.types.ts
Labels: pr: to review soon, priority: low

#5583 [5582] Trigger fit-to-screen after arrangeAll action in diagrams
  CHANGELOG.adoc
  integration-tests-playwright/playwright/e2e/arrange-all.spec.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/useArrangeAll.ts
Labels: pr: to review soon, priority: high

#5576 [fix] Fix VS Code extension compilation errors
  packages/sirius-web/frontend/sirius-web/src/nodes/EllipseNodeConverter.ts
  vscode-extension/src/view/app/App.tsx
  vscode-extension/src/view/app/nodes/EllipseNodeConverter.ts
Labels: pr: to review soon, priority: high

#5557 [5556] Update label of NewRepresentationArea component's entries
  CHANGELOG.adoc
  packages/sirius-web/frontend/sirius-web-application/src/onboarding/NewRepresentationArea.tsx
Labels: pr: to review soon, priority: high

#5594 [releng] Re-enable the build of the VS Code extension
  .github/workflows/build.yml
Labels: pr: to review soon, priority: low

#5578 [5568] Preserve empty labels to be highlighted
  CHANGELOG.adoc
  integration-tests-cypress/cypress/e2e/project/diagrams/delete-node-with-shortcut.cy.ts
  integration-tests-playwright/playwright/e2e/delete-node.spec.ts
  integration-tests-playwright/playwright/e2e/diagram.spec.ts
  integration-tests-playwright/playwright/e2e/label.spec.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/Label.tsx
Labels: pr: to review soon, priority: high

#5577 [5570] Make sure newly created elements are automatically selected in the Explorer
  CHANGELOG.adoc
  integration-tests-cypress/cypress/e2e/project/explorer/explorer.cy.ts
  packages/browser/frontend/sirius-components-browser/src/modelbrowser/ModelBrowserTreeView.tsx
  packages/selection/frontend/sirius-components-selection/src/SelectionDialogTreeView.tsx
  packages/sirius-web/frontend/sirius-web-application/src/modals/duplicate-object/DuplicateObjectKeyboardShortcut.tsx
  packages/sirius-web/frontend/sirius-web-application/src/modals/duplicate-object/DuplicateObjectKeyboardShortcut.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/explorer/ExplorerView.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/explorer/context-menu-contributions/DocumentTreeItemContextMenuContribution.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/explorer/context-menu-contributions/ObjectTreeItemContextMenuContribution.tsx
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItem.tsx
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItem.types.ts
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItemAction.tsx
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItemAction.types.ts
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItemWithChildren.tsx
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItemWithChildren.types.ts
  packages/trees/frontend/sirius-components-trees/src/treeitems/context-menu/DefaultMenuItem.tsx
  packages/trees/frontend/sirius-components-trees/src/treeitems/context-menu/TreeItemContextMenu.tsx
  packages/trees/frontend/sirius-components-trees/src/treeitems/context-menu/TreeItemContextMenu.types.ts
  packages/trees/frontend/sirius-components-trees/src/treeitems/context-menu/TreeItemContextMenuEntry.types.ts
  packages/trees/frontend/sirius-components-trees/src/trees/Tree.tsx
  packages/trees/frontend/sirius-components-trees/src/trees/Tree.types.ts
  packages/trees/frontend/sirius-components-trees/src/trees/TreeRepresentation.tsx
  packages/trees/frontend/sirius-components-trees/src/views/TreeView.tsx
  packages/trees/frontend/sirius-components-trees/src/views/TreeView.types.ts
Labels: pr: to review soon, priority: high

#5592 [5580] Use parent width for list child label during layout
  CHANGELOG.adoc
  integration-tests-cypress/cypress/e2e/project/diagrams/diagram-list.cy.ts
  integration-tests-playwright/playwright/e2e/list.spec.ts
  integration-tests-playwright/playwright/helpers/PlaywrightNode.ts
  integration-tests-playwright/playwright/resources/diagramList.xml
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/layout.tsx
Labels: pr: to review soon, priority: high
