Repository eclipse-sirius/sirius-web, pull requests merged in 2025-03, with the labels that each got.

#4553 [4534] Used full representation id when retrieve row context menu
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/representation/services/PersistentRepresentationMetadataProvider.java
  packages/sirius-web/backend/sirius-web-tests/src/main/java/org/eclipse/sirius/web/tests/services/representation/RepresentationIdBuilder.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/tables/PapayaTableRowControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/data/PapayaIdentifiers.java
  packages/tables/frontend/sirius-components-tables/src/rows/RowContextMenuContent.tsx
Labels: pr: to review soon, priority: high

#4593 [4469] Remove useless mutations send at the table opening
  CHANGELOG.adoc
  packages/tables/frontend/sirius-components-tables/src/columns/useTableColumnFiltering.ts
  packages/tables/frontend/sirius-components-tables/src/columns/useTableColumnOrdering.ts
  packages/tables/frontend/sirius-components-tables/src/columns/useTableColumnVisibility.ts
  packages/tables/frontend/sirius-components-tables/src/table/TableContent.tsx
  packages/tables/frontend/sirius-components-tables/src/table/useGlobalFilter.ts
Labels: pr: to review soon, priority: high

#4538 [4535] Conserve page size on table filter changes
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/tables/table.cy.ts
  integration-tests/cypress/workbench/Table.ts
  packages/sirius-web/backend/sirius-web-e2e-tests/src/main/java/org/eclipse/sirius/web/e2e/tests/templates/TablePapayaProjectTemplateInitializer.java
  packages/tables/frontend/sirius-components-tables/src/representation/TableRepresentation.tsx
  packages/tables/frontend/sirius-components-tables/src/rows/RowHeader.tsx
  packages/tables/frontend/sirius-components-tables/src/table/CursorBasedPagination.tsx
Labels: pr: to review soon, priority: low

#4662 [4661] Prevent table pagination to be reset on the first page
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/tables/table.cy.ts
  integration-tests/cypress/workbench/Table.ts
  packages/tables/frontend/sirius-components-tables/src/columns/useTableColumnFiltering.ts
  packages/tables/frontend/sirius-components-tables/src/table/CursorBasedPagination.tsx
Labels: pr: to review soon, priority: high

#4621 [releng] Switch to xyflow 12.4.4
  CHANGELOG.adoc
  package-lock.json
  packages/diagrams/frontend/sirius-components-diagrams/package.json
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/layout.tsx
  packages/selection/frontend/sirius-components-selection/package.json
  packages/sirius-web/frontend/sirius-web-application/package.json
  packages/sirius-web/frontend/sirius-web-papaya/package.json
  packages/sirius-web/frontend/sirius-web-view-fork/package.json
  packages/sirius-web/frontend/sirius-web/package.json
  vscode-extension/package.json
Labels: pr: to review soon, priority: high

#4605 [4583] Improve the performance to retrieve if a representation is vie…
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-view-fork/src/main/java/org/eclipse/sirius/web/view/fork/controllers/RepresentationMetadataIsVewBasedDataFetcher.java
  packages/sirius-web/backend/sirius-web-view-fork/src/main/java/org/eclipse/sirius/web/view/fork/dto/GetRepresentationMetadataViewBasedInput.java
  packages/sirius-web/backend/sirius-web-view-fork/src/main/java/org/eclipse/sirius/web/view/fork/dto/GetRepresentationMetadataViewBasedPayload.java
  packages/sirius-web/backend/sirius-web-view-fork/src/main/java/org/eclipse/sirius/web/view/fork/services/GetRepresentationMetadataViewBasedEventHandler.java
Labels: pr: to review soon, priority: low

#4623 [releng] Switch to Turbo 2.4.4
  CHANGELOG.adoc
  package-lock.json
  package.json
Labels: pr: to review soon, priority: low

#4452 [4451] Keep using the same node after a refresh if possible
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx
Labels: pr: to review soon, priority: high

#4576 [4575] Memoize the style of a label
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/Label.tsx
Labels: pr: to review later, priority: low

#4651 [doc] Add shape on support for edges connected to edges
  CHANGELOG.adoc
  doc/iterations/2025.4/add_support_for_edges_connected_to_edges.adoc
Labels: pr: to review later, priority: low

#4647 [doc] Add a shape on rectilinear custom edges
  CHANGELOG.adoc
  doc/iterations/2025.4/force_custom_edges_to_stay_rectilinear.adoc
  doc/iterations/2025.4/images/custom-edges-after-bendpoint-suppression.png
  doc/iterations/2025.4/images/custom-edges-before-bendpoint-suppression.png
  doc/iterations/2025.4/images/custom-edges-intermediate-point-translation.png
  doc/iterations/2025.4/images/custom-edges-new-bendpoints-one-axis.png
  doc/iterations/2025.4/images/custom-edges-new-bendpoints-two-axis.png
  doc/iterations/2025.4/images/custom-edges-point-types.png
Labels: pr: to review soon, priority: low

#4579 [4577] Remove payload from DiagramContext to improve performances
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/contexts/DiagramContext.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/contexts/DiagramContext.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/representation/DiagramRepresentation.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/representation/DiagramSubscriptionProvider.tsx
Labels: pr: to review soon, priority: low

#4671 [cleanup] Fix the graphql type RepresentationDescriptionMetadata
  packages/core/backend/sirius-components-collaborative/src/main/resources/schema/core.graphqls
Labels: pr: to review soon, priority: high

#4640 [4518] Allow createCommit post REST API to amend commit
  .github/workflows/build.yml
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/object/services/EObjectRestDeserializer.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/object/services/EObjectRestSerializer.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/object/services/api/IEObjectRestDeserializer.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/object/services/api/IEObjectRestSerializer.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/data/versioning/controllers/CommitRestController.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/data/versioning/dto/RestDataVersion.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/data/versioning/dto/RestDataVersionRequest.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/data/versioning/handlers/CreateCommitRestEventHandler.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/data/versioning/services/ComposedProjectDataVersioningRestService.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/data/versioning/services/DefaultProjectDataVersiongRestService.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/data/versioning/services/RestDataVersionPayloadSerializer.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/data/versioning/services/api/IDefaultProjectDataVersioningRestService.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/data/versioning/services/api/IProjectDataVersioningRestService.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/data/versioning/services/api/IProjectDataVersioningRestServiceDelegate.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/data/versioning/services/api/IRestDataVersionPayloadSerializerService.java
  packages/sirius-web/backend/sirius-web/pom.xml
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/AbstractIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/RestResponseSerializationCustomizer.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/objects/ObjectRestControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/projects/CommitChangesNoPayloadRestControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/projects/CommitRestControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/projects/RestDataVersionPayloadSerializerTestService.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/rest/RestControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/rest/RestTestsData.java
Labels: pr: to review soon, priority: high

#4591 [doc] Make it easier to invoke the same tool multiple times in a row
  CHANGELOG.adoc
  doc/iterations/2025.4/repeated_tool_invocation.adoc
Labels: pr: to review soon, priority: high

#4649 [doc] Add shape for moving handles
  CHANGELOG.adoc
  doc/iterations/2025.4/add_support_to_move_edge_handle.adoc
Labels: pr: to review later, priority: low

#4517 [doc] ADR to add row filters in table representation
  CHANGELOG.adoc
  doc/adrs/186_add_support_of_row_level_filters_in_tables.adoc
Labels: pr: to review soon, priority: high

#4682 [4678] Add support of virtual rows in tables
  CHANGELOG.adoc
  packages/tables/frontend/sirius-components-tables/src/representation/tableIdProvider.ts
Labels: pr: to review soon, priority: low

#4680 [4679] Remove coupling between TreeView and useSelection
  CHANGELOG.adoc
  packages/browser/frontend/sirius-components-browser/src/modelbrowser/ModelBrowserTreeView.tsx
  packages/browser/frontend/sirius-components-browser/src/modelbrowser/ModelBrowserTreeView.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/drop/useDrop.tsx
  packages/forms/frontend/sirius-components-widget-reference/src/ReferencePropertySection.tsx
  packages/forms/frontend/sirius-components-widget-reference/src/modals/BrowseModal.tsx
  packages/forms/frontend/sirius-components-widget-reference/src/modals/CreateModal.tsx
  packages/forms/frontend/sirius-components-widget-reference/src/modals/TransferModal.tsx
  packages/forms/frontend/sirius-components-widget-reference/src/modals/TransferModal.types.ts
  packages/portals/frontend/sirius-components-portals/src/representations/PortalRepresentation.tsx
  packages/selection/frontend/sirius-components-selection/src/SelectionDialog.tsx
  packages/selection/frontend/sirius-components-selection/src/SelectionDialog.types.ts
  packages/selection/frontend/sirius-components-selection/src/SelectionDialogTreeView.tsx
  packages/selection/frontend/sirius-components-selection/src/SelectionDialogTreeView.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/explorer/ExplorerView.tsx
  packages/trees/frontend/sirius-components-trees/src/index.ts
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItem.tsx
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItem.types.ts
  packages/trees/frontend/sirius-components-trees/src/trees/Tree.tsx
  packages/trees/frontend/sirius-components-trees/src/trees/Tree.types.ts
  packages/trees/frontend/sirius-components-trees/src/trees/TreeRepresentation.tsx
  packages/trees/frontend/sirius-components-trees/src/views/TreeView.tsx
  packages/trees/frontend/sirius-components-trees/src/views/TreeView.types.ts
  packages/trees/frontend/sirius-components-trees/src/views/useExpandAllTreePath.ts
  packages/trees/frontend/sirius-components-trees/src/views/useExpandAllTreePath.types.ts
  packages/trees/frontend/sirius-components-trees/src/views/useTreePath.ts
  packages/trees/frontend/sirius-components-trees/src/views/useTreePath.types.ts
Labels: pr: to review soon, priority: low

#4690 [4693] Fix an issue with nodes not correctly hidden on diagram represe…
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx
Labels: pr: to review soon, priority: high

#4658 [4657] Resize node when a compartment is hidden
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/ListNodeLayoutHandler.ts
Labels: pr: to review later, priority: low

#4695 [4464] Reduce usage of SelectionEntry#kind
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/selection/useDiagramSelection.ts
  packages/portals/frontend/sirius-components-portals/src/representations/PortalRepresentation.tsx
Labels: pr: to review soon, priority: high

#4697 [4464] Remove SelectionEntry#kind
  CHANGELOG.adoc
  packages/core/frontend/sirius-components-core/src/selection/SelectionContext.types.ts
  packages/core/frontend/sirius-components-core/src/workbench/Workbench.tsx
  packages/core/frontend/sirius-components-omnibox/src/OmniboxObjectList.tsx
  packages/core/frontend/sirius-components-omnibox/src/useExecuteOmniboxCommand.ts
  packages/deck/frontend/sirius-components-deck/src/representation/DeckRepresentation.tsx
  packages/deck/frontend/sirius-components-deck/src/utils/deckGQLHelper.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/connector/ConnectorContextualMenu.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/connector/ConnectorContextualMenu.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/usePalette.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/usePalette.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/selection/useDiagramSelection.ts
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/Group.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/PageList.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/ToolbarActionWidget.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/WidgetEntry.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/ListPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/TreePropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/__tests__/TreePropertySection.test.tsx
  packages/forms/frontend/sirius-components-widget-reference/src/ReferencePropertySection.tsx
  packages/forms/frontend/sirius-components-widget-reference/src/modals/CreateModal.tsx
  packages/forms/frontend/sirius-components-widget-reference/src/modals/CreateModalMachine.ts
  packages/gantt/frontend/sirius-components-gantt/src/representation/Gantt.tsx
  packages/sirius-web/frontend/sirius-web-application/src/modals/new-object/NewObjectModal.tsx
  packages/sirius-web/frontend/sirius-web-application/src/modals/new-object/NewObjectModal.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/modals/new-representation/NewRepresentationModal.tsx
  packages/sirius-web/frontend/sirius-web-application/src/modals/new-representation/NewRepresentationModal.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/modals/new-representation/NewRepresentationModalMachine.ts
  packages/sirius-web/frontend/sirius-web-application/src/modals/new-root-object/NewRootObjectModal.tsx
  packages/sirius-web/frontend/sirius-web-application/src/modals/new-root-object/NewRootObjectModal.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/onboarding/NewRepresentationArea.tsx
  packages/sirius-web/frontend/sirius-web-application/src/onboarding/RepresentationsArea.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/EditProjectView.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/explorer/ExplorerView.tsx
  packages/tables/frontend/sirius-components-tables/src/cells/CheckboxCell.tsx
  packages/tables/frontend/sirius-components-tables/src/cells/IconLabelCell.tsx
  packages/tables/frontend/sirius-components-tables/src/cells/MultiSelectCell.tsx
  packages/tables/frontend/sirius-components-tables/src/cells/SelectCell.tsx
  packages/tables/frontend/sirius-components-tables/src/cells/TextareaCell.tsx
  packages/tables/frontend/sirius-components-tables/src/cells/TextfieldCell.tsx
  packages/tables/frontend/sirius-components-tables/src/table/useTableColumns.tsx
  packages/trees/frontend/sirius-components-trees/src/trees/TreeRepresentation.tsx
  vscode-extension/src/view/app/App.tsx
Labels: pr: to review soon, priority: high

#4692 [4691] Set the local diagram's state even when in read-only
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx
Labels: pr: to review soon, priority: high

#3798 [3740] Add support for object duplication from Explorer
  CHANGELOG.adoc
  doc/iterations/2024.9/add_support_for_object_duplication.adoc
  doc/screenshots/duplicationDialog.png
  integration-tests/cypress/e2e/project/explorer/explorer-duplicate.cy.ts
  packages/browser/frontend/sirius-components-browser/src/modelbrowser/ModelBrowserTreeView.tsx
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/utils/SiriusEMFCopier.java
  packages/forms/frontend/sirius-components-widget-reference/src/components/FilterableSortableList.tsx
  packages/forms/frontend/sirius-components-widget-reference/src/modals/CreateModal.tsx
  packages/forms/frontend/sirius-components-widget-reference/src/modals/TransferModal.tsx
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/controllers/EditingContextContainmentFeatureNamesDataFetcher.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/controllers/MutationDuplicateObjectDataFetcher.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/dto/DuplicateObjectInput.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/dto/DuplicateObjectSuccessPayload.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/dto/EditingContextContainmentFeatureNamesInput.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/dto/EditingContextContainmentFeatureNamesPayload.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/ContainmentFeatureNamesEventHandler.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/DuplicateObjectEventHandler.java
  packages/sirius-web/backend/sirius-web-application/src/main/resources/schema/duplicateobject.graphqls
  packages/sirius-web/backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/services/api/IMessageService.java
  packages/sirius-web/backend/sirius-web-infrastructure/src/main/java/org/eclipse/sirius/web/infrastructure/configuration/i18n/MessageService.java
  packages/sirius-web/backend/sirius-web-infrastructure/src/main/resources/i18n/messages.properties
  packages/sirius-web/backend/sirius-web-tests/src/main/java/org/eclipse/sirius/web/tests/graphql/ContainmentFeatureNamesQueryRunner.java
  packages/sirius-web/backend/sirius-web-tests/src/main/java/org/eclipse/sirius/web/tests/graphql/DuplicateObjectMutationRunner.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/objects/ObjectDuplicationControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/data/StudioIdentifiers.java
  packages/sirius-web/frontend/sirius-web-application/src/modals/duplicate-object/DuplicateObjectKeyboardShortcut.tsx
  packages/sirius-web/frontend/sirius-web-application/src/modals/duplicate-object/DuplicateObjectKeyboardShortcut.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/modals/duplicate-object/DuplicateObjectModal.tsx
  packages/sirius-web/frontend/sirius-web-application/src/modals/duplicate-object/DuplicateObjectModal.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/modals/duplicate-object/useContainmentFeatureNames.ts
  packages/sirius-web/frontend/sirius-web-application/src/modals/duplicate-object/useContainmentFeatureNames.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/modals/duplicate-object/useDuplicateObject.ts
  packages/sirius-web/frontend/sirius-web-application/src/modals/duplicate-object/useDuplicateObject.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/ObjectTreeItemContextMenuContribution.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/explorer/ExplorerView.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/explorer/ExplorerView.types.ts
  scripts/check-coverage.jsh
Labels: pr: to review soon, priority: high

#4205 [4204] Prevent the changeDescriptionSink from crashing because of the related representation refresh
  CHANGELOG.adoc
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/EditingContextEventProcessor.java
  packages/emf/backend/sirius-components-interpreter/src/main/java/org/eclipse/sirius/components/interpreter/Result.java
Labels: pr: to review soon, priority: low

#4207 [4206] Improve performance of diagram viewport change
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/useArrangeAll.ts
Labels: pr: to review later, priority: low

#4209 [4208] Improve performance of details view rendering on selection change
  CHANGELOG.adoc
  packages/forms/frontend/sirius-components-forms/src/views/FormBasedView.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/details/DetailsView.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/details/DetailsView.types.ts
Labels: pr: to review later, priority: low

#4717 [fix] Fix an issue with some papaya icons having a wrong path
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/classdiagram/tools/classnode/NewAttributeToolProvider.java
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/classdiagram/tools/classnode/NewOperationToolProvider.java
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/classdiagram/tools/diagram/ImportExistingTypesToolProvider.java
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/classdiagram/tools/diagram/NewClassToolProvider.java
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/classdiagram/tools/diagram/NewEnumToolProvider.java
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/classdiagram/tools/diagram/NewInterfaceToolProvider.java
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/classdiagram/tools/diagram/NewRecordToolProvider.java
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/classdiagram/tools/interfacenode/ImportAllInterfaceSubtypesNodeToolProvider.java
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/classdiagram/tools/interfacenode/ImportInterfaceImplementationsNodeToolProvider.java
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/componentdiagram/tools/CreateComponentNodeToolProvider.java
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/componentdiagram/tools/ImportAllDependenciesNodeToolProvider.java
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/componentdiagram/tools/ImportDependenciesNodeToolProvider.java
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/table/PackageTableRowContextMenuProvider.java
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/views/details/ComponentPageDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/views/details/PackagePageDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/views/details/ProjectPageDescriptionProvider.java
Labels: pr: to review soon, priority: high

#4659 [doc] Add ADR on support for edges connected to edges
  CHANGELOG.adoc
  doc/adrs/188_add_support_for_edges_on_edges.adoc
Labels: pr: to review soon, priority: high

#4705 [4704] Stop zooming in when selecting an element
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/selection/useDiagramSelection.ts
Labels: pr: to review soon, priority: high

#4494 [4493] Add an user indicator when a representation is loading
  CHANGELOG.adoc
  packages/core/frontend/sirius-components-core/src/index.ts
  packages/core/frontend/sirius-components-core/src/progress/RepresentationLoadingIndicator.tsx
  packages/deck/frontend/sirius-components-deck/src/representation/DeckRepresentation.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/usePalette.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/representation/DiagramSubscriptionProvider.tsx
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FormDescriptionEditorRepresentation.tsx
  packages/forms/frontend/sirius-components-forms/src/groups/Group.tsx
  packages/forms/frontend/sirius-components-forms/src/representations/FormRepresentation.tsx
  packages/gantt/frontend/sirius-components-gantt/src/representation/GanttRepresentation.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/details/DetailsView.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/explorer/ExplorerView.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/related-elements/RelatedElementsView.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/representations/RepresentationsView.tsx
  packages/tables/frontend/sirius-components-tables/src/representation/TableRepresentation.tsx
  packages/trees/frontend/sirius-components-trees/src/trees/TreeRepresentation.tsx
Labels: pr: to review later, priority: low

#4698 [2807] Add an experimental version of the SVG Export
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/index.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/Label.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/MarkerDefinitions.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/node/FreeFormNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/node/IconLabelNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/node/ListNode.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/panel/ExportImageButton.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/panel/experimental-svg-export/ImageElementSVGExportHandler.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/panel/experimental-svg-export/RectElementSVGExportHandler.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/panel/experimental-svg-export/SVGDefsElementSVGExportHandler.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/panel/experimental-svg-export/SVGElementSVGExportHandler.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/panel/experimental-svg-export/SVGExportEngine.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/panel/experimental-svg-export/SVGExportEngine.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/panel/experimental-svg-export/SVGExportHandlerExtensionPoints.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/panel/experimental-svg-export/TextElementSVGExportHandler.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/panel/experimental-svg-export/useExperimentalSvgExport.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/panel/experimental-svg-export/useExperimentalSvgExport.types.ts
  packages/sirius-web/frontend/sirius-web/src/nodes/EllipseNode.tsx
  vscode-extension/src/view/app/nodes/EllipseNode.tsx
Labels: pr: to review soon, priority: high

#4715 [4714] Contribute default routes using the router extension point
  CHANGELOG.adoc
  packages/sirius-web/frontend/sirius-web-application/src/extension/DefaultExtensionRegistry.tsx
  packages/sirius-web/frontend/sirius-web-application/src/index.ts
  packages/sirius-web/frontend/sirius-web-application/src/router/Router.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/library-browser/LibraryBrowserView.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/library-browser/LibraryBrowserView.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/views/project-browser/ProjectBrowserView.tsx
Labels: pr: to review soon, priority: high

#4599 [doc] Add shape about new manage visibility menu
  CHANGELOG.adoc
  doc/adrs/189_add_actions_on_diagram_nodes.adoc
  doc/iterations/2025.4/add_visibility_tool_on_diagram_nodes.adoc
  doc/iterations/2025.4/images/manage_visibility_menu.png
  doc/iterations/2025.4/images/manage_visibility_selectall_unselectall_valued_content.png
Labels: pr: to review later, priority: low

#4712 [4706] Enable backend rendering of edges that have another edge as so…
  CHANGELOG.adoc
  packages/compatibility/backend/sirius-components-compatibility-emf/src/test/java/org/eclipse/sirius/components/compatibility/emf/compatibility/diagrams/EdgeMappingConverterTests.java
  packages/compatibility/backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/diagrams/EdgeMappingConverter.java
  packages/compatibility/backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/diagrams/RelationBasedSemanticElementsProvider.java
  packages/compatibility/backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/services/diagrams/CompatibilityPaletteProvider.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/test/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/InvokeSingleClickOnDiagramElementToolEventHandlerTests.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/test/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/TestDiagramDescriptionBuilder.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/EdgeComponent.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/description/EdgeDescription.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/renderer/DiagramRenderingCache.java
  packages/diagrams/backend/sirius-components-diagrams/src/test/java/org/eclipse/sirius/components/diagrams/renderer/DiagramElementChangeVisibilityTests.java
  packages/diagrams/backend/sirius-components-diagrams/src/test/java/org/eclipse/sirius/components/diagrams/renderer/DiagramRendererEdgeTests.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/PaletteDefaultToolsProvider.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/RelationBasedSemanticElementsProvider.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/TargetProvider.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewDiagramDescriptionConverter.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewDiagramDescriptionConverterContext.java
  packages/view/backend/sirius-components-view-emf/src/test/java/org/eclipse/sirius/components/view/emf/diagram/ViewPaletteProviderTests.java
Labels: pr: to review soon, priority: high

#4739 [doc] Add a shape for user diagram appearance view
  CHANGELOG.adoc
  doc/iterations/2025.4/add_support_to_manage_the_appearance_of_nodes_in_the_palette.adoc
  doc/iterations/2025.4/images/diagram-appearance-palette-color-picker.png
  doc/iterations/2025.4/images/diagram-appearance-palette-details.png
  doc/iterations/2025.4/images/diagram-appearance-palette-entry.png
  doc/iterations/2025.4/images/diagram-appearance-setting-color-library-quick-access.png
  doc/iterations/2025.4/images/diagram-appearance-setting-color-library.png
Labels: pr: to review soon, priority: low

#4734 [doc] Add an ADR to lower the coupling in services used to convert view based descriptions
  CHANGELOG.adoc
  doc/adrs/190_update_the_template_used_to_convert_elements_of_the_DSL.adoc
Labels: pr: to review soon, priority: high

#4740 [4736] Restore correct border node positioning
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/layoutBorderNodes.ts
Labels: pr: to review soon, priority: high

#4754 [4753] Remove default table cell editing mechanism
  CHANGELOG.adoc
  packages/tables/frontend/sirius-components-tables/src/table/TableContent.tsx
Labels: pr: to review soon, priority: high

#4755 [fix] Export DuplicateObjectModal for downstream applications to use
  packages/sirius-web/frontend/sirius-web-application/src/index.ts
Labels: pr: to review soon, priority: low
