Repository eclipse-sirius/sirius-web, pull requests merged in 2025-05, with the labels that each got.

#4862 [4861] Keep the specified position of the handle when creating an edge
  CHANGELOG.adoc
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/dto/ReferencePosition.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/providers/GenericDiagramToolReferencePositionProvider.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/resources/schema/diagram.graphqls
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/convertDiagram.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/convertHandles.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/graphql/subscription/diagramEventSubscription.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/graphql/subscription/diagramEventSubscription.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/connector/ConnectorContextualMenu.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/EdgeLayout.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/EdgeLayout.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/handles/ConnectionHandles.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/handles/ConnectionHandles.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/handles/useHandleChange.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/handles/useHandlesLayout.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/UpdateHandleFromReferencePosition.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/layoutHandles.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/useLayout.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/useSynchronizeLayoutData.ts
Labels: pr: to review later, priority: low

#4884 [4877] Change handle position after dragging first/last segments on n…
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/rectilinear-edge/RectilinearEdgeCalculation.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/rectilinear-edge/useTemporaryLines.ts
Labels: pr: to review soon, priority: high

#4897 [4879] Prevents an edge segment from being parallel to node borders
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/rectilinear-edge/MultiLabelRectilinearEditableEdge.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/rectilinear-edge/RectilinearEdgeCalculation.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/rectilinear-edge/useBendingPoints.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/layoutParams.ts
Labels: pr: to review soon, priority: high

#4910 [4909] Move CreateForkedStudioMutationRunner to sirius-web-tests
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-tests/pom.xml
  packages/sirius-web/backend/sirius-web-tests/src/main/java/org/eclipse/sirius/web/tests/services/fork/CreateForkedStudioMutationRunner.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/studiofork/TestCreateForkedStudio.java
Labels: pr: to review later, priority: low

#4892 [releng] Export sirius-web tests in a test-jar for downstream products
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web/pom.xml
Labels: pr: to review soon, priority: low

#4888 [4887] Add DiagramNodeActionExtensionPoint
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/index.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/actions/Action.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/actions/DiagramNodeActionExtensionPoint.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/actions/DiagramNodeActionExtensionPoint.types.ts
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/services/nodeaction/PapayaShowLabelNodeAction.java
  packages/sirius-web/backend/sirius-web-table/src/main/java/org/eclipse/sirius/web/table/services/CreateForkedStudioService.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/ActionControllerTests.java
  packages/sirius-web/frontend/sirius-web-papaya/src/PapayaExtensionRegistry.tsx
  packages/sirius-web/frontend/sirius-web-papaya/src/nodeactions/PapayaComponentLabelDetailNodeActionContribution.tsx
  packages/sirius-web/frontend/sirius-web/src/extension/SiriusWebExtensionRegistryMergerStrategy.tsx
Labels: pr: to review soon, priority: high

#4848 [4840] Reduce the amount of data fetched from the DB on project opening
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/StudioCapableEditingContextPredicate.java
  packages/sirius-web/backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/boundedcontexts/semanticdata/repositories/ISemanticDataRepository.java
  packages/sirius-web/backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/boundedcontexts/semanticdata/services/SemanticDataSearchService.java
  packages/sirius-web/backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/boundedcontexts/semanticdata/services/api/ISemanticDataSearchService.java
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/services/PapayaCapableEditingContextPredicate.java
Labels: pr: to review later, priority: low

#4898 [releng] Switch to Sirius EMF JSON 2.5.0
  CHANGELOG.adoc
  packages/emf/backend/sirius-components-emf/pom.xml
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/services/EObjectIDManager.java
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/services/IDAdapter.java
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/services/JSONResourceFactory.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/services/EObjectRandomIDManager.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/projects/ProjectDownloadControllerIntegrationTests.java
Labels: pr: to review soon, priority: high

#4903 [doc] Add an ADR to improve table representation lifecycle
  CHANGELOG.adoc
  doc/adrs/192_improve_table_lifecycle.adoc
Labels: pr: to review soon, priority: high

#4871 [4866] Disable the "last tool" shortcut in the palette if is not available in the current state
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/Palette.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/tool-list-item/ToolListItem.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/tool-list-item/ToolListItem.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/tool-list/PaletteToolList.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/tool-list/PaletteToolSectionList.tsx
Labels: pr: to review soon, priority: low

#4920 [doc] Update some documentation
  packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/api/IIdentityService.java
  packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/api/IIdentityServiceDelegate.java
  packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/api/IInput.java
  packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/api/IObjectService.java
  packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/api/IPayload.java
  packages/core/backend/sirius-components-events/src/main/java/org/eclipse/sirius/components/events/ICause.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/renderer/DiagramRenderer.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/tools/ITool.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/tools/Palette.java
  packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/tools/ToolSection.java
  packages/forms/backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/renderer/FormRenderer.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/AbstractIntegrationTests.java
Labels: pr: to review soon, priority: high

#4922 [cleanup] Remove the unused ITreeCreationService
  packages/trees/backend/sirius-components-collaborative-trees/src/main/java/org/eclipse/sirius/components/collaborative/trees/api/ITreeCreationService.java
Labels: pr: to review later, priority: low

#4923 [test] Improve the management of the Spring test context caching to speed up tests
  doc/kb/001_removal_of_the_DirtiesContext_annotation.adoc
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/AbstractIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/configurationproperties/StudioDisabledTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/configurationproperties/ValidationEnabledTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/libraries/LibraryImportByCopyControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/libraries/LibraryImportByReferenceControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/resources/spring.properties
Labels: pr: to review soon, priority: high

#4934 [4931] Add updateTargetObjectId to IRepresentationMetadataUpdateService
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/boundedcontexts/representationdata/RepresentationMetadata.java
  packages/sirius-web/backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/boundedcontexts/representationdata/services/RepresentationMetadataUpdateService.java
  packages/sirius-web/backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/boundedcontexts/representationdata/services/api/IRepresentationMetadataUpdateService.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/data/TestIdentifiers.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/domain/DomainEventsTest.java
Labels: pr: to review soon, priority: high

#4937 [4933] Update the MigrationData accessible via ResourceMetadataAdapter
  CHANGELOG.adoc
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/ResourceMetadataAdapter.java
  packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/migration/MigrationService.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/DefaultDomainResourceProvider.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/DefaultViewResourceProvider.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/StudioStereotypeHandler.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/migration/DiagramLabelStyleBorderSizeMigrationParticipantTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/migration/MigrationParticipantOrderTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/migration/NodeDescriptionLabelExpressionMigrationParticipantTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/migration/NodeStyleDescriptionColorMigrationParticipantTests.java
  packages/starters/backend/sirius-components-flow-starter/src/main/java/org/eclipse/sirius/components/flow/starter/services/EmptyFlowProvider.java
  packages/starters/backend/sirius-components-flow-starter/src/main/java/org/eclipse/sirius/components/flow/starter/services/RobotFlowProvider.java
Labels: pr: to review soon, priority: high

#4869 [doc] Add an ADR about using nested route and nested router
  CHANGELOG.adoc
  doc/adrs/193_leverage_react_router_for_nested_routes.adoc
Labels: pr: to review soon, priority: low

#4870 [releng] Switch to xyflow 12.6.0
  CHANGELOG.adoc
  package-lock.json
  packages/diagrams/frontend/sirius-components-diagrams/package.json
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/selection/useDiagramSelection.ts
  packages/selection/frontend/sirius-components-selection/package.json
  packages/sirius-web/frontend/sirius-web-application/package.json
  packages/sirius-web/frontend/sirius-web-papaya/package.json
  packages/sirius-web/frontend/sirius-web-view-fork/package.json
  packages/sirius-web/frontend/sirius-web/package.json
  vscode-extension/package.json
Labels: pr: to review soon, priority: low

#4947 [4946] Add loading indicator in library publish/import/update dialogs
  CHANGELOG.adoc
  packages/sirius-web/frontend/sirius-web-application/src/libraries/PublishLibraryDialog.tsx
  packages/sirius-web/frontend/sirius-web-application/src/omnibox/ImportLibraryDialog.tsx
  packages/sirius-web/frontend/sirius-web-application/src/omnibox/ImportLibraryDialog.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/omnibox/LibrariesImportTable.tsx
  packages/sirius-web/frontend/sirius-web-application/src/omnibox/LibrariesImportTable.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/explorer/context-menu-contributions/update-library/UpdateLibraryModal.tsx
Labels: pr: to review soon, priority: high

#4853 [4850] Improve handles position when an edge is connected to another
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/ConnectionLine.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/EdgeLayout.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/EdgeLayout.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/handles/useHandleChange.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/node/EdgeAnchorNode.tsx
Labels: pr: to review later, priority: low

#4949 [4731] Ensure that the project context menu is closed when an action is triggered
  CHANGELOG.adoc
  packages/sirius-web/frontend/sirius-web-application/src/views/project-browser/list-projects-area/ProjectActionButton.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/project-browser/list-projects-area/ProjectActionButton.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/views/project-browser/list-projects-area/ProjectDownloadMenuItemExtension.tsx
Labels: pr: to review soon, priority: low

#4930 [fix] Add missing frontend dependencies
  package-lock.json
  packages/sirius-web/frontend/sirius-web/package.json
Labels: pr: to review soon, priority: high

#4914 [4831] Fix the computation of the previous / next page and the ordering of the projects in the project browser
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/pagination/services/LimitProvider.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/pagination/services/api/ILimitProvider.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/controllers/ViewerProjectsDataFetcher.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/services/ProjectApplicationService.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/services/api/IProjectApplicationService.java
  packages/sirius-web/backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/boundedcontexts/project/repositories/ProjectSearchRepositoryDelegate.java
  packages/sirius-web/backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/boundedcontexts/project/services/ProjectSearchService.java
  packages/sirius-web/backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/boundedcontexts/project/services/api/IProjectSearchService.java
  packages/sirius-web/backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/pagination/Window.java
  packages/sirius-web/backend/sirius-web-tests-data/src/main/resources/sirius-web-scripts/projects-order.sql
  packages/sirius-web/backend/sirius-web-tests/src/main/java/org/eclipse/sirius/web/tests/graphql/ProjectsQueryRunner.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/projects/ProjectControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/projects/ProjectPaginationIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/projects/ProjectRestControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/data/StudioIdentifiers.java
Labels: pr: to review soon, priority: high

#4959 [4958] Fix state access in tree-related useEffect
  CHANGELOG.adoc
  packages/browser/frontend/sirius-components-browser/src/modelbrowser/ModelBrowserTreeView.tsx
  packages/selection/frontend/sirius-components-selection/src/SelectionDialogTreeView.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/explorer/ExplorerView.tsx
  packages/trees/frontend/sirius-components-trees/src/trees/TreeRepresentation.tsx
Labels: pr: to review soon, priority: low

#4960 [4102] Reduce the number of database queries when rendering a Tree/Explorer
  CHANGELOG.adoc
  packages/core/backend/sirius-components-representations/src/main/java/org/eclipse/sirius/components/representations/IRepresentationRenderVariableCustomizer.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/representations/DomainExplorerServices.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/representations/DomainViewTreeDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/ExplorerChildrenProvider.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/ExplorerDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/ExplorerRenderVariablesCustomizer.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/ExplorerServices.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/api/IExplorerServices.java
  packages/trees/backend/sirius-components-collaborative-trees/src/main/java/org/eclipse/sirius/components/collaborative/trees/TreeService.java
  packages/trees/backend/sirius-components-collaborative-trees/src/main/java/org/eclipse/sirius/components/collaborative/trees/handlers/DefaultExpandAllTreePathHandler.java
  packages/trees/backend/sirius-components-collaborative-trees/src/test/java/org/eclipse/sirius/components/collaborative/trees/architecture/handlers/DefaultExpandAllTreePathHandlerTests.java
Labels: pr: to review soon, priority: high

#4981 [doc] Add a shape and ADR to let specifier control the workbench views available
  doc/adrs/195_control_the_views_available_in_a_workbench.adoc
  doc/iterations/2025.6/control_the_views_available_in_a_workbench.adoc
Labels: pr: to review soon, priority: high

#4969 [4968] Remove auto-generated tool Delete from the diagram for unsynch…
  CHANGELOG.adoc
  integration-tests/cypress/support/serverCommands.js
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/api/DiagramImageConstants.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/dto/DeleteFromDiagramInput.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/dto/DeletionPolicy.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/DeleteFromDiagramEventHandler.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/resources/schema/diagram.graphqls
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/test/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/DeleteFromDiagramEventHandlerTests.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/test/java/org/eclipse/sirius/components/collaborative/diagrams/providers/GenericDiagramToolReferencePositionProviderTests.java
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/delete/useDiagramDelete.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/tools/useDelete.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/tools/useDelete.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/tools/useInvokePaletteTool.tsx
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/migration/participants/NodePaletteDeleteFromDiagramMigrationParticipant.java
  packages/sirius-web/backend/sirius-web-tests-data/src/main/resources/sirius-web-scripts/migration.sql
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/data/MigrationIdentifiers.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/migration/NodePaletteDeleteFromDiagramMigrationParticipantTests.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/PaletteDefaultToolsProvider.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewDiagramDescriptionConverter.java
Labels: pr: to review soon, priority: high

#4977 [fix] manage visibility modal now shows hidden element as unchecked
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/actions/visibility/ManageVisibilityModalListItems.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/actions/visibility/ManageVisibilityNodeAction.tsx
Labels: pr: to review soon, priority: high
