Repository eclipse-sirius/sirius-web, pull requests merged in 2025-08, with the labels that each got.

#5278 [5275] Take the deletion of a representation into account in portal
  CHANGELOG.adoc
  packages/portals/backend/sirius-components-collaborative-portals/src/main/java/org/eclipse/sirius/components/collaborative/portals/PortalEventProcessor.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/portal/PortalControllerIntegrationTests.java
  packages/trees/backend/sirius-components-trees-tests/src/main/java/org/eclipse/sirius/components/trees/tests/graphql/DeleteTreeItemMutationRunner.java
Labels: pr: to review soon, priority: high

#5281 [enh] Add a missing capability for project settings tab
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/capability/SiriusWebCapabilities.java
  packages/sirius-web/backend/sirius-web-e2e-tests/src/main/java/org/eclipse/sirius/web/e2e/tests/capabilities/DisableProjectSettingsTabsViewCapabilityVoter.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/capabilities/ProjectCapabilitiesControllerTests.java
Labels: pr: to review soon, priority: high

#5314 [fix] Correctly type the state used by ConnectionLine component
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/ConnectionLine.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/ConnectionLine.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/node/FreeFormNode.tsx
Labels: pr: to review soon, priority: high

#5337 [5335] Fix the missing libraries menu in the navigation bar menu
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/boundedcontexts/project/services/ProjectSearchService.java
  packages/sirius-web/backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/boundedcontexts/project/services/api/IProjectSearchService.java
  packages/sirius-web/frontend/sirius-web-application/src/extension/DefaultExtensionRegistry.tsx
Labels: pr: to review soon, priority: high

#5322 [5321] Add missing variables to ViewPaletteProvider
  CHANGELOG.adoc
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/api/IPaletteProvider.java
  packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/GetPaletteEventHandler.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewPaletteProvider.java
  packages/view/backend/sirius-components-view-emf/src/test/java/org/eclipse/sirius/components/view/emf/diagram/ViewPaletteProviderTests.java
Labels: pr: to review soon, priority: high

#5232 [doc] Add shape and ADR for multiple query language support
  CHANGELOG.adoc
  doc/adrs/203_add_support_for_multiple_query_interpreters.adoc
  doc/iterations/2025.8/add_support_for_multiple_query_languages.adoc
Labels: pr: to review soon, priority: high

#5345 [5343] Add fallback to IRepresentationMetadataProviders in RepresentationApplicationService
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/representation/services/RepresentationApplicationService.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/representations/RepresentationControllerIntegrationTests.java
Labels: pr: to review soon, priority: low

#5347 [cleanup] Stop logging NumberFormatException in Result.asInt()
  packages/emf/backend/sirius-components-interpreter/src/main/java/org/eclipse/sirius/components/interpreter/Result.java
Labels: pr: to review later, priority: low

#5346 [5341] Add support for project list and view capabilities
  CHANGELOG.adoc
  doc/reference/capabilities.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/capability/DemoCapabilityVoter.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/capability/SiriusWebCapabilities.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/capability/controllers/ProjectsCapabilitiesCanListDataFetcher.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/controllers/ViewerProjectDataFetcher.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/controllers/ViewerProjectsDataFetcher.java
  packages/sirius-web/backend/sirius-web-application/src/main/resources/schema/capabilities.graphqls
  packages/sirius-web/frontend/sirius-web-application/src/extension/DefaultExtensionRegistry.tsx
  packages/sirius-web/frontend/sirius-web-application/src/navigationBar/NavigationBarMenu.tsx
  packages/sirius-web/frontend/sirius-web-application/src/viewer/ViewerContext.tsx
  packages/sirius-web/frontend/sirius-web-application/src/viewer/useViewer.fragment.ts
  packages/sirius-web/frontend/sirius-web-application/src/viewer/useViewer.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/views/project-browser/ProjectBrowserView.tsx
Labels: pr: to review soon, priority: high

#5364 [doc] Mention that Tables now support checkbox cell widgets
  doc/specifier/representation-table.adoc
Labels: pr: to review later, priority: low

#5365 [releng] Use a distinct name for the diagram image server Docker image
  .github/workflows/build.yml
Labels: pr: to review soon, priority: high

#5372 [5277] Fix find all projects to include the nature
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/boundedcontexts/project/repositories/ProjectSearchRepositoryDelegate.java
  packages/sirius-web/backend/sirius-web-tests/src/main/java/org/eclipse/sirius/web/tests/graphql/ProjectsQueryRunner.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/projects/ProjectControllerIntegrationTests.java
Labels: pr: to review soon, priority: high

#5329 [5325] Add support for capability check on Graphql and controllers
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/controllers/MutationRenameProjectDataFetcher.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/controllers/MutationUploadProjectDataFetcher.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/controllers/ProjectDownloadController.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/capabilities/ProjectCapabilitiesControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/capabilities/ViewerCapabilitiesControllerTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/libraries/LibraryControllerWithDemoProfileIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/projects/ProjectControllerWithDemoProfileIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/projects/ProjectTemplateControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/projects/ProjectTemplateControllerWithDemoProfileIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/capabilities/DisableProjectsUploadCapabilityVoter.java
Labels: pr: to review soon, priority: high

#5385 [releng] Switch to Spring Boot 3.5.5
  CHANGELOG.adoc
  packages/releng/backend/sirius-web-parent/pom.xml
Labels: pr: to review soon, priority: low

#5355 [5354] Add unicode support for direct edit input
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/direct-edit/useDiagramDirectEdit.tsx
  packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItem.tsx
Labels: pr: to review soon, priority: high

#5353 [5352] Fix tooltips for disabled buttons
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/panel/ArrangeAllButton.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/panel/DiagramPanel.tsx
Labels: pr: to review later, priority: low

#5383 [5351] Use borderColor for list node style and connectionLineActiveNo…
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/ListNodeConverter.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/node/ListNode.tsx
Labels: pr: to review soon, priority: high

#5397 [fix] Fix flaky library tests
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/libraries/LibraryControllerWithDemoProfileIntegrationTests.java
Labels: pr: to review soon, priority: high

#5265 [doc] Add shape and ADR for exporting query result
  CHANGELOG.adoc
  doc/adrs/205_add_support_for_exporting_query_result.adoc
  doc/iterations/2025.10/add_support_for_exporting_query_result.adoc
  doc/iterations/2025.10/images/query-view-with-export-button.png
Labels: pr: to review soon, priority: high

#5094 [5093] Remove state machine from TextfieldPropertySection
  CHANGELOG.adoc
  integration-tests/cypress/e2e/project/details/details.cy.ts
  integration-tests/cypress/e2e/project/details/textfield-auto-completion.cy.ts
  integration-tests/cypress/workbench/Explorer.ts
  packages/forms/frontend/sirius-components-forms/src/propertysections/ProposalsList.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/TextfieldPropertySection.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/TextfieldPropertySection.types.ts
  packages/forms/frontend/sirius-components-forms/src/propertysections/TextfieldPropertySectionMachine.ts
Labels: pr: to review later, priority: low

#5389 [5384] Add support for uploading read-only documents
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/controllers/MutationUploadDocumentDataFetcher.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/dto/UploadDocumentInput.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/services/UploadDocumentEventHandler.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/services/UploadFileLoader.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/services/api/IUploadFileLoader.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/services/ProjectImporter.java
  packages/sirius-web/backend/sirius-web-application/src/main/resources/schema/document.graphqls
  packages/sirius-web/backend/sirius-web-tests/src/main/java/org/eclipse/sirius/web/tests/graphql/UploadDocumentMutationRunner.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/documents/DocumentControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/migration/DiagramLabelStyleBorderSizeMigrationParticipantTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/migration/NodeDescriptionLabelExpressionMigrationParticipantTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/migration/NodeDescriptionUserResizableMigrationParticipantTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/migration/NodeStyleDescriptionColorMigrationParticipantTests.java
  packages/sirius-web/frontend/sirius-web-application/src/modals/upload-document/UploadDocumentModal.tsx
  packages/sirius-web/frontend/sirius-web-application/src/modals/upload-document/UploadDocumentModal.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/modals/upload-document/useUploadDocument.ts
  packages/sirius-web/frontend/sirius-web-application/src/modals/upload-document/useUploadDocument.types.ts
Labels: pr: to review soon, priority: high
