Repository eclipse-sirius/sirius-web, pull requests merged in 2025-01, with the labels that each got.

#4307 [releng] Upgrade turbo to version 2.3.3
  CHANGELOG.adoc
  package-lock.json
  package.json
  packages/charts/frontend/sirius-components-charts/package.json
  packages/core/frontend/sirius-components-core/package.json
  packages/core/frontend/sirius-components-omnibox/package.json
  packages/deck/frontend/sirius-components-deck/package.json
  packages/diagrams/frontend/sirius-components-diagrams/package.json
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/package.json
  packages/forms/frontend/sirius-components-forms/package.json
  packages/forms/frontend/sirius-components-widget-reference/package.json
  packages/gantt/frontend/sirius-components-gantt/package.json
  packages/portals/frontend/sirius-components-portals/package.json
  packages/selection/frontend/sirius-components-selection/package.json
  packages/sirius-web/frontend/sirius-web-application/package.json
  packages/sirius-web/frontend/sirius-web-papaya/package.json
  packages/sirius-web/frontend/sirius-web-table/package.json
  packages/tables/frontend/sirius-components-tables/package.json
  packages/trees/frontend/sirius-components-trees/package.json
  packages/validation/frontend/sirius-components-validation/package.json
  turbo.json
Labels: pr: to review later, priority: low

#4181 [fix] Fix empty tree items in domain view tree representation
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/trees/DomainExplorerControllerTests.java
Labels: pr: to review soon, priority: high

#4357 [4356] Add a minimap to diagrams
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx
  packages/sirius-web/frontend/sirius-web-papaya/src/diagrams/PapayaDiagramInformationPanel.tsx
Labels: pr: to review soon, priority: high

#4369 [4368] Add GraphQL subscription exception handler
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-infrastructure/src/main/java/org/eclipse/sirius/web/infrastructure/configuration/graphql/GraphQLConfiguration.java
Labels: pr: to review soon, priority: low

#4388 [4282] Fix frontend warning about non-unique fragment name
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/handles/useConnectionCandidatesQuery.ts
Labels: pr: to review soon, priority: high

#4379 [doc] Shape on lowering the coupling between project and editing context
  CHANGELOG.adoc
  doc/iterations/2025.2/lower_coupling_between_project_and_editing_context.adoc
Labels: pr: to review soon, priority: high

#4269 [doc] Add a shape for adding the support of non synchronized tables
  CHANGELOG.adoc
  doc/iterations/2025.2/add_support_of_non_synchronized_tables.adoc
Labels: pr: to review soon, priority: high

#4387 [doc] Add shape on loading indicators for long actions
  CHANGELOG.adoc
  doc/iterations/2025.2/add_loading_indicators_for_long_actions.adoc
Labels: pr: to review soon, priority: high

#4386 [1047] Only show the relation's name as initial text on direct edit
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/representations/RelationEdgeDescriptionProvider.java
Labels: pr: to review later, priority: low

#4391 [doc] Add shape on impact analysis before tool execution
  CHANGELOG.adoc
  doc/iterations/2025.2/add_impact_analysis_before_tool_execution.adoc
Labels: pr: to review soon, priority: high

#4394 [doc] Add an ADR on support actions in table row context menu
  CHANGELOG.adoc
  doc/adrs/178_add_support_of_actions_in_table_row_menu.adoc
Labels: pr: to review soon, priority: high

#4284 [doc] Contribute a shape for model publication
  CHANGELOG.adoc
  doc/adrs/179_add_support_for_artifact_publication_from_a_project.adoc
  doc/iterations/2025.2/add_support_for_artifact_publication_from_a_project.adoc
Labels: pr: to review soon, priority: low

#4399 [4398] Add swagger path to authorized routes
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-infrastructure/src/main/java/org/eclipse/sirius/web/infrastructure/configuration/mvc/FrontendRouterConfiguration.java
Labels: pr: to review soon, priority: high

#4396 [doc] Add ADR for widget diagnostics provider in View-based Forms
  CHANGELOG.adoc
  doc/adrs/180-view-forms-diagnostics.adoc
Labels: pr: to review soon, priority: low

#4237 [4233] Add Cursor-based pagination in Project related GET REST APIs
  CHANGELOG.adoc
  integration-tests/cypress/support/serverCommands.js
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/controllers/ProjectRestController.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/controllers/ViewerProjectsDataFetcher.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/services/ProjectApplicationService.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/services/api/IProjectApplicationService.java
  packages/sirius-web/backend/sirius-web-application/src/main/resources/schema/siriusweb.graphqls
  packages/sirius-web/backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/boundedcontexts/project/repositories/IProjectRepository.java
  packages/sirius-web/backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/boundedcontexts/project/repositories/ProjectSearchRepository.java
  packages/sirius-web/backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/boundedcontexts/project/repositories/ProjectSearchRepositoryDelegate.java
  packages/sirius-web/backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/boundedcontexts/project/repositories/ProjectSearchRepositoryImpl.java
  packages/sirius-web/backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/boundedcontexts/project/services/ProjectSearchService.java
  packages/sirius-web/backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/boundedcontexts/project/services/Window.java
  packages/sirius-web/backend/sirius-web-domain/src/main/java/org/eclipse/sirius/web/domain/boundedcontexts/project/services/api/IProjectSearchService.java
  packages/sirius-web/backend/sirius-web-tests/src/main/java/org/eclipse/sirius/web/tests/graphql/ProjectsQueryRunner.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/projects/ProjectControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/projects/ProjectRestControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/projects/ProjectSearchControllerConfiguration.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/projects/ProjectSearchControllerIntegrationTests.java
  packages/sirius-web/frontend/sirius-web-application/src/views/project-browser/list-projects-area/ListProjectsArea.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/project-browser/list-projects-area/ListProjectsArea.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/views/project-browser/list-projects-area/ProjectsTable.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/project-browser/list-projects-area/ProjectsTable.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/views/project-browser/list-projects-area/useProjects.fragments.ts
  packages/sirius-web/frontend/sirius-web-application/src/views/project-browser/list-projects-area/useProjects.ts
  packages/sirius-web/frontend/sirius-web-application/src/views/project-browser/list-projects-area/useProjects.types.ts
  vscode-extension/src/data/ServerData.ts
Labels: pr: to review soon, priority: high

#4371 [4346] Improve the query view with object icons and a loading feedback
  CHANGELOG.adoc
  packages/core/backend/sirius-components-collaborative/src/main/resources/schema/core.graphqls
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/object/controllers/ObjectIconURLsDataFetcher.java
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/query/QueryView.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/query/QueryView.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/query/useEvaluateExpression.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/query/useEvaluateExpression.types.ts
Labels: pr: to review soon, priority: high

#4342 [4338] Improve the information available to debug performance issues
  CHANGELOG.adoc
  doc/how-to/debug-performance-related-issues.adoc
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/EditingContextEventProcessor.java
  packages/emf/backend/sirius-components-interpreter/src/main/java/org/eclipse/sirius/components/interpreter/AQLInterpreter.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/services/EditingContextPersistenceService.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/services/EditingContextSearchService.java
  packages/sirius-web/backend/sirius-web-infrastructure/src/main/java/org/eclipse/sirius/web/infrastructure/configuration/graphql/GraphQLConfiguration.java
  packages/sirius-web/backend/sirius-web/src/main/resources/application.properties
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/forms/CompletionProposalsControllerTests.java
  packages/sirius-web/frontend/sirius-web-application/src/graphql/ApolloLinkUndoRedoStack.tsx
  packages/sirius-web/frontend/sirius-web-application/src/graphql/ApolloLoggerLink.tsx
  packages/sirius-web/frontend/sirius-web-application/src/graphql/useCreateApolloClient.ts
Labels: pr: to review soon, priority: high

#4402 [4400] Add response code annotations to REST APIs
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/dto/Identified.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/object/controllers/ObjectRestController.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/controllers/ProjectRestController.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/data/versioning/controllers/CommitRestController.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/data/versioning/dto/RestBranch.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/data/versioning/dto/RestCommit.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/data/versioning/dto/RestDataIdentity.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/data/versioning/dto/RestDataVersion.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/dto/RestProject.java
Labels: pr: to review soon, priority: high

#4406 [doc] Add shape and ADR for supporting custom navigation bar menu
  doc/adrs/181_support_custom_navigation_bar.adoc
  doc/iterations/2025.2/support_custom_navigation_bar.adoc
Labels: pr: to review later, priority: high

#4382 [4381] Set activeFilterIds variable in DefaultExpandAllTreePathHandler
  CHANGELOG.adoc
  packages/trees/backend/sirius-components-collaborative-trees/src/main/java/org/eclipse/sirius/components/collaborative/trees/handlers/DefaultExpandAllTreePathHandler.java
  packages/trees/backend/sirius-components-collaborative-trees/src/test/java/org/eclipse/sirius/components/collaborative/trees/architecture/handlers/DefaultExpandAllTreePathHandlerTests.java
Labels: pr: to review soon, priority: low

#4344 [4343] Keep filters when opening a table
  CHANGELOG.adoc
  packages/forms/backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/components/TableWidgetComponent.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/tables/PapayaTableControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/resources/scripts/papaya.sql
  packages/tables/backend/sirius-components-collaborative-tables/src/main/java/org/eclipse/sirius/components/collaborative/tables/TableCreationParameters.java
  packages/tables/backend/sirius-components-collaborative-tables/src/main/java/org/eclipse/sirius/components/collaborative/tables/TableEventProcessorFactory.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/components/LineComponent.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/components/TableComponent.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/components/TableComponentProps.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/descriptions/ColumnDescription.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/elements/TableElementProps.java
Labels: pr: to review soon, priority: low

#3867 [3578] Fix tooltip and menu visibility in a full screen mode
  CHANGELOG.adoc
  packages/sirius-web/frontend/sirius-web-application/src/theme/siriusWebTheme.ts
  vscode-extension/src/view/app/theme/siriusWebTheme.ts
Labels: pr: to review later, priority: low

#4363 [4360] Fix an issue when opening tables from a form
  CHANGELOG.adoc
  packages/tables/frontend/sirius-components-tables/src/columns/useTableColumnFiltering.ts
  packages/tables/frontend/sirius-components-tables/src/columns/useTableColumnFiltering.types.ts
Labels: pr: to review soon, priority: high

#3534 [3533] Add a dedicated component to handle diagram subscription
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/representation/DiagramRepresentation.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/representation/DiagramRepresentation.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/representation/DiagramSubscriptionProvider.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/representation/DiagramSubscriptionProvider.types.ts
  packages/diagrams/frontend/sirius-components-diagrams/src/representation/useDiagramSubscription.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/representation/useDiagramSubscription.types.ts
Labels: pr: to review later, priority: low

#4361 [4359] Fix an issue where two pagination forms where display in tables
  CHANGELOG.adoc
  packages/tables/frontend/sirius-components-tables/src/table/TableContent.tsx
Labels: pr: to review soon, priority: low

#4433 [releng] Update swagger dependencies versions
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/pom.xml
  packages/sirius-web/backend/sirius-web-infrastructure/pom.xml
Labels: pr: to review later, priority: low

#4395 [doc] Add shape about improving the image export
  CHANGELOG.adoc
  doc/iterations/2025.2/Improve_image_export.adoc
  doc/iterations/2025.2/images/diagram-image-export.png
Labels: pr: to review soon, priority: high

#4432 [4430] Add the PNG export of a diagram
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/panel/DiagramPanel.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/panel/ExportImageButton.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/panel/useExportToImage.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/panel/useExportToImage.types.ts
Labels: pr: to review soon, priority: high

#4424 [4422] Prevent application crash when an edge path is malformed durin…
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/SmoothStepEdgeWrapper.tsx
Labels: pr: to review soon, priority: high

#4427 [4426] Remove last usages of mui styled pattern
  CHANGELOG.adoc
  packages/deck/frontend/sirius-components-deck/src/card/DeckCard.tsx
  packages/deck/frontend/sirius-components-deck/src/common/DeckInput.tsx
  packages/deck/frontend/sirius-components-deck/src/laneHeader/DeckLaneHeader.tsx
  packages/deck/frontend/sirius-components-deck/src/styled/DeckLaneStyledComponents.tsx
  packages/deck/frontend/sirius-components-deck/src/styled/DeckStyledComponents.tsx
  vscode-extension/src/view/app/toast/ToastProvider.tsx
Labels: pr: to review soon, priority: high

#4435 [4346] Make the selection available as variables to evaluate expressions
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/query/dto/EvaluateExpressionInput.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/query/services/EvaluateExpressionEventHandler.java
  packages/sirius-web/backend/sirius-web-application/src/main/resources/schema/query.graphqls
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/query/QueryIntegrationTests.java
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/query/useEvaluateExpression.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/query/useEvaluateExpression.types.ts
Labels: pr: to review soon, priority: high

#4438 [4437] Fix DialogContextProvider missing
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/representation/DiagramSubscriptionProvider.tsx
Labels: pr: to review soon, priority: high

#4436 [doc] Add shape for supporting selections in URLs
  CHANGELOG.adoc
  doc/iterations/2025.2/add_the_current_selection_to_the_url_of_the_project_workbench.adoc
Labels: pr: to review soon, priority: high

#4340 [4335] Add support of column reordering in table representation
  CHANGELOG.adoc
  packages/forms/frontend/sirius-components-forms/src/propertysections/TableWidgetPropertySection.tsx
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/tables/PapayaTableColumnControllerIntegrationTests.java
  packages/tables/backend/sirius-components-collaborative-tables/src/main/java/org/eclipse/sirius/components/collaborative/tables/dto/ReorderTableColumnsInput.java
  packages/tables/backend/sirius-components-collaborative-tables/src/main/java/org/eclipse/sirius/components/collaborative/tables/handlers/ReorderTableColumnsEventHandler.java
  packages/tables/backend/sirius-components-collaborative-tables/src/main/resources/schema/table.graphqls
  packages/tables/backend/sirius-components-tables-graphql/src/main/java/org/eclipse/sirius/components/tables/graphql/datafetchers/mutation/MutationReorderTableColumnsDataFetcher.java
  packages/tables/backend/sirius-components-tables-tests/src/main/java/org/eclipse/sirius/components/tables/tests/graphql/ReorderTableColumnsMutationRunner.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/Column.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/components/ColumnComponent.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/elements/ColumnElementProps.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/events/ReorderTableColumnsEvent.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/renderer/TableElementFactory.java
  packages/tables/frontend/sirius-components-tables/src/columns/useTableColumnOrdering.ts
  packages/tables/frontend/sirius-components-tables/src/columns/useTableColumnOrdering.types.ts
  packages/tables/frontend/sirius-components-tables/src/representation/TableRepresentation.tsx
  packages/tables/frontend/sirius-components-tables/src/representation/useTableSubscription.ts
  packages/tables/frontend/sirius-components-tables/src/table/TableContent.tsx
  packages/tables/frontend/sirius-components-tables/src/table/TableContent.types.ts
  packages/tables/frontend/sirius-components-tables/src/table/useTableColumns.tsx
Labels: pr: to review soon, priority: high

#4442 [4346] Improve the user experience with the query view
  CHANGELOG.adoc
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/query/QueryView.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/query/QueryView.types.ts
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/query/useExpression.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/query/useExpression.types.ts
Labels: pr: to review soon, priority: high

#4441 [4440] Add the representation description name in details view
  CHANGELOG.adoc
  packages/forms/backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/description/LabelDescription.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/representation/services/RepresentationMetadataDetailsViewPageDescriptionProvider.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/representations/RepresentationControllerIntegrationTests.java
Labels: pr: to review soon, priority: high

#4439 [4425] Add new table cell widget description for textarea
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/table/CellTypePredicate.java
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/table/PackageTableRepresentationDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/table/ProjectTableRepresentationDescriptionProvider.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/tables/PapayaTableCellControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/tables/PapayaViewTableControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/forms/FormWithTableDescriptionProvider.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/tables/ViewTableDescriptionProvider.java
  packages/tables/backend/sirius-components-collaborative-tables/src/main/java/org/eclipse/sirius/components/collaborative/tables/dto/EditTextareaCellInput.java
  packages/tables/backend/sirius-components-collaborative-tables/src/main/java/org/eclipse/sirius/components/collaborative/tables/handlers/ChangeGlobalFilterValueEventHandler.java
  packages/tables/backend/sirius-components-collaborative-tables/src/main/java/org/eclipse/sirius/components/collaborative/tables/handlers/EditCellEventHandler.java
  packages/tables/backend/sirius-components-collaborative-tables/src/main/resources/schema/table.graphqls
  packages/tables/backend/sirius-components-tables-graphql/src/main/java/org/eclipse/sirius/components/tables/graphql/datafetchers/mutation/MutationEditTextareaCellDataFetcher.java
  packages/tables/backend/sirius-components-tables-tests/src/main/java/org/eclipse/sirius/components/tables/tests/graphql/EditTextareaCellMutationRunner.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/TextareaCell.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/components/LineComponent.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/components/TextareaCellComponent.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/components/TextareaCellComponentProps.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/descriptions/TextareaCellDescription.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/elements/TextareaCellElementProps.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/renderer/TableComponentPropsValidator.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/renderer/TableElementFactory.java
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/renderer/TableInstancePropsValidator.java
  packages/tables/frontend/sirius-components-tables/src/actions/ExportAllDataButton.tsx
  packages/tables/frontend/sirius-components-tables/src/cells/Cell.tsx
  packages/tables/frontend/sirius-components-tables/src/cells/TextareaCell.tsx
  packages/tables/frontend/sirius-components-tables/src/cells/TextareaCell.types.ts
  packages/tables/frontend/sirius-components-tables/src/cells/useEditTextareaCell.tsx
  packages/tables/frontend/sirius-components-tables/src/cells/useEditTextareaCell.types.ts
  packages/tables/frontend/sirius-components-tables/src/representation/useTableSubscription.ts
  packages/tables/frontend/sirius-components-tables/src/table/TableContent.types.ts
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/table/CellTextareaWidgetDescriptionBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/table/TableBuilders.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/table/ViewTableDescriptionConverter.java
  packages/view/backend/sirius-components-view-table-edit/src/main/java/org/eclipse/sirius/components/view/table/provider/CellDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-table-edit/src/main/java/org/eclipse/sirius/components/view/table/provider/CellTextareaWidgetDescriptionItemProvider.java
  packages/view/backend/sirius-components-view-table-edit/src/main/java/org/eclipse/sirius/components/view/table/provider/TableItemProviderAdapterFactory.java
  packages/view/backend/sirius-components-view-table-edit/src/main/resources/icons/full/obj16/CellTextareaWidgetDescription.svg
  packages/view/backend/sirius-components-view-table-edit/src/main/resources/plugin.properties
  packages/view/backend/sirius-components-view-table/src/main/java/org/eclipse/sirius/components/view/table/CellTextareaWidgetDescription.java
  packages/view/backend/sirius-components-view-table/src/main/java/org/eclipse/sirius/components/view/table/TableFactory.java
  packages/view/backend/sirius-components-view-table/src/main/java/org/eclipse/sirius/components/view/table/TablePackage.java
  packages/view/backend/sirius-components-view-table/src/main/java/org/eclipse/sirius/components/view/table/impl/CellTextareaWidgetDescriptionImpl.java
  packages/view/backend/sirius-components-view-table/src/main/java/org/eclipse/sirius/components/view/table/impl/TableFactoryImpl.java
  packages/view/backend/sirius-components-view-table/src/main/java/org/eclipse/sirius/components/view/table/impl/TablePackageImpl.java
  packages/view/backend/sirius-components-view-table/src/main/java/org/eclipse/sirius/components/view/table/util/TableAdapterFactory.java
  packages/view/backend/sirius-components-view-table/src/main/java/org/eclipse/sirius/components/view/table/util/TableSwitch.java
  packages/view/backend/sirius-components-view-table/src/main/resources/model/table.ecore
  packages/view/backend/sirius-components-view-table/src/main/resources/model/table.genmodel
Labels: pr: to review soon, priority: high

#4466 [4465] Allow end users to view the PNG export of a diagram more easily
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/panel/ExportImageButton.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/panel/useExportToImage.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/panel/useExportToImage.types.ts
Labels: pr: to review soon, priority: high

#4350 [4345] Make table cells independently selectable
  CHANGELOG.adoc
  packages/tables/frontend/sirius-components-tables/src/table/TableContent.tsx
  packages/tables/frontend/sirius-components-tables/src/table/TableContent.types.ts
  packages/tables/frontend/sirius-components-tables/src/table/useTableColumns.tsx
Labels: pr: to review soon, priority: low

#4353 [4352] Add support to range column filters in table
  CHANGELOG.adoc
  packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/URLParser.java
  packages/core/backend/sirius-components-core/src/test/java/org/eclipse/sirius/components/core/URLParserTests.java
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/table/PackageTableRepresentationDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/table/PapayaColumnFilterPredicate.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/tables/PapayaTableCellControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/tables/PapayaTableColumnControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/tables/PapayaTableControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/tables/TableIconURLControllerTests.java
  packages/tables/backend/sirius-components-tables/pom.xml
  packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/components/TableComponent.java
  packages/tables/frontend/sirius-components-tables/src/cells/CheckboxCell.tsx
  packages/tables/frontend/sirius-components-tables/src/cells/IconLabelCell.tsx
  packages/tables/frontend/sirius-components-tables/src/cells/MultiSelectCell.tsx
  packages/tables/frontend/sirius-components-tables/src/cells/SelectCell.tsx
  packages/tables/frontend/sirius-components-tables/src/cells/TextareaCell.tsx
  packages/tables/frontend/sirius-components-tables/src/cells/TextfieldCell.tsx
  packages/tables/frontend/sirius-components-tables/src/columns/useTableColumnFiltering.ts
  packages/tables/frontend/sirius-components-tables/src/representation/tableIdProvider.ts
  packages/tables/frontend/sirius-components-tables/src/table/useTableColumns.tsx
Labels: pr: to review soon, priority: low

#4454 [releng] Upgrade to Sirius Desktop 7.4.6
  CHANGELOG.adoc
  packages/view/backend/sirius-components-view-emf/pom.xml
Labels: pr: to review later, priority: low

#4456 [4455] Keep reference values navigable even when in read-only mode
  CHANGELOG.adoc
  packages/forms/frontend/sirius-components-widget-reference/src/components/ValuedReferenceAutocomplete.tsx
Labels: pr: to review soon, priority: low

#4448 [4362] Add new navigationBarCenterContributionExtensionPoint
  CHANGELOG.adoc
  packages/sirius-web/frontend/sirius-web-application/src/index.ts
  packages/sirius-web/frontend/sirius-web-application/src/navigationBar/NavigationBar.tsx
  packages/sirius-web/frontend/sirius-web-application/src/navigationBar/NavigationBarExtensionPoints.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/EditProjectNavbar/EditProjectNavbar.tsx
  packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/EditProjectNavbar/EditProjectNavbarExtensionPoints.tsx
  packages/sirius-web/frontend/sirius-web-papaya/src/PapayaExtensionRegistry.tsx
Labels: pr: to review soon, priority: low

#4429 [doc] Update the shapes and ADR related to the publication of libraries
  CHANGELOG.adoc
  doc/adrs/179_add_support_for_artifact_publication_from_a_project.adoc
  doc/adrs/179_add_support_for_regular_commands_in_the_command_palette.adoc
  doc/iterations/2025.2/add_support_for_artifact_publication_from_a_project.adoc
  doc/iterations/2025.2/add_support_for_the_import_of_libraries.adoc
  doc/iterations/2025.2/add_support_for_the_publication_of_libraries.adoc
Labels: pr: to review soon, priority: high

#4457 [4414] Return valid JSON on commit changes REST APIs
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/data/versioning/services/RestDataVersionPayloadSerializer.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/projects/CommitChangesNoPayloadRestControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/projects/CommitRestControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/projects/RestDataVersionPayloadSerializerTestService.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/OnRestCommitPayloadTests.java
Labels: pr: to review later, priority: low

#4475 [4474] Add EMF Services for Query View
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/query/services/EMFQueryServices.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/query/services/EvaluateExpressionEventHandler.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/query/services/SiriusWebInterpreterJavaServiceProvider.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/query/QueryIntegrationTests.java
Labels: pr: to review soon, priority: high

#4327 [4326] Add quickAccessTools to diagram's palette in view dsl
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/classdiagram/tools/diagram/DiagramPaletteProvider.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/diagram/DiagramPaletteBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/diagram/EdgePaletteBuilder.java
  packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/diagram/NodePaletteBuilder.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/DiagramPaletteItemProvider.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/EdgePaletteItemProvider.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/NodePaletteItemProvider.java
  packages/view/backend/sirius-components-view-diagram-edit/src/main/resources/plugin.properties
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/DiagramPackage.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/DiagramPalette.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/EdgePalette.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/NodePalette.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/DiagramPackageImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/DiagramPaletteImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/EdgePaletteImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/java/org/eclipse/sirius/components/view/diagram/impl/NodePaletteImpl.java
  packages/view/backend/sirius-components-view-diagram/src/main/resources/model/diagram.ecore
  packages/view/backend/sirius-components-view-diagram/src/main/resources/model/diagram.genmodel
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ToolConverter.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ToolFinder.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewPaletteProvider.java
Labels: pr: to review later, priority: low

#4488 [fix] Update RestDataVersionPayloadSerializer to @JsonComponent
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/data/versioning/services/RestDataVersionPayloadSerializer.java
Labels: pr: to review soon, priority: high

#4479 [4478] Provide an API to search custom resource on download document …
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/controllers/DocumentDownloadController.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/services/api/IDocumentDownloadResourceSearchService.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/documents/DocumentDownloadControllerIntegrationTests.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/documents/PapayaDocumentDownloadResourceSearchService.java
Labels: pr: to review soon, priority: high

#4490 [4489] Fix issue where next page is disabled despite having more elem…
  CHANGELOG.adoc
  packages/emf/backend/sirius-components-emf-tables/src/main/java/org/eclipse/sirius/components/emf/tables/CursorBasedNavigationServices.java
Labels: pr: to review soon, priority: high

#4380 [4310] Border does not appear when using ListLayoutStrategy with a da…
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/converter/ListNodeConverter.ts
  packages/tests/backend/sirius-components-tests/src/test/java/org/eclipse/sirius/components/tests/GeneralPurposeTests.java
Labels: pr: to review soon, priority: high

#4487 [4390] Fix an issue displaying irrelevant help text and diagnostics
  CHANGELOG.adoc
  packages/forms/backend/sirius-components-forms-graphql/src/main/java/org/eclipse/sirius/components/forms/graphql/datafetchers/form/WidgetHasHelpTextDataFetcher.java
  packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/forms/HelpTextControllerTests.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/form/converters/validation/DiagnosticProvider.java
Labels: pr: to review soon, priority: high

#4472 [4458] Export direct edit functionalities
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/index.ts
Labels: pr: to review later, priority: low

#4484 [fix] Replace requestIdleCallback with setTimeout for browsers compat…
  CHANGELOG.adoc
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/layout.tsx
Labels: pr: to review soon, priority: high
