Repository eclipse-sirius/sirius-web, pull requests merged in 2025-10, with the labels that each got.

#5604 [5590] Fix filter modal menu not rendering correctly
  CHANGELOG.adoc
  packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/SplitButtonWidget.tsx
  packages/forms/frontend/sirius-components-forms/src/propertysections/SplitButtonPropertySection.tsx
Labels: pr: to review soon, priority: high

#5606 [4171] Make sure the close button is always visible in representation tabs
  CHANGELOG.adoc
  packages/core/frontend/sirius-components-core/src/workbench/RepresentationNavigation.tsx
Labels: pr: to review soon, priority: low

#5150 [5148] Remove concerns from the EditingContextEventProcessor by adding the ability to react to change descriptions
  CHANGELOG.adoc
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/api/ChangeDescriptionParameters.java
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/api/ChangeKind.java
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/ChangeDescriptionConsumerOrchestrator.java
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/ChangeDescriptionPublisher.java
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/EditingContextEventProcessor.java
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/EditingContextEventProcessorCleaner.java
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/EditingContextEventProcessorFactory.java
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/EditingContextEventProcessorParameters.java
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/EditingContextSaver.java
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/RepresentationEventProcessorRefresher.java
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/api/IChangeDescriptionConsumer.java
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/api/IChangeDescriptionListener.java
  packages/portals/backend/sirius-components-collaborative-portals/src/main/java/org/eclipse/sirius/components/collaborative/portals/PortalEventProcessor.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/representation/services/RenameRepresentationEventHandler.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/representation/services/RepresentationMetadataDetailsViewPageDescriptionProvider.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/DeleteRepresentationTreeItemEventHandler.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/RenameRepresentationTreeItemHandler.java
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/representations/services/RepresentationsFormDescriptionProvider.java
  packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/table/ViewRowFilterProvider.java
Labels: pr: to review later, priority: high

#5286 [5285] Extract the creation of RepresentationEventProcessors and the dispatch of IInput from the EditingContextEventProcessor
  CHANGELOG.adoc
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/EditingContextEventProcessor.java
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/EditingContextEventProcessorFactory.java
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/EditingContextEventProcessorFactoryParameters.java
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/EditingContextEventProcessorParameters.java
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/InputDispatcher.java
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/api/IInputDispatcher.java
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/api/IRepresentationEventProcessorProvider.java
  packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/representations/RepresentationEventProcessorProvider.java
Labels: pr: to review later, priority: low

#5607 [fix] Set the nodeSelectableProvider of the tree filter modal to false
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/diagram/services/filter/DiagramFilterDescriptionProvider.java
Labels: pr: to review soon, priority: high

#5618 [5526] Close diagram palette after invoking a 'Show in ...' action
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/DiagramElementPalette.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/Palette.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/ShowInSection.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/tool-list/PaletteToolList.tsx
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/tool-list/PaletteToolList.types.ts
  packages/palette/frontend/sirius-components-palette/src/PaletteExtensionSection.types.ts
Labels: pr: to review soon, priority: high

#5609 [5608] Hide empty sections on the palette
  CHANGELOG.adoc
  integration-tests-playwright/playwright/e2e/palette.spec.ts
  integration-tests-playwright/playwright/resources/diagramPalette.xml
  packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/tool-list/PaletteToolList.tsx
  packages/sirius-web/backend/sirius-web-e2e-tests/src/main/java/org/eclipse/sirius/web/e2e/tests/diagrampalette/DiagramPaletteDomainProvider.java
  packages/sirius-web/backend/sirius-web-e2e-tests/src/main/java/org/eclipse/sirius/web/e2e/tests/diagrampalette/DiagramPaletteViewProvider.java
Labels: pr: to review soon, priority: high

#5629 [5627] Fix "Duplicate object" action with "update incoming reference"
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/DefaultObjectDuplicator.java
Labels: pr: to review soon, priority: high

#5623 [5617] Fix duplication of an element to a mono valued containment
  CHANGELOG.adoc
  packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/DefaultObjectDuplicator.java
Labels: pr: to review soon, priority: high
